### ISSUE TITLE
setting output mode on Logistical pipe connected to ANY INVENTORY causes crash. Ex Nihilo crucible.

### ISSUE THREAD

**Issue by Coffeene** [aidancbrady/Mekanism#1841]
Setting the logistal pipe to output connected to a jabba barrel will result in a crash, and unloadable unless one or the other mod is removed. Putting this here as the error reports mekanism and not jabba.  (whole report) http://pastebin.com/6gcVuhjA

java.lang.ArrayIndexOutOfBoundsException: 1
	at mekanism.common.transporter.TransporterManager.copyInvFromSide(TransporterManager.java:82)
	at mekanism.common.transporter.TransporterManager.getPredictedInsert(TransporterManager.java:252)
	at mekanism.common.transporter.TransporterPathfinder$InventoryFinder.loop(TransporterPathfinder.java:259)
	at mekanism.common.transporter.TransporterPathfinder$InventoryFinder.find(TransporterPathfinder.java:277)
	at mekanism.common.transporter.TransporterPathfinder.getPaths(TransporterPathfinder.java:295)
	at mekanism.common.transporter.TransporterPathfinder.getNewBasePath(TransporterPathfinder.java:318)
	at mekanism.common.transporter.TransporterStack.recalculatePath(TransporterStack.java:162)
	at mekanism.common.multipart.PartLogisticalTransporter.insert_do(PartLogisticalTransporter.java:445)
	at mekanism.common.multipart.PartLogisticalTransporter.insert(PartLogisticalTransporter.java:427)
	at mekanism.common.util.TransporterUtils.insert(TransporterUtils.java:152)
	at mekanism.common.multipart.PartLogisticalTransporter.pullItems(PartLogisticalTransporter.java:372)
	at mekanism.common.multipart.PartLogisticalTransporter.update(PartLogisticalTransporter.java:195)
	at codechicken.multipart.TileMultipart$$anonfun$updateEntity$1.apply(TileMultipart.scala:81)
	at codechicken.multipart.TileMultipart$$anonfun$updateEntity$1.apply(TileMultipart.scala:81)
	at codechicken.multipart.TileMultipart.operate(TileMultipart.scala:75)
	at codechicken.multipart.TileMultipart.func_145845_h(TileMultipart.scala:81)
	at net.minecraft.world.World.func_72939_s(World.java:1912)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by aidancbrady** [comment]
This should be fixed by now.
