### ISSUE TITLE
ConcurrentModificationException in transmitters

### ISSUE THREAD

**Issue by ruifung** [aidancbrady/Mekanism#2005]
Log:
```
[09:00:23] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.util.ConcurrentModificationException
[09:00:23] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at java.util.LinkedHashMap$LinkedHashIterator.nextNode(Unknown Source)
[09:00:23] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at java.util.LinkedHashMap$LinkedKeyIterator.next(Unknown Source)
[09:00:23] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at mekanism.api.transmitters.DynamicNetwork.fullRefresh(DynamicNetwork.java:95)
[09:00:23] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at mekanism.common.multipart.PartTransmitter.getTransmitterNetwork(PartTransmitter.java:122)
[09:00:23] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at mekanism.common.multipart.PartTransmitter.getTransmitterNetwork(PartTransmitter.java:86)
[09:00:23] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at mekanism.common.multipart.PartTransmitter.refreshTransmitterNetwork(PartTransmitter.java:43)
[09:00:23] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at TGridTransmitter$$14$class.refreshTransmitterNetwork(UnknownSource)
[09:00:23] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at TileMultipart_cmp$$29.refreshTransmitterNetwork(Unknown Source)
[09:00:23] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at mekanism.api.transmitters.TransmitterNetworkRegistry$NetworkLoader.refreshChunk(TransmitterNetworkRegistry.java:150)
[09:00:23] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at mekanism.api.transmitters.TransmitterNetworkRegistry$NetworkLoader.onChunkLoad(TransmitterNetworkRegistry.java:132)
[09:00:23] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at cpw.mods.fml.common.eventhandler.ASMEventHandler_480_NetworkLoader_onChunkLoad_Load.invoke(.dynamic)
[09:00:23] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
[09:00:23] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
[09:00:23] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.world.chunk.Chunk.func_76631_c(Chunk.java:923)
[09:00:23] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:46)
[09:00:23] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12)
[09:00:23] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344)
[09:00:23] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302)
[09:00:23] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12)
[09:00:23] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126)
[09:00:23] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
[09:00:23] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
[09:00:23] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.world.World.func_72964_e(World.java:419)
[09:00:23] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.world.World.func_147439_a(World.java:345)
[09:00:23] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at buildcraft.silicon.TileLaser.findTable(TileLaser.java:183)
[09:00:23] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at buildcraft.silicon.TileLaser.func_145845_h(TileLaser.java:84)
[09:00:23] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.world.World.func_72939_s(World.java:1939)
[09:00:23] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
[09:00:23] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
[09:00:23] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
[09:00:23] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[09:00:23] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
[09:00:23] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[09:02:11] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NullPointerException
[09:03:27] [Server thread/WARN]: Can't keep up! Did the system time change, or i
s the server overloaded? Running 184204ms behind, skipping 3684 tick(s)
```

**Comment by JagSwag2014** [comment]
Got the same issue.

http://pastebin.com/QKp8j9LZ

**Comment by aidancbrady** [comment]
Should be fixed
