### ISSUE TITLE
Lapis Sword + Crafting GUI = crash

### ISSUE THREAD

**Issue by Slind14** [aidancbrady/Mekanism#2013]
When putting a lapis sword in any crafting GUI it crashes the client. (crafting table, player 2x2 crafting field..)

```
net.minecraft.util.ReportedException: Updating screen events
        at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1643) ~[bao.class:?]
        at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:962) ~[bao.class:?]
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [bao.class:?]
        at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_60]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_60]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_60]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_60]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 36
        at net.minecraft.item.Item$ToolMaterial.fun     at net.minecraft.client.gui.inventory.GuiContainer.public_func_146984_a(GuiContainer.java) ~[bex.class:?]
        at codechicken.nei.guihook.DefaultSlotClickHandler.callHandleMouseClick(DefaultSlotClickHandler.java) ~[DefaultSlotClickHandler.class:?]
        at codechicken.nei.guihook.DefaultSlotClickHandler.handleSlotClick(DefaultSlotClickHandler.java:17) ~[DefaultSlotClickHandler.class:?]
        at codechicken.nei.guihook.GuiContainerManager.handleMouseClick(GuiContainerManager.java:452) ~[GuiContainerManager.class:?]
        at net.minecraft.client.gui.inventory.GuiContainer.managerHandleMouseClick(GuiContainer.java) ~[bex.class:?]
        at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java:590) ~[bex.class:?]
        at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:306) ~[bdw.class:?]
        at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java) ~[bex.class:?]
        at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268) ~[bdw.class:?]
        at net.minecraft.client.Miodechicken.nei.guihook.GuiContainerManager.handleSlotClick(GuiContainerManager.java:503)
        at net.minecraft.client.gui.inventory.GuiContainer.func_146984_a(GuiContainer.java:638)
        at net.minecraft.client.gui.inventory.GuiContainer.public_func_146984_a(GuiContainer.java)
        at codechicken.nei.guihook.DefaultSlotClickHandler.callHandleMouseClick(DefaultSlotClickHandler.java)
        at codechicken.nei.guihook.DefaultSlotClickHandler.handleSlotClick(DefaultSlotClickHandler.java:17)
        at codechicken.nei.guihook.GuiContainerManager.handleMouseClick(GuiContainerManager.java:452)
        at net.minecraft.client.gui.inventory.GuiContainer.managerHandleMouseClick(GuiContainer.java)
        at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java:590)
        at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:306)
        at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
        at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
        at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1629)
        at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:962)
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
        at net.minecraft.client.main.Main.main(SourceFile:148)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by aidancbrady** [comment]
Looks like an NEI issue, I can't reproduce on my end
