### ISSUE TITLE
Crash server report

### ISSUE THREAD

**Issue by MrHelp** [aidancbrady/Mekanism#2045]
---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 12/19/14 5:59 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at net.minecraft.item.ItemStack.func_77976_d(ItemStack.java:208)
	at mekanism.common.tile.TileEntityDigitalMiner.canInsert(TileEntityDigitalMiner.java:416)
	at mekanism.common.tile.TileEntityDigitalMiner.onUpdate(TileEntityDigitalMiner.java:213)
	at mekanism.common.tile.TileEntityBasicBlock.func_145845_h(TileEntityBasicBlock.java:59)
	at net.minecraft.world.World.func_72939_s(World.java:2491)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:943)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.item.ItemStack.func_77976_d(ItemStack.java:208)
	at mekanism.common.tile.TileEntityDigitalMiner.canInsert(TileEntityDigitalMiner.java:416)
	at mekanism.common.tile.TileEntityDigitalMiner.onUpdate(TileEntityDigitalMiner.java:213)
	at mekanism.common.tile.TileEntityBasicBlock.func_145845_h(TileEntityBasicBlock.java:59)

-- Block entity being ticked --
Details:
	Name: DigitalMiner // mekanism.common.tile.TileEntityDigitalMiner
	Block type: ID #856 (tile.MachineBlock // mekanism.common.block.BlockMachine)
	Block data value: 4 / 0x4 / 0b0100
	Block location: World: (-3809,61,709), Chunk: (at 15,3,5 in -239,44; contains blocks -3824,0,704 to -3809,255,719), Region: (-8,1; contains chunks -256,32 to -225,63, blocks -4096,0,512 to -3585,255,1023)
	Actual block type: ID #856 (tile.MachineBlock // mekanism.common.block.BlockMachine)
	Actual block data value: 4 / 0x4 / 0b0100
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:2491)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)

-- Affected level --
Details:
	Level name: world
	All players: 19 total; [GCEntityPlayerMP['Gogas'/541, l='world', x=-1464.53, y=12.00, z=-1972.32](Gogas at -1464.5281017530367,12.0,-1972.317705369969), GCEntityPlayerMP['MrWatcher'/3502, l='world', x=156.50, y=68.00, z=323.37](MrWatcher at 156.50140940665923,68.0,323.37171883868206), GCEntityPlayerMP['APXOHT'/16835, l='world', x=249.95, y=57.00, z=7943.70](APXOHT at 249.94872926355234,57.0,7943.699999988079), GCEntityPlayerMP['kazama17'/32300, l='world', x=6360.57, y=70.00, z=-780.74](kazama17 at 6360.565771862992,70.0,-780.7418833769332), GCEntityPlayerMP['KiLka'/35485, l='world', x=6974.81, y=19.00, z=-4746.43](KiLka at 6974.806201503753,19.0,-4746.426114145055), GCEntityPlayerMP['DrakonChik_Pro'/45453, l='world', x=6359.86, y=70.00, z=-788.98](DrakonChik_Pro at 6359.8592742565215,70.0,-788.9797630844954), GCEntityPlayerMP['Anemis'/54056, l='world', x=902.53, y=44.00, z=273.90](Anemis at 902.5295739221013,44.0,273.90414578719873), GCEntityPlayerMP['HamsterGold'/57379, l='world', x=-1288.42, y=69.00, z=-429.30](HamsterGold at -1288.421474255731,69.0,-429.30000001192093), GCEntityPlayerMP['AIIOCYM'/80193, l='world', x=-77.34, y=63.42, z=479.65](AIIOCYM at -77.33816881396126,63.41999998688698,479.65080454756264), GCEntityPlayerMP['shaxter'/60001, l='world', x=-702.04, y=70.00, z=110.51](shaxter at -702.0392527294684,70.0,110.50886398862409), GCEntityPlayerMP['PsyhoShark'/24747, l='world', x=153.94, y=68.00, z=321.45](PsyhoShark at 153.9441812098393,68.0,321.4461472105418), GCEntityPlayerMP['MrDiamond1006'/87276, l='world', x=612.27, y=31.00, z=-315.78](MrDiamond1006 at 612.269500168742,31.0,-315.77990925362786), GCEntityPlayerMP['Anigami'/49791, l='world', x=543.18, y=73.00, z=-7703.11](Anigami at 543.1771077719129,73.0,-7703.114840757943), GCEntityPlayerMP['mene'/62330, l='world', x=517.26, y=64.00, z=-398.27](mene at 517.2584111139798,64.0,-398.2696563111153), GCEntityPlayerMP['Fraydom'/102339, l='world', x=-70.73, y=63.00, z=-579.34](Fraydom at -70.73308907936463,63.0,-579.344813441995), GCEntityPlayerMP['Lankaster-_'/22914, l='world', x=-125.65, y=64.00, z=9666.86](Lankaster-_ at -125.64619746750294,64.0,9666.862205176412), GCEntityPlayerMP['VipDeath'/46496, l='world', x=7175.34, y=48.00, z=6710.13](VipDeath at 7175.33825767215,48.0,6710.125878835481), GCEntityPlayerMP['GameSIT'/118504, l='world', x=-3810.18, y=61.00, z=706.85](GameSIT at -3810.181416222455,61.0,706.8535941875668), GCEntityPlayerMP['g4nst3r'/118703, l='world', x=5113.40, y=68.00, z=-5663.05](g4nst3r at 5113.3993629982015,68.0,-5663.050971928828)]
	Chunk stats: ServerChunkCache: 1698 Drop: 0
	Level seed: 2451159423915798400
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: BIOMESOP
	Level spawn location: World: (33,182,-6), Chunk: (at 1,11,10 in 2,-1; contains blocks 32,0,-16 to 47,255,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 42913153 game time, 48281672 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 5391 (now: false), thunder time: 63254 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:943)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows Server 2012 R2 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 14423983960 bytes (13755 MB) / 16777216000 bytes (16000 MB) up to 16777216000 bytes (16000 MB)
	JVM Flags: 31 total; -Xms16000m -Xmx16000m -XX:MaxPermSize=512m -XX:+UnlockCommercialFeatures -XX:+UseLargePages -XX:+AggressiveOpts -XX:+UseAdaptiveSizePolicy -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:UseSSE=4 -XX:+DisableExplicitGC -XX:MaxGCPauseMillis=100 -XX:ParallelGCThreads=8 -XX:ThreadPriorityPolicy=42 -XX:CompileThreshold=1500 -XX:+TieredCompilation -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=15 -XX:+UnlockExperimentalVMOptions -XX:+UseAdaptiveGCBoundary -XX:PermSize=1024M -XX:+UseGCOverheadLimit -XX:+UseBiasedLocking -Xnoclassgc -Xverify:none -XX:+UseThreadPriorities -XX:+UseStringCache -XX:+OptimizeStringConcat -XX:+UseFastAccessorMethods -Xrs -XX:+UseCompressedOops
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 17331, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.85.1236 Cauldron-MCPC-Plus vgit-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212 (MC: 1.7.10) (API v1.7.10-R0.1-SNAPSHOT) Minecraft Forge 10.13.2.1236 64 mods loaded, 64 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.85.1236} [Forge Mod Loader] (cauldron-1.7.10-1.1236.05.212-server.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.2.1236} [Minecraft Forge] (cauldron-1.7.10-1.1236.05.212-server.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	appliedenergistics2-core{rv2-beta-1} [AppliedEnergistics2 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	<CoFH ASM>{000} [CoFH ASM Data Initialization] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	minecraftloader{0.1} [MinecraftLoader] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NotEnoughItems{1.0.3.76} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.3.76-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	IC2{2.2.657-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.657-experimental.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AdvancedMachines{1.1.3} [IC2 Advanced Machines Addon] (AdvancedMachinesAS-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels] (AdvancedSolarPanel-1.7.10-3.5.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	appliedenergistics2{rv2-beta-1} [Applied Energistics 2] (appliedenergistics2-rv2-beta-1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Backpack{2.0.1} [Backpack] (backpack-2.0.1-1.7.x.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CoFHCore{1.7.10R3.0.0B9} [CoFH Core] (CoFHCore-[1.7.10]3.0.0B9-40.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BigReactors{0.4.0A} [Big Reactors] (BigReactors-0.4.0A.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1034-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	customnpcs{1.7.10b} [CustomNpcs] (CustomNPCs_1.7.10b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	DragonMounts{r41-1.7.10} [Dragon Mounts] (DragonMounts-r41-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	flansmod{4.8.0} [Flan's Mod] (Flans Mod-1.7.10-4.8.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	GalacticraftCore{3.0.6} [Galacticraft Core] (GalacticraftCore-1.7-3.0.6.247.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	GalacticraftMars{3.0.6} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.6.247.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	GraviSuite{1.7.10-2.0.3} [Graviation Suite] (GraviSuite-1.7.10-2.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	headshots{0.3} [Headshots] (Headshot-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	IC2LaserFix{2.0} [IC2 Laser Fix] (IC2LaserFix-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	IC2NuclearControl{2.0.8c} [Nuclear Control 2] (IC2NuclearControl-2.0.8c.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	inventorytweaks{1.58-147-645ca10} [Inventory Tweaks] (InventoryTweaks-1.58-147.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded{1.7.10R2.8.0RC6} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ForgeMultipart{1.1.0.314} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Mekanism{7.1.1} [Mekanism] (Mekanism-1.7.10-7.1.1.135.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MekanismGenerators{7.1.1} [MekanismGenerators] (MekanismGenerators-1.7.10-7.1.1.135.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MekanismTools{7.1.1} [MekanismTools] (MekanismTools-1.7.10-7.1.1.135.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0RC6} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatAtum{1.7.10R2.8.0RC6} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0RC6} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0RC6} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0RC6} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0RC6} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatForestry{1.7.10R2.8.0RC6} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0RC6} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatIC2{1.7.10R2.8.0RC6} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0RC6} [MFR Compat: Mystcraft] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0RC6} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0RC6} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatRP2{1.7.10R2.8.0RC6} [MFR Compat: RP2] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0RC6} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Baubles{1.0.1.8} [Baubles] (Baubles-1.7.10-1.0.1.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Thaumcraft{4.2.1.4} [Thaumcraft] (Thaumcraft-1.7.10-4.2.1.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0RC6} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0RC6} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Waila{1.5.6a} [Waila] (Waila-1.5.6a_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	TConstruct{1.7.10-1.7.1.build771} [Tinkers' Construct] (TConstruct-1.7.10-1.7.1c.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0RC6} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	TwilightForest{2.3.2} [The Twilight Forest] (twilightforest-1.7.10-2.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0RC6} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0RC6} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	numina{0.4.0.100} [Numina] (Numina-0.4.0.100.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	powersuits{0.11.0.176} [MachineMuse's Modular Powersuits] (ModularPowersuits-0.11.0.176.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NetherOres{1.7.10R2.3.0RC3} [Nether Ores] (NetherOres-[1.7.10]2.3.0RC3-84.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ResonantEngine{3.3.0} [Resonant Engine] (resonant-engine-3.3.0.368-core.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	McMultipart{1.1.0.314} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ForgeMicroblock{1.1.0.314} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AE2 Version: beta rv2-beta-1 for Forge 10.13.2.1230
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: bukkit
	TConstruct Environment: Environment healthy.
	AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:OFF, BC:OFF, MJ6:OFF, MJ5:OFF, RF:ON, RFItem:ON, MFR:ON, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Mekanism:ON, ImmibisMicroblocks:OFF, BetterStorage:OFF
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 19 / 100; [GCEntityPlayerMP['Gogas'/541, l='world', x=-1464.53, y=12.00, z=-1972.32](Gogas at -1464.5281017530367,12.0,-1972.317705369969), GCEntityPlayerMP['MrWatcher'/3502, l='world', x=156.50, y=68.00, z=323.37](MrWatcher at 156.50140940665923,68.0,323.37171883868206), GCEntityPlayerMP['APXOHT'/16835, l='world', x=249.95, y=57.00, z=7943.70](APXOHT at 249.94872926355234,57.0,7943.699999988079), GCEntityPlayerMP['kazama17'/32300, l='world', x=6360.57, y=70.00, z=-780.74](kazama17 at 6360.565771862992,70.0,-780.7418833769332), GCEntityPlayerMP['KiLka'/35485, l='world', x=6974.81, y=19.00, z=-4746.43](KiLka at 6974.806201503753,19.0,-4746.426114145055), GCEntityPlayerMP['DrakonChik_Pro'/45453, l='world', x=6359.86, y=70.00, z=-788.98](DrakonChik_Pro at 6359.8592742565215,70.0,-788.9797630844954), GCEntityPlayerMP['Anemis'/54056, l='world', x=902.53, y=44.00, z=273.90](Anemis at 902.5295739221013,44.0,273.90414578719873), GCEntityPlayerMP['HamsterGold'/57379, l='world', x=-1288.42, y=69.00, z=-429.30](HamsterGold at -1288.421474255731,69.0,-429.30000001192093), GCEntityPlayerMP['AIIOCYM'/80193, l='world', x=-77.34, y=63.42, z=479.65](AIIOCYM at -77.33816881396126,63.41999998688698,479.65080454756264), GCEntityPlayerMP['shaxter'/60001, l='world', x=-702.04, y=70.00, z=110.51](shaxter at -702.0392527294684,70.0,110.50886398862409), GCEntityPlayerMP['PsyhoShark'/24747, l='world', x=153.94, y=68.00, z=321.45](PsyhoShark at 153.9441812098393,68.0,321.4461472105418), GCEntityPlayerMP['MrDiamond1006'/87276, l='world', x=612.27, y=31.00, z=-315.78](MrDiamond1006 at 612.269500168742,31.0,-315.77990925362786), GCEntityPlayerMP['Anigami'/49791, l='world', x=543.18, y=73.00, z=-7703.11](Anigami at 543.1771077719129,73.0,-7703.114840757943), GCEntityPlayerMP['mene'/62330, l='world', x=517.26, y=64.00, z=-398.27](mene at 517.2584111139798,64.0,-398.2696563111153), GCEntityPlayerMP['Fraydom'/102339, l='world', x=-70.73, y=63.00, z=-579.34](Fraydom at -70.73308907936463,63.0,-579.344813441995), GCEntityPlayerMP['Lankaster-_'/22914, l='world', x=-125.65, y=64.00, z=9666.86](Lankaster-_ at -125.64619746750294,64.0,9666.862205176412), GCEntityPlayerMP['VipDeath'/46496, l='world', x=7175.34, y=48.00, z=6710.13](VipDeath at 7175.33825767215,48.0,6710.125878835481), GCEntityPlayerMP['GameSIT'/118504, l='world', x=-3810.18, y=61.00, z=706.85](GameSIT at -3810.181416222455,61.0,706.8535941875668), GCEntityPlayerMP['g4nst3r'/118703, l='world', x=5113.40, y=68.00, z=-5663.05](g4nst3r at 5113.3993629982015,68.0,-5663.050971928828)]
	Is Modded: Definitely; Server brand changed to 'cauldron,craftbukkit,mcpc,fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by aidancbrady** [comment]
Closing due to lack of activity
