### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by ScarecrowKrone** [aidancbrady/Mekanism#2060]
I am constantly getting this console spam on my server, and it occasionally is linked to server crashes. Since your mod is mentioned along with others I thought I'd report it here and then you can send me to go bother someone else if the fault does not lie with Mekanism.

[19:00:49] [Server thread/WARN] [/]: java.util.ConcurrentModificationException
[19:00:49] [Server thread/WARN] [/]: 	at java.util.LinkedHashMap$LinkedHashIterator.nextEntry(LinkedHashMap.java:394)
[19:00:49] [Server thread/WARN] [/]: 	at java.util.LinkedHashMap$KeyIterator.next(LinkedHashMap.java:405)
[19:00:49] [Server thread/WARN] [/]: 	at mekanism.api.transmitters.DynamicNetwork.fullRefresh(DynamicNetwork.java:95)
[19:00:49] [Server thread/WARN] [/]: 	at mekanism.common.multipart.PartTransmitter.getTransmitterNetwork(PartTransmitter.java:122)
[19:00:49] [Server thread/WARN] [/]: 	at mekanism.common.multipart.PartTransmitter.getTransmitterNetwork(PartTransmitter.java:86)
[19:00:49] [Server thread/WARN] [/]: 	at mekanism.common.multipart.PartTransmitter.refreshTransmitterNetwork(PartTransmitter.java:43)
[19:00:49] [Server thread/WARN] [/]: 	at TGridTransmitter$$14$class.refreshTransmitterNetwork(Unknown Source)
[19:00:49] [Server thread/WARN] [/]: 	at TileMultipart_cmp$$33.refreshTransmitterNetwork(Unknown Source)
[19:00:49] [Server thread/WARN] [/]: 	at mekanism.api.transmitters.TransmitterNetworkRegistry$NetworkLoader.refreshChunk(TransmitterNetworkRegistry.java:150)
[19:00:49] [Server thread/WARN] [/]: 	at mekanism.api.transmitters.TransmitterNetworkRegistry$NetworkLoader.onChunkLoad(TransmitterNetworkRegistry.java:132)
[19:00:49] [Server thread/WARN] [/]: 	at cpw.mods.fml.common.eventhandler.ASMEventHandler_616_NetworkLoader_onChunkLoad_Load.invoke(.dynamic)
[19:00:49] [Server thread/WARN] [/]: 	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
[19:00:49] [Server thread/WARN] [/]: 	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
[19:00:49] [Server thread/WARN] [/]: 	at net.minecraft.world.chunk.Chunk.func_76631_c(Chunk.java:1019)
[19:00:49] [Server thread/WARN] [/]: 	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:49)
[19:00:49] [Server thread/WARN] [/]: 	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:15)
[19:00:49] [Server thread/WARN] [/]: 	at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344)
[19:00:49] [Server thread/WARN] [/]: 	at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302)
[19:00:49] [Server thread/WARN] [/]: 	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12)
[19:00:49] [Server thread/WARN] [/]: 	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:164)
[19:00:49] [Server thread/WARN] [/]: 	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:137)
[19:00:49] [Server thread/WARN] [/]: 	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:260)
[19:00:49] [Server thread/WARN] [/]: 	at net.minecraft.world.World.func_72964_e(World.java:739)
[19:00:49] [Server thread/WARN] [/]: 	at net.minecraft.world.World.func_72921_c(World.java:891)
[19:00:49] [Server thread/WARN] [/]: 	at appeng.tile.networking.TileController.updateMeta(TileController.java:154)
[19:00:49] [Server thread/WARN] [/]: 	at appeng.tile.networking.TileController.onPowerChange(TileController.java:94)
[19:00:49] [Server thread/WARN] [/]: 	at sun.reflect.GeneratedMethodAccessor58.invoke(Unknown Source)
[19:00:49] [Server thread/WARN] [/]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:00:49] [Server thread/WARN] [/]: 	at java.lang.reflect.Method.invoke(Method.java:606)
[19:00:49] [Server thread/WARN] [/]: 	at appeng.me.NetworkEventBus$EventMethod.invoke(NetworkEventBus.java:41)
[19:00:49] [Server thread/WARN] [/]: 	at appeng.me.NetworkEventBus$MENetworkEventInfo.invoke(NetworkEventBus.java:70)
[19:00:49] [Server thread/WARN] [/]: 	at appeng.me.NetworkEventBus.postEventTo(NetworkEventBus.java:172)
[19:00:49] [Server thread/WARN] [/]: 	at appeng.me.Grid.postEventTo(Grid.java:186)
[19:00:49] [Server thread/WARN] [/]: 	at appeng.me.cache.EnergyGridCache.addNode(EnergyGridCache.java:311)
[19:00:49] [Server thread/WARN] [/]: 	at appeng.me.GridCacheWrapper.addNode(GridCacheWrapper.java:34)
[19:00:49] [Server thread/WARN] [/]: 	at appeng.me.Grid.add(Grid.java:150)
[19:00:49] [Server thread/WARN] [/]: 	at appeng.me.GridNode.setGrid(GridNode.java:444)
[19:00:49] [Server thread/WARN] [/]: 	at appeng.me.GridPropagator.visitNode(GridPropagator.java:21)
[19:00:49] [Server thread/WARN] [/]: 	at appeng.me.GridNode.visitorNode(GridNode.java:218)
[19:00:49] [Server thread/WARN] [/]: 	at appeng.me.GridNode.beginVisition(GridNode.java:186)
[19:00:49] [Server thread/WARN] [/]: 	at appeng.me.GridNode.validateGrid(GridNode.java:454)
[19:00:49] [Server thread/WARN] [/]: 	at appeng.me.GridConnection.destroy(GridConnection.java:111)
[19:00:49] [Server thread/WARN] [/]: 	at appeng.me.GridNode.destroy(GridNode.java:470)
[19:00:49] [Server thread/WARN] [/]: 	at appeng.me.helpers.AENetworkProxy.invalidate(AENetworkProxy.java:163)
[19:00:49] [Server thread/WARN] [/]: 	at appeng.tile.grid.AENetworkPowerTile.func_145843_s(AENetworkPowerTile.java:94)
[19:00:49] [Server thread/WARN] [/]: 	at appeng.tile.AEBaseTile.onChunkUnload(AEBaseTile.java:115)
[19:00:49] [Server thread/WARN] [/]: 	at appeng.tile.powersink.IC2.onChunkUnload(IC2.java:60)
[19:00:49] [Server thread/WARN] [/]: 	at appeng.tile.grid.AENetworkPowerTile.onChunkUnload(AENetworkPowerTile.java:79)
[19:00:49] [Server thread/WARN] [/]: 	at net.minecraft.world.World.func_72939_s(World.java:2448)
[19:00:49] [Server thread/WARN] [/]: 	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)
[19:00:49] [Server thread/WARN] [/]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:943)
[19:00:49] [Server thread/WARN] [/]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
[19:00:49] [Server thread/WARN] [/]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
[19:00:49] [Server thread/WARN] [/]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
[19:00:49] [Server thread/WARN] [/]: 	at java.lang.Thread.run(Thread.java:745)

**Comment by unpairedbracket** [comment]
I'm going to close this as #2059 seems to be the same issue and has had more activity.
