### ISSUE TITLE
[crash] Placing Cables

### ISSUE THREAD

**Issue by SheepRaider** [aidancbrady/Mekanism#2082]
When I placed a basic cable the game crashed and now I can't even play since it crash every time i load the map

---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 1/10/15 12:47 AM
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: cofh/api/energy/IEnergyProvider
	at mekanism.common.util.CableUtils.isOutputter(CableUtils.java:144)
	at mekanism.common.util.CableUtils.getConnections(CableUtils.java:114)
	at mekanism.common.util.CableUtils.getConnections(CableUtils.java:94)
	at mekanism.common.multipart.PartUniversalCable.isValidAcceptor(PartUniversalCable.java:225)
	at mekanism.common.multipart.PartSidedPipe.getPossibleAcceptorConnections(PartSidedPipe.java:212)
	at mekanism.common.multipart.PartSidedPipe.refreshConnections(PartSidedPipe.java:477)
	at mekanism.common.multipart.PartSidedPipe.onChunkLoad(PartSidedPipe.java:530)
	at codechicken.multipart.TileMultipart$$anonfun$onChunkLoad$1.apply(TileMultipart.scala:91)
	at codechicken.multipart.TileMultipart$$anonfun$onChunkLoad$1.apply(TileMultipart.scala:91)
	at codechicken.multipart.TileMultipart.operate(TileMultipart.scala:75)
	at codechicken.multipart.TileMultipart.onChunkLoad(TileMultipart.scala:91)
	at codechicken.multipart.TickScheduler$ChunkTickScheduler.load(TickScheduler.scala:240)
	at codechicken.lib.world.WorldExtension.loadChunk(WorldExtension.java:47)
	at codechicken.lib.world.WorldExtensionManager$WorldExtensionEventHandler.onChunkLoad(WorldExtensionManager.java:57)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_141_WorldExtensionEventHandler_onChunkLoad_Load.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraft.world.chunk.Chunk.func_76631_c(Chunk.java:923)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:46)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12)
	at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344)
	at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:265)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:130)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:153)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.ClassNotFoundException: cofh.api.energy.IEnergyProvider
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 30 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 32 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (x86) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 192271968 bytes (183 MB) / 464879616 bytes (443 MB) up to 1037959168 bytes (989 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 20, tcache: 0, allocated: 15, tallocated: 98
	FML: MCP v9.05 FML v7.10.85.1264 Minecraft Forge 10.13.2.1264 Optifine OptiFine_1.7.10_HD_B4 23 mods loaded, 23 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	FML{7.10.85.1264} [Forge Mod Loader] (forge-1.7.10-10.13.2.1264.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	Forge{10.13.2.1264} [Minecraft Forge] (forge-1.7.10-10.13.2.1264.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	MCVanillaTweaks{1.0} [Mariculture - Vanilla Tweaks] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	ArchimedesShips{1.7.10 v1.7.1} [Archimedes' Ships] (ArchimedesShips-1.7.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	dungeonpack{1.7.10-1.0} [Dungeon Pack] (dungeonpack-1.7.10-1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	Enchiridion{1.1} [Enchiridion] (Enchiridion-1.7.X-1.2b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	enhancedbiomes{2.4.1 for MC 1.7.10} [Enhanced Biomes] (Enhanced Biomes 2.5 for MC 1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	enhancedportals{3.0.9} [EnhancedPortals] (EnhancedPortals_1.7.10-universal-3.0.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	reaper_lantern{1.45} [Lantern mod] (Lantern1.45[1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	Mariculture{1.2.4a} [Mariculture] (Mariculture-Base-1.7.10-1.2.4a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	radixcore{1.3.4} [RadixCore] (RadixCore-1.7.10-1.3.4-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	mca{4.1.5} [Minecraft Comes Alive] (MCA-1.7.10-4.1.5-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	ForgeMultipart{1.1.0.314} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	Mekanism{7.1.1} [Mekanism] (Mekanism-1.7.10-7.1.1.127.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	MekanismGenerators{7.1.1} [MekanismGenerators] (MekanismGenerators-1.7.10-7.1.1.127.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	MekanismTools{7.1.1} [MekanismTools] (MekanismTools-1.7.10-7.1.1.127.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	cfm{3.4.7} [§9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.7(1.7.10).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	harvestcraft{1.7.10b} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10c.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	primitivemobs{1.0} [Primitive Mobs] (primitivemobs-1.0c-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	SpawnCommands{2.0.0} [SpawnCommands] (SpawnCommands-v2.0.0-mc1.7.10-forge.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	McMultipart{1.1.0.314} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	ForgeMicroblock{1.1.0.314} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by EEVV** [comment]
Ill try this with java 1.8 now

**Comment by EEVV** [comment]
I can confirm this is an incompatibility issue with thermal expansion.

**Comment by EEVV** [comment]
ok i had this issue without using redstone arsenal. I read something about the same problem.

**Comment by EEVV** [comment]
And as soon as i add in computer craft and openccsensors it shows the same thing

**Comment by EEVV** [comment]
openccsensors is the problem!

**Comment by grimallq** [comment]
Spam much? There is an edit button

One (or more) of your mods has an outdated CofH Energy API. Update everything that is using RF Power.

**Comment by unpairedbracket** [comment]
Thanks @grimallq - @EEVV, do what grimallq says, that should fix it.

**Comment by radfast** [comment]
Hello @unpairedbracket, you may be interested in https://github.com/micdoodle8/Galacticraft/commit/7d8331bc47aee29c119685f59674e1e10585905b and https://github.com/micdoodle8/Galacticraft/issues/791 - you're welcome to use anything from that commit if it is helpful to you.
