### ISSUE TITLE
Crash with Forestry and Mekanism

### ISSUE THREAD

**Issue by Dinmagol** [aidancbrady/Mekanism#2101]
All I know is, that forestry crashes with mekanism. I disabled all features of forestry, but the backpacks. only reason, i added it.
it fixed something, but not all. ideas?

---- Minecraft Crash Report ----
// Why did you do that?

Description: Initializing game

java.lang.NoClassDefFoundError: mekanism/common/tile/TileEntityChanceMachine
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at cpw.mods.fml.common.ProxyInjector.inject(ProxyInjector.java:59)
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:492)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:492)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:204)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: mekanism.common.tile.TileEntityChanceMachine
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 35 more
Caused by: java.lang.NoClassDefFoundError: mekanism/common/tile/TileEntityBasicMachine
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 37 more
Caused by: java.lang.ClassNotFoundException: mekanism.common.tile.TileEntityBasicMachine
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 41 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at cpw.mods.fml.common.ProxyInjector.inject(ProxyInjector.java:59)
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:492)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:492)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:204)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.7.0_71, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 589912880 bytes (562 MB) / 965738496 bytes (921 MB) up to 1908932608 bytes (1820 MB)
	JVM Flags: 3 total; -Xms256M -Xmx2048M -XX:PermSize=256m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1263 Minecraft Forge 10.13.2.1263 132 mods loaded, 132 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed
	FML{7.10.85.1263} [Forge Mod Loader] (forge-1.7.10-10.13.2.1263-universal.jar) Unloaded->Constructed
	Forge{10.13.2.1263} [Minecraft Forge] (forge-1.7.10-10.13.2.1263-universal.jar) Unloaded->Constructed
	appliedenergistics2-core{rv2-alpha-26} [AppliedEnergistics2 Core] (minecraft.jar) Unloaded->Constructed
	Aroma1997Core{1.0.2.13} [Aroma1997Core] (Aroma1997Core-1.7.10-1.0.2.13.jar) Unloaded->Constructed
	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed
	<CoFH ASM>{000} [CoFH ASM Data Initialization] (minecraft.jar) Unloaded->Constructed
	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) Unloaded->Constructed
	MobiusCore{1.2.3} [MobiusCore] (minecraft.jar) Unloaded->Constructed
	NotEnoughItems{1.0.3.67} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.3.67-universal.jar) Unloaded->Constructed
	ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) Unloaded->Constructed
	OpenModsCore{0.6} [OpenModsCore] (minecraft.jar) Unloaded->Constructed
	lotr{Beta v18.2 for Minecraft 1.7.10} [The Lord of the Rings Mod] ([1.7.10] The Lord of the Rings Mod Public Beta 18.2.jar) Unloaded->Constructed
	appliedenergistics2{rv2-alpha-26} [Applied Energistics 2] (appliedenergistics2-rv2-alpha-26.jar) Unloaded->Constructed
	ArchimedesShips{1.7.10 v1.7.1} [Archimedes' Ships] (ArchimedesShips-1.7.1.jar) Unloaded->Constructed
	Aroma1997CoreHelper{1.0.2.13} [Aroma1997Core|Helper] (Aroma1997Core-1.7.10-1.0.2.13.jar) Unloaded->Constructed
	ATG{0.10.0} [Alternate Terrain Generation] (ATG-1.7.2-0.10.0.jar) Unloaded->Constructed
	bdlib{1.5.1.32} [BD Lib] (bdlib-mc1710-1.5.1.32.jar) Unloaded->Constructed
	BetterTitleScreen{1.7.10-1.1} [Better Title Screen] (BetterTitleScreen-1.7.10-1.1.jar) Unloaded->Constructed
	BiblioCraft{1.9.1} [BiblioCraft] (BiblioCraft[v1.9.1][MC1.7.10].jar) Unloaded->Constructed
	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1019-universal.jar) Unloaded->Constructed
	BiblioWoodsBoP{1.9} [BiblioWoods Biomes O'Plenty Edition] (BiblioWoods[BiomesOPlenty][v1.9].jar) Unloaded->Constructed
	CoFHCore{1.7.10R3.0.0B8} [CoFH Core] (CoFHCore-[1.7.10]3.0.0B8-36.jar) Unloaded->Constructed
	Forestry{3.3.0.6} [Forestry for Minecraft] (forestry_1.7.10-3.3.0.6.jar) Unloaded->Constructed
	BiblioWoodsForestry{1.7} [BiblioWoods Forestry Edition] (BiblioWoods[Forestry][v1.7].jar) Unloaded->Constructed
	ThermalFoundation{1.7.10R1.0.0B3} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.0.0B3-8.jar) Unloaded->Constructed
	ThermalExpansion{1.7.10R4.0.0B6} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.0B6-16.jar) Unloaded->Constructed
	BigReactors{0.4.1A2} [Big Reactors] (BigReactors-0.4.1A2.jar) Unloaded->Constructed
	AWWayofTime{v1.3.0b} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.0b-3.jar) Unloaded->Constructed
	bluepower{0.1.766} [Blue Power] (BluePower-1.7.10-0.1.766-universal.jar) Unloaded->Constructed
	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed
	Thaumcraft{4.2.1.4} [Thaumcraft] (Thaumcraft-1.7.10-4.2.1.4.jar) Unloaded->Constructed
	Botania{r1.3-152} [Botania] (Botania r1.3-152.jar) Unloaded->Constructed
	CarpentersBlocks{3.3.3} [Carpenter's Blocks] (Carpenter's Blocks v3.3.3 - MC 1.7.10.jar) Unloaded->Constructed
	ChickenChunks{1.3.4.14} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.14-universal.jar) Unloaded->Constructed
	chisel{1.5.7} [Chisel] (Chisel-1.7.10-1.5.7.jar) Unloaded->Constructed
	DynamicLights{1.3.7} [Dynamic Lights] (DynamicLights-1.7.10.jar) Unloaded->Constructed
	DynamicLights_onFire{1.0.4} [Dynamic Lights Burning Entity Module] (DynamicLights-1.7.10.jar) Unloaded->Constructed
	DynamicLights_creepers{1.0.4} [Dynamic Lights Creeper Module] (DynamicLights-1.7.10.jar) Unloaded->Constructed
	DynamicLights_dropItems{1.0.7} [Dynamic Lights EntityItem Module] (DynamicLights-1.7.10.jar) Unloaded->Constructed
	DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module] (DynamicLights-1.7.10.jar) Unloaded->Constructed
	DynamicLights_mobEquipment{1.0.7} [Dynamic Lights Mob Equipment Light Module] (DynamicLights-1.7.10.jar) Unloaded->Constructed
	DynamicLights_flameArrows{1.0.0} [Dynamic Lights Fiery Arrows Light Module] (DynamicLights-1.7.10.jar) Unloaded->Constructed
	DynamicLights_floodLights{1.0.1} [Dynamic Lights Flood Light] (DynamicLights-1.7.10.jar) Unloaded->Constructed
	DynamicLights_otherPlayers{1.0.7} [Dynamic Lights OtherPlayers Light Module] (DynamicLights-1.7.10.jar) Unloaded->Constructed
	DynamicLights_thePlayer{1.1.3} [Dynamic Lights Player Light Module] (DynamicLights-1.7.10.jar) Unloaded->Constructed
	Enchiridion{1.1} [Enchiridion] (Enchiridion-1.7.X-1.2b.jar) Unloaded->Constructed
	EnderStorage{1.4.5.25} [EnderStorage] (EnderStorage-1.7.10-1.4.5.25-universal.jar) Unloaded->Constructed
	Waila{1.5.5} [Waila] (Waila-1.5.5_1.7.10.jar) Unloaded->Constructed
	extracells{2.2.40} [ExtraCells] (ExtraCells-1.7.10-2.2.40b66.jar) Unloaded->Constructed
	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed
	MineFactoryReloaded{1.7.10R2.8.0RC5} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded->Constructed
	TConstruct{1.7.10-1.8.2.build858} [Tinkers' Construct] (TConstruct-1.7.10-1.8.2a.jar) Unloaded->Constructed
	ExtraTiC{0.8.4} [ExtraTiC] (ExtraTiC-1.7.10-1.0.3.jar) Unloaded->Constructed
	ForgeMultipart{1.1.0.314} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed
	ExtraUtilities{1.2.0} [Extra Utilities] (extrautilities-1.2.0.jar) Unloaded->Constructed
	fognerf{1.7.10-0.3} [Fog Nerf] (fognerf-1.7.10-0.4.jar) Unloaded->Constructed
	GalacticraftCore{3.0.7} [Galacticraft Core] (GalacticraftCore-1.7-3.0.7.255.jar) Unloaded->Constructed
	GalacticraftMars{3.0.7} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.7.255.jar) Unloaded->Constructed
	GraveStone{2.11.3} [GraveStone] (GraveStone-2.11.3.jar) Unloaded->Constructed
	InfernalMobs{1.5.9} [Infernal Mobs] (InfernalMobs-1.7.10.jar) Unloaded->Constructed
	inpure|core{1.7.10R1.0.0B7} [INpureCore] (INpureCore-[1.7.10]1.0.0B7-19.jar) Unloaded->Constructed
	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) Unloaded->Constructed
	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) Unloaded->Constructed
	JABBA{1.1.4} [JABBA] (Jabba-1.1.4_1.7.10.jar) Unloaded->Constructed
	journeymap{5.0.1} [JourneyMap] (JourneyMap5.0.1_Unlimited_MC1.7.10.jar) Unloaded->Constructed
	Railcraft{9.4.0.0} [Railcraft] (Railcraft_1.7.10-9.4.0.0.jar) Unloaded->Constructed
	RedstoneArsenal{1.7.10R1.1.0RC1} [Redstone Arsenal] (RedstoneArsenal-[1.7.10]1.1.0RC1-19.jar) Unloaded->Constructed
	Mekanism{7.1.0} [Mekanism] (Mekanism-1.7.10-7.1.0.92.jar) Unloaded
	MekanismGenerators{7.1.0} [MekanismGenerators] (MekanismGenerators-1.7.10-7.1.0.92.jar) Unloaded
	MekanismTools{7.1.0} [MekanismTools] (MekanismTools-1.7.10-7.1.0.92.jar) Unloaded
	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0RC5} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded
	MineFactoryReloaded|CompatAtum{1.7.10R2.8.0RC4} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded
	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0RC5} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded
	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0RC4} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded
	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0RC4} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded
	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0RC4} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded
	MineFactoryReloaded|CompatForestry{1.7.10R2.8.0RC5} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded
	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0RC4} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded
	MineFactoryReloaded|CompatIC2{1.7.10R2.8.0RC4} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded
	MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0RC4} [MFR Compat: Mystcraft] (MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded
	MrTJPCoreMod{1.0} [MrTJPCoreMod] (MrTJPCore-1.7.10-1.0.3.5-universal.jar) Unloaded
	ProjRed|Core{4.5.8.59} [ProjectRed] (ProjectRed-1.7.10-4.5.8.59-Base.jar) Unloaded
	ProjRed|Exploration{4.5.8.59} [ProjectRed-Exploration] (ProjectRed-1.7.10-4.5.8.59-World.jar) Unloaded
	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0RC4} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded
	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0RC4} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded
	MineFactoryReloaded|CompatRP2{1.7.10R2.8.0RC4} [MFR Compat: RP2] (MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded
	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0RC4} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded
	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0RC5} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded
	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0RC4} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded
	TwilightForest{2.3.2} [The Twilight Forest] (twilightforest-1.7.10-2.3.2.jar) Unloaded
	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0RC5} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded
	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0RC5} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.0RC5-694.jar) Unloaded
	NEIAddons{1.12.2.9} [NEI Addons] (neiaddons-mc1710-1.12.2.9.jar) Unloaded
	NEIAddons|Botany{1.12.2.9} [NEI Addons: Botany] (neiaddons-mc1710-1.12.2.9.jar) Unloaded
	NEIAddons|Forestry{1.12.2.9} [NEI Addons: Forestry] (neiaddons-mc1710-1.12.2.9.jar) Unloaded
	NEIAddons|CraftingTables{1.12.2.9} [NEI Addons: Crafting Tables] (neiaddons-mc1710-1.12.2.9.jar) Unloaded
	NEIAddons|ExNihilo{1.12.2.9} [NEI Addons: Ex Nihilo] (neiaddons-mc1710-1.12.2.9.jar) Unloaded
	neiintegration{1.0.1} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.1.jar) Unloaded
	notenoughkeys{@MOD_VERSION@} [NotEnoughKEys] (NotEnoughKeys-1.7.10-1.0.0b29.jar) Unloaded
	ObsidiPlates{3.0.0.18} [ObsidiPlates] (ObsidiPlates-1.7.10-universal-3.0.0.18.jar) Unloaded
	OpenMods{0.6} [OpenMods] (OpenModsLib-1.7.10-0.6-snapshot-268.jar) Unloaded
	OpenBlocks{1.3} [OpenBlocks] (OpenBlocks-1.7.10-1.3-snapshot-513.jar) Unloaded
	MapWriter{2.1.1} [MapWriter] (Opis-1.2.3_1.7.10.jar) Unloaded
	Opis{1.2.3} [Opis] (Opis-1.2.3_1.7.10.jar) Unloaded
	ProjRed|Transmission{4.5.8.59} [ProjectRed-Transmission] (ProjectRed-1.7.10-4.5.8.59-Integration.jar) Unloaded
	ProjRed|Transportation{4.5.8.59} [ProjectRed-Transportation] (ProjectRed-1.7.10-4.5.8.59-Mechanical_beta.jar) Unloaded
	ProjRed|Compatibility{4.5.8.59} [ProjectRed-Compatibility] (ProjectRed-1.7.10-4.5.8.59-Compat.jar) Unloaded
	ProjRed|Integration{4.5.8.59} [ProjectRed-Integration] (ProjectRed-1.7.10-4.5.8.59-Integration.jar) Unloaded
	ProjRed|Illumination{4.5.8.59} [ProjectRed-Illumination] (ProjectRed-1.7.10-4.5.8.59-Lighting.jar) Unloaded
	ProjRed|Expansion{4.5.8.59} [ProjectRed-Expansion] (ProjectRed-1.7.10-4.5.8.59-Mechanical_beta.jar) Unloaded
	libsandstone{1.0.0} [libsandstone] (LibSandstone-1.0.0.jar) Unloaded
	xreliquary{1.2} [Reliquary] (Reliquary-1.2.223.jar) Unloaded
	secretroomsmod{4.7.1} [The SecretRoomsMod] (secretroomsmod-1.7.10-4.7.1.376.jar) Unloaded
	SpecialMobs{3.0.3} [Special Mobs] (SpecialMobs-1.7.10-3.0.3.jar) Unloaded
	ThaumicTinkerer{unspecified} [Thaumic Tinkerer] (ThaumicTinkerer-2.5-1.7.10-161.jar) Unloaded
	erebus{0.2pre11c} [Erebus] (TheErebus-0.2pre11c.jar) Unloaded
	TiCTooltips{1.2.1} [TiC Tooltips] (TiCTooltips-mc1.7.10-1.2.1.jar) Unloaded
	TMechworks{1.7.10-86.e500b88} [Tinkers' Mechworks] (TMechworks-1.7.10-0.2.10.jar) Unloaded
	torchLevers{1.4.1} [Torch Levers] (TorchLeversV1.4.1.jar) Unloaded
	Translocator{1.1.1.13} [Translocator] (Translocator-1.7.10-1.1.1.13-universal.jar) Unloaded
	WailaHarvestability{1.1.0} [Waila Harvestability] (WailaHarvestability-mc1.7.x-1.1.0.jar) Unloaded
	wawla{1.0.9} [What Are We Looking At] (Wawla-1.0.9_1.7.10.jar) Unloaded
	weaponmod{v1.14.3} [Balkon's WeaponMod] (weaponmod-1.14.3.jar) Unloaded
	witchery{0.22.0} [Witchery] (witchery-1.7.10-0.22.0.jar) Unloaded
	WR-CBE|Core{1.4.1.9} [WR-CBE Core] (WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded
	WR-CBE|Addons{1.4.1.9} [WR-CBE Addons] (WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded
	WR-CBE|Logic{1.4.1.9} [WR-CBE Logic] (WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded
	McMultipart{1.1.0.314} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded
	aobd{2.3.6} [Another One Bites The Dust] (AOBD-2.3.6.jar) Unloaded
	IguanaTweaksTConstruct{1.7.10-2.1.2.101} [Iguana Tinker Tweaks] (IguanaTinkerTweaks-1.7.10-2.1.2.jar) Unloaded
	ForgeMicroblock{1.1.0.314} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded
	OpenModsLib crash transformers: [gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED],[map_gen_fix:ENABLED],[movement_callback:FINISHED],[stencil_patches:FINISHED]
	AE2 Version: alpha rv2-alpha-26 for Forge 10.13.2.1230
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
	Launched Version: 1.7.10
	LWJGL: 2.9.1
	OpenGL: GeForce GTS 450/PCIe/SSE2 GL version 4.4.0 NVIDIA 344.75, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [JSTR.zip]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by unpairedbracket** [comment]
Try installing the IC2 API http://ic2api.player.to:8080/job/IC2_experimental/

**Comment by Dinmagol** [comment]
Thank you, for the quick response.
Though your idea didn't changed a thing.

**Comment by grimallq** [comment]
@Dinmagol I think this was one of those weird bugs fixed ~20 versions ago, nobody even remembers they existed. Mind updating? You're still on build 92.

**Comment by aidancbrady** [comment]
Ah yes, IC2 issue
