### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by Flukethoughts** [aidancbrady/Mekanism#2125]
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextEntry(HashMap.java:922)
	at java.util.HashMap$ValueIterator.next(HashMap.java:950)
	at mekanism.common.EnergyNetwork.getAcceptors(EnergyNetwork.java:234)
	at mekanism.common.EnergyNetwork.doEmit(EnergyNetwork.java:176)
	at mekanism.common.EnergyNetwork.tickEmit(EnergyNetwork.java:148)
	at mekanism.common.EnergyNetwork.onUpdate(EnergyNetwork.java:359)
	at mekanism.api.transmitters.DynamicNetwork.tick(DynamicNetwork.java:305)
	at mekanism.api.transmitters.TransmitterNetworkRegistry.tickEnd(TransmitterNetworkRegistry.java:85)
	at mekanism.api.transmitters.TransmitterNetworkRegistry.onTick(TransmitterNetworkRegistry.java:73)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_299_TransmitterNetworkRegistry_onTick_ServerTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:252)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:851)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
	at java.lang.Thread.run(Thread.java:745)

**Comment by aidancbrady** [comment]
Should be fixed
