### ISSUE TITLE
Minecraft crashing when placing logistical tranporter "pipe"

### ISSUE THREAD

**Issue by DurekuRyuu** [aidancbrady/Mekanism#2147]
So yeah, every time i place a logistical transporter my Minecraft crashes.
Can i please get some help?
My current mod list is:

InvTweaks
Optifine
Minecraft coder pack
FML 
Forge
Code chicken core
NEI
Chicken chunks
Universal electricity
Mekanism
Mekanism generators
Numina
Power converters
Forge multipart
Forge microblocks

Crash report as follows:

Time: 2/20/15 3:41 PM
Description: Unexpected error

java.lang.NoClassDefFoundError: mekanism/common/multipart/PartLogisticalTransporter$TransporterPipeProxy
	at mekanism.common.multipart.PartLogisticalTransporter.<init>(PartLogisticalTransporter.java:65)
	at mekanism.common.multipart.PartSidedPipe.getPartType(PartSidedPipe.java:116)
	at mekanism.common.multipart.ItemPartTransmitter.newPart(ItemPartTransmitter.java:77)
	at codechicken.multipart.TItemMultiPart$class.place$1(ItemMultiPart.scala:32)
	at codechicken.multipart.TItemMultiPart$class.onItemUse(ItemMultiPart.scala:47)
	at codechicken.multipart.JItemMultiPart.func_77648_a(ItemMultiPart.scala:14)
	at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:129)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(PlayerControllerMP.java:353)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1435)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1941)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: mekanism.common.multipart.PartLogisticalTransporter$TransporterPipeProxy
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	... 19 more
Caused by: java.lang.NoClassDefFoundError: buildcraft/api/transport/IPipe
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 21 more
Caused by: java.lang.ClassNotFoundException: buildcraft.api.transport.IPipe
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	... 26 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at mekanism.common.multipart.PartLogisticalTransporter.<init>(PartLogisticalTransporter.java:65)
	at mekanism.common.multipart.PartSidedPipe.getPartType(PartSidedPipe.java:116)
	at mekanism.common.multipart.ItemPartTransmitter.newPart(ItemPartTransmitter.java:77)
	at codechicken.multipart.TItemMultiPart$class.place$1(ItemMultiPart.scala:32)
	at codechicken.multipart.TItemMultiPart$class.onItemUse(ItemMultiPart.scala:47)
	at codechicken.multipart.JItemMultiPart.func_77648_a(ItemMultiPart.scala:14)
	at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:129)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(PlayerControllerMP.java:353)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1435)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['DrakeQuiLau'/83, l='MpServer', x=140.00, y=65.62, z=-195.72]]
	Chunk stats: MultiplayerChunkCache: 289, 298
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (133,4,-201), Chunk: (at 5,0,7 in 8,-13; contains blocks 128,0,-208 to 143,255,-193), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 1539 game time, 1539 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 27 total; [EntityPig['Pig'/9, l='MpServer', x=78.50, y=64.00, z=-131.50], EntityBat['Bat'/10, l='MpServer', x=94.28, y=39.00, z=-245.53], EntityZombie['Zombie'/11, l='MpServer', x=90.50, y=40.00, z=-247.50], EntityBat['Bat'/12, l='MpServer', x=93.06, y=39.00, z=-247.56], EntityPig['Pig'/13, l='MpServer', x=84.22, y=64.00, z=-131.78], EntityPig['Pig'/14, l='MpServer', x=85.81, y=64.00, z=-130.19], EntityPig['Pig'/15, l='MpServer', x=81.78, y=64.00, z=-132.34], EntityZombie['Zombie'/17, l='MpServer', x=97.50, y=40.00, z=-248.50], EntityBat['Bat'/19, l='MpServer', x=95.50, y=39.00, z=-247.13], EntityBat['Bat'/18, l='MpServer', x=96.00, y=39.00, z=-245.88], EntityClientPlayerMP['DrakeQuiLau'/83, l='MpServer', x=140.00, y=65.62, z=-195.72], EntityItem['item.item.seeds'/20, l='MpServer', x=98.09, y=62.13, z=-246.41], EntityCreeper['Creeper'/88, l='MpServer', x=171.50, y=33.00, z=-242.50], EntityItem['item.item.seeds'/28, l='MpServer', x=121.03, y=63.13, z=-226.75], EntityZombie['Zombie'/31, l='MpServer', x=168.69, y=33.00, z=-235.84], EntityBat['Bat'/90, l='MpServer', x=95.50, y=39.00, z=-245.25], EntityItem['item.item.seeds'/30, l='MpServer', x=156.56, y=64.13, z=-216.84], EntityBat['Bat'/32, l='MpServer', x=178.48, y=33.53, z=-240.49], EntityItem['item.item.seeds'/33, l='MpServer', x=165.72, y=64.13, z=-231.22], EntityCreeper['Creeper'/39, l='MpServer', x=198.50, y=22.00, z=-226.50], EntityCow['Cow'/42, l='MpServer', x=202.50, y=64.00, z=-132.50], EntityCow['Cow'/43, l='MpServer', x=202.50, y=64.00, z=-134.19], EntityCow['Cow'/40, l='MpServer', x=202.50, y=64.00, z=-135.78], EntityCow['Cow'/41, l='MpServer', x=204.50, y=64.00, z=-134.50], EntitySlime['Slime'/59, l='MpServer', x=217.47, y=23.00, z=-237.31], EntityWaypointContainer['unknown'/183, l='MpServer', x=0.00, y=0.00, z=0.00], EntityBat['Bat'/60, l='MpServer', x=211.88, y=34.00, z=-208.59]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2432)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:916)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Mac OS X (x86_64) version 10.9.5
	Java Version: 1.6.0_65, Apple Inc.
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Apple Inc.
	Memory: 191652040 bytes (182 MB) / 412246016 bytes (393 MB) up to 7507476480 bytes (7159 MB)
	Mod Pack: Unknown / None
	LiteLoader Mods: 2 loaded mod(s)
          - Gammabright version 3.1
          - VoxelMap version 1.2.1
	LaunchWrapper: 29 active transformer(s)
          - Transformer: cpw.mods.fml.common.asm.transformers.PatchingTransformer
          - Transformer: optifine.OptiFineClassTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.MarkerTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.SideTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.EventSubscriptionTransformer
          - Transformer: codechicken.lib.asm.ClassHeirachyManager
          - Transformer: codechicken.core.asm.InterfaceDependancyTransformer
          - Transformer: codechicken.core.asm.TweakTransformer
          - Transformer: codechicken.core.asm.DelegatedTransformer
          - Transformer: codechicken.core.asm.DefaultImplementationTransformer
          - Transformer: invtweaks.forge.asm.ContainerTransformer
          - Transformer: codechicken.nei.asm.NEITransformer
          - Transformer: universalelectricity.compatibility.asm.UniversalTransformer
          - Transformer: com.mumfrey.liteloader.transformers.event.EventProxyTransformer
          - Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CrashReportTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.DeobfuscationTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.AccessTransformer
          - Transformer: net.minecraftforge.transformers.ForgeAccessTransformer
          - Transformer: codechicken.core.asm.CodeChickenAccessTransformer
          - Transformer: invtweaks.forge.asm.ITAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ItemStackTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.TerminalTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.LiteLoaderEventInjectionTransformer
          - Transformer: com.thevoxelbox.voxelmap.litemod.VoxelMapTransformer
          - Transformer: com.mumfrey.liteloader.common.transformers.LiteLoaderPacketTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.MinecraftOverlayTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAPITransformer
	JVM Flags: 3 total; -Xmx7168m -Xincgc -XX:MaxPermSize=256m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 Optifine OptiFine_1.7.10_HD_U_B1 16 mods loaded, 16 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.85.1291} [Forge Mod Loader] (modpack.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.2.1291} [Minecraft Forge] (modpack.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CodeChickenCore{1.0.4.35} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NotEnoughItems{1.0.4.83} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.83-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ChickenChunks{1.3.4.17} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.17-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	inventorytweaks{1.58-147-645ca10} [Inventory Tweaks] (InventoryTweaks-1.58-147.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	UniversalElectricity{@MAJOR@.@MINOR@.@REVIS@} [Universal Electricity] (universal-electricity-4.0.0.88-core.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ForgeMultipart{1.1.1.320} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Mekanism{7.1.1} [Mekanism] (Mekanism-1.7.10-7.1.1.127.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MekanismGenerators{7.1.1} [MekanismGenerators] (MekanismGenerators-1.7.10-7.1.1.127.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MekanismTools{7.1.1} [MekanismTools] (MekanismTools-1.7.10-7.1.1.127.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	numina{0.4.0.87} [Numina] (Numina-0.4.0.87.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	PowerConverters{1.7.10-3.0.4.46} [Power Converters] (PowerConverters-1.7.10-3.0.4.46.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	McMultipart{1.1.1.320} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ForgeMicroblock{1.1.1.320} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Launched Version: 1.7.10-Forge10.13.2.1291
	LWJGL: 2.9.1
	OpenGL: NVIDIA GeForce GTX 660M OpenGL Engine GL version 2.1 NVIDIA-8.26.28 310.40.55b01, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by aidancbrady** [comment]
Looks to me like a mod conflict.  Try using just Mekanism and see if it works.

**Comment by MinecraftGuy800** [comment]
It happens even with just mekanism...
