### ISSUE TITLE
Issues with the Digital Miner

### ISSUE THREAD

**Issue by MastaC729** [aidancbrady/Mekanism#2167]
When it gets to the end of the list (around 300-600 blocks left to mine, the server throws the following error:

Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at net.minecraft.item.ItemStack.func_77976_d(ItemStack.java:187)
	at mekanism.common.tile.TileEntityDigitalMiner.canInsert(TileEntityDigitalMiner.java:421)
	at mekanism.common.tile.TileEntityDigitalMiner.onUpdate(TileEntityDigitalMiner.java:213)
	at mekanism.common.tile.TileEntityBasicBlock.func_145845_h(TileEntityBasicBlock.java:59)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.item.ItemStack.func_77976_d(ItemStack.java:187)
	at mekanism.common.tile.TileEntityDigitalMiner.canInsert(TileEntityDigitalMiner.java:421)
	at mekanism.common.tile.TileEntityDigitalMiner.onUpdate(TileEntityDigitalMiner.java:213)
	at mekanism.common.tile.TileEntityBasicBlock.func_145845_h(TileEntityBasicBlock.java:59)

-- Block entity being ticked --
Details:
	Name: DigitalMiner // mekanism.common.tile.TileEntityDigitalMiner
	Block type: ID #1684 (tile.MachineBlock // mekanism.common.block.BlockMachine)
	Block data value: 4 / 0x4 / 0b0100
	Block location: World: (578,55,1628), Chunk: (at 2,3,12 in 36,101; contains blocks 576,0,1616 to 591,255,1631), Region: (1,3; contains chunks 32,96 to 63,127, blocks 512,0,1536 to 1023,255,2047)
	Actual block type: ID #1684 (tile.MachineBlock // mekanism.common.block.BlockMachine)
	Actual block data value: 4 / 0x4 / 0b0100
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: world
	All players: 2 total; [EntityPlayerMP['xk_cortex'/703, l='world', x=-203.30, y=251.70, z=622.09], EntityPlayerMP['MastaC729'/350, l='world', x=584.82, y=60.77, z=1658.76]]
	Chunk stats: ServerChunkCache: 1787 Drop: 0
	Level seed: -4327795169150375818
	Level generator: ID 04 - BIOMESOP, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (467,64,941), Chunk: (at 3,4,13 in 29,58; contains blocks 464,0,928 to 479,255,943), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,0,512 to 511,255,1023)
	Level time: 13264529 game time, 4235628 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 20391 (now: false), thunder time: 10552 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

Let me know if you need me to supply anything else.

**Comment by aidancbrady** [comment]
This was fixed - please update to the latest Mekanism build.
