### ISSUE TITLE
Galacticraft water eletrolizer + gas conduit = java.lang.NullPointerException: Ticking block entity

### ISSUE THREAD

**Issue by 23Link89** [aidancbrady/Mekanism#2195]
Crash:
---- Minecraft Crash Report ----
// Oops.

Time: 3/10/15 7:47 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at micdoodle8.mods.galacticraft.planets.mars.tile.TileEntityElectrolyzer.drawGas(TileEntityElectrolyzer.java:455)
	at crazypants.enderio.conduit.gas.GasConduitNetwork.extractFrom(GasConduitNetwork.java:242)
	at crazypants.enderio.conduit.gas.GasConduit.doExtract(GasConduit.java:101)
	at crazypants.enderio.conduit.gas.GasConduit.updateEntity(GasConduit.java:75)
	at crazypants.enderio.conduit.TileConduitBundle.func_145845_h(TileConduitBundle.java:216)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at micdoodle8.mods.galacticraft.planets.mars.tile.TileEntityElectrolyzer.drawGas(TileEntityElectrolyzer.java:455)
	at crazypants.enderio.conduit.gas.GasConduitNetwork.extractFrom(GasConduitNetwork.java:242)
	at crazypants.enderio.conduit.gas.GasConduit.doExtract(GasConduit.java:101)
	at crazypants.enderio.conduit.gas.GasConduit.updateEntity(GasConduit.java:75)
	at crazypants.enderio.conduit.TileConduitBundle.func_145845_h(TileConduitBundle.java:216)

-- Block entity being ticked --
Details:
	Name: blockConduitBundleTileEntity // crazypants.enderio.conduit.TileConduitBundle
	Block type: ID #593 (tile.blockConduitBundle // crazypants.enderio.conduit.BlockConduitBundle)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-90,18,1005), Chunk: (at 6,1,13 in -6,62; contains blocks -96,0,992 to -81,255,1007), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,0,512 to -1,255,1023)
	Actual block type: ID #593 (tile.blockConduitBundle // crazypants.enderio.conduit.BlockConduitBundle)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: TEST MOD
	All players: 1 total; [GCEntityPlayerMP['23link89'/93, l='TEST MOD', x=-88.41, y=17.00, z=1005.31]]
	Chunk stats: ServerChunkCache: 1089 Drop: 0
	Level seed: -4907925741736817213
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by halvors** [comment]
This doesn't look like a Mekanism issue. Think this belongs on the Galacticraft bugtracker.

**Comment by aidancbrady** [comment]
Not Mekanism :)
