### ISSUE TITLE
Tried to test last build for version 8, but had a cyclical dependency error

### ISSUE THREAD

**Issue by kotoroshinoto** [aidancbrady/Mekanism#2198]
[16:52:29] [Server thread/ERROR] [FML]: A dependency cycle was detected in the input mod set so an ordering cannot be determined
[16:52:29] [Server thread/ERROR] [FML]: The first mod in the cycle is FMLMod:EnderIO{1.7.10-2.2.8.349}
[16:52:29] [Server thread/ERROR] [FML]: The mod cycle involves
[16:52:29] [Server thread/ERROR] [FML]: Dummy Container (After) @2097918299 : before: [], after: []
[16:52:29] [Server thread/ERROR] [FML]: APIContainer{MekanismAPI|core:8.0.0} : before: [EnderIO], after: [Mekanism]
[16:52:29] [Server thread/ERROR] [FML]: FMLMod:Mekanism{8.0.0} : before: [], after: [ForgeMultipart, BuildCraftAPI|power, BuildCraftAPI|tools, BuildCraftAPI|transport, IC2API, CoFHAPI|energy, ComputerCraft, Galacticraft API, MineFactoryReloaded, MetallurgyCore, EnderIO, ExtraUtilities, Railcraft, Forestry, RedstoneArsenal]
[16:52:29] [Server thread/ERROR] [FML]: Dummy Container (AfterAll) @398228595 : before: [], after: []
[16:52:29] [Server thread/ERROR] [FML]: FMLMod:EnderIO{1.7.10-2.2.8.349} : before: [], after: [Forge@10.13.0.1150,), MineFactoryReloaded]
[16:52:29] [Server thread/ERROR] [FML]: The full error
cpw.mods.fml.common.toposort.ModSortingException: There was a cycle detected in the input graph, sorting is not possible
        at cpw.mods.fml.common.toposort.TopologicalSort.explore(TopologicalSort.java:190) ~[TopologicalSort.class:?]
        at cpw.mods.fml.common.toposort.TopologicalSort.explore(TopologicalSort.java:199) ~[TopologicalSort.class:?]
        at cpw.mods.fml.common.toposort.TopologicalSort.explore(TopologicalSort.java:199) ~[TopologicalSort.class:?]
        at cpw.mods.fml.common.toposort.TopologicalSort.explore(TopologicalSort.java:199) ~[TopologicalSort.class:?]
        at cpw.mods.fml.common.toposort.TopologicalSort.explore(TopologicalSort.java:199) ~[TopologicalSort.class:?]
        at cpw.mods.fml.common.toposort.TopologicalSort.explore(TopologicalSort.java:199) ~[TopologicalSort.class:?]
        at cpw.mods.fml.common.toposort.TopologicalSort.topologicalSort(TopologicalSort.java:145) ~[TopologicalSort.class:?]
        at cpw.mods.fml.common.toposort.ModSorter.sort(ModSorter.java:133) ~[ModSorter.class:?]
        at cpw.mods.fml.common.Loader.sortModList(Loader.java:256) [Loader.class:?]
        at cpw.mods.fml.common.Loader.loadMods(Loader.java:472) [Loader.class:?]
        at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87) [FMLServerHandler.class:?]
        at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314) [FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117) [lt.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[16:52:29] [Server thread/ERROR]: Encountered an unexpected exception
cpw.mods.fml.common.toposort.ModSortingException: There was a cycle detected in the input graph, sorting is not possible

**Comment by kotoroshinoto** [comment]
Mekanism api has condition Before enderio and and after mekanism
Mekanism has condition: after enderio.

(it also reports : enderio has condition: after forge and after MFR but i dont think thats the problem here)

**Comment by kotoroshinoto** [comment]
looking at the repo, the file:
./src/main/java/mekanism/common/Mekanism.java:
contains the line				"after:MineFactoryReloaded;after:MetallurgyCore;after:EnderIO;after:ExtraUtilities;after:Railcraft;after:Forestry;after:RedstoneArsenal")


so why would the API think that it was supposed to load BEFORE enderio?

**Comment by aidancbrady** [comment]
Merging with #2180

**Comment by codewarrior0** [comment]
Is there a good reason why Mekanism v8 needs to be loaded after EnderIO?

The problem is that EnderIO uses v8's MekanismAPI|gas, which implicitly requires Mekanism, which explicitly requires EnderIO in its `required-before` dependency. Removing EnderIO from Mek's `required-before` resolves the cycle and allows the game to start up.

**Comment by kotoroshinoto** [comment]
maybe you could split the API and the rest of the mod so that one can load first and the other can load last?
