### ISSUE TITLE
Version 8 not compatible with AoBD 2.4.0

### ISSUE THREAD

**Issue by codewarrior0** [aidancbrady/Mekanism#2205]
Relevant portion of log file:

```
[23:02:32] [Client thread/ERROR] [FML/]: Caught exception from aobd
java.lang.NoClassDefFoundError: mekanism/api/AdvancedInput
	at ganymedes01.aobd.recipes.modules.MekanismModule.initOre(MekanismModule.java:63) ~[MekanismModule.class:?]
	at ganymedes01.aobd.recipes.RecipesModule.init(RecipesModule.java:37) ~[RecipesModule.class:?]
	at ganymedes01.aobd.recipes.ModulesHandler.init(ModulesHandler.java:31) ~[ModulesHandler.class:?]
	at ganymedes01.aobd.AOBD.init(AOBD.java:72) ~[AOBD.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
```

Probably AoBD's problem and not yours. Just making a note of it.

**Comment by unpairedbracket** [comment]
When we release v8 it'll be up to them to update AoBD, as our api has changed. Until then it wouldn't make sense for them to do so.
