### ISSUE TITLE
Game crash with v1.7.10-7.1.2.185

### ISSUE THREAD

**Issue by liamnotneeson** [aidancbrady/Mekanism#2209]
Here's the crash report:
java.lang.UnsupportedClassVersionError: mekanism/common/asm/LoadingHook : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.6.0_65]
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637) ~[?:1.6.0_65]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621) ~[?:1.6.0_65]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141) ~[?:1.6.0_65]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283) ~[?:1.6.0_65]
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58) ~[?:1.6.0_65]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197) ~[?:1.6.0_65]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.6.0_65]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190) ~[?:1.6.0_65]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306) ~[?:1.6.0_65]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247) ~[?:1.6.0_65]
	at java.lang.Class.forName0(Native Method) ~[?:1.6.0_65]
	at java.lang.Class.forName(Class.java:249) ~[?:1.6.0_65]

**Comment by Maxiebyte** [comment]
Updata Java.

**Comment by liamnotneeson** [comment]
Okay I just did and it still crashed

**Comment by grimallq** [comment]
New log?

**Comment by liamnotneeson** [comment]
What do you mean?

**Comment by Maxiebyte** [comment]
Grmialiq means the crash that happens **after** you updated Java.

**Comment by liamnotneeson** [comment]
Grmialiq isn't in the crash report

**Comment by halvors** [comment]
Think i'm also experiencing this, Client crashen on join whenever there are energfy cubes i think.

**Comment by Maxiebyte** [comment]
@liamnotneeson Sorry, it was a typo. Grimallq means the crash that happens **after** you updated Java.
