### ISSUE TITLE
Gas-Burning Generator Crash (NPE) (Version 7.1.2.185)

### ISSUE THREAD

**Issue by karlzoller** [aidancbrady/Mekanism#2210]
NullPointerException thrown when picking up and re-placing an empty gas-burning generator. 

Steps to repro:
1. Craft new Gas-burning generator.
2. Place generator 
3. Break generator with a tool retrieve (Strictly game mode 0)
4. Place generator back down (Strictly game mode 0)

If the generator contains any gas when picked up and replaced then no crash occurs.

Stack trace:
```
java.lang.NullPointerException: Unexpected error
	at mekanism.generators.common.tile.TileEntityGasGenerator.readSustainedData(TileEntityGasGenerator.java:327)
	at mekanism.generators.common.item.ItemBlockGenerator.placeBlockAt(ItemBlockGenerator.java:177)
	at net.minecraft.item.ItemBlock.func_77648_a(ItemBlock.java:103)
	at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:129)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(PlayerControllerMP.java:360)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1436)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1942)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:962)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

```

**Comment by NitroxydeX** [comment]
I see there is a fix from @Dannerick. When it's pushed to the Jenkins?

Same error happening to me:

---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 16.03.15 15:10
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at mekanism.generators.common.tile.TileEntityGasGenerator.readSustainedData(TileEntityGasGenerator.java:327)
	at mekanism.generators.common.item.ItemBlockGenerator.placeBlockAt(ItemBlockGenerator.java:177)
	at net.minecraft.item.ItemBlock.func_77648_a(ItemBlock.java:103)
	at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:129)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(PlayerControllerMP.java:360)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1435)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1941)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at mekanism.generators.common.tile.TileEntityGasGenerator.readSustainedData(TileEntityGasGenerator.java:327)
	at mekanism.generators.common.item.ItemBlockGenerator.placeBlockAt(ItemBlockGenerator.java:177)
	at net.minecraft.item.ItemBlock.func_77648_a(ItemBlock.java:103)
	at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:129)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(PlayerControllerMP.java:360)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1435)

**Comment by aidancbrady** [comment]
Merged!
