### ISSUE TITLE
Crash on game load

### ISSUE THREAD

**Issue by estebes** [aidancbrady/Mekanism#2254]
---- Minecraft Crash Report ----
// You're mean.

Time: 3/20/15 7:33 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoSuchMethodError: mekanism.common.recipe.RecipeHandler.addChemicalInjectionChamberRecipe(Lmekanism/api/AdvancedInput;Lnet/minecraft/item/ItemStack;)V
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:692)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:288)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:541)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoSuchMethodError: mekanism.common.recipe.RecipeHandler.addChemicalInjectionChamberRecipe(Lmekanism/api/AdvancedInput;Lnet/minecraft/item/ItemStack;)V
	at ganymedes01.aobd.recipes.modules.MekanismModule.initOre(MekanismModule.java:63)
	at ganymedes01.aobd.recipes.RecipesModule.init(RecipesModule.java:37)
	at ganymedes01.aobd.recipes.ModulesHandler.init(ModulesHandler.java:31)
	at ganymedes01.aobd.AOBD.init(AOBD.java:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:691)

**Comment by unpairedbracket** [comment]
There should be a new version of AOBD out any minute (possibly already is) to support Mekanism 8.

**Comment by aidancbrady** [comment]
Happy that the first v8 issue is a compat issue!  @ganymedes01, time to push the Mekanism integration update :)

**Comment by estebes** [comment]
Ty for the fast response :) can't wait to try the new fusion rector

**Comment by unpairedbracket** [comment]
Hope you enjoy it, and I hope you enjoy the level of infrastructure required to make it run smoothly :P

**Comment by estebes** [comment]
In my current world i've dedicated myself to go full ic2. Dont think it cant get any "grindier" than that ahah. Will report if any more crashes or bugs are found.

**Comment by ganymedes01** [comment]
I'll be releasing the fixed version soon :3
