### ISSUE TITLE
Placing Hohlraum causes crash, can't reload

### ISSUE THREAD

**Issue by Greylocke** [aidancbrady/Mekanism#2296]
Now this is a fun one...

In a working (but not active) reactor, I placed a new Hohlraum in the Controller and hit it with 500MJ. It did not ignite. When I opened the Controller again, the Hohlraum was still there. I clicked on it to pull it out of the Controller, but it disappeared. So I made a new one, dropped it in, then got this error. Now the world will not load.

---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 3/21/15 5:38 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at mekanism.generators.common.FusionReactor.hasHohlraum(FusionReactor.java:99)
	at mekanism.generators.common.FusionReactor.simulate(FusionReactor.java:123)
	at mekanism.generators.common.tile.reactor.TileEntityReactorController.onUpdate(TileEntityReactorController.java:115)
	at mekanism.common.tile.TileEntityBasicBlock.func_145845_h(TileEntityBasicBlock.java:73)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by aidancbrady** [comment]
Fixed in development :)
