### ISSUE TITLE
Crash when crafting factory

### ISSUE THREAD

**Issue by plumpudding** [aidancbrady/Mekanism#2311]
Compiled from this commit: https://github.com/aidancbrady/Mekanism/tree/f8f1467304c1c60332ad3e9559308d0e64edf4a2

with NEI 1.0.4.90 and CCC 1.0.4.35

crashed when crafting an enriching factory

also I used an AE2 crafting terminal, but it crashed with a crafting terminal too

Log:
[20:20:52] [Client thread/INFO] [STDOUT/]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
// Sorry :(

Time: 22.03.15 20:20
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at mekanism.common.recipe.MekanismRecipe.func_77572_b(MekanismRecipe.java:221)
	at net.minecraft.item.crafting.CraftingManager.func_82787_a(CraftingManager.java:325)
	at appeng.container.implementations.ContainerCraftingTerm.func_75130_a(ContainerCraftingTerm.java:59)
	at appeng.container.slot.SlotCraftingMatrix.func_75215_d(SlotCraftingMatrix.java:60)
	at net.minecraft.inventory.Container.func_75144_a(SourceFile:157)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78753_a(PlayerControllerMP.java:419)
	at codechicken.nei.guihook.GuiContainerManager.handleSlotClick(GuiContainerManager.java:503)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146984_a(GuiContainer.java:638)
	at appeng.client.gui.AEBaseGui.func_146984_a(AEBaseGui.java:399)
	at net.minecraft.client.gui.inventory.GuiContainer.public_func_146984_a(GuiContainer.java)
	at codechicken.nei.guihook.DefaultSlotClickHandler.callHandleMouseClick(DefaultSlotClickHandler.java)
	at codechicken.nei.guihook.DefaultSlotClickHandler.handleSlotClick(DefaultSlotClickHandler.java:17)
	at codechicken.nei.guihook.GuiContainerManager.handleMouseClick(GuiContainerManager.java:452)
	at net.minecraft.client.gui.inventory.GuiContainer.managerHandleMouseClick(GuiContainer.java)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java:590)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:306)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
	at appeng.client.gui.AEBaseGui.func_146274_d(AEBaseGui.java:141)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1628)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
	at mekanism.common.recipe.MekanismRecipe.func_77572_b(MekanismRecipe.java:221)
	at net.minecraft.item.crafting.CraftingManager.func_82787_a(CraftingManager.java:325)
	at appeng.container.implementations.ContainerCraftingTerm.func_75130_a(ContainerCraftingTerm.java:59)
	at appeng.container.slot.SlotCraftingMatrix.func_75215_d(SlotCraftingMatrix.java:60)
	at net.minecraft.inventory.Container.func_75144_a(SourceFile:157)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78753_a(PlayerControllerMP.java:419)
	at codechicken.nei.guihook.GuiContainerManager.handleSlotClick(GuiContainerManager.java:503)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146984_a(GuiContainer.java:638)
	at appeng.client.gui.AEBaseGui.func_146984_a(AEBaseGui.java:399)
	at net.minecraft.client.gui.inventory.GuiContainer.public_func_146984_a(GuiContainer.java)
	at codechicken.nei.guihook.DefaultSlotClickHandler.callHandleMouseClick(DefaultSlotClickHandler.java)
	at codechicken.nei.guihook.DefaultSlotClickHandler.handleSlotClick(DefaultSlotClickHandler.java:17)
	at codechicken.nei.guihook.GuiContainerManager.handleMouseClick(GuiContainerManager.java:452)
	at net.minecraft.client.gui.inventory.GuiContainer.managerHandleMouseClick(GuiContainer.java)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java:590)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:306)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
	at appeng.client.gui.AEBaseGui.func_146274_d(AEBaseGui.java:141)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)

-- Affected screen --
Details:
	Screen name: appeng.client.gui.implementations.GuiCraftingTerm

**Comment by Stette** [comment]
Had the same crash!  https://github.com/aidancbrady/Mekanism/issues/2306

**Comment by plumpudding** [comment]
now trying to get the crash when this happens in a crafting table, 
also trying the same in a fresh world

**Comment by aidancbrady** [comment]
Fixed!

**Comment by Stette** [comment]
Nice @aidancbrady! Is there a newer build out somewhere? I used used your Jenkins before, but it seems to be down?

**Comment by plumpudding** [comment]
https://www.dropbox.com/sh/1adjevdhqvse4ds/AACcTX_HIqEuO2Sn6n-apt7xa?dl=0

freshly baked from latest development

**Comment by unpairedbracket** [comment]
@plumpudding out of interest (in relation to #2307), are you compiling on Windows? I'm looking for someone who has successfully done so, to see if it's possible.

**Comment by plumpudding** [comment]
No I am using Arch Linux

**Comment by Slamper** [comment]
@unpairedbracket I'm able to build on Windows except the last step releaseJAR. But even if that step fails the working JARS can be found in ./outputs

**Comment by unpairedbracket** [comment]
Yeah, Windows seems to have issues with gradle copy jobs.
