### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by saytheb** [aidancbrady/Mekanism#2318]
Running into the following crash with 8.0.1 and 8.0.0. I can't figure out where the heck this is coming from as this is the entire crash message (crash log is at: http://pastebin.com/swTErh4w)

Any ideas? (I've checked Galacticraft and the Mekanism folder does not exist in the jar.)

java.lang.NullPointerException
	at mekanism.api.gas.GasNetwork.getAcceptors(GasNetwork.java:315) ~[GasNetwork.class:?]
	at mekanism.api.gas.GasNetwork.tickEmit(GasNetwork.java:146) ~[GasNetwork.class:?]
	at mekanism.api.gas.GasNetwork.onUpdate(GasNetwork.java:259) ~[GasNetwork.class:?]
	at mekanism.api.transmitters.DynamicNetwork.tick(DynamicNetwork.java:280) ~[DynamicNetwork.class:?]
	at mekanism.api.transmitters.TransmitterNetworkRegistry.tickEnd(TransmitterNetworkRegistry.java:85) ~[TransmitterNetworkRegistry.class:?]
	at mekanism.api.transmitters.TransmitterNetworkRegistry.onTick(TransmitterNetworkRegistry.java:73) ~[TransmitterNetworkRegistry.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_887_TransmitterNetworkRegistry_onTick_ServerTickEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:?]
	at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:247) [FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:590) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]

**Comment by Cracks777** [comment]
mekanism has updated there api and most mods that connect gas to have not updated there api yet, so you crash? are you using ender io?

**Comment by saytheb** [comment]
Yep, but this is also with 8.0.1 which as unpairedbracket commented in your report to EIO should have had backwards compatibility added (https://github.com/SleepyTrousers/EnderIO/issues/2141)

**Comment by Cracks777** [comment]
yes thats what i thought too, but 

<Kodos> You should tweet a link to the download page for us lazy folks
[18:05] <Cracks777_> aidancbrady, ender io gas conduits are still crashing sometimes, like when you hook them up to a gas tank.
[18:05] <aidancbrady> yeah - we’ll have to wait for them to update
[18:06] <Cracks777_> ok,
[18:07] <aidancbrady> it looks like tterrag1098 already has it fixed in development: https://github.com/SleepyTrousers/EnderIO/commit/752342d15d3077288bfd8e8fd0c5d1c58236c2d8

**Comment by Cracks777** [comment]
it did fix some things but didnt solve all the problems so we have to wait for ender io to update the api

**Comment by aidancbrady** [comment]
Added a null check, don't know how this could happen though.

**Comment by saytheb** [comment]
Was this null check add in 8.0.1.198? If so, the crash is still present. Thanks for the fast response!
