### ISSUE TITLE
NullPointerException on placement of a dynamic tank.

### ISSUE THREAD

**Issue by HeliosDK** [aidancbrady/Mekanism#2355]
java.lang.NullPointerException
	at mekanism.common.tile.TileEntityContainerBlock.func_70302_i_(TileEntityContainerBlock.java:82) ~[TileEntityContainerBlock.class:?]
	at enviromine.handlers.RotHandler.rotInvo(RotHandler.java:81) ~[RotHandler.class:?]
	at enviromine.handlers.EM_EventManager.onPlayerInteract(EM_EventManager.java:416) ~[EM_EventManager.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_373_EM_EventManager_onPlayerInteract_PlayerInteractEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:?]
	at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:100) [ForgeEventFactory.class:?]
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1434) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1941) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_40]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_40]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_40]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_40]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]

**Comment by HeliosDK** [comment]
Client crashes but server continues on newest enviromine is used with mekanism 8.1.198

**Comment by aidancbrady** [comment]
Should be fixed in development

**Comment by karakufire** [comment]
I encounter this in 8.0.2.
Next of top line, 'at mekanism.common.tile.....', is similar as I encountered.
Perhaps different issue.
(Sorry maybe my writing is hard to read, I'm Japanese. If necessary, I write in Japanese.)

Here crash report:
java.lang.NullPointerException: Exception in server tick loop
	at mekanism.common.tile.TileEntityContainerBlock.func_70302_i_(TileEntityContainerBlock.java:82)
	at autounify.core.AutoUnify.onWorldTick(AutoUnify.java:262)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_34_AutoUnify_onWorldTick_WorldTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:255)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:645)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
