### ISSUE TITLE
Factory Server/Client Visual Desync?

### ISSUE THREAD

**Issue by Towsty** [aidancbrady/Mekanism#2367]
Currently using Mekanism 8.0.2.567 with Forge 1340

In this picture there are three basic factories. From left to right Crushing, Enriching, Smelting.
![2015-03-25_15 30 29](https://cloud.githubusercontent.com/assets/5897643/6834759/19d93a88-d304-11e4-975c-f14e518b6964.png)

In the image below I am looking at an Enriching factory even though it says Smelting. Sorting is on, the machine is getting power, and it is functioning the way it is supposed to. Though visually the sorting is off, the machine is not currently process, and the machine has no power. 
![2015-03-25_15 33 52](https://cloud.githubusercontent.com/assets/5897643/6834813/62434ed0-d304-11e4-91ef-61a872bc564e.png)

Each machine was upgraded using the basic factory upgrade.
Any thoughts?

**Comment by aidancbrady** [comment]
Does this happen every time you open the interface?

**Comment by Towsty** [comment]
Yes. Exact same

**Comment by Towsty** [comment]
This is the section of log that is output when I open the factory.

```javascript
java.lang.ArrayIndexOutOfBoundsException: 16842752
[15:58:43] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at     mekanism.common.tile.component.TileComponentUpgrade.read(TileComponentUpgrade.java:176)
[15:58:43] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at mekanism.common.tile.TileEntityBasicBlock.handlePacketData(TileEntityBasicBlock.java:123)
[15:58:43] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at mekanism.common.tile.TileEntityElectricBlock.handlePacketData(TileEntityElectricBlock.java:138)
[15:58:43] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at mekanism.common.tile.TileEntityFactory.handlePacketData(TileEntityFactory.java:666)
[15:58:43] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at mekanism.common.network.PacketTileEntity.onMessage(PacketTileEntity.java:27)
[15:58:43] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at mekanism.common.network.PacketTileEntity.onMessage(PacketTileEntity.java:17)
```

**Comment by Cracks777** [comment]
using the smelting elete factory mine are smelting, the arrow stays full for about 30 secs then it will drop the ingot and smelt another, but it pasues between each one

**Comment by Cracks777** [comment]
![image](https://cloud.githubusercontent.com/assets/10608111/6835529/662ff598-d309-11e4-9fb1-f208365090cf.png)

**Comment by Towsty** [comment]
I would like to add that this chunk of the log goes from line 89125 to line 320446 in repeating chunks

**Comment by Cracks777** [comment]
i updated to v570 and everything works fine

**Comment by aidancbrady** [comment]
Can't reproduce, there's a good chance it's a transition issue.  Break and replace the block :)

**Comment by Towsty** [comment]
I had broken and replaced them many times - I'm wondering if I had swapped out their core machines if it would have triggered somethin. Eitherway - updated to the latest dev build fixed the problem. Thanks for the help! Always a pleasure.
