### ISSUE TITLE
Power Converter and Cofh Core causing Crashes

### ISSUE THREAD

**Issue by ZerkonTerona** [aidancbrady/Mekanism#2379]
I've been getting this Error when I try to load up minecraft with forge. I'd been using Galacticraft and began installing a lot of mods, one by one, and they all worked find until I added Power Crystals' Converters Mod and its new core from Cofh. The reason I'm putting this here is because the first line seems to indicate that it's trying to find the Configurator, which is a mekanism item.Though some of the other lines seem to indicate that it's items from the cofh core that's the issue, resulting in me not really being sure one way or the other...

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 3/26/15 12:35 PM
Description: Initializing game

java.lang.NoClassDefFoundError: mekanism/common/item/ItemConfigurator
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at cpw.mods.fml.common.registry.ObjectHolderRegistry.scanTarget(ObjectHolderRegistry.java:70)
	at cpw.mods.fml.common.registry.ObjectHolderRegistry.findObjectHolders(ObjectHolderRegistry.java:39)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:512)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:239)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: mekanism.common.item.ItemConfigurator
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 15 more
Caused by: java.lang.NoClassDefFoundError: cofh/api/item/IToolHammer
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 17 more
Caused by: java.lang.ClassNotFoundException: cofh.api.item.IToolHammer
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 21 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 23 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at cpw.mods.fml.common.registry.ObjectHolderRegistry.scanTarget(ObjectHolderRegistry.java:70)
	at cpw.mods.fml.common.registry.ObjectHolderRegistry.findObjectHolders(ObjectHolderRegistry.java:39)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:512)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:239)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (x86) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 71784760 bytes (68 MB) / 286887936 bytes (273 MB) up to 523501568 bytes (499 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 38 mods loaded, 38 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed
	FML{7.10.85.1291} [Forge Mod Loader] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed
	Forge{10.13.2.1291} [Minecraft Forge] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed
	<CoFH ASM>{000} [CoFH ASM Data Initialization] (minecraft.jar) Unloaded->Constructed
	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) Unloaded->Constructed
	malisiscore{1.7.10-0.10.5+unknown-b0.git-unknown} [Malisis Core] (malisiscore-1.7.10-0.10.5.jar) Unloaded->Constructed
	ArchimedesShips{1.7.10 v1.7.1} [Archimedes' Ships] (ArchimedesShips-1.7.1.jar) Unloaded->Constructed
	BuildCraft|Core{6.4.5} [BuildCraft] (buildcraft-6.4.5.jar) Unloaded->Constructed
	BuildCraft|Transport{6.4.5} [BC Transport] (buildcraft-6.4.5.jar) Unloaded->Constructed
	BuildCraft|Silicon{6.4.5} [BC Silicon] (buildcraft-6.4.5.jar) Unloaded->Constructed
	BuildCraft|Builders{6.4.5} [BC Builders] (buildcraft-6.4.5.jar) Unloaded->Constructed
	BuildCraft|Energy{6.4.5} [BC Energy] (buildcraft-6.4.5.jar) Unloaded->Constructed
	BuildCraft|Factory{6.4.5} [BC Factory] (buildcraft-6.4.5.jar) Unloaded->Constructed
	CoFHCore{1.7.10R3.0.0B1} [CoFH Core] (CoFHCore-[1.7.10]3.0.0B1-19.jar) Unloaded->Constructed
	BuildMod{v1.0} [Build Mod] (CoroUtil-1.1.1.jar) Unloaded->Constructed
	CoroAI{v1.0} [CoroAI] (CoroUtil-1.1.1.jar) Unloaded->Constructed
	ExtendedRenderer{v1.0} [Extended Renderer] (CoroUtil-1.1.1.jar) Unloaded->Constructed
	ConfigMod{v1.0} [Extended Mod Config] (CoroUtil-1.1.1.jar) Unloaded->Constructed
	Eln{46} [Electrical Age] (ElectricalAge_BETA-1.9_r46.jar) Unloaded->Constructed
	EllianMaterialDetector{3.3.10} [Ellian's Material Detector] (EllianDetector_3.3.10.jar) Unloaded->Constructed
	flansmod{4.9.0} [Flan's Mod] (Flans Mod-1.7.10-4.9.0.jar) Unloaded->Constructed
	IC2{2.2.700-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.700-experimental.jar) Unloaded->Constructed
	GalacticraftCore{3.0.8} [Galacticraft Core] (GalacticraftCore-1.7-3.0.8.257.jar) Unloaded->Constructed
	GalacticraftMars{3.0.8} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.8.257.jar) Unloaded->Constructed
	VoltzEngine{0.1.0} [Voltz Engine] (VoltzEngine-1.7.10-0.1.0b81-dev.jar) Unloaded->Constructed
	icbm{2.3.0.75} [ICBM] (ICBM-1.7.10-2.3.0b75-dev.jar) Unloaded->Constructed
	malisisdoors{1.7.10-1.4.3} [Malisis' Doors] (malisisdoors-1.7.10-1.4.3.jar) Unloaded->Constructed
	ForgeMultipart{1.1.1.320} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded->Constructed
	Mekanism{8.0.2} [Mekanism] (Mekanism-1.7.10-8.0.2.201.jar) Unloaded->Constructed
	MekanismGenerators{8.0.2} [MekanismGenerators] (MekanismGenerators-1.7.10-8.0.2.201.jar) Unloaded->Constructed
	MekanismTools{8.0.2} [MekanismTools] (MekanismTools-1.7.10-8.0.2.201.jar) Unloaded->Constructed
	pandorasbox{2.0} [Pandora's Box] (PandorasBox-2.0.jar) Unloaded->Constructed
	PowerConverters{1.7.10-3.0.0.28} [Power Converters] (PowerConverters-1.7.10-3.0.0.28.jar) Unloaded->Constructed
	ResonantEngine{3.0.0} [Resonant Engine] (resonant-engine-3.0.0.255-core.jar) Unloaded->Constructed
	secretroomsmod{4.7.1} [The SecretRoomsMod] (secretroomsmod-1.7.10-4.7.1.409.jar) Unloaded->Constructed
	weather2{v2.3.6} [weather2] (Weather-2.3.7.jar) Unloaded->Constructed
	McMultipart{1.1.1.320} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded->Constructed
	ForgeMicroblock{1.1.1.320} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded->Constructed
	Launched Version: 1.7.10-Forge10.13.2.1291
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics 4600 GL version 4.2.0 - Build 10.18.10.3574, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 3/26/15 12:35 PM
Description: Initializing game

java.lang.NoClassDefFoundError: mekanism/common/item/ItemConfigurator
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at cpw.mods.fml.common.registry.ObjectHolderRegistry.scanTarget(ObjectHolderRegistry.java:70)
	at cpw.mods.fml.common.registry.ObjectHolderRegistry.findObjectHolders(ObjectHolderRegistry.java:39)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:512)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:239)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: mekanism.common.item.ItemConfigurator
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 15 more
Caused by: java.lang.NoClassDefFoundError: cofh/api/item/IToolHammer
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 17 more
Caused by: java.lang.ClassNotFoundException: cofh.api.item.IToolHammer
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 21 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 23 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at cpw.mods.fml.common.registry.ObjectHolderRegistry.scanTarget(ObjectHolderRegistry.java:70)
	at cpw.mods.fml.common.registry.ObjectHolderRegistry.findObjectHolders(ObjectHolderRegistry.java:39)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:512)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:239)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (x86) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 71784760 bytes (68 MB) / 286887936 bytes (273 MB) up to 523501568 bytes (499 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 38 mods loaded, 38 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed
	FML{7.10.85.1291} [Forge Mod Loader] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed
	Forge{10.13.2.1291} [Minecraft Forge] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed
	<CoFH ASM>{000} [CoFH ASM Data Initialization] (minecraft.jar) Unloaded->Constructed
	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) Unloaded->Constructed
	malisiscore{1.7.10-0.10.5+unknown-b0.git-unknown} [Malisis Core] (malisiscore-1.7.10-0.10.5.jar) Unloaded->Constructed
	ArchimedesShips{1.7.10 v1.7.1} [Archimedes' Ships] (ArchimedesShips-1.7.1.jar) Unloaded->Constructed
	BuildCraft|Core{6.4.5} [BuildCraft] (buildcraft-6.4.5.jar) Unloaded->Constructed
	BuildCraft|Transport{6.4.5} [BC Transport] (buildcraft-6.4.5.jar) Unloaded->Constructed
	BuildCraft|Silicon{6.4.5} [BC Silicon] (buildcraft-6.4.5.jar) Unloaded->Constructed
	BuildCraft|Builders{6.4.5} [BC Builders] (buildcraft-6.4.5.jar) Unloaded->Constructed
	BuildCraft|Energy{6.4.5} [BC Energy] (buildcraft-6.4.5.jar) Unloaded->Constructed
	BuildCraft|Factory{6.4.5} [BC Factory] (buildcraft-6.4.5.jar) Unloaded->Constructed
	CoFHCore{1.7.10R3.0.0B1} [CoFH Core] (CoFHCore-[1.7.10]3.0.0B1-19.jar) Unloaded->Constructed
	BuildMod{v1.0} [Build Mod] (CoroUtil-1.1.1.jar) Unloaded->Constructed
	CoroAI{v1.0} [CoroAI] (CoroUtil-1.1.1.jar) Unloaded->Constructed
	ExtendedRenderer{v1.0} [Extended Renderer] (CoroUtil-1.1.1.jar) Unloaded->Constructed
	ConfigMod{v1.0} [Extended Mod Config] (CoroUtil-1.1.1.jar) Unloaded->Constructed
	Eln{46} [Electrical Age] (ElectricalAge_BETA-1.9_r46.jar) Unloaded->Constructed
	EllianMaterialDetector{3.3.10} [Ellian's Material Detector] (EllianDetector_3.3.10.jar) Unloaded->Constructed
	flansmod{4.9.0} [Flan's Mod] (Flans Mod-1.7.10-4.9.0.jar) Unloaded->Constructed
	IC2{2.2.700-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.700-experimental.jar) Unloaded->Constructed
	GalacticraftCore{3.0.8} [Galacticraft Core] (GalacticraftCore-1.7-3.0.8.257.jar) Unloaded->Constructed
	GalacticraftMars{3.0.8} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.8.257.jar) Unloaded->Constructed
	VoltzEngine{0.1.0} [Voltz Engine] (VoltzEngine-1.7.10-0.1.0b81-dev.jar) Unloaded->Constructed
	icbm{2.3.0.75} [ICBM] (ICBM-1.7.10-2.3.0b75-dev.jar) Unloaded->Constructed
	malisisdoors{1.7.10-1.4.3} [Malisis' Doors] (malisisdoors-1.7.10-1.4.3.jar) Unloaded->Constructed
	ForgeMultipart{1.1.1.320} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded->Constructed
	Mekanism{8.0.2} [Mekanism] (Mekanism-1.7.10-8.0.2.201.jar) Unloaded->Constructed
	MekanismGenerators{8.0.2} [MekanismGenerators] (MekanismGenerators-1.7.10-8.0.2.201.jar) Unloaded->Constructed
	MekanismTools{8.0.2} [MekanismTools] (MekanismTools-1.7.10-8.0.2.201.jar) Unloaded->Constructed
	pandorasbox{2.0} [Pandora's Box] (PandorasBox-2.0.jar) Unloaded->Constructed
	PowerConverters{1.7.10-3.0.0.28} [Power Converters] (PowerConverters-1.7.10-3.0.0.28.jar) Unloaded->Constructed
	ResonantEngine{3.0.0} [Resonant Engine] (resonant-engine-3.0.0.255-core.jar) Unloaded->Constructed
	secretroomsmod{4.7.1} [The SecretRoomsMod] (secretroomsmod-1.7.10-4.7.1.409.jar) Unloaded->Constructed
	weather2{v2.3.6} [weather2] (Weather-2.3.7.jar) Unloaded->Constructed
	McMultipart{1.1.1.320} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded->Constructed
	ForgeMicroblock{1.1.1.320} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded->Constructed
	Launched Version: 1.7.10-Forge10.13.2.1291
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics 4600 GL version 4.2.0 - Build 10.18.10.3574, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

Also, If this is the wrong place to put this or if this may have been answered already, then sorry about that. Tried googling the Def error and couldn't get a straight answer that applied to specifically this problem.Also, I checked the jar file and the Configurator Class file IS there.

**Comment by unpairedbracket** [comment]
Is the IToolHammer class definitely present in CoFHCore? The CoFHCore version you're using is quite old I think (3.0.0B1), maybe try updating it to the latest (currently 3.0.0RC7)?

**Comment by ZerkonTerona** [comment]
Thank you, that did fix it. I didn't realize it was outdated because Internet explorer wouldn't let me get to curse.com (which is where most all of the dl links link to.)Thanks again.
