### ISSUE TITLE
Just a random null pointer

### ISSUE THREAD

**Issue by jaz000** [aidancbrady/Mekanism#2427]
To be fair I do have just about every mod going loaded here,
could be mek, could be extrautils, could easily be somethign else
but I fix this problem by rolling back only mekanism

I got this error with 8.0.3.207 and 8.0.3.212
but rolling back to 7.1.2.177 (with every other mod the same) I don't get this error
That was the version this world has been using up untill now, and it's only now I added about 50 of the other mods :-)

---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 3/31/15 7:47 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at mekanism.common.tile.TileEntityContainerBlock.func_70302_i_(TileEntityContainerBlock.java:82)
	at com.rwtema.extrautils.tileentity.transfernodes.TNHelper.isValidTileEntity(TNHelper.java:89)
	at com.rwtema.extrautils.tileentity.transfernodes.TNHelper.isValidTileEntity(TNHelper.java:63)
	at com.rwtema.extrautils.tileentity.transfernodes.pipes.PipeBase.shouldConnectToTile(PipeBase.java:79)
	at com.rwtema.extrautils.tileentity.transfernodes.TileEntityTransferNode.shouldConnectToTile(TileEntityTransferNode.java:618)

http://pastebin.com/8AP6Us8p

**Comment by enterprise12nx** [comment]
just a thought, because of the new Mek API extra utilities could be using an outdated version of the Mek API which is causing the crash, make sure your using the latest version.

latest is V1.2.2

**Comment by aidancbrady** [comment]
This looks a lot like a transition issue.  Added a null check anyway :)
