### ISSUE TITLE
Mekanism 8.1.1.217 NETWORK PROBLEMS!

### ISSUE THREAD

**Issue by NitroxydeX** [aidancbrady/Mekanism#2497]
Seems that the FluidNetwork have some problems. Pump in the Nether can't pump anything

```
 Encountered an unexpected exception
java.lang.NullPointerException
        at mekanism.common.FluidNetwork.tickEmit(FluidNetwork.java:158) ~[FluidNetwork.class:?]
        at mekanism.common.FluidNetwork.onUpdate(FluidNetwork.java:244) ~[FluidNetwork.class:?]
        at mekanism.api.transmitters.DynamicNetwork.tick(DynamicNetwork.java:323) ~[DynamicNetwork.class:?]
        at mekanism.api.transmitters.TransmitterNetworkRegistry.tickEnd(TransmitterNetworkRegistry.java:101) ~[TransmitterNetworkRegistry.class:?]
        at mekanism.api.transmitters.TransmitterNetworkRegistry.onTick(TransmitterNetworkRegistry.java:87) ~[TransmitterNetworkRegistry.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_619_TransmitterNetworkRegistry_onTick_ServerTickEvent.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) ~[EventBus.class:?]
        at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:247) ~[FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:590) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
```

After placing some fancy new Pressurized Tubes (ALL OLD ONES GOT DELETED, WHY?!)
```
 Encountered an unexpected exception
java.lang.ClassCastException: mekanism.common.tile.TileEntityChemicalOxidizer cannot be cast to mekanism.api.gas.IGasHandler
        at mekanism.api.gas.GasNetwork.getAcceptors(GasNetwork.java:294) ~[GasNetwork.class:?]
        at mekanism.api.gas.GasNetwork.tickEmit(GasNetwork.java:138) ~[GasNetwork.class:?]
        at mekanism.api.gas.GasNetwork.onUpdate(GasNetwork.java:247) ~[GasNetwork.class:?]
        at mekanism.api.transmitters.DynamicNetwork.tick(DynamicNetwork.java:323) ~[DynamicNetwork.class:?]
        at mekanism.api.transmitters.TransmitterNetworkRegistry.tickEnd(TransmitterNetworkRegistry.java:101) ~[TransmitterNetworkRegistry.class:?]
        at mekanism.api.transmitters.TransmitterNetworkRegistry.onTick(TransmitterNetworkRegistry.java:87) ~[TransmitterNetworkRegistry.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_619_TransmitterNetworkRegistry_onTick_ServerTickEvent.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) ~[EventBus.class:?]
        at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:247) ~[FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:590) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
```

```
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at mekanism.api.transmitters.TransmitterNetworkRegistry.getNetworkFromOrphan(TransmitterNetworkRegistry.java:168)
	at mekanism.api.transmitters.TransmitterNetworkRegistry.assignOrphans(TransmitterNetworkRegistry.java:133)
	at mekanism.api.transmitters.TransmitterNetworkRegistry.tickEnd(TransmitterNetworkRegistry.java:95)
	at mekanism.api.transmitters.TransmitterNetworkRegistry.onTick(TransmitterNetworkRegistry.java:87)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_620_TransmitterNetworkRegistry_onTick_ServerTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:247)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:590)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

**Comment by unpairedbracket** [comment]
I think the second and third of these should be fixed in development, sorry for the trouble. The first should also, but I'm confused as to why it was happening in the first place, so it might not be.

**Comment by unpairedbracket** [comment]
Can confirm the first is *not* fixed. Investigating...

**Comment by unpairedbracket** [comment]
First was because I was making Coord4Ds without a dimension ID. Now fixed, try the new build. Thanks for finding these and sorry for the disruption.

**Comment by NitroxydeX** [comment]
Tested for more than 2 hours now. No problems during this period. Seems to work. Good job @unpairedbracket! :)

**Comment by unpairedbracket** [comment]
Good good. As always, let us know if anything else is wrong.
