### ISSUE TITLE
Mekanism crashes

### ISSUE THREAD

**Issue by TheSuperMingela** [aidancbrady/Mekanism#2502]
---- Minecraft Crash Report ----
// My bad.

Time: 11.04.15 12:16
Description: Exception in server tick loop

java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextEntry(HashMap.java:926)
	at java.util.HashMap$EntryIterator.next(HashMap.java:966)
	at java.util.HashMap$EntryIterator.next(HashMap.java:964)
	at mekanism.api.transmitters.DynamicNetwork.commit(DynamicNetwork.java:86)
	at mekanism.api.transmitters.TransmitterNetworkRegistry.commitChanges(TransmitterNetworkRegistry.java:180)
	at mekanism.api.transmitters.TransmitterNetworkRegistry.tickEnd(TransmitterNetworkRegistry.java:97)
	at mekanism.api.transmitters.TransmitterNetworkRegistry.onTick(TransmitterNetworkRegistry.java:87)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_734_TransmitterNetworkRegistry_onTick_ServerTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:247)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:590)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by halvors** [comment]
What version are you running, a lot of these crashes was fixed in 8.1.1.219

**Comment by TheSuperMingela** [comment]
iam running 8.1.1.219 it crashed just one time

**Comment by unpairedbracket** [comment]
The only way I can see this happening is through a race condition on loading a chunk asynchronously, or if you have something installed that's doing stupid things with threading different parts of ticks. It should only happen very rarely, if at all, but I'll see if there's any way I can stop it.
