### ISSUE TITLE
Crash at world loading

### ISSUE THREAD

**Issue by Selgald** [aidancbrady/Mekanism#2504]
When I try to load my world MC crashes.
I used 218 when this started, update to 219 has no effect.

---- Minecraft Crash Report ----
// Everything's going to plan. No, really, that was supposed to happen.

Time: 4/11/15 2:45 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at mekanism.common.content.transporter.TransporterPathfinder.getPaths(TransporterPathfinder.java:227)
	at mekanism.common.content.transporter.TransporterPathfinder.getNewBasePath(TransporterPathfinder.java:280)
	at mekanism.common.content.transporter.TransporterStack.recalculatePath(TransporterStack.java:161)
	at mekanism.common.multipart.MultipartTransporter.insert_do(MultipartTransporter.java:276)
	at mekanism.common.multipart.MultipartTransporter.insert(MultipartTransporter.java:258)
	at mekanism.common.util.TransporterUtils.insert(TransporterUtils.java:161)
	at mekanism.common.multipart.PartLogisticalTransporter.pullItems(PartLogisticalTransporter.java:181)
	at mekanism.common.multipart.MultipartTransporter.update(MultipartTransporter.java:57)
	at mekanism.common.multipart.PartLogisticalTransporter.update(PartLogisticalTransporter.java:161)
	at codechicken.multipart.TileMultipart$$anonfun$updateEntity$1.apply(TileMultipart.scala:82)
	at codechicken.multipart.TileMultipart$$anonfun$updateEntity$1.apply(TileMultipart.scala:82)
	at codechicken.multipart.TileMultipart.operate(TileMultipart.scala:76)
	at codechicken.multipart.TileMultipart.func_145845_h(TileMultipart.scala:82)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at mekanism.common.content.transporter.TransporterPathfinder.getPaths(TransporterPathfinder.java:227)
	at mekanism.common.content.transporter.TransporterPathfinder.getNewBasePath(TransporterPathfinder.java:280)
	at mekanism.common.content.transporter.TransporterStack.recalculatePath(TransporterStack.java:161)
	at mekanism.common.multipart.MultipartTransporter.insert_do(MultipartTransporter.java:276)
	at mekanism.common.multipart.MultipartTransporter.insert(MultipartTransporter.java:258)
	at mekanism.common.util.TransporterUtils.insert(TransporterUtils.java:161)
	at mekanism.common.multipart.PartLogisticalTransporter.pullItems(PartLogisticalTransporter.java:181)
	at mekanism.common.multipart.MultipartTransporter.update(MultipartTransporter.java:57)
	at mekanism.common.multipart.PartLogisticalTransporter.update(PartLogisticalTransporter.java:161)
	at codechicken.multipart.TileMultipart$$anonfun$updateEntity$1.apply(TileMultipart.scala:82)
	at codechicken.multipart.TileMultipart$$anonfun$updateEntity$1.apply(TileMultipart.scala:82)
	at codechicken.multipart.TileMultipart.operate(TileMultipart.scala:76)
	at codechicken.multipart.TileMultipart.func_145845_h(TileMultipart.scala:82)

-- Block entity being ticked --
Details:
	Name: savedMultipart // TileMultipart_cmp$$33
	Block type: ID #446 (tile.multipart // codechicken.multipart.BlockMultipart)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-284,71,-153), Chunk: (at 4,4,7 in -18,-10; contains blocks -288,0,-160 to -273,255,-145), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Actual block type: ID #446 (tile.multipart // codechicken.multipart.BlockMultipart)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: New World
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 679 Drop: 0
	Level seed: -1320740021844763344
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (97,64,-293), Chunk: (at 1,4,11 in 6,-19; contains blocks 96,0,-304 to 111,255,-289), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 407660 game time, 816343 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 68766 (now: false), thunder time: 119337 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by ZealousZcar** [comment]
The same thing happens to my MC when I try to load it up.

**Comment by Selgald** [comment]
Updated to 224, still crashing at world loading.

**Comment by ZealousZcar** [comment]
Same . . .

**Comment by ZealousZcar** [comment]
Downgrade to 216 seems to fix it.

**Comment by aidancbrady** [comment]
Merging with #2508
