### ISSUE TITLE
Mechanical pipe crash in Galacticraft dimensions

### ISSUE THREAD

**Issue by spookydonut** [aidancbrady/Mekanism#2528]
Happens when pulling from a thermal expansion tank, either wrenching the tank to push into the pipes or using a configurator on the pipe to put it into pull mode.

Forge 10.13.2.1291
Mekanism build 217
TE 4.0.0RC7
TD 1.0.0RC8
Galacticraft 3.0.11

I'm going to guess this might be a forge problem.

java.lang.NullPointerException: Exception in server tick loop
	at mekanism.common.FluidNetwork.tickEmit(FluidNetwork.java:158)
	at mekanism.common.FluidNetwork.onUpdate(FluidNetwork.java:244)
	at mekanism.api.transmitters.DynamicNetwork.tick(DynamicNetwork.java:323)
	at mekanism.api.transmitters.TransmitterNetworkRegistry.tickEnd(TransmitterNetworkRegistry.java:101)
	at mekanism.api.transmitters.TransmitterNetworkRegistry.onTick(TransmitterNetworkRegistry.java:87)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_236_TransmitterNetworkRegistry_onTick_ServerTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:247)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:590)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by aidancbrady** [comment]
Update Mekanism, you're using a slightly outdated version.
