### ISSUE TITLE
crash with transport pipe

### ISSUE THREAD

**Issue by ShawnRHayes** [aidancbrady/Mekanism#2533]
---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 4/14/15 11:19 AM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at mekanism.common.content.transporter.TransporterPathfinder.getPaths(TransporterPathfinder.java:227)
	at mekanism.common.content.transporter.TransporterPathfinder.getNewBasePath(TransporterPathfinder.java:280)
	at mekanism.common.content.transporter.TransporterStack.recalculatePath(TransporterStack.java:161)
	at mekanism.common.multipart.MultipartTransporter.insert_do(MultipartTransporter.java:276)
	at mekanism.common.multipart.MultipartTransporter.insert(MultipartTransporter.java:258)
	at mekanism.common.util.TransporterUtils.insert(TransporterUtils.java:161)
	at mekanism.common.multipart.PartLogisticalTransporter.pullItems(PartLogisticalTransporter.java:181)
	at mekanism.common.multipart.MultipartTransporter.update(MultipartTransporter.java:57)
	at mekanism.common.multipart.PartLogisticalTransporter.update(PartLogisticalTransporter.java:161)
	at codechicken.multipart.TileMultipart$$anonfun$updateEntity$1.apply(TileMultipart.scala:82)
	at codechicken.multipart.TileMultipart$$anonfun$updateEntity$1.apply(TileMultipart.scala:82)
	at codechicken.multipart.TileMultipart.operate(TileMultipart.scala:76)
	at codechicken.multipart.TileMultipart.func_145845_h(TileMultipart.scala:82)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by aidancbrady** [comment]
Fixed in development :)

**Comment by JZELITE** [comment]
I just got this same crash, worked fine last night, logged on today and this crash, I tried out the latest dev builds and same issue :(

**Comment by cram42** [comment]
Getting the same issue on build 8.1.1.288 with Forge 10.13.3.1374.
