### ISSUE TITLE
Logistical transporter pipe bug (all tiers)

### ISSUE THREAD

**Issue by lordshadowhawk** [aidancbrady/Mekanism#2537]
logistical transporter pipes (all types) seem to be causing a intermittent world crash (ticking block entity) requiring the removal of the pipe through region editing. 

bug has occured in the following instances. 
occasional: on placement connecting to a chest
occasional: after random period of time will crash the server, requiring the pipe to be removed via nbt edit from the region file.
occasional: after shutting down the server and booting it back up again.

this seems to be happening on any pipe that connects to a chest. (tried vanilla chests, iorn chests, ender chests, alchemical chests.)

this bug only seems to have happened since the pipes were changed to differing tiers. and all versions of the logistical pipe seem to be having this issue.

if you need full server logs i can provide. 

---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 15/04/15 1:19 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at mekanism.common.content.transporter.TransporterPathfinder.getPaths(TransporterPathfinder.java:227)
	at mekanism.common.content.transporter.TransporterPathfinder.getNewBasePath(TransporterPathfinder.java:280)
	at mekanism.common.content.transporter.TransporterStack.recalculatePath(TransporterStack.java:161)
	at mekanism.common.multipart.MultipartTransporter.insert_do(MultipartTransporter.java:276)
	at mekanism.common.multipart.MultipartTransporter.insert(MultipartTransporter.java:258)
	at mekanism.common.util.TransporterUtils.insert(TransporterUtils.java:161)
	at mekanism.common.multipart.PartLogisticalTransporter.pullItems(PartLogisticalTransporter.java:181)
	at mekanism.common.multipart.MultipartTransporter.update(MultipartTransporter.java:57)
	at mekanism.common.multipart.PartLogisticalTransporter.update(PartLogisticalTransporter.java:161)
	at codechicken.multipart.TileMultipart$$anonfun$updateEntity$1.apply(TileMultipart.scala:82)
	at codechicken.multipart.TileMultipart$$anonfun$updateEntity$1.apply(TileMultipart.scala:82)
	at codechicken.multipart.TileMultipart.operate(TileMultipart.scala:76)
	at codechicken.multipart.TileMultipart.func_145845_h(TileMultipart.scala:82)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at mekanism.common.content.transporter.TransporterPathfinder.getPaths(TransporterPathfinder.java:227)
	at mekanism.common.content.transporter.TransporterPathfinder.getNewBasePath(TransporterPathfinder.java:280)
	at mekanism.common.content.transporter.TransporterStack.recalculatePath(TransporterStack.java:161)
	at mekanism.common.multipart.MultipartTransporter.insert_do(MultipartTransporter.java:276)
	at mekanism.common.multipart.MultipartTransporter.insert(MultipartTransporter.java:258)
	at mekanism.common.util.TransporterUtils.insert(TransporterUtils.java:161)
	at mekanism.common.multipart.PartLogisticalTransporter.pullItems(PartLogisticalTransporter.java:181)
	at mekanism.common.multipart.MultipartTransporter.update(MultipartTransporter.java:57)
	at mekanism.common.multipart.PartLogisticalTransporter.update(PartLogisticalTransporter.java:161)
	at codechicken.multipart.TileMultipart$$anonfun$updateEntity$1.apply(TileMultipart.scala:82)
	at codechicken.multipart.TileMultipart$$anonfun$updateEntity$1.apply(TileMultipart.scala:82)
	at codechicken.multipart.TileMultipart.operate(TileMultipart.scala:76)
	at codechicken.multipart.TileMultipart.func_145845_h(TileMultipart.scala:82)

-- Block entity being ticked --

Details:
	
Name: savedMultipart // TileMultipart_cmp$$42
	
Block type: ID #1278 (tile.multipart // codechicken.multipart.BlockMultipart)
	
Block data value: 0 / 0x0 / 0b0000
	
Block location: World: (-1794,89,1358), Chunk: (at 14,5,14 in -113,84; contains blocks -1808,0,1344 to -1793,255,1359), Region: (-4,2; contains chunks -128,64 to -97,95, blocks -2048,0,1024 to -1537,255,1535)
	Actual block type: ID #1278 (tile.multipart // codechicken.multipart.BlockMultipart)
	Actual block data value: 0 / 0x0 / 0b0000

**Comment by EzerArch** [comment]
I'm having this issue too: https://gist.github.com/EzerArch/45adacad7585a7cc7ff1

Once you close the world, you cannot open it again.

**Comment by aidancbrady** [comment]
Fixed in development, silly issue on my part
