### ISSUE TITLE
Chemical oxidizer possible bug

### ISSUE THREAD

**Issue by lordshadowhawk** [aidancbrady/Mekanism#2543]
When trying to connect to chemical oxidizer with ender io item conduit, bc pipes map crashes with the following error:

occurrence: intermittent

tested multiple forge versions from recomended to current. 
running current release of mekanism

seems to be a different bug than the logistic pipe bug i ran into yesterday.

---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 15/04/15 2:11 PM
Description: Ticking block entity

java.lang.AbstractMethodError
	at mekanism.common.tile.TileEntityChemicalOxidizer.onUpdate(TileEntityChemicalOxidizer.java:147)
	at mekanism.common.tile.TileEntityBasicBlock.func_145845_h(TileEntityBasicBlock.java:73)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at mekanism.common.tile.TileEntityChemicalOxidizer.onUpdate(TileEntityChemicalOxidizer.java:147)
	at mekanism.common.tile.TileEntityBasicBlock.func_145845_h(TileEntityBasicBlock.java:73)

-- Block entity being ticked --
Details:
	Name: ChemicalOxidizer // mekanism.common.tile.TileEntityChemicalOxidizer
	Block type: ID #1721 (tile.MachineBlock2 // mekanism.common.block.BlockMachine)
	Block data value: 1 / 0x1 / 0b0001
	Block location: World: (-1774,65,1349), Chunk: (at 2,4,5 in -111,84; contains blocks -1776,0,1344 to -1761,255,1359), Region: (-4,2; contains chunks -128,64 to -97,95, blocks -2048,0,1024 to -1537,255,1535)
	Actual block type: ID #1721 (tile.MachineBlock2 // mekanism.common.block.BlockMachine)
	Actual block data value: 1 / 0x1 / 0b0001

**Comment by aidancbrady** [comment]
Integration issue - some mod you have is shipping an outdated Mekanism API.
