### ISSUE TITLE
Mechanism Launch CRASH! (mac)

### ISSUE THREAD

**Issue by GiantLNT** [aidancbrady/Mekanism#2554]
For Some reason when ever I launch my game with the latest forge, latest mekanism, with generators, and tools and it crashes and giving this report.

[20:49:59] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[20:49:59] [main/INFO] [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[20:49:59] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[20:49:59] [main/INFO] [FML]: Forge Mod Loader version 7.10.85.1291 for Minecraft 1.7.10 loading
[20:49:59] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.6.0_65, running on Mac OS X:x86_64:10.8.5, installed at /System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
[20:49:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:461]: java.lang.UnsupportedClassVersionError: mekanism/common/asm/LoadingHook : Unsupported major.minor version 51.0
[20:49:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.ClassLoader.defineClass1(Native Method)
[20:49:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
[20:49:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
[20:49:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
[20:49:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
[20:49:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
[20:49:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
[20:49:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.security.AccessController.doPrivileged(Native Method)
[20:49:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
[20:49:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117)
[20:49:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
[20:49:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
[20:49:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.Class.forName0(Native Method)
[20:49:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.Class.forName(Class.java:249)
[20:49:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:417)
[20:49:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:346)
[20:49:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:214)
[20:49:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
[20:49:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67)
[20:49:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
[20:49:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126)
[20:49:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[20:49:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[20:49:59] [main/ERROR] [FML]: An error occurred trying to configure the minecraft home at /Users/lukethomson/Library/Application Support/minecraft for Forge Mod Loader
java.lang.UnsupportedClassVersionError: mekanism/common/asm/LoadingHook : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.6.0_65]
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637) ~[?:1.6.0_65]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621) ~[?:1.6.0_65]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141) ~[?:1.6.0_65]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283) ~[?:1.6.0_65]
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58) ~[?:1.6.0_65]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197) ~[?:1.6.0_65]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.6.0_65]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190) ~[?:1.6.0_65]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306) ~[?:1.6.0_65]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247) ~[?:1.6.0_65]
	at java.lang.Class.forName0(Native Method) ~[?:1.6.0_65]
	at java.lang.Class.forName(Class.java:249) ~[?:1.6.0_65]
	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:417) ~[forge-1.7.10-10.13.2.1291.jar:?]
	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:346) ~[forge-1.7.10-10.13.2.1291.jar:?]
	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:214) ~[forge-1.7.10-10.13.2.1291.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90) [forge-1.7.10-10.13.2.1291.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67) [forge-1.7.10-10.13.2.1291.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34) [forge-1.7.10-10.13.2.1291.jar:?]
	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126) [forge-1.7.10-10.13.2.1291.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
Exception in thread "main" [20:49:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:461]: java.lang.UnsupportedClassVersionError: mekanism/common/asm/LoadingHook : Unsupported major.minor version 51.0
[20:49:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.ClassLoader.defineClass1(Native Method)
[20:49:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
[20:49:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
[20:49:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
[20:49:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
[20:49:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
[20:49:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
[20:49:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.security.AccessController.doPrivileged(Native Method)
[20:49:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
[20:49:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117)
[20:49:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
[20:49:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
[20:49:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.Class.forName0(Native Method)
[20:49:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.Class.forName(Class.java:249)
[20:49:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:417)
[20:49:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:346)
[20:49:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:214)
[20:49:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
[20:49:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67)
[20:49:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
[20:49:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126)
[20:49:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[20:49:59] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by grimallq** [comment]
Java 7+ required.

**Comment by GunnerBones** [comment]
I have the exact same issue, I just got Java 7 and I run mine craft 1.7.10 forge with mekanism, and this happens, pretty much the exact same error log. Can someone help us

**Comment by hehe3301** [comment]
@GunnerBones This is resolved by updating to java 8. for god's sake do so

**Comment by GunnerBones** [comment]
My Java is already updated to 8

**Comment by grimallq** [comment]
You're on a Mac. Macs are notorious for being a pin with Java config. You need to manually reconfigure the Minecraft launcher.

Or use Yosemite with the official Java  update.
