### ISSUE TITLE
Game Crash on Startup 

### ISSUE THREAD

**Issue by MrLuigiConnor** [aidancbrady/Mekanism#2619]
I'm trying to play with a few mods and they crash when I add mekanism, and after removing the other mods, there still seems to be a crash. Any advice?

[08:23:21] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[08:23:21] [main/INFO] [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[08:23:21] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[08:23:21] [main/INFO] [FML]: Forge Mod Loader version 7.10.85.1291 for Minecraft 1.7.10 loading
[08:23:21] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.6.0_65, running on Mac OS X:x86_64:10.9.5, installed at /System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
[08:23:21] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:461]: java.lang.UnsupportedClassVersionError: mekanism/common/asm/LoadingHook : Unsupported major.minor version 51.0
[08:23:21] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.ClassLoader.defineClass1(Native Method)
[08:23:21] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
[08:23:21] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
[08:23:21] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
[08:23:21] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
[08:23:21] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
[08:23:21] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
[08:23:21] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.security.AccessController.doPrivileged(Native Method)
[08:23:21] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
[08:23:21] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117)
[08:23:21] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
[08:23:21] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
[08:23:21] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.Class.forName0(Native Method)
[08:23:21] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.Class.forName(Class.java:249)
[08:23:21] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:417)
[08:23:21] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:346)
[08:23:21] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:214)
[08:23:21] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
[08:23:21] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67)
[08:23:21] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
[08:23:21] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126)
[08:23:21] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[08:23:21] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[08:23:21] [main/ERROR] [FML]: An error occurred trying to configure the minecraft home at /Users/connor/Library/Application Support/minecraft for Forge Mod Loader
java.lang.UnsupportedClassVersionError: mekanism/common/asm/LoadingHook : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.6.0_65]
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637) ~[?:1.6.0_65]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621) ~[?:1.6.0_65]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141) ~[?:1.6.0_65]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283) ~[?:1.6.0_65]
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58) ~[?:1.6.0_65]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197) ~[?:1.6.0_65]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.6.0_65]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190) ~[?:1.6.0_65]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117) ~[launchwrapper-1.11.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306) ~[?:1.6.0_65]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247) ~[?:1.6.0_65]
	at java.lang.Class.forName0(Native Method) ~[?:1.6.0_65]
	at java.lang.Class.forName(Class.java:249) ~[?:1.6.0_65]
	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:417) ~[forge-1.7.10-10.13.2.1291.jar:?]
	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:346) ~[forge-1.7.10-10.13.2.1291.jar:?]
	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:214) ~[forge-1.7.10-10.13.2.1291.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90) [forge-1.7.10-10.13.2.1291.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67) [forge-1.7.10-10.13.2.1291.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34) [forge-1.7.10-10.13.2.1291.jar:?]
	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126) [forge-1.7.10-10.13.2.1291.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
Exception in thread "main" [08:23:21] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:461]: java.lang.UnsupportedClassVersionError: mekanism/common/asm/LoadingHook : Unsupported major.minor version 51.0
[08:23:21] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.ClassLoader.defineClass1(Native Method)
[08:23:21] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
[08:23:21] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
[08:23:22] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
[08:23:22] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
[08:23:22] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
[08:23:22] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
[08:23:22] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.security.AccessController.doPrivileged(Native Method)
[08:23:22] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
[08:23:22] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117)
[08:23:22] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
[08:23:22] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
[08:23:22] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.Class.forName0(Native Method)
[08:23:22] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at java.lang.Class.forName(Class.java:249)
[08:23:22] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:417)
[08:23:22] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:346)
[08:23:22] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:214)
[08:23:22] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
[08:23:22] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67)
[08:23:22] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
[08:23:22] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126)
[08:23:22] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[08:23:22] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:464]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by scootashy** [comment]
try upgrading forge to 1395 and see if all your mods with mekanism loads up. if one of your other mods wont work then try forge 1388 and 1370 I found it worked on all them. mekanism right now updated to new fluid reg it may or may not be compatable for 1291 in future depending if the authors can and will code it to run on them all or not like some mods have. As of right now thats your only way for this build or downgrade your mekanism to 228 to run on forge 1291

**Comment by MrLuigiConnor** [comment]
thanks

**Comment by MrLuigiConnor** [comment]
I'm running mechanism by itself on 228 with forge 1291 and having the same problem. Could it be my minecraft that isn't working?

**Comment by scootashy** [comment]
try to backup your world then let it start with no world and see if it starts then to be sure you dont have a world problem

**Comment by MrLuigiConnor** [comment]
I completely deleted my mine craft folder and tried again, but no luck. I tried on the technic launcher and that fixes it, but it isn't the simplest option.

**Comment by scootashy** [comment]
forge at times can be touchy well hope the newer forge works for you with whatever mods you using. all the mods on my server have now updated and work for both old and new fluid and forge changes. will see if the authors will add support compatablity for 1291 or not. but hoping to see things become stable for the next recommeded release of forge 1.7.10. the last one was 1327

**Comment by Maxiebyte** [comment]
**java.lang.UnsupportedClassVersionError**: mekanism/common/asm/LoadingHook : **Unsupported major.minor version _51.0_**

You need to update Java.

**Comment by MrLuigiConnor** [comment]
thanks
