### ISSUE TITLE
Says minechem isn't installed

### ISSUE THREAD

**Issue by drago15243** [aidancbrady/Mekanism#2648]
It gives no crash report, but it says one of my mods needs mechanism, even though it's installed. Dont know if it's mechanism or another mod.
uhh the log is too big to paste, so you can download it if you want:https://copy.com/XGHXsZxIdpDOIz8z

**Comment by enterprise12nx** [comment]
looks like a problem with hunger overhaul, make sure its updated.

**Comment by drago15243** [comment]
ok Thanks a lot, I thought that too, but wasn't sure.

**Comment by enterprise12nx** [comment]
java.lang.NoClassDefFoundError: iguanaman/hungeroverhaul/IguanaConfig
	at mariculture.plugins.PluginHungerOverhaul.addInformation(PluginHungerOverhaul.java:40)
	at mariculture.fishery.items.ItemVanillaFish.func_77624_a(ItemVanillaFish.java:114)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:525)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.updateFilteredItems(GuiContainerCreative.java:378)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147053_i(GuiContainerCreative.java:350)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147050_b(GuiContainerCreative.java:550)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146286_b(GuiContainerCreative.java:456)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:306)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146274_d(GuiContainerCreative.java:566)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1628)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at mariculture.plugins.PluginHungerOverhaul.addInformation(PluginHungerOverhaul.java:40)
	at mariculture.fishery.items.ItemVanillaFish.func_77624_a(ItemVanillaFish.java:114)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:525)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.updateFilteredItems(GuiContainerCreative.java:378)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147053_i(GuiContainerCreative.java:350)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147050_b(GuiContainerCreative.java:550)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146286_b(GuiContainerCreative.java:456)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:306)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146274_d(GuiContainerCreative.java:566)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)


its pointing to a plugin or something with hunger overhaul still, or maybe "iguana config"
mariculture.fishery.items.ItemVanillaFish

im not really sure what mods you have, so a modlist would be good, but this isnt really the place for this.
technic would be a much bigger help, plowmanplow99 is always there helping

**Comment by enterprise12nx** [comment]
you also have a lot of ID mismatches, it all seems kinda messy

**Comment by drago15243** [comment]
i deleted all configs, and reinstalled all mods, took a while but it finally works, might have bin agricraft.
thanks for trying to help =D.
