### ISSUE TITLE
Pressurized Tubes empty after Server-Crash | Build 229 & Forge 1403

### ISSUE THREAD

**Issue by NitroxydeX** [aidancbrady/Mekanism#2658]
Weird problem:

Removed a ton of Pressurized Tubes from my Electrolytic Seperator - Gas Burning Generator Construction. A while after placed a Lamp from Project Red to prevent Mobspawn: Caused Server Crash.

```
Description: Exception in server tick loop

java.lang.ClassCastException: mrtjp.projectred.illumination.TileLamp cannot be cast to mekanism.api.gas.IGasHandler
	at mekanism.api.gas.GasNetwork.getAcceptors(GasNetwork.java:298)
	at mekanism.api.gas.GasNetwork.tickEmit(GasNetwork.java:142)
	at mekanism.api.gas.GasNetwork.onUpdate(GasNetwork.java:251)
	at mekanism.api.transmitters.DynamicNetwork.tick(DynamicNetwork.java:318)
	at mekanism.api.transmitters.TransmitterNetworkRegistry.tickEnd(TransmitterNetworkRegistry.java:101)
	at mekanism.api.transmitters.TransmitterNetworkRegistry.onTick(TransmitterNetworkRegistry.java:87)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_624_TransmitterNetworkRegistry_onTick_ServerTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:247)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:590)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

So, why recognizes Mekanism the Lamp even when the Tubes are long gone? And why are all Pressurized Tubes empty after the crash or is it a bug when the Server get's restarted?

**Comment by RAWRwins254** [comment]
The first issue, I have no idea. But Yes there's a bug where server reboots/crashes empty all mekanism piping. I haven't yet checked to see if it can be fixed or if it's a mc limitation.

**Comment by NitroxydeX** [comment]
@RAWRwins254 hadn't a issue with pipes before the rewrite of the network. sooo... should be fixable.

**Comment by RAWRwins254** [comment]
Good to hear.

**Comment by aidancbrady** [comment]
Fixed both issues.
