### ISSUE TITLE
Bug when starting(problems in recipes)

### ISSUE THREAD

**Issue by MateusMoreiraBR** [aidancbrady/Mekanism#2666]
When I start the game it always happens, whether or not with other mods.
following bug:
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoSuchFieldError: fluid
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:692)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:288)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:541)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoSuchFieldError: fluid
	at mekanism.common.recipe.inputs.FluidInput.hashIngredients(FluidInput.java:50)
	at mekanism.common.recipe.inputs.MachineInput.hashCode(MachineInput.java:28)
	at java.util.HashMap.hash(HashMap.java:338)
	at java.util.HashMap.put(HashMap.java:611)
	at mekanism.common.recipe.RecipeHandler$Recipe.put(RecipeHandler.java:576)
	at mekanism.common.recipe.RecipeHandler.addRecipe(RecipeHandler.java:65)
	at mekanism.common.recipe.RecipeHandler.addElectrolyticSeparatorRecipe(RecipeHandler.java:169)
	at mekanism.common.Mekanism.addRecipes(Mekanism.java:818)
	at mekanism.common.Mekanism.init(Mekanism.java:1227)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:691)
	... 10 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 295279024 bytes (281 MB) / 618377216 bytes (589 MB) up to 3167551488 bytes (3020 MB)
	JVM Flags: 7 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn512M -Xmx3072M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 Optifine OptiFine_1.7.10_HD_U_B6 10 mods loaded, 10 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
	FML{7.10.85.1291} [Forge Mod Loader] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized
	Forge{10.13.2.1291} [Minecraft Forge] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized
	FastCraft{1.21} [FastCraft] (fastcraft-1.21.jar) Unloaded->Constructed->Pre-initialized->Initialized
	ForgeMultipart{1.1.2.331} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
	Mekanism{8.1.2} [Mekanism] (Mekanism-1.7.10-8.1.2.229 (1).jar) Unloaded->Constructed->Pre-initialized->Errored
	MekanismGenerators{8.1.2} [MekanismGenerators] (MekanismGenerators-1.7.10-8.1.2.229 (1).jar) Unloaded->Constructed->Pre-initialized->Errored
	MekanismTools{8.1.2} [MekanismTools] (MekanismTools-1.7.10-8.1.2.229 (1).jar) Unloaded->Constructed->Pre-initialized->Errored
	McMultipart{1.1.2.331} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
	ForgeMicroblock{1.1.2.331} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized

**Comment by grimallq** [comment]
Build 229 is for Forge 1355+.

**Comment by MateusMoreiraBR** [comment]
but when I go to use the forge profile, does not enter
so enters the forge 1291 profile

**Comment by MateusMoreiraBR** [comment]
what i do?

**Comment by HanatakeYurii** [comment]
What are you using to load mods? manual installation? special launcher (FTB, Technic, MultiMC...)?

**Comment by bochen415** [comment]
I think he might be referring to Curse Voice

**Comment by MateusMoreiraBR** [comment]
I'm using manual installation

**Comment by HanatakeYurii** [comment]
If it's a manual installation, go to http://files.minecraftforge.net/ , then download and install a version newer than 1355 (I would even recommend to use a version newer than 1395)

**Comment by MateusMoreiraBR** [comment]
I installed but not entered, carried the green bar in the launcher and not opened, then I looked at the forge folder and it had only one file, and the folder with the forge that works had 2.
![capturar](https://cloud.githubusercontent.com/assets/12472518/7716813/d578a910-fe6d-11e4-916a-74cc9208f338.JPG)
