### ISSUE TITLE
Server crash with gas generator and Ender IO gas conduit.

### ISSUE THREAD

**Issue by Belgabor** [aidancbrady/Mekanism#2698]
Version: 8.1.1.228 (old forge, cannot update)
Ender IO: 2.3.0.235 beta

```
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 5/28/15 12:37 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at mekanism.generators.common.tile.TileEntityGasGenerator.receiveGas(TileEntityGasGenerator.java:254)
	at mekanism.generators.common.tile.TileEntityGasGenerator.receiveGas(TileEntityGasGenerator.java:266)
	at crazypants.enderio.conduit.gas.GasConduitNetwork.doNetworkTick(GasConduitNetwork.java:110)
	at crazypants.enderio.conduit.ConduitNetworkTickHandler.tickEnd(ConduitNetworkTickHandler.java:63)
	at crazypants.enderio.conduit.ConduitNetworkTickHandler.onServerTick(ConduitNetworkTickHandler.java:47)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_149_ConduitNetworkTickHandler_onServerTick_ServerTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:247)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:590)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

Now I wouldn't normally report this as we aren't running the current version, but taking a look at the code point that caused it makes me wonder this doesn't cause issues more often =)
My Java is a bit rusty, but wouldn't that line cause a NPE whenever isTankEmpty gets set to true?

**Comment by aidancbrady** [comment]
No, the tank would already be filled in line 250's call of fluidTank.receive().  I did fix two other issues though that solve the crash.
