### ISSUE TITLE
Mekanism causes a crash when using NEI

### ISSUE THREAD

**Issue by twothe** [aidancbrady/Mekanism#2776]
Using version 246 and NEI 1.0.5.111 with Forge 1448

Whenever I click on any item in the NEI menu, the game crashes immediately with the following error message:

```
[27/6/2015 23:30:57 PM] net.minecraft.util.ReportedException: Updating screen events
[27/6/2015 23:30:57 PM] 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1654) ~[bao.class:?]
[27/6/2015 23:30:57 PM] 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) ~[bao.class:?]
[27/6/2015 23:30:57 PM] 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
[27/6/2015 23:30:57 PM] 	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
[27/6/2015 23:30:57 PM] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
[27/6/2015 23:30:57 PM] 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
[27/6/2015 23:30:57 PM] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
[27/6/2015 23:30:57 PM] 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
[27/6/2015 23:30:57 PM] 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
[27/6/2015 23:30:57 PM] 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
[27/6/2015 23:30:57 PM] Caused by: java.lang.ClassCastException: net.minecraft.item.ItemStack cannot be cast to mekanism.common.recipe.machines.BasicMachineRecipe
[27/6/2015 23:30:57 PM] 	at mekanism.client.nei.MachineRecipeHandler.loadCraftingRecipes(MachineRecipeHandler.java:106) ~[MachineRecipeHandler.class:?]
[27/6/2015 23:30:57 PM] 	at codechicken.nei.recipe.TemplateRecipeHandler.loadCraftingRecipes(TemplateRecipeHandler.java:327) ~[TemplateRecipeHandler.class:?]
[27/6/2015 23:30:57 PM] 	at mekanism.client.nei.MachineRecipeHandler.loadCraftingRecipes(MachineRecipeHandler.java:99) ~[MachineRecipeHandler.class:?]
[27/6/2015 23:30:57 PM] 	at codechicken.nei.recipe.TemplateRecipeHandler.getRecipeHandler(TemplateRecipeHandler.java:465) ~[TemplateRecipeHandler.class:?]
[27/6/2015 23:30:57 PM] 	at codechicken.nei.recipe.GuiCraftingRecipe.openRecipeGui(GuiCraftingRecipe.java:20) ~[GuiCraftingRecipe.class:?]
[27/6/2015 23:30:57 PM] 	at codechicken.nei.ItemPanel.mouseUp(ItemPanel.java:258) ~[ItemPanel.class:?]
[27/6/2015 23:30:57 PM] 	at codechicken.nei.LayoutManager.onMouseUp(LayoutManager.java:166) ~[LayoutManager.class:?]
[27/6/2015 23:30:57 PM] 	at codechicken.nei.guihook.GuiContainerManager.mouseUp(GuiContainerManager.java:365) ~[GuiContainerManager.class:?]
[27/6/2015 23:30:57 PM] 	at codechicken.nei.guihook.GuiContainerManager.overrideMouseUp(GuiContainerManager.java:357) ~[GuiContainerManager.class:?]
[27/6/2015 23:30:57 PM] 	at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java) ~[bex.class:?]
[27/6/2015 23:30:57 PM] 	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:306) ~[bdw.class:?]
[27/6/2015 23:30:57 PM] 	at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java) ~[bex.class:?]
[27/6/2015 23:30:57 PM] 	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268) ~[bdw.class:?]
[27/6/2015 23:30:57 PM] 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640) ~[bao.class:?]
[27/6/2015 23:30:57 PM] 	
... 9 more
```

**Comment by Dawnflash** [comment]
Try replicating with only Mekanism, NEI nad FMP.
The issue is unlikely in Mekanism, you have a different mod or config causing that. Try to pinpoint the cause by trial and error.

**Comment by aidancbrady** [comment]
@Dawnflash is exactly right- this is due to a mod attempting to integrate with an outdated MDK.  I guarantee this issue won't arise with only Mekanism and its dependencies installed.

On a positive note, all major mods I know have releases out with updated Mekanism compatibility - try updating some!
