### ISSUE TITLE
Problem with Mekanism on Server

### ISSUE THREAD

**Issue by Shaggy84675** [aidancbrady/Mekanism#2811]
Hello, when I leave from server I've got this error and server crash.
---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 7/10/15 12:11 PM
Description: Exception in server tick loop

java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
	at java.util.HashMap$ValueIterator.next(HashMap.java:1458)
	at mekanism.api.transmitters.TransmitterNetworkRegistry.assignOrphans(TransmitterNetworkRegistry.java:136)
	at mekanism.api.transmitters.TransmitterNetworkRegistry.tickEnd(TransmitterNetworkRegistry.java:96)
	at mekanism.api.transmitters.TransmitterNetworkRegistry.onTick(TransmitterNetworkRegistry.java:88)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_279_TransmitterNetworkRegistry_onTick_ServerTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:251)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:862)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
	at java.lang.Thread.run(Thread.java:745)

Thanks for reply.

**Comment by aidancbrady** [comment]
What version are you using?

**Comment by RAWRwins254** [comment]
@Shaggy84675 reply with versions of both Forge and mekanism. Without those version numbers, nobody (not even Aidan) would be able to assist.

**Comment by Shaggy84675** [comment]
Sorry. I got this error, when I updated Mekanism from version 7.1.1.127 to newest version (8.1.5-246). Forge version is 10.13.4.1448. I tried create new map and then it works. No crashes. So I deleted all my Mekanism machines and pipes etc. (My Server is currently in preparing, so there wasn't many things) and then it works, but later when I start my server then will not possible do this process.

**Comment by Dawnflash** [comment]
That is a huge update from 7 to 8. You should expect crashes on that part. The last part of your statement is rather hard to understand, but simply reconstructing your Mekanism workshops anew should be just fine for the world.

**Comment by Shaggy84675** [comment]
Yeah. Sorry about that. I mean my server is currently in preparing, so there wasn't many things from Mekanism to delete. But later when I start the server for players, They will have much Mekanism things and it will not be so easy to remove. So how is the process for this huge update?

**Comment by Dawnflash** [comment]
Going through huge updates is a drag, there is no 'solution'. If old objects can't survive the update, you need to keep a rollback version of the world and reconstruct everything as-is in the rollback version.
People reset their entire servers on larger updates of several major mods, such as Gregtech, so take that into account.

**Comment by Shaggy84675** [comment]
Okay. Thanks for helps :)
