### ISSUE TITLE
Crash while placing cable

### ISSUE THREAD

**Issue by OnurMeteCandar** [aidancbrady/Mekanism#2881]
I have the latest build of mekanism and I crash while I try to put down a cable or a tube. Here is the crash report :

---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 03.08.2015 19:40
Description: Ticking memory connection

java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:322)
	at scala.None$.get(Option.scala:320)
	at codechicken.multipart.MultiPartRegistry$.writePartID(MultiPartRegistry.scala:191)
	at codechicken.multipart.TileMultipart.writeAddPart(TileMultipart.scala:289)
	at codechicken.multipart.TileMultipart.addPart_impl(TileMultipart.scala:275)
	at codechicken.multipart.MultipartGenerator$.addPart(MultipartGenerator.scala:98)
	at codechicken.multipart.TileMultipart$.addPart(TileMultipart.scala:599)
	at codechicken.multipart.TItemMultiPart$class.place$1(ItemMultiPart.scala:37)
	at codechicken.multipart.TItemMultiPart$class.onItemUse(ItemMultiPart.scala:47)
	at codechicken.multipart.JItemMultiPart.func_77648_a(ItemMultiPart.scala:14)
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:505)
	at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:128)
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:389)
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at scala.None$.get(Option.scala:322)
	at scala.None$.get(Option.scala:320)
	at codechicken.multipart.MultiPartRegistry$.writePartID(MultiPartRegistry.scala:191)
	at codechicken.multipart.TileMultipart.writeAddPart(TileMultipart.scala:289)
	at codechicken.multipart.TileMultipart.addPart_impl(TileMultipart.scala:275)
	at codechicken.multipart.MultipartGenerator$.addPart(MultipartGenerator.scala:98)
	at codechicken.multipart.TileMultipart$.addPart(TileMultipart.scala:599)
	at codechicken.multipart.TItemMultiPart$class.place$1(ItemMultiPart.scala:37)
	at codechicken.multipart.TItemMultiPart$class.onItemUse(ItemMultiPart.scala:47)
	at codechicken.multipart.JItemMultiPart.func_77648_a(ItemMultiPart.scala:14)
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:505)
	at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:128)
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:389)
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@23cbe9
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (x86) version 6.1
	Java Version: 1.8.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 179565952 bytes (171 MB) / 360460288 bytes (343 MB) up to 1037959168 bytes (989 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1481 11 mods loaded, 11 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1481-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1481} [Minecraft Forge] (forge-1.7.10-10.13.4.1481-1.7.10.jar) 
	UCHIJAAAA	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	Mekanism{8.1.5} [Mekanism] (Mekanism-1.7.10-8.1.5.246.jar) 
	UCHIJAAAA	MekanismGenerators{8.1.5} [MekanismGenerators] (MekanismGenerators-1.7.10-8.1.5.246.jar) 
	UCHIJAAAA	MekanismTools{8.1.5} [MekanismTools] (MekanismTools-1.7.10-8.1.5.246.jar) 
	UCHIJAAAA	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) 
	UCHIJAAAA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJAAAA	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['Candarian'/72, l='Mod Showcase', x=-81,79, y=65,29, z=66,64]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by OnurMeteCandar** [comment]
Can anyone help?

**Comment by ruifung** [comment]
First, nobody keeps watching github for notifications, so don't expect instant reply.

Also, 8.1.7 is the latest build of mekanism, neither have I encountered this issue on 8.1.5.

Can you place any covers or panels? Because the crash doesn't seem to be involving any Mekanism code.. just forge multipart?

**Comment by OnurMeteCandar** [comment]
I tried removing forge multipart but it keeps saying I need it

**Comment by ruifung** [comment]
Yes, it needs forge multipart, but im not sure why its crashing.
Heck, I can't even reproduce it.

**Comment by OnurMeteCandar** [comment]
İts not only me either it crashes in my friends PCs as well

**Comment by aidancbrady** [comment]
There's a chance it's an issue with another mod, but yeah, this definitely isn't me.  I'd suggest reporting to FMP.

**Comment by ruifung** [comment]
It's probably a issue with FMP anyway, it appears its getting None for a Option, and trying to call get on it (which fails because its None).
