### ISSUE TITLE
TileEntity error in console of server + crash dupe bug with gas generators

### ISSUE THREAD

**Issue by robotunicr0n** [aidancbrady/Mekanism#2906]
Stacktrace at the bottom. The first issue occurred a week ago or so when I placed a gas-generator underneath a universal power cable. As soon as I did this my client crashed (server stayed up with no issues). As soon as I got back in, I still had the gas-generator in my hand, but I had also placed it, effectively duping the generator. I thought it was just under pipes that this happened or something so I tried to avoid that, but ended up crashing/duping 5 times over the course of the day I was playing. We weren't using gas-generators much for our power anyway, preferring wind turbines, so we let the one I had running in the basement sit, adding a bit of power to our grid.

This morning I logged in to check on the console for the server and this was inside:
 [FML]: A TileEntity GasGenerator(mekanism.generators.common.tile.TileEntityGasGenerator) has thrown an exception during loading, its state cannot be restored. Report this to the mod author
java.lang.NullPointerException
at net.minecraft.tileentity.TileEntity.func_145827_c(TileEntity.java:116) [aor.class:?]
at mekanism.generators.common.tile.TileEntityGasGenerator.func_145839_a(TileEntityGasGenerator.java:269) ~[TileEntityGasGenerator.class:?]
at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:41) [ChunkIOProvider.class:?]
at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:496) [aqk.class:?]
at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344) [AsynchronousExecutor.class:?]
at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12) [ChunkIOExecutor.class:?]
at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302) [AsynchronousExecutor.class:?]
at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) [ms.class:?]
at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126) [ms.class:?]
at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12) [ChunkIOProvider.class:?]
at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) [ms.class:?]
at net.minecraft.world.World.func_147439_a(World.java:345) [ahb.class:?]
at net.minecraft.world.World.func_72964_e(World.java:419) [ahb.class:?]
at net.minecraft.world.World.func_72878_l(World.java:3424) [ahb.class:?]
at net.minecraft.world.World.func_72879_k(World.java:3361) [ahb.class:?]
at net.minecraft.world.World.func_94577_B(World.java:3383) [ahb.class:?]
at mekanism.common.util.MekanismUtils.isGettingPowered(MekanismUtils.java:678) [MekanismUtils.class:?]
at mekanism.common.multipart.PartSidedPipe.redstoneRefresh(PartSidedPipe.java:466) [PartSidedPipe.class:?]
at mekanism.common.multipart.PartSidedPipe.onNeighborChanged(PartSidedPipe.java:545) [PartSidedPipe.class:?]
at codechicken.multipart.TileMultipart$$anonfun$onNeighborBlockChange$1.apply(TileMultipart.scala:166) [TileMultipart$$anonfun$onNeighborBlockChange$1.class:?]
at codechicken.multipart.TileMultipart$$anonfun$onNeighborBlockChange$1.apply(TileMultipart.scala:166) [TileMultipart$$anonfun$onNeighborBlockChange$1.class:?]
at codechicken.multipart.TileMultipart.operate(TileMultipart.scala:76) [TileMultipart.class:?]
at codechicken.multipart.BlockMultipart.func_149695_a(BlockMultipart.scala:80) [BlockMultipart.class:?]
at codechicken.multipart.TileMultipart.onNeighborBlockChange(TileMultipart.scala:166) [TileMultipart.class:?]
at net.minecraft.world.World.func_147459_d(World.java:652) [ahb.class:?]
at appeng.util.BlockUpdate.call(BlockUpdate.java:42) [BlockUpdate.class:?]
at appeng.hooks.TickHandler.processQueue(TickHandler.java:287) [TickHandler.class:?]
at net.minecraft.world.World.func_147460_e(World.java:697) [ahb.class:?]
at appeng.hooks.TickHandler.onTick(TickHandler.java:271) [TickHandler.class:?]
at cpw.mods.fml.common.eventhandler.ASMEventHandler_469_TickHandler_onTick_TickEvent.invoke(.dynamic) [?:?]
at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) [ASMEventHandler.class:?]
at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:?]
at cpw.mods.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:268) [FMLCommonHandler.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:620) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
java.lang.NullPointerException

I haven't been able to check yet with my players if they were messing around with the generators last night, but I will do so shortly. I don't know if there are issues logging into the server as no one is on. Will ask someone to sanity check login and see if the server is still functional. This is on Bevo's Tech Pack v12, on 1.7 of Minecraft I believe.

**Comment by robotunicr0n** [comment]
Here's a follow up, I determined this was only occurring in chunks with gas powered generators that were not player chunk loaded (ie players weren't present, keeping the chunks loaded) but rather it's an overlap with the chunkloader from chicken chunks. The tile entity error occurs when the chunk load ticks (or however that works...). I removed all the gas generators from the server as there was only one and we didn't need it for power anymore. I think it's resolved now.. going to toss it and all the dupes that were created from the bug mentioned above into the ExtraUtilities trashcan and be done with it.

**Comment by ruifung** [comment]
According to the ATLauncher page, its using version 7.1.2.177 of Mekanism. The current version is 8.1.7 and I do not have this problem. I have like..30 gas burning generators in my base and its chunkloaded with world anchors, so I think this might be fixed?

**Comment by robotunicr0n** [comment]
Yeah probably, I didn't realize there was a newer version of Mekanism but I guess I shouldn't be surprised as there hasn't been a modpack update for a good long while and there are plenty of other mods complaining everytime I log in that they're out of date.

In that case this is probably a non-issue so I'll close it.
