### ISSUE TITLE
Inserting oxygen into the gas-burning generator crashes the game

### ISSUE THREAD

**Issue by dbulm2** [aidancbrady/Mekanism#2923]
~~Rotating an electrolytic separator filled with water tries to insert hydrogen/oxygen into the generator, while there's still hydrogen/oxygen in it, crashing the game with~~

Inserting Oxygen into the generator will crash the game with:

java.lang.NullPointerException: Ticking block entity
	at mekanism.common.FuelHandler.getFuel(FuelHandler.java:33)
	at mekanism.generators.common.tile.TileEntityGasGenerator.canReceiveGas(TileEntityGasGenerator.java:296)
	at mekanism.common.tile.TileEntityElectrolyticSeparator.onUpdate(TileEntityElectrolyticSeparator.java:225)
	at mekanism.common.tile.TileEntityBasicBlock.func_145845_h(TileEntityBasicBlock.java:73)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

Version: Mekanism-1.7.10-8.1.5.246.jar

**Comment by vedalken254** [comment]
@dbulm2 last I knew this has been fixed... You're running an older version. Please update.

**Comment by vedalken254** [comment]
@dbulm2 yup... it's been fixed: @aidancbrady responded in this issue: https://github.com/aidancbrady/Mekanism/issues/2842
