### ISSUE TITLE
Crash on NEI examination of recipies

### ISSUE THREAD

**Issue by Syndaryl** [aidancbrady/Mekanism#2954]
MEKANISM-1.7.10-8.1.7.252
MEKANISMGENERATORS-1.7.10-8.1.7.252
MEKANISMTOOLS-1.7.10-8.1.7.252

When I try to look at the recipe of any item via NEI, Minecraft crashes. It looks like somewhere in there, the MachineRecipeHandler is trying an invalid cast.

I'm using the latest version of the Resonant Rise modpack (just updated from ATLauncher).

    [08/9/2015 11:28:31 AM] [11:28:31] [Client thread/FATAL]: Reported exception thrown!
    [08/9/2015 11:28:31 AM] net.minecraft.util.ReportedException: Updating screen events
    [08/9/2015 11:28:31 AM] 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1654) ~[bao.class:?]
    [08/9/2015 11:28:31 AM] 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) ~[bao.class:?]
    [08/9/2015 11:28:31 AM] 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
    [08/9/2015 11:28:31 AM] 	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
    [08/9/2015 11:28:31 AM] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
    [08/9/2015 11:28:31 AM] 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
    [08/9/2015 11:28:31 AM] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
    [08/9/2015 11:28:31 AM] 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_51]
    [08/9/2015 11:28:31 AM] 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
    [08/9/2015 11:28:31 AM] 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
    [08/9/2015 11:28:31 AM] Caused by: java.lang.ClassCastException: net.minecraft.item.ItemStack cannot be cast to mekanism.common.recipe.machines.BasicMachineRecipe
    [08/9/2015 11:28:31 AM] 	at mekanism.client.nei.MachineRecipeHandler.loadUsageRecipes(MachineRecipeHandler.java:124) ~[MachineRecipeHandler.class:?]
    [08/9/2015 11:28:31 AM] 	at codechicken.nei.recipe.TemplateRecipeHandler.loadUsageRecipes(TemplateRecipeHandler.java:346) ~[TemplateRecipeHandler.class:?]
    [08/9/2015 11:28:31 AM] 	at codechicken.nei.recipe.TemplateRecipeHandler.getUsageHandler(TemplateRecipeHandler.java:471) ~[TemplateRecipeHandler.class:?]
    [08/9/2015 11:28:31 AM] 	at codechicken.nei.recipe.GuiUsageRecipe.openRecipeGui(GuiUsageRecipe.java:20) ~[GuiUsageRecipe.class:?]
    [08/9/2015 11:28:31 AM] 	at codechicken.nei.recipe.RecipeItemInputHandler.lastKeyTyped(RecipeItemInputHandler.java:20) ~[RecipeItemInputHandler.class:?]
    [08/9/2015 11:28:31 AM] 	at codechicken.nei.guihook.GuiContainerManager.lastKeyTyped(GuiContainerManager.java:307) ~[GuiContainerManager.class:?]
    [08/9/2015 11:28:31 AM] 	at net.minecraft.client.gui.inventory.GuiContainer.func_73869_a(GuiContainer.java) ~[bex.class:?]
    [08/9/2015 11:28:31 AM] 	at net.minecraft.client.gui.inventory.GuiContainer.public_func_73869_a(GuiContainer.java) ~[bex.class:?]
    [08/9/2015 11:28:31 AM] 	at codechicken.nei.guihook.GuiContainerManager.callKeyTyped(GuiContainerManager.java) ~[GuiContainerManager.class:?]
    [08/9/2015 11:28:31 AM] 	at codechicken.nei.guihook.GuiContainerManager.keyTyped(GuiContainerManager.java:475) ~[GuiContainerManager.class:?]
    [08/9/2015 11:28:31 AM] 	at codechicken.nei.guihook.GuiContainerManager.handleKeyboardInput(GuiContainerManager.java:465) ~[GuiContainerManager.class:?]
    [08/9/2015 11:28:31 AM] 	at net.minecraft.client.gui.inventory.GuiContainer.func_146282_l(GuiContainer.java) ~[bex.class:?]
    [08/9/2015 11:28:31 AM] 	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:276) ~[bdw.class:?]
    [08/9/2015 11:28:31 AM] 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640) ~[bao.class:?]
    [08/9/2015 11:28:31 AM] 	... 9 more
    [08/9/2015 11:28:31 AM] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
    [08/9/2015 11:28:31 AM] // This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]
    [08/9/2015 11:28:31 AM] 
    [08/9/2015 11:28:31 AM] Time: 9/8/15 11:28 AM
    [08/9/2015 11:28:31 AM] Description: Updating screen events
    [08/9/2015 11:28:31 AM] 
    [08/9/2015 11:28:31 AM] java.lang.ClassCastException: net.minecraft.item.ItemStack cannot be cast to mekanism.common.recipe.machines.BasicMachineRecipe
    [08/9/2015 11:28:31 AM] 	at mekanism.client.nei.MachineRecipeHandler.loadUsageRecipes(MachineRecipeHandler.java:124)
    [08/9/2015 11:28:31 AM] 	at codechicken.nei.recipe.TemplateRecipeHandler.loadUsageRecipes(TemplateRecipeHandler.java:346)
    [08/9/2015 11:28:31 AM] 	at codechicken.nei.recipe.TemplateRecipeHandler.getUsageHandler(TemplateRecipeHandler.java:471)
    [08/9/2015 11:28:31 AM] 	at codechicken.nei.recipe.GuiUsageRecipe.openRecipeGui(GuiUsageRecipe.java:20)
    [08/9/2015 11:28:31 AM] 	at codechicken.nei.recipe.RecipeItemInputHandler.lastKeyTyped(RecipeItemInputHandler.java:20)
    [08/9/2015 11:28:31 AM] 	at codechicken.nei.guihook.GuiContainerManager.lastKeyTyped(GuiContainerManager.java:307)
    [08/9/2015 11:28:31 AM] 	at net.minecraft.client.gui.inventory.GuiContainer.func_73869_a(GuiContainer.java)
    [08/9/2015 11:28:31 AM] 	at net.minecraft.client.gui.inventory.GuiContainer.public_func_73869_a(GuiContainer.java)
    [08/9/2015 11:28:31 AM] 	at codechicken.nei.guihook.GuiContainerManager.callKeyTyped(GuiContainerManager.java)
    [08/9/2015 11:28:31 AM] 	at codechicken.nei.guihook.GuiContainerManager.keyTyped(GuiContainerManager.java:475)
    [08/9/2015 11:28:31 AM] 	at codechicken.nei.guihook.GuiContainerManager.handleKeyboardInput(GuiContainerManager.java:465)
    [08/9/2015 11:28:31 AM] 	at net.minecraft.client.gui.inventory.GuiContainer.func_146282_l(GuiContainer.java)
    [08/9/2015 11:28:31 AM] 	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:276)
    [08/9/2015 11:28:31 AM] 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
    [08/9/2015 11:28:31 AM] 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
    [08/9/2015 11:28:31 AM] 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    [08/9/2015 11:28:31 AM] 	at net.minecraft.client.main.Main.main(SourceFile:148)
    [08/9/2015 11:28:31 AM] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    [08/9/2015 11:28:31 AM] 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    [08/9/2015 11:28:31 AM] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    [08/9/2015 11:28:31 AM] 	at java.lang.reflect.Method.invoke(Unknown Source)
    [08/9/2015 11:28:31 AM] 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    [08/9/2015 11:28:31 AM] 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    [08/9/2015 11:28:31 AM] 
    [08/9/2015 11:28:31 AM] 
    [08/9/2015 11:28:31 AM] A detailed walkthrough of the error, its code path and all known details is as follows:
    [08/9/2015 11:28:31 AM] ---------------------------------------------------------------------------------------
    [08/9/2015 11:28:31 AM] 
    [08/9/2015 11:28:31 AM] -- Head --
    [08/9/2015 11:28:31 AM] Stacktrace:
    [08/9/2015 11:28:31 AM] 	at mekanism.client.nei.MachineRecipeHandler.loadUsageRecipes(MachineRecipeHandler.java:124)
    [08/9/2015 11:28:31 AM] 	at codechicken.nei.recipe.TemplateRecipeHandler.loadUsageRecipes(TemplateRecipeHandler.java:346)
    [08/9/2015 11:28:31 AM] 	at codechicken.nei.recipe.TemplateRecipeHandler.getUsageHandler(TemplateRecipeHandler.java:471)
    [08/9/2015 11:28:31 AM] 	at codechicken.nei.recipe.GuiUsageRecipe.openRecipeGui(GuiUsageRecipe.java:20)
    [08/9/2015 11:28:31 AM] 	at codechicken.nei.recipe.RecipeItemInputHandler.lastKeyTyped(RecipeItemInputHandler.java:20)
    [08/9/2015 11:28:31 AM] 	at codechicken.nei.guihook.GuiContainerManager.lastKeyTyped(GuiContainerManager.java:307)
    [08/9/2015 11:28:31 AM] 	at net.minecraft.client.gui.inventory.GuiContainer.func_73869_a(GuiContainer.java)
    [08/9/2015 11:28:31 AM] 	at net.minecraft.client.gui.inventory.GuiContainer.public_func_73869_a(GuiContainer.java)
    [08/9/2015 11:28:31 AM] 	at codechicken.nei.guihook.GuiContainerManager.callKeyTyped(GuiContainerManager.java)
    [08/9/2015 11:28:31 AM] 	at codechicken.nei.guihook.GuiContainerManager.keyTyped(GuiContainerManager.java:475)
    [08/9/2015 11:28:31 AM] 	at codechicken.nei.guihook.GuiContainerManager.handleKeyboardInput(GuiContainerManager.java:465)
    [08/9/2015 11:28:31 AM] 	at net.minecraft.client.gui.inventory.GuiContainer.func_146282_l(GuiContainer.java)
    [08/9/2015 11:28:31 AM] 	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:276)
    [08/9/2015 11:28:31 AM] 
    [08/9/2015 11:28:31 AM] -- Affected screen --
    [08/9/2015 11:28:31 AM] Details:
    [08/9/2015 11:28:31 AM] 	Screen name: net.minecraft.client.gui.inventory.GuiChest

**Comment by Syndaryl** [comment]
When I roll back to the last versions used for Resonant Rise 
* MEKANISM-1.7.10-8.1.5.240.jar
* MEKANISMGENERATORS-1.7.10-8.1.5.240.jar
* MEKANISMTOOLS-1.7.10-8.1.5.240.jar

I stop getting the issue.

**Comment by aidancbrady** [comment]
MineTweaker is out of date.
