### ISSUE TITLE
Server Fluid Transport Crash 1.7.10-8.1.7.252

### ISSUE THREAD

**Issue by TheTux94** [aidancbrady/Mekanism#3012]
Hello,
I got this error today after connecting an electric pump to a power source. It only happens in multiplayer, water pumps works fine on singleplayer worlds.

java.lang.NoSuchMethodError: net.minecraftforge.fluids.FluidStack.getFluidID()I
at mekanism.common.FluidNetwork.tickEmit(FluidNetwork.java:168)
at mekanism.common.FluidNetwork.onUpdate(FluidNetwork.java:248)
at mekanism.api.transmitters.DynamicNetwork.tick(DynamicNetwork.java:321)
at mekanism.api.transmitters.TransmitterNetworkRegistry.tickEnd(TransmitterNetworkRegistry.java:105)
at mekanism.api.transmitters.TransmitterNetworkRegistry.onTick(TransmitterNetworkRegistry.java:91)
at cpw.mods.fml.common.eventhandler.ASMEventHandler_184_TransmitterNetworkRegistry_onTick_ServerTickEvent.invoke(.dynamic)
at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:247)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:590)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

To fix this I had to user MCEdit to delete the water pump and the ticks related to that block.

The server starts fine but it crashes as soon as any player logs in.

After some research I noticed that it's a problem regarding mechanical pumps. Pumps are able to take the water in (I tried with the IC2 pump) but when the water starts going through the mechanical pipe the server crashes.

Thanks in advance

**Comment by TheTux94** [comment]
I made some more testing and it appears that it's a bug that occurs when transporting any kind of fluid with any kind of fluid pipe (I tried with Ender IO pipes too).

Here's one more example crash:
java.lang.NoSuchMethodError: net.minecraftforge.fluids.FluidStack.getFluidID()I
	at mekanism.common.FluidNetwork.tickEmit(FluidNetwork.java:168)
	at mekanism.common.FluidNetwork.onUpdate(FluidNetwork.java:248)
	at mekanism.api.transmitters.DynamicNetwork.tick(DynamicNetwork.java:321)
	at mekanism.api.transmitters.TransmitterNetworkRegistry.tickEnd(TransmitterNetworkRegistry.java:105)
	at mekanism.api.transmitters.TransmitterNetworkRegistry.onTick(TransmitterNetworkRegistry.java:91)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_184_TransmitterNetworkRegistry_onTick_ServerTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:247)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:590)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by TheTux94** [comment]
After few hours of investigating I noticed that the problem was not caused by this mod but by Forge and how it handles fluids. I managed to fix the problem by downgrading Forge on the server.

I apologize for posting this issue here, I hope it may be useful to someone who will encounter the same  bug.

**Comment by vedalken254** [comment]
@TheTux94 forge version so people can avoid?

**Comment by TheTux94** [comment]
Old buggy version: 1.7.10-10.13.2.1291
Upgraded to: 1.7.10-10.13.4.1541-1.7.10

I meant "upgraded" instead of "downgraded", edited the original post.

**Comment by AryanVainala** [comment]
It doesn't work for me. Someone please help!

**Comment by AryanVainala** [comment]
Time: 14/12/16 17:28
Description: Updating screen events

java.lang.NoSuchMethodError: net.minecraftforge.fluids.FluidStack.getFluidID()I
	at mekanism.common.item.ItemBlockMachine.setFluidStack(ItemBlockMachine.java:665)
	at mekanism.common.block.BlockMachine.func_149666_a(BlockMachine.java:473)
	at net.minecraft.item.ItemBlock.func_150895_a(ItemBlock.java:181)
	at net.minecraft.creativetab.CreativeTabs.func_78018_a(CreativeTabs.java:312)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147050_b(GuiContainerCreative.java:479)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146286_b(GuiContainerCreative.java:456)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:306)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146274_d(GuiContainerCreative.java:566)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1628)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at info.mineshafter.GameStarter.main(GameStarter.java:24)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at mekanism.common.item.ItemBlockMachine.setFluidStack(ItemBlockMachine.java:665)
	at mekanism.common.block.BlockMachine.func_149666_a(BlockMachine.java:473)
	at net.minecraft.item.ItemBlock.func_150895_a(ItemBlock.java:181)
	at net.minecraft.creativetab.CreativeTabs.func_78018_a(CreativeTabs.java:312)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147050_b(GuiContainerCreative.java:479)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146286_b(GuiContainerCreative.java:456)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:306)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146274_d(GuiContainerCreative.java:566)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiContainerCreative

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [GCEntityClientPlayerMP['monster66380'/311, l='MpServer', x=959.03, y=70.12, z=788.97]]
	Chunk stats: MultiplayerChunkCache: 230, 230
	Level seed: 0
	Level generator: ID 04 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (944,64,776), Chunk: (at 0,4,8 in 59,48; contains blocks 944,0,768 to 959,255,783), Region: (1,1; contains chunks 32,32 to 63,63, blocks 512,0,512 to 1023,255,1023)
	Level time: 96992 game time, 83964 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 70 total; [EntitySquid['Squid'/137, l='MpServer', x=948.62, y=46.00, z=731.19], EntityBat['Bat'/136, l='MpServer', x=945.25, y=23.10, z=731.56], EntityBat['Bat'/139, l='MpServer', x=958.65, y=26.22, z=739.59], EntitySquid['Squid'/138, l='MpServer', x=957.53, y=46.39, z=731.14], EntityBat['Bat'/140, l='MpServer', x=951.17, y=20.70, z=863.66], EntityBat['Bat'/565, l='MpServer', x=1009.44, y=43.73, z=823.49], EntityBat['Bat'/156, l='MpServer', x=957.34, y=11.71, z=734.76], EntitySquid['Squid'/157, l='MpServer', x=967.48, y=46.00, z=738.31], EntitySquid['Squid'/158, l='MpServer', x=969.73, y=45.00, z=729.46], EntitySquid['Squid'/171, l='MpServer', x=963.41, y=54.98, z=749.32], EntitySquid['Squid'/170, l='MpServer', x=963.66, y=48.34, z=739.94], EntitySquid['Squid'/169, l='MpServer', x=973.27, y=52.28, z=747.86], EntitySquid['Squid'/168, l='MpServer', x=965.49, y=50.84, z=750.47], EntitySquid['Squid'/175, l='MpServer', x=965.63, y=53.25, z=750.35], EntitySquid['Squid'/174, l='MpServer', x=973.73, y=55.25, z=754.46], EntitySquid['Squid'/173, l='MpServer', x=964.31, y=50.36, z=751.52], EntitySquid['Squid'/172, l='MpServer', x=967.28, y=51.40, z=740.52], EntitySquid['Squid'/163, l='MpServer', x=977.38, y=49.31, z=742.39], EntitySquid['Squid'/162, l='MpServer', x=973.46, y=51.43, z=727.69], GCEntityClientPlayerMP['monster66380'/311, l='MpServer', x=959.03, y=70.12, z=788.97], EntitySquid['Squid'/161, l='MpServer', x=971.34, y=49.40, z=732.87], EntitySquid['Squid'/160, l='MpServer', x=967.70, y=48.97, z=725.00], EntitySquid['Squid'/167, l='MpServer', x=970.43, y=48.74, z=746.33], EntitySquid['Squid'/166, l='MpServer', x=971.48, y=52.82, z=746.17], EntitySquid['Squid'/165, l='MpServer', x=970.25, y=52.34, z=748.15], EntitySquid['Squid'/164, l='MpServer', x=964.26, y=48.31, z=738.79], EntitySquid['Squid'/187, l='MpServer', x=986.07, y=47.08, z=729.58], EntitySquid['Squid'/184, l='MpServer', x=976.78, y=45.43, z=732.30], EntitySquid['Squid'/185, l='MpServer', x=981.40, y=45.00, z=728.75], EntitySquid['Squid'/190, l='MpServer', x=982.56, y=48.25, z=724.49], EntitySquid['Squid'/191, l='MpServer', x=976.98, y=46.92, z=741.41], EntitySquid['Squid'/188, l='MpServer', x=980.69, y=49.48, z=732.10], EntitySquid['Squid'/189, l='MpServer', x=985.67, y=48.82, z=734.32], EntitySquid['Squid'/178, l='MpServer', x=975.38, y=53.00, z=811.46], EntitySquid['Squid'/179, l='MpServer', x=976.52, y=53.36, z=810.84], EntitySquid['Squid'/176, l='MpServer', x=972.53, y=53.00, z=750.19], EntitySquid['Squid'/177, l='MpServer', x=974.18, y=53.00, z=809.20], EntitySquid['Squid'/180, l='MpServer', x=972.77, y=53.14, z=821.32], EntityBat['Bat'/197, l='MpServer', x=987.25, y=48.10, z=826.25], EntitySquid['Squid'/196, l='MpServer', x=978.91, y=54.35, z=817.00], EntitySquid['Squid'/198, l='MpServer', x=987.50, y=48.00, z=821.50], EntitySquid['Squid'/193, l='MpServer', x=990.22, y=55.52, z=811.89], EntitySquid['Squid'/192, l='MpServer', x=974.17, y=52.00, z=746.26], EntitySquid['Squid'/195, l='MpServer', x=985.50, y=54.00, z=824.38], EntitySquid['Squid'/194, l='MpServer', x=982.13, y=54.09, z=818.72], EntitySquid['Squid'/221, l='MpServer', x=999.66, y=55.34, z=851.97], EntitySquid['Squid'/222, l='MpServer', x=995.40, y=54.38, z=848.47], EntitySquid['Squid'/216, l='MpServer', x=1002.58, y=54.39, z=846.79], EntityBat['Bat'/217, l='MpServer', x=997.11, y=21.00, z=854.67], EntitySquid['Squid'/212, l='MpServer', x=998.57, y=54.25, z=841.50], EntitySquid['Squid'/213, l='MpServer', x=995.58, y=54.00, z=843.47], EntitySquid['Squid'/214, l='MpServer', x=1001.53, y=54.00, z=842.94], EntitySquid['Squid'/215, l='MpServer', x=1000.20, y=54.00, z=842.76], EntitySquid['Squid'/209, l='MpServer', x=991.04, y=55.00, z=816.73], EntitySquid['Squid'/210, l='MpServer', x=998.23, y=55.32, z=828.83], EntitySquid['Squid'/211, l='MpServer', x=998.54, y=55.00, z=823.09], EntitySquid['Squid'/237, l='MpServer', x=1010.77, y=54.46, z=847.51], EntitySquid['Squid'/236, l='MpServer', x=1019.49, y=56.34, z=758.55], EntitySquid['Squid'/235, l='MpServer', x=1014.56, y=58.67, z=759.33], EntitySquid['Squid'/234, l='MpServer', x=1014.89, y=56.39, z=760.49], EntitySquid['Squid'/233, l='MpServer', x=1008.56, y=57.08, z=760.53], EntitySquid['Squid'/232, l='MpServer', x=1017.39, y=56.38, z=761.67], EntityBat['Bat'/110, l='MpServer', x=891.75, y=31.82, z=832.61], EntitySquid['Squid'/231, l='MpServer', x=1019.92, y=54.23, z=737.59], EntityBat['Bat'/108, l='MpServer', x=881.75, y=39.10, z=764.25], EntityBat['Bat'/109, l='MpServer', x=881.69, y=39.10, z=764.34], EntityBat['Bat'/254, l='MpServer', x=1030.00, y=40.00, z=825.00], EntityBat['Bat'/116, l='MpServer', x=942.42, y=42.53, z=784.54], EntityBat['Bat'/115, l='MpServer', x=934.92, y=39.88, z=784.05], EntityBat['Bat'/112, l='MpServer', x=907.52, y=39.00, z=724.23]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2432)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:909)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at info.mineshafter.GameStarter.main(GameStarter.java:24)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Mac OS X (x86_64) version 10.10.5
	Java Version: 1.7.0_80, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 174209160 bytes (166 MB) / 458227712 bytes (437 MB) up to 1029177344 bytes (981 MB)
	JVM Flags: 2 total; -Xmx1G -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 95
	FML: MCP v9.05 FML v7.10.85.1286 Minecraft Forge 10.13.2.1286 25 mods loaded, 25 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.85.1286} [Forge Mod Loader] (forge-1.7.10-10.13.2.1286.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.2.1286} [Minecraft Forge] (forge-1.7.10-10.13.2.1286.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	GalacticraftCore{3.0.12} [Galacticraft Core] (GalacticraftCore-1.7-3.0.12.375 (1).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	SpaceCore{4.1.9} [4Space Core] (4Space-4.1.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ExoCore{0.1.2} [4Space Exoplanets Core] (4Space-4.1.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ExoElipse{0.1.2} [4Space Exoplanets Elipse] (4Space-4.1.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	SpaceCallisto{4.1.9} [4Space Callisto] (4Space-4.1.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	SpaceEuropa{4.1.9} [4Space Europa] (4Space-4.1.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	SpaceVenus{4.1.9} [4Space Venus] (4Space-4.1.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	SpaceIo{4.1.9} [4Space Io] (4Space-4.1.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	SpaceMercury{4.1.9} [4Space Mercury] (4Space-4.1.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	SpacePluto{4.1.9} [4Space Pluto] (4Space-4.1.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BiomesOPlenty{2.0.2} [Biomes O' Plenty] (Biomes-O-Plenty-Mod-1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.12.375 (1).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ForgeMultipart{1.1.2.331} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Mekanism{8.1.9} [Mekanism] (Mekanism-1.7.10-8.1.9.265.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MekanismGenerators{8.1.9} [MekanismGenerators] (MekanismGenerators-1.7.10-8.1.9.265.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MekanismTools{8.1.9} [MekanismTools] (MekanismTools-1.7.10-8.1.9.265.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	cfm{3.4.7} [�9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.7(1.7.10).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	kitchen{1.3.22} [The Kitchen Mod] (TheKitchenMod-1.3.22-1.7.2-10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	TooMuchTNT{2.9} [TooMuchTNT] (Too-Much-TNT-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	McMultipart{1.1.2.331} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ForgeMicroblock{1.1.2.331} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Launched Version: 1.7.10-Forge10.13.2.1286
	LWJGL: 2.9.1
	OpenGL: Intel HD Graphics 4000 OpenGL Engine GL version 2.1 INTEL-10.6.33, Intel Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
