### ISSUE TITLE
crash on start up after editing ore gen on other mods

### ISSUE THREAD

**Issue by mrgreaper** [aidancbrady/Mekanism#3036]
the error we are getting is :

16:45:05] [Server thread/ERROR] [FML/]: Caught exception from Mekanism
java.lang.NullPointerException
	at net.minecraft.item.ItemStack.func_77960_j(ItemStack.java:217) ~[add.class:?]
	at mekanism.api.util.StackUtils.equalsWildcard(StackUtils.java:62) ~[StackUtils.class:?]
	at mekanism.api.util.StackUtils.equalsWildcardWithNBT(StackUtils.java:67) ~[StackUtils.class:?]
	at mekanism.common.recipe.inputs.ItemStackInput.testEquality(ItemStackInput.java:66) ~[ItemStackInput.class:?]
	at mekanism.common.recipe.inputs.ItemStackInput.testEquality(ItemStackInput.java:8) ~[ItemStackInput.class:?]
	at mekanism.common.recipe.inputs.MachineInput.equals(MachineInput.java:36) ~[MachineInput.class:?]
	at java.util.HashMap.putVal(Unknown Source) ~[?:1.8.0_05]
	at java.util.HashMap.put(Unknown Source) ~[?:1.8.0_05]
	at mekanism.common.recipe.RecipeHandler$Recipe.put(RecipeHandler.java:581) ~[RecipeHandler$Recipe.class:?]
	at mekanism.common.Mekanism.serverStarting(Mekanism.java:1048) ~[Mekanism.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_05]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_05]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_05]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_05]
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) ~[FMLModContainer.class:?]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_05]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_05]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[LoadController.class:?]
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_05]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_05]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_05]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_05]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) [LoadController.class:?]
	at cpw.mods.fml.common.Loader.serverStarting(Loader.java:789) [Loader.class:?]
	at cpw.mods.fml.common.FMLCommonHandler.handleServerStarting(FMLCommonHandler.java:278) [FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:277) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[16:45:05] [Server thread/ERROR] [FML/]: A fatal exception occurred during the server starting event
java.lang.NullPointerException
	at net.minecraft.item.ItemStack.func_77960_j(ItemStack.java:217) ~[add.class:?]
	at mekanism.api.util.StackUtils.equalsWildcard(StackUtils.java:62) ~[StackUtils.class:?]
	at mekanism.api.util.StackUtils.equalsWildcardWithNBT(StackUtils.java:67) ~[StackUtils.class:?]
	at mekanism.common.recipe.inputs.ItemStackInput.testEquality(ItemStackInput.java:66) ~[ItemStackInput.class:?]
	at mekanism.common.recipe.inputs.ItemStackInput.testEquality(ItemStackInput.java:8) ~[ItemStackInput.class:?]
	at mekanism.common.recipe.inputs.MachineInput.equals(MachineInput.java:36) ~[MachineInput.class:?]
	at java.util.HashMap.putVal(Unknown Source) ~[?:1.8.0_05]
	at java.util.HashMap.put(Unknown Source) ~[?:1.8.0_05]
	at mekanism.common.recipe.RecipeHandler$Recipe.put(RecipeHandler.java:581) ~[RecipeHandler$Recipe.class:?]
	at mekanism.common.Mekanism.serverStarting(Mekanism.java:1048) ~[Mekanism.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_05]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_05]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_05]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_05]
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) ~[FMLModContainer.class:?]
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_05]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_05]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[LoadController.class:?]
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_05]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_05]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_05]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_05]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) ~[LoadController.class:?]
	at cpw.mods.fml.common.Loader.serverStarting(Loader.java:789) [Loader.class:?]
	at cpw.mods.fml.common.FMLCommonHandler.handleServerStarting(FMLCommonHandler.java:278) [FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:277) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]

this is with the latest stable build of mekinism (252)
after a lot of searching i found 3 similier bug reports but all are closed so im guessing its an old bug that has returned? 
couldnt say which mod caused it (tried to reset each mod one after the other but issue persisted

reset all configs from a back up and the world begins to load again
also tested with a new world, as i thought at first i had a corrupted world but the same issue happened

also tried dev version 255, same issue 

It seems that mekenism does not like it if a mod has turned of its ore generation so we now have 5 copper ores 4 or 5 tins lol (it was that or dropping mekenism from the server) 

also have you thought about adding the mod to curse? it would make life a lot easier and since they host the files for free you wouldnt need the adfly links :)

**Comment by VT-14** [comment]
What I've done in the past is turn off ores from the config of the mod generating it (in this case, go to Mekanism's config and turn off copper and tin ore generation).

I never learned to use CoFH's worldgen tools properly, but a quick look at FTB Infinity Evolved's default config for Tinkers' Construct shows me that they turned off TC's generic Copper, Tin, and Aluminum ores (bushes and gravel ores are still turned on).  Looking at Immersive Engineering's config, all of those ores are also turned off (vein sizes set to 0).  I couldn't find any oregen config for Thermal Foundation ores, but I'm sure those are embedded in CoFH.

Depending on what mod you are using to alter worldgen, you may have to disable all the copper, tin, etc. ores individually.

**Comment by mrgreaper** [comment]
that was the issue though, with all the world gen set to default it all works fine (accept i get 5 different coppers etc)

once i turn off ore gen to get down to one copper, one tin etc thats when mekanism crashes.

so i had to make a choice, keep mek and have multiple copper ores or lose mek but have only one copper ore..... i have learnt to embrace the multiple ores :)

**Comment by VT-14** [comment]
What mod are you using to alter world gen?

**Comment by mrgreaper** [comment]
biomes o plenty :)

**Comment by Stephen789Git** [comment]
I'm getting this issue too, but I'm editing ore gen in the config files...
I looked through the src here, and it looks like it's stemming from the map in the main mod class
roundabouts 1048, as the crash info says

**Comment by Tsyklop** [comment]
same issue

**Comment by erythreas34** [comment]
I get the same problem here.

**Comment by Stephen789Git** [comment]
It seems to stem from the map that it's using. Perhaps an ore registration error in there?
I'm not familiar with that map utility, so I'm not sure where to even look for that.

**Comment by Sharkking** [comment]
I am having the same crash. It seems to work on the client but i am unable to play a new generated world. I have Biomes'o'Plenty and RTG disabled for testing but it gives the above crash on the server as well, Even when using all default config from other mods,

**Comment by VT-14** [comment]
Can someone who is still having this issue post a mod list?  I want to see if I can get it to work tonight.  If possible, I would like the list to have CoFH Core, as that's what I'm familiar with when altering world gen.

**Comment by Stephen789Git** [comment]
I'm creating a world now to get you an up-to-date list, but in the config I turned off duplicate ores in galacticraft, mariculture, metallurgy, railcraft, immersive engineering, forestry, and TConstruct.

If it really is a problem with ore registration, perhaps an exception check in the code could fix it?

**Comment by Stephen789Git** [comment]
here's my mod lister output for my current setup: http://pastebin.com/MNnVfMg9

**Comment by VT-14** [comment]
@Stephen789Git Sorry, but that mod list is way longer than my attention span.  How are you editing ore gen?  In my experience, CoFH Core want you to disable ALL other ore gen and pull the ores it needs directly

I'm going to see if I can duplicate this issue with the FTB Infinity pack updated with the most up to date mods and a default set of configs and adding Mekanism to it.

**Comment by Stephen789Git** [comment]
I edited the oregen directly from the configs of the mods. I wasn't aware that CoFH core allowed you to do that, I'll look into it as a fix.

**Comment by VT-14** [comment]
@Stephen789Git Copy your config folder elsewhere, and remove the folder completely from that minecraft instance.  That will generate default configs for all of your mods.  If that fails, then you probably have a mod conflict and it could be any number of mods you have installed causing it.

I'll take a look at any crashlog you feel like posting with default configs, but I can't guarantee I'll be able to spot the issue.  I'm not a programmer, just someone who has banged my head against personal packs a few times.

**Comment by Stephen789Git** [comment]
here's the crash report after I reset the configs:
http://pastebin.com/VPREjACQ

**Comment by VT-14** [comment]
Full log please.

A forge crash log should have a mod list and each mod's activation status.  At the bottom, some mods (like Ender IO) often write up issues they found, like known conflict mods and outdated APIs being loaded.

**Comment by Stephen789Git** [comment]
it's not an actual crash, though, it only kicks back to the title screen. After the paste I sent you it just states that the server was forced to an incorrect state and has the output of mods shutting dimensions down.

**Comment by Sharkking** [comment]
Hello @VT-14

trying to provide more information to help addressing this issue: 

1st try upgrading from working version 1.7.2.185 

on startup: 
Missing Blocks/Items:
Mekanism:FrictionBoots
aobd:bottle_lithium

and a full startup log containing the crash: (note forge doesn´t write a crashlog in this case): http://boss2.strict-hosting.com/pack/startup.txt

2nd try: removed the config folder completely / crashed:
http://boss2.strict-hosting.com/pack/startup2.txt

3rd try: generating a new map with fresh config folder / crashed:
http://boss2.strict-hosting.com/pack/startup3.txt

4th try: generating a fresh world without RTG and No Biomes'o'Plenty usage (level-type=NORMAL) / Crashed
http://boss2.strict-hosting.com/pack/startup4.txt

Modlist (jar versions):
http://boss2.strict-hosting.com/pack/jars.txt

please let me know if i can help any further. Thanks

Sharkking

**Comment by VT-14** [comment]
That log has what I was looking for (Forge edits the vanilla crash logs).  The modlist I was looking for previously was generated at [07:59:05] (near the bottom).  It does confirm that Mekanism is the mod that is throwing the fatal error, but that doesn't necessarily mean it's the cause.

Noteworthy events from the 3rd log.

> [07:58:32] [Server thread/INFO] [STDOUT]: [eu.thesociety.DragonbornSR.DragonsRadioMod.Handler.Cmsg:writeError:20]: [Dragon's Radio Mod] *** Error caught by Dragon's Radio Mod ***
[07:58:32] [Server thread/INFO] [STDOUT]: [eu.thesociety.DragonbornSR.DragonsRadioMod.Handler.Cmsg:writeError:21]: java.io.IOException: Server returned HTTP response code: 403 for URL: http://www.thesociety.eu/dragonsradiomod/validate.php?port=25565
[07:58:32] [Server thread/INFO] [STDOUT]: [eu.thesociety.DragonbornSR.DragonsRadioMod.Handler.Cmsg:writeError:22]: [Dragon's Radio Mod] *** End of Exception caught by Dragon's Radio Mod ***
[07:58:32] [Server thread/INFO] [STDOUT]: [eu.thesociety.DragonbornSR.DragonsRadioMod.Handler.Cmsg:writeError:23]: [Dragon's Radio Mod] Please Report this error to DragonbornSR! (info@thesociety.eu)

Rotarycraft was throwing a lot of errors, but I don't think that was the cause.  Dragon API did as well, and I have no idea how that one compares.

At [07:58:42], dimensions -19, -37, and -39 Could not be registered and should be changed in the configs.  I suspect Galacticraft, but any mod that generates dimensions could be an issue.  You may need to blacklist those from RFTools.

This Mekanism error is thrown 7 times.  I checked and it is indeed in ALL of your logs.
> [07:58:51] [Server thread/ERROR] [Mekanism]: [Mekanism] NuclearCraft attempted to addrecipe of type Combiner with an invalid input.
Mess around with NuclearCraft (update, see if there is a config to turn off Mekanism compatibility, remove it, etc.)

**Comment by VT-14** [comment]
The other option, and this applies to anyone having ore-gen issues, is to try disabling the Combiner.

Mekanism config, line 78. try
     B:CombinerEnabled=false

I just tried with Mekanism, ReactorCraft, RotaryCraft, and DragonAPI only on a modpack, and it loaded with no issues (no changes to configs by me).
Mekanism: 8.8.8.258
Reika mods: V10d

**Comment by Sharkking** [comment]
thanks so far i will give it a try

**Comment by Stephen789Git** [comment]
I tried this on my pack, but it still crashed to title: http://pastebin.com/NPZsq0bX
(it's only a partial log, but that's because pastebin has a character limit)

**Comment by Sharkking** [comment]
I encountered the same. Even removing all Decoration Mods, removing the map to generate a new one and delete the config folder each time did not help. I will try with the setup VT mentioned and add mod by mod to see where it crashes

**Comment by VT-14** [comment]
I'm not a coder, but it looks like something is trying to add a recipe to Mekanism (causing Mekanism to crash).  That suggests cross mod compatibility issues.

Which means the best way to solve this is to mess with your mod list and try different combinations until you narrow down on exactly what combination of mods crash.  I think the typical way is to load half your mod list (and Mekanism and required dependancies of loaded mods) and see if it crashes. then, try the other half.  from the half(s) that is(were) crashing, only load half of those (now quarters) and repeat until you find the mod(s) causing the issue.


A mod author will usually be willing to test a pack with a handful of mods in it.  If not the author themself, a random user (like myself) might try to replicate it and may be able to provide more insight.  The reported test pack should consist of only the mods that are crashing together (and doesn't crash if Mekanism is removed) and their dependancies.  NEI would likely also be an acceptable addition.

**Comment by aidancbrady** [comment]
After doing a bit of research, I can conclude that this is indeed due to some kind of faulty integration.

**Comment by Sharkking** [comment]
Just a short information

After adding mod after mod i finally found out that in our Case ExtraPlanets for Galacticcraft causing the crash

**Comment by Stephen789Git** [comment]
I don't have extraplanets installed. Could it be GalaxySpace causing the crash for me?

**Comment by Stephen789Git** [comment]
So is there a fix for this issue?
