### ISSUE TITLE
Server crash when loading with Mekanism in 1.7.10

### ISSUE THREAD

**Issue by jeviuss** [aidancbrady/Mekanism#3152]
Hi, I'm not sure what's wrong here but I've spent about an hour trying to figure out what went wrong!

`[11:16:45] [Server thread/ERROR]: Caught exception from Mekanism java.lang.NullPointerException at net.minecraft.item.ItemStack.func_77960_j(ItemStack.java:243) ~[add.class:?]
at mekanism.api.util.StackUtils.equalsWildcard(StackUtils.java:63) ~[StackUtils.class:?]
 at mekanism.api.util.StackUtils.equalsWildcardWithNBT(StackUtils.java:68) ~[StackUtils.class:?] 
at mekanism.common.recipe.inputs.ItemStackInput.testEquality(ItemStackInput.java:66) ~[ItemStackInput.class:?] 
at mekanism.common.recipe.inputs.ItemStackInput.testEquality(ItemStackInput.java:8) ~[ItemStackInput.class:?]
 at mekanism.common.recipe.inputs.MachineInput.equals(MachineInput.java:36) ~[MachineInput.class:?] 
at java.util.HashMap.putVal(HashMap.java:634) ~[?:1.8.0_60] 
at java.util.HashMap.put(HashMap.java:611) ~[?:1.8.0_60]
 at mekanism.common.recipe.RecipeHandler$Recipe.put(RecipeHandler.java:546) ~[RecipeHandler$Recipe.class:?] 
at mekanism.common.Mekanism.serverStarting(Mekanism.java:1086) ~[Mekanism.class:?] 
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60] 
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_60] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60] at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60] 
at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) ~[FMLModContainer.class:1.7.10-R0.1-SNAPSHOT] 
at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?] 
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60] at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60] 
at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[server-1.7.10.jar:?] 
at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[server-1.7.10.jar:?] at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[server-1.7.10.jar:?] at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[server-1.7.10.jar:?] at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[server-1.7.10.jar:?] at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[LoadController.class:1.7.10-R0.1-SNAPSHOT] at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[LoadController.class:1.7.10-R0.1-SNAPSHOT] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_60] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60] at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60] at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[server-1.7.10.jar:?] at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[server-1.7.10.jar:?] at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[server-1.7.10.jar:?] at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[server-1.7.10.jar:?] at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[server-1.7.10.jar:?] at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) [LoadController.class:1.7.10-R0.1-SNAPSHOT] at cpw.mods.fml.common.Loader.serverStarting(Loader.java:789) [Loader.class:1.7.10-R0.1-SNAPSHOT] at cpw.mods.fml.common.FMLCommonHandler.handleServerStarting(FMLCommonHandler.java:282) [FMLCommonHandler.class:1.7.10-R0.1-SNAPSHOT] at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:367) [lt.class:?] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631) [MinecraftServer.class:?] at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]`

**Comment by aidancbrady** [comment]
Fixed in dev :)

**Comment by jeviuss** [comment]
Thanks :)
