### ISSUE TITLE
Server Crash with latest Mekanism using 1.7.10 1614.

### ISSUE THREAD

**Issue by DraksterAU** [aidancbrady/Mekanism#3167]
See below;

```
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 09/04/16 13:53
Description: Exception in server tick loop

java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
        at java.util.HashMap$ValueIterator.next(HashMap.java:1458)
        at mekanism.api.transmitters.TransmitterNetworkRegistry.assignOrphans(TransmitterNetworkRegistry.java:139)
        at mekanism.api.transmitters.TransmitterNetworkRegistry.tickEnd(TransmitterNetworkRegistry.java:99)
        at mekanism.api.transmitters.TransmitterNetworkRegistry.onTick(TransmitterNetworkRegistry.java:91)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_411_TransmitterNetworkRegistry_onTick_ServerTickEvent.invoke(.dynamic)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
        at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:251)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:884)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:683)
        at java.lang.Thread.run(Thread.java:745)

```

**Comment by VT-14** [comment]
This Crash Report has the 3 most common mistakes I've seen on GitHub and various other bug trackers...

1) "Latest" is not a version number.  You should clearly indicate the version numbers of Minecraft, Forge, and any affected mods.  Not doing this just creates work for anyone trying to help you as they now have to figure out what version you are talking about; and you could be unknowingly using an outdated version anyway.

2) A Crash Log is usually well over 100 lines for a reason.  Posting the header and the few lines of code that are being blamed for the errors is like trying tying to understand this entire post by only reading the first line and the sentence "Yes; according to Soaryn, this is a bad idea."

3) The crash has no context.  Is this crashing on server startup?  Did you hook an Extra Utilities Ender Collector to an Immersive Engineering Item Robin (Yes; according to Soaryn, this is a bad idea.)?  Did you recently update or change the mods on this server?

**Comment by DraksterAU** [comment]
1) Latest and the date of the post is a version number. Unless you're a dimwit.
2) The relevant portion of the crash report is posted. The rest is irrelevant. I do not use pastebin unless I am posting entire server logs, or my post is going to be 100 lines long.
3) This crashes randomly. Sometimes after hours, sometimes after minutes.... and I am never the one online when it happens... so I cant help there. A simple look at the code will suffice.

4) Do not post in response to another persons issue unless it is actually helpful.

**Comment by DraksterAU** [comment]
Closing. Author will have got the important portion of this anyway.

**Comment by VT-14** [comment]
1) Assuming you aren't a dimwit and are actually using the "latest" version, then it is still more work for someone else.  Taking a minute to write "Mekanism 1.7.10 - 8.1.9.265, Minecraft 1.7.10, and Forge 1614" [I assume that was the Forge version number in the title] is not hard, and refusing to do so makes you look like a jerk and will get you yelled at or ignored.

2) Yes, only a few bits of the log are relevant.  However, you are not qualified to determine what is relevant.  Unless you got lucky and the issue is already known or super obvious, then not posting a full log will only get you asked to post the full log or ignored.  Refusing to post a full crashlog will get you yelled at or ignored.

3) Useful information.  You revealed that the server does indeed start and the crash doesn't have a relation to time.

4) If you are going to be posting bug reports, then you should know how to properly post them.  I am trying to help you.  Though, considering that I've now yelled at you, I'll probably start ignoring you.
