### ISSUE TITLE
Ticking memory connection crash when trying to place logical transporter

### ISSUE THREAD

**Issue by sader22** [aidancbrady/Mekanism#3177]
---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 18.04.2016 19:40
Description: Ticking memory connection

java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:322)
	at scala.None$.get(Option.scala:320)
	at codechicken.multipart.MultiPartRegistry$.writePartID(MultiPartRegistry.scala:191)
	at codechicken.multipart.TileMultipart.writeAddPart(TileMultipart.scala:289)
	at codechicken.multipart.TileMultipart.addPart_impl(TileMultipart.scala:275)
	at codechicken.multipart.MultipartGenerator$.addPart(MultipartGenerator.scala:97)
	at codechicken.multipart.TileMultipart$.addPart(TileMultipart.scala:601)
	at codechicken.multipart.TItemMultiPart$class.place$1(ItemMultiPart.scala:37)
	at codechicken.multipart.TItemMultiPart$class.onItemUse(ItemMultiPart.scala:47)
	at codechicken.multipart.JItemMultiPart.func_77648_a(ItemMultiPart.scala:14)
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:505)
	at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:128)
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:389)
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at scala.None$.get(Option.scala:322)
	at scala.None$.get(Option.scala:320)
	at codechicken.multipart.MultiPartRegistry$.writePartID(MultiPartRegistry.scala:191)
	at codechicken.multipart.TileMultipart.writeAddPart(TileMultipart.scala:289)
	at codechicken.multipart.TileMultipart.addPart_impl(TileMultipart.scala:275)
	at codechicken.multipart.MultipartGenerator$.addPart(MultipartGenerator.scala:97)
	at codechicken.multipart.TileMultipart$.addPart(TileMultipart.scala:601)
	at codechicken.multipart.TItemMultiPart$class.place$1(ItemMultiPart.scala:37)
	at codechicken.multipart.TItemMultiPart$class.onItemUse(ItemMultiPart.scala:47)
	at codechicken.multipart.JItemMultiPart.func_77648_a(ItemMultiPart.scala:14)
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:505)
	at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:128)
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:389)
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@282a794
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_77, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 524891904 bytes (500 MB) / 1272524800 bytes (1213 MB) up to 4187619328 bytes (3993 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn1G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 9 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCHIJAAAA	ForgeMultipart{1.1.2.331} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
	UCHIJAAAA	Mekanism{8.1.9} [Mekanism] (Mekanism-1.7.10-8.1.9.267.jar) 
	UCHIJAAAA	MekanismGenerators{8.1.9} [MekanismGenerators] (MekanismGenerators-1.7.10-8.1.9.267.jar) 
	UCHIJAAAA	MekanismTools{8.1.9} [MekanismTools] (MekanismTools-1.7.10-8.1.9.267.jar) 
	UCHIJAAAA	McMultipart{1.1.2.331} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
	UCHIJAAAA	ForgeMicroblock{1.1.2.331} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['sader'/250, l='New World', x=101,22, y=69,00, z=230,38]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by sader22** [comment]
I know some of this eror up there but they not solved

**Comment by aidancbrady** [comment]
This is fixed in v9.

**Comment by sader22** [comment]
when we can download v 9 ?
