### ISSUE TITLE
Security Settings inconsistent / ineffective

### ISSUE THREAD

**Issue by TacoMage** [aidancbrady/Mekanism#3197]
In a LAN game, we did some experimenting with the new security settings and found the following out:

Personal chests are not affected by any setting.  Private chests are still accessible and breakable by non-owners.
Machines can be accessed by non-owners, and broken with some modded tools, but not vanilla.

If you place an item into a machine that you don't own, the game will crash when the job completes.  Log and stacktrace below.

---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 4/29/16 11:06 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at mekanism.common.recipe.inputs.MachineInput.inputContains(MachineInput.java:30)
	at mekanism.common.recipe.inputs.ItemStackInput.useItemStackFromInventory(ItemStackInput.java:44)
	at mekanism.common.recipe.machines.BasicMachineRecipe.canOperate(BasicMachineRecipe.java:21)
	at mekanism.common.tile.TileEntityElectricMachine.canOperate(TileEntityElectricMachine.java:217)
	at mekanism.common.tile.TileEntityElectricMachine.onUpdate(TileEntityElectricMachine.java:154)
	at mekanism.common.tile.TileEntityBasicBlock.func_145845_h(TileEntityBasicBlock.java:77)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at mekanism.common.recipe.inputs.MachineInput.inputContains(MachineInput.java:30)
	at mekanism.common.recipe.inputs.ItemStackInput.useItemStackFromInventory(ItemStackInput.java:44)
	at mekanism.common.recipe.machines.BasicMachineRecipe.canOperate(BasicMachineRecipe.java:21)
	at mekanism.common.tile.TileEntityElectricMachine.canOperate(TileEntityElectricMachine.java:217)
	at mekanism.common.tile.TileEntityElectricMachine.onUpdate(TileEntityElectricMachine.java:154)
	at mekanism.common.tile.TileEntityBasicBlock.func_145845_h(TileEntityBasicBlock.java:77)

-- Block entity being ticked --
Details:
	Name: Crusher // mekanism.common.tile.TileEntityCrusher
	Block type: ID #168 (tile.MachineBlock // mekanism.common.block.BlockMachine)
	Block data value: 3 / 0x3 / 0b0011
	Block location: World: (894,64,510), Chunk: (at 14,4,14 in 55,31; contains blocks 880,0,496 to 895,255,511), Region: (1,0; contains chunks 32,0 to 63,31, blocks 512,0,0 to 1023,255,511)
	Actual block type: ID #168 (tile.MachineBlock // mekanism.common.block.BlockMachine)
	Actual block data value: 3 / 0x3 / 0b0011
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: Test
	All players: 2 total; [EntityPlayerMP['TacoMage'/47, l='Test', x=894.50, y=64.00, z=507.73], EntityPlayerMP['Towsty_'/4403933, l='Test', x=890.87, y=64.00, z=510.19]]
	Chunk stats: ServerChunkCache: 958 Drop: 0
	Level seed: -1148483617326649471
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (12,64,172), Chunk: (at 12,4,12 in 0,10; contains blocks 0,0,160 to 15,255,175), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 2273792 game time, 6104 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 135653 (now: false), thunder time: 34206 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by aidancbrady** [comment]
I've hopefully fixed this issue. Try out the latest build and let me know if it works for you.
