### ISSUE TITLE
Changing inventory contents while in turbine GUI causes crash, #3239 on next load

### ISSUE THREAD

**Issue by cobra** [aidancbrady/Mekanism#3241]
I was playing around a bit in my test world, when I opened the the industrial turbine GUI and changed the player inventory (in one case by accidentally shift-clicking, in the other case by deleting an itemstack via dropping it into NEI's item pane). Minecraft crashed with this log, and after restarting it triggered #3239 each time I loaded this world. I managed to escape this crash loop by rapidly clicking after opening it, deleting a block and breaking the multiblock.
````
[18:32:50] [Client thread/INFO]: mekanism.generators.client.gui.GuiIndustrialTurbine
[18:32:50] [Client thread/INFO]: mekanism.common.inventory.container.ContainerFilter
[18:33:02] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking memory connection
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) ~[nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) ~[bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
Caused by: java.lang.IndexOutOfBoundsException: Index: 32, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_91]
	at java.util.ArrayList.get(ArrayList.java:429) ~[?:1.8.0_91]
	at net.minecraft.inventory.Container.func_75144_a(SourceFile:191) ~[zs.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:883) ~[nh.class:?]
	at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:32) ~[ix.class:?]
	at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:10) ~[ix.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) ~[nc.class:?]
	... 5 more
````

**Comment by aidancbrady** [comment]
Fixed, thanks!
