### ISSUE TITLE
Crash when placing personal chest

### ISSUE THREAD

**Issue by condensedapple** [aidancbrady/Mekanism#3267]
#### Issue Description:
Placing and opening a personal chest crashed the server next to EnderIO-ItemConduits that are "doing sth", the client disconnected to title screen.

#### What happens:
The server crashes, the client disconnects to title screen. (also happens in singleplayer)
The following message appears in the server console.
```
java.lang.ArrayIndexOutOfBoundsException: 54
	at mekanism.common.tile.TileEntityContainerBlock.func_70301_a(TileEntityContainerBlock.java:87)
	at com.enderio.core.common.util.ItemUtil.doInsertItemInv(ItemUtil.java:388)
	at com.enderio.core.common.util.ItemUtil.doInsertItemInv(ItemUtil.java:375)
	at com.enderio.core.common.util.ItemUtil.doInsertItem(ItemUtil.java:325)
	at crazypants.enderio.conduit.item.NetworkedInventory.insertItem(NetworkedInventory.java:284)
	at crazypants.enderio.conduit.item.NetworkedInventory.insertIntoTargets(NetworkedInventory.java:245)
	at crazypants.enderio.conduit.item.NetworkedInventory.doTransfer(NetworkedInventory.java:193)
	at crazypants.enderio.conduit.item.NetworkedInventory.transferItems(NetworkedInventory.java:166)
	at crazypants.enderio.conduit.item.NetworkedInventory.onTick(NetworkedInventory.java:113)
	at crazypants.enderio.conduit.item.ItemConduitNetwork.doNetworkTick(ItemConduitNetwork.java:214)
	at crazypants.enderio.conduit.ConduitNetworkTickHandler.tickEnd(ConduitNetworkTickHandler.java:63)
	at crazypants.enderio.conduit.ConduitNetworkTickHandler.onServerTick(ConduitNetworkTickHandler.java:47)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_338_ConduitNetworkTickHandler_onServerTick_ServerTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:247)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:590)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

#### What you expected to happen:
Everything works normally (placing a chest is not that extraordinary ;)

#### Steps to reproduce:
1. Place any chest (e.g. minecraft vanilla)
2. Fill it with any items
3. Place an EnderIO-Item Conduit and configure it to export from this chest
4. Place a Mekanism-Personal Chest next to the conduit and configure it to import in this personal chest
5. Try to open the personal chest
6. crash

____
#### Affected Versions

- EnderIO: 2.3.0.425_beta
- EnderCore: 0.2.0.34_beta
- Mekanism 9.0.1.270
- Minecraft: 1.7.10
- Forge: 10.13.4.1614

#### crash-report:
https://gist.github.com/condensedapple/00f785303f8b1833cad5093a214b5187

**Comment by aidancbrady** [comment]
Fixed! Thanks.
