### ISSUE TITLE
Server crash when connecting Mekanism Generator to Thermal Expansion Tesseract

### ISSUE THREAD

**Issue by DraksterAU** [aidancbrady/Mekanism#3414]
Hi Aidan,

When connecting a Mek v9 generator to a Thermal Expansion Tesseract, a server crash occurs.
See below.

Hoping you can be of assistance, they aren't known for it. Works fine with Mek v8.

Using v9.0.2.274 of Mekanism.

Regards,
DraksterAU

```
> ---- Minecraft Crash Report ----
> // Surprise! Haha. Well, this is awkward.
> 
> Time: 27/06/16 23:45
> Description: Ticking block entity
> 
> java.lang.NullPointerException: Ticking block entity
>         at TEnergyReceiver$$PassThrough$class.receiveEnergy(Unknown Source)
>         at TileMultipart_cmp$$0.receiveEnergy(Unknown Source)
>         at cofh.thermalexpansion.block.ender.TileTesseract.receiveEnergy(TileTesseract.java:832)
>         at cofh.thermalexpansion.block.ender.TileTesseract.sendEnergy(TileTesseract.java:284)
>         at cofh.thermalexpansion.block.ender.TileTesseract.receiveEnergy(TileTesseract.java:917)
>         at mekanism.common.util.CableUtils.emit_do_do(CableUtils.java:245)
>         at mekanism.common.util.CableUtils.emit_do(CableUtils.java:209)
>         at mekanism.common.util.CableUtils.emit(CableUtils.java:181)
>         at mekanism.generators.common.tile.TileEntityGenerator.onUpdate(TileEntityGenerator.java:93)
>         at mekanism.generators.common.tile.TileEntityWindGenerator.onUpdate(TileEntityWindGenerator.java:27)
>         at mekanism.common.tile.TileEntityBasicBlock.func_145845_h(TileEntityBasicBlock.java:77)
>         at net.minecraft.world.World.func_72939_s(World.java:2548)
>         at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:673)
>         at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:976)
>         at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
>         at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:831)
>         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:683)
>         at java.lang.Thread.run(Thread.java:745)
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Stacktrace:
>         at TEnergyReceiver$$PassThrough$class.receiveEnergy(Unknown Source)
>         at TileMultipart_cmp$$0.receiveEnergy(Unknown Source)
>         at cofh.thermalexpansion.block.ender.TileTesseract.receiveEnergy(TileTesseract.java:832)
>         at cofh.thermalexpansion.block.ender.TileTesseract.sendEnergy(TileTesseract.java:284)
>         at cofh.thermalexpansion.block.ender.TileTesseract.receiveEnergy(TileTesseract.java:917)
>         at mekanism.common.util.CableUtils.emit_do_do(CableUtils.java:245)
>         at mekanism.common.util.CableUtils.emit_do(CableUtils.java:209)
>         at mekanism.common.util.CableUtils.emit(CableUtils.java:181)
>         at mekanism.generators.common.tile.TileEntityGenerator.onUpdate(TileEntityGenerator.java:93)
>         at mekanism.generators.common.tile.TileEntityWindGenerator.onUpdate(TileEntityWindGenerator.java:27)
>         at mekanism.common.tile.TileEntityBasicBlock.func_145845_h(TileEntityBasicBlock.java:77)
> 
> -- Block entity being ticked --
> Details:
>         Name: WindTurbine // mekanism.generators.common.tile.TileEntityWindGenerator
>         Block type: ID #1337 (tile.Generator // mekanism.generators.common.block.BlockGenerator)
>         Block data value: 6 / 0x6 / 0b0110
>         Block location: World: (388,78,28), Chunk: (at 4,4,12 in 24,1; contains blocks 384,0,16 to 399,255,31), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
>         Actual block type: ID #1337 (tile.Generator // mekanism.generators.common.block.BlockGenerator)
>         Actual block data value: 6 / 0x6 / 0b0110
> Stacktrace:
>         at net.minecraft.world.World.func_72939_s(World.java:2548)
>         at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:673)
> 
> -- Affected level --
> Details:
>         Level name: D9K-411
>         All players: 1 total; [GCEntityPlayerMP['matty705'/56769, l='D9K-411', x=387.79, y=78.00, z=26.22](matty705 at 387.78961622113394,78.0,26.220885384976125)]
>         Chunk stats: ServerChunkCache: 551 Drop: 0
>         Level seed: 3897733675631633044
>         Level generator: ID 00 - default, ver 1. Features enabled: true
>         Level generator options:
>         Level spawn location: World: (112,72,214), Chunk: (at 0,4,6 in 7,13; contains blocks 112,0,208 to 127,255,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
>         Level time: 225006074 game time, 226987442 day time
>         Level dimension: 105
>         Level storage version: 0x04ABD - Anvil
>         Level weather: Rain time: 135462 (now: false), thunder time: 3550 (now: false)
>         Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
> Stacktrace:
>         at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:976)
>         at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
>         at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:831)
>         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:683)
>         at java.lang.Thread.run(Thread.java:745)
> 
> 
```

**Comment by aidancbrady** [comment]
Fairly sure this is not on my end, I've been doing some internal testing with tesseracts and have experienced no issues.  If you have some free time you could sort through your mod list to find the offender, I've seen this reported before.

**Comment by DraksterAU** [comment]
What thermal expansion and cofh versions are you using during testing?

**Comment by aidancbrady** [comment]
TE 4.1.2-240, CoFH 3.1.2-325
