### ISSUE TITLE
[1.7.10] Dev Branch Crash

### ISSUE THREAD

**Issue by jznomoney** [aidancbrady/Mekanism#3428]
I have just compiled the code for the development branch https://github.com/aidancbrady/Mekanism/commit/41ea222aab2bbc947e6ac61c4812fe726596b166 and when I launched my server I got a crash.

---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 6/30/16 4:17 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at mekanism.generators.common.tile.reactor.TileEntityReactorPort.onUpdate(TileEntityReactorPort.java:67)
	at mekanism.common.tile.TileEntityBasicBlock.func_145845_h(TileEntityBasicBlock.java:77)
	at net.minecraft.world.World.func_72939_s(World.java:2529)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:633)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:954)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
	at java.lang.Thread.run(Unknown Source)

**Comment by SteelShot** [comment]
The Server loaded fine for me, lemme build a reactor and check, i dont have one built yet

**Comment by SteelShot** [comment]
Works fine here buddy :/

![2016-07-01_03 51 59](https://cloud.githubusercontent.com/assets/5291010/16510569/37eec5d0-3f3f-11e6-8d1f-6f2323263d62.png)

**Comment by SteelShot** [comment]
Off Topic: Oh btw Aidan, the newest fix for the TE expansion and any other power transfer pipe/conduit/cable seems perfectly fine, you da Boss! :)

**Comment by jznomoney** [comment]
my reactors have water going in and steam being pumped out.

**Comment by jznomoney** [comment]
I tried restoring a backup from the day before still crashing.

net.minecraft.util.ReportedException: Ticking block entity
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:971) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) ~[lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_92]
Caused by: java.lang.NullPointerException
        at mekanism.generators.common.tile.reactor.TileEntityReactorPort.onUpdate(TileEntityReactorPort.java:67) ~[TileEntityReactorPort.class:?]
        at mekanism.common.tile.TileEntityBasicBlock.func_145845_h(TileEntityBasicBlock.java:77) ~[TileEntityBasicBlock.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:2529) ~[ahb.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:633) ~[mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:954) ~[MinecraftServer.class:?]
        ... 4 more
[17:50:38 ERROR]:       Cause of unexpected exception was
java.lang.NullPointerException
        at mekanism.generators.common.tile.reactor.TileEntityReactorPort.onUpdate(TileEntityReactorPort.java:67) ~[TileEntityReactorPort.class:?]
        at mekanism.common.tile.TileEntityBasicBlock.func_145845_h(TileEntityBasicBlock.java:77) ~[TileEntityBasicBlock.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:2529) ~[ahb.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:633) ~[mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:954) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) ~[lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_92]

**Comment by SteelShot** [comment]
Darn forgot about this, had reset my world an been pregen it till now, gimme 20 mins-ish ill try to build a steam reactor.

**Comment by SteelShot** [comment]
Again no crash with a steam reactor built
![2016-07-03_00 03 21](https://cloud.githubusercontent.com/assets/5291010/16542833/a763defa-40b1-11e6-9a5a-84fd32acaf83.png)
![2016-07-03_00 03 29](https://cloud.githubusercontent.com/assets/5291010/16542834/aa4afa40-40b1-11e6-8697-8f3b746c9ef7.png)

**Comment by jznomoney** [comment]
I'm wondering if it has to do with the new autoeject on the steam.  I have bunch of mechanism mechanical pipes attached to the reactors pulling out the gas.

**Comment by jznomoney** [comment]
I mean pulling out steam not gas.

**Comment by SteelShot** [comment]
![2016-07-03_01 23 52](https://cloud.githubusercontent.com/assets/5291010/16543091/d742674e-40bc-11e6-9ef6-70d684faddcc.png)

Works perfectly fine on my side, btw there is the edit reply feature

**Comment by aidancbrady** [comment]
Shouldn't be occurring, you may have downloaded a slightly broken build when I was still adding the feature. v9.0.3 is out with the changes :)
