### ISSUE TITLE
Crash when mining enriching chamber

### ISSUE THREAD

**Issue by EurypteriD192** [aidancbrady/Mekanism#3436]
Bug constantly happening when attempting to remove any Mekanism mashines
mashine is public but i tried changing that to private or other every single time it crashes if attempting to mine it.

---- Minecraft Crash Report ----
// My bad.

```
Time: 7/3/16 6:53 PM
Description: Unexpected error

java.lang.ClassCastException: net.minecraft.client.entity.EntityClientPlayerMP cannot be cast to net.minecraft.entity.player.EntityPlayerMP
	at mekanism.common.util.SecurityUtils.canAccess(SecurityUtils.java:55)
	at mekanism.common.block.BlockMachine.func_149737_a(BlockMachine.java:770)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78743_b(PlayerControllerMP.java:177)
	at net.minecraft.client.Minecraft.func_147116_af(Minecraft.java:1409)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1948)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at mekanism.common.util.SecurityUtils.canAccess(SecurityUtils.java:55)
	at mekanism.common.block.BlockMachine.func_149737_a(BlockMachine.java:770)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78743_b(PlayerControllerMP.java:177)
	at net.minecraft.client.Minecraft.func_147116_af(Minecraft.java:1409)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['EurypteriD'/303, l='MpServer', x=-500.57, y=68.62, z=1635.80]]
	Chunk stats: MultiplayerChunkCache: 724, 733
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-244,64,240), Chunk: (at 12,4,0 in -16,15; contains blocks -256,0,240 to -241,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 157105 game time, 195152 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 42 total; [EntitySquid['Squid'/384, l='MpServer', x=-522.50, y=47.00, z=1611.50], EntitySheep['Sheep'/448, l='MpServer', x=-433.41, y=68.00, z=1564.94], EntitySheep['Sheep'/449, l='MpServer', x=-433.50, y=68.00, z=1568.50], EntitySheep['Sheep'/450, l='MpServer', x=-442.50, y=70.00, z=1618.50], EntitySheep['Sheep'/451, l='MpServer', x=-440.50, y=70.00, z=1619.50], EntitySheep['Sheep'/452, l='MpServer', x=-442.50, y=70.00, z=1620.50], EntitySheep['Sheep'/453, l='MpServer', x=-444.50, y=70.00, z=1622.50], EntityPig['Pig'/455, l='MpServer', x=-425.50, y=67.00, z=1561.22], EntityPig['Pig'/456, l='MpServer', x=-428.50, y=67.00, z=1560.50], EntityPig['Pig'/457, l='MpServer', x=-425.50, y=67.00, z=1562.81], EntityPig['Pig'/458, l='MpServer', x=-429.50, y=68.00, z=1565.50], EntitySquid['Squid'/395, l='MpServer', x=-515.88, y=62.28, z=1589.50], EntitySheep['Sheep'/459, l='MpServer', x=-429.50, y=68.00, z=1570.50], EntityBat['Bat'/396, l='MpServer', x=-503.47, y=23.76, z=1669.68], EntitySheep['Sheep'/402, l='MpServer', x=-481.91, y=68.00, z=1623.94], EntitySheep['Sheep'/403, l='MpServer', x=-487.84, y=68.00, z=1632.19], EntityBat['Bat'/404, l='MpServer', x=-478.94, y=39.00, z=1669.31], EntityBat['Bat'/405, l='MpServer', x=-487.69, y=37.00, z=1692.78], EntityPig['Pig'/406, l='MpServer', x=-483.88, y=63.00, z=1704.94], EntityMinecartChest['entity.MinecartChest.name'/415, l='MpServer', x=-479.50, y=25.50, z=1565.50], EntityBat['Bat'/416, l='MpServer', x=-465.53, y=35.00, z=1587.01], EntityBat['Bat'/417, l='MpServer', x=-469.31, y=23.12, z=1633.15], EntityPig['Pig'/418, l='MpServer', x=-469.51, y=69.00, z=1617.25], EntityBat['Bat'/419, l='MpServer', x=-475.22, y=35.56, z=1686.52], EntityBat['Bat'/367, l='MpServer', x=-561.31, y=31.00, z=1704.22], EntityClientPlayerMP['EurypteriD'/303, l='MpServer', x=-500.57, y=68.62, z=1635.80], EntityBat['Bat'/435, l='MpServer', x=-458.88, y=31.00, z=1585.69], EntitySheep['Sheep'/436, l='MpServer', x=-461.84, y=70.00, z=1615.09], EntityBat['Bat'/437, l='MpServer', x=-457.25, y=36.10, z=1619.25], EntitySquid['Squid'/373, l='MpServer', x=-551.78, y=55.03, z=1650.13], EntityPig['Pig'/438, l='MpServer', x=-451.81, y=65.00, z=1677.13], EntitySheep['Sheep'/374, l='MpServer', x=-551.09, y=69.00, z=1673.09], EntitySheep['Sheep'/439, l='MpServer', x=-453.56, y=66.00, z=1677.34], EntitySheep['Sheep'/375, l='MpServer', x=-549.47, y=63.00, z=1680.53], EntityBat['Bat'/440, l='MpServer', x=-460.84, y=22.75, z=1684.97], EntitySheep['Sheep'/441, l='MpServer', x=-456.50, y=63.00, z=1686.91], EntityPig['Pig'/442, l='MpServer', x=-456.16, y=63.00, z=1685.63], EntitySquid['Squid'/379, l='MpServer', x=-535.50, y=47.09, z=1604.25], EntitySheep['Sheep'/443, l='MpServer', x=-463.22, y=64.00, z=1687.72], EntityBat['Bat'/380, l='MpServer', x=-536.72, y=50.00, z=1681.63], EntitySquid['Squid'/383, l='MpServer', x=-512.41, y=58.09, z=1588.34], EntitySheep['Sheep'/447, l='MpServer', x=-434.59, y=68.00, z=1566.06]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:425)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 816630416 bytes (778 MB) / 1528934400 bytes (1458 MB) up to 4281597952 bytes (4083 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 Optifine OptiFine_1.7.10_HD_U_D6 52 mods loaded, 37 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJAAAA	OpenComputers|Core{1.5.22.46} [OpenComputers (Core)] (minecraft.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	<DragonAPI ASM>{0} [DragonAPI ASM Data Initialization] (minecraft.jar) 
	UCHIJAAAA	BiblioCraft{1.11.5} [BiblioCraft] (BiblioCraft[v1.11.5][MC1.7.10].jar) 
	UCHIJAAAA	ChickenChunks{1.3.4.19} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.19-universal.jar) 
	UCHIJAAAA	CoFHCore{1.7.10R3.1.2} [CoFH Core] (CoFHCore-[1.7.10]3.1.2-325.jar) 
	UCHIJAAAA	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	MrTJPCoreMod{1.1.0.33} [MrTJPCore] (MrTJPCore-1.7.10-1.1.0.33-universal.jar) 
	UCHIJAAAA	ProjRed|Core{4.7.0pre12.95} [ProjectRed Core] (ProjectRed-1.7.10-4.7.0pre12.95-Base.jar) 
	UCHIJAAAA	DragonAPI{1.0} [DragonAPI] (DragonAPI 1.7.10 V15a.jar) 
	UCHIJAAAA	EnderStorage{1.4.7.38} [EnderStorage] (EnderStorage-1.7.10-1.4.7.38-universal.jar) 
	UCHIJAAAA	inventorytweaks{1.58-147-645ca10} [Inventory Tweaks] (InventoryTweaks-1.58-147.jar) 
	UCHIJAAAA	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
	UCHIJAAAA	journeymap{@JMVERSION@} [JourneyMap] (journeymap-1.7.10-5.1.0-fairplay.jar) 
	UCHIJAAAA	malisiscore{1.7.10-0.14.3} [MalisisCore] (malisiscore-1.7.10-0.14.3.jar) 
	UCHIJAAAA	malisisdoors{1.7.10-1.13.2} [Malisis' Doors] (malisisdoors-1.7.10-1.13.2.jar) 
	UCHIJAAAA	Mekanism{9.0.3} [Mekanism] (Mekanism-1.7.10-9.0.3.276.jar) 
	UCHIJAAAA	MekanismGenerators{9.0.3} [MekanismGenerators] (MekanismGenerators-1.7.10-9.0.3.276.jar) 
	UCHIJAAAA	MekanismTools{9.0.3} [MekanismTools] (MekanismTools-1.7.10-9.0.3.276.jar) 
	UCHIJAAAA	MineFactoryReloaded{1.7.10R2.8.1} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.1} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.1} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UCHIJAAAA	ProjRed|Transmission{4.7.0pre12.95} [ProjectRed Transmission] (ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar) 
	UCHIJAAAA	OpenComputers{1.5.22.46} [OpenComputers] (OpenComputers-MC1.7.10-1.5.22.46-universal.jar) 
	UCHIJAAAA	ProjectBlue{1.1.6} [Project Blue] (ProjectBlue-1.1.6-mc1.7.10.jar) 
	UCHIJAAAA	ProjRed|Integration{4.7.0pre12.95} [ProjectRed Integration] (ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar) 
	UCHIJAAAA	ProjRed|Fabrication{4.7.0pre12.95} [ProjectRed Fabrication] (ProjectRed-1.7.10-4.7.0pre12.95-Fabrication.jar) 
	UCHIJAAAA	ProjRed|Illumination{4.7.0pre12.95} [ProjectRed Illumination] (ProjectRed-1.7.10-4.7.0pre12.95-Lighting.jar) 
	UCHIJAAAA	RotaryCraft{1.0} [RotaryCraft] (RotaryCraft 1.7.10 V15a.jar) 
	UCHIJAAAA	ReactorCraft{1.0} [ReactorCraft] (ReactorCraft 1.7.10 V15a.jar) 
	UCHIJAAAA	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UD	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.1} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatAtum{1.7.10R2.8.1} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.1} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.1} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.1} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.1} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatForestry{1.7.10R2.8.1} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatIC2{1.7.10R2.8.1} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.1} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.1} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.1} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.1} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.1} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.1} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.1} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 368.39' Renderer: 'GeForce GTX 970/PCIe/SSE2'
	CoFHCore: -[1.7.10]3.1.2-325
	MineFactoryReloaded: -[1.7.10]2.8.1-174
	Launched Version: 1.7.10-Forge10.13.4.1558-1.7.10
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 970/PCIe/SSE2 GL version 4.5.0 NVIDIA 368.39, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
	OptiFine Version: OptiFine_1.7.10_HD_U_D6
	Render Distance Chunks: 13
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	OpenGlVersion: 4.5.0 NVIDIA 368.39
	OpenGlRenderer: GeForce GTX 970/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8
```

**Comment by aidancbrady** [comment]
Update to #277 :)
