### ISSUE TITLE
Unexpected error: I can't touch containers anymore

### ISSUE THREAD

**Issue by EzerArch** [aidancbrady/Mekanism#3437]
Since I updated Mekanism to 276, my Minecraft client crashes every time I touch (left-click) a tank, any tank, gas or liquid, old or new. Right-click still works.

![2016-07-03_17 26 29](https://cloud.githubusercontent.com/assets/6743303/16547416/5371cc98-4143-11e6-8efc-95ffbcff51c9.png)

![2016-07-03_17 14 13](https://cloud.githubusercontent.com/assets/6743303/16547417/58d29398-4143-11e6-8181-5091504429de.png)

```
Description: Unexpected error

java.lang.ClassCastException: net.minecraft.client.entity.EntityClientPlayerMP cannot be cast to net.minecraft.entity.player.EntityPlayerMP
	at mekanism.common.util.SecurityUtils.canAccess(SecurityUtils.java:55)
	at mekanism.common.block.BlockMachine.func_149737_a(BlockMachine.java:770)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78743_b(PlayerControllerMP.java:177)
```
Full log: https://gist.github.com/EzerArch/b689f403bbcb2601e5b369acb6338ff3

**Comment by EzerArch** [comment]
YAY, it's fixed! https://github.com/aidancbrady/Mekanism/commit/fdc21d8de5459111b98ab9ed53ba6c5b5cf153d0
