### ISSUE TITLE
reactor port causes server crash

### ISSUE THREAD

**Issue by cobra** [aidancbrady/Mekanism#3463]
Crashes each time the world is loaded.
The offending port was connecting to an ultimate mechanical pipe leading to a turbine. Two other ports with pipes to the same turbine didn't cause problems, as did other unconnected ports.
````
java.lang.NullPointerException: Ticking block entity
	at mekanism.generators.common.tile.reactor.TileEntityReactorPort.onUpdate(TileEntityReactorPort.java:95)
	at mekanism.common.tile.TileEntityBasicBlock.func_145845_h(TileEntityBasicBlock.java:77)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
````

**Comment by iKaneki-Ken** [comment]
This has been reported and fixed already.

**Comment by cobra** [comment]
Where? I couldn't find something related to this one.
BTW, version is 1.7.10-9.0.3.278.

**Comment by iKaneki-Ken** [comment]
https://github.com/aidancbrady/Mekanism/issues/3470

**Comment by cobra** [comment]
Isn't that a completely different crash? This one is in the reactor port, yours was in the turbine valve tile entity class.

**Comment by aidancbrady** [comment]
Should be fixed in development.
