### ISSUE TITLE
[1.9.4] Crash when right-clicking on Advanced Pressure Tube with Configureator 

### ISSUE THREAD

**Issue by drewbit** [aidancbrady/Mekanism#3474]
Compiled on 11/07/2016

Title pretty much says it all. Tube was connected to a gas-burning generator.

http://paste.ee/p/zbTtB

**Comment by drewbit** [comment]
Here's a screenshot of the setup if needed: 
http://imgur.com/C2wcCye

**Comment by Chris54721** [comment]
This happens with every wrench, looks like it's trying to use the CoFH API:

```
java.lang.NoSuchMethodError: cofh.api.item.IToolHammer.isUsable(Lnet/minecraft/item/ItemStack;Lnet/minecraft/entity/EntityLivingBase;Lnet/minecraft/util/math/BlockPos;)Z
	at mekanism.common.util.MekanismUtils.hasUsableWrench(MekanismUtils.java:1509) ~[MekanismUtils.class:?]
	at mekanism.common.multipart.PartSidedPipe.onActivated(PartSidedPipe.java:596) ~[PartSidedPipe.class:?]
	at mcmultipart.multipart.MultipartContainer.onActivated(MultipartContainer.java:369) ~[MultipartContainer.class:?]
	at mcmultipart.block.BlockMultipartContainer.func_180639_a(BlockMultipartContainer.java:184) ~[BlockMultipartContainer.class:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:409) ~[bkr.class:?]
```

**Comment by aidancbrady** [comment]
Not on my end. Mekanism ships with the latest CoFH API, and it seems like another mod in your installation is shipping with an outdated copy, which is interfering.  I bet you'll notice that everything works fine with only Mekanism and MCForge installed.

**Comment by FiveEYZ** [comment]
so about this item...

the mod that is interfering is McJtyLib 

McJtyLib is a  required mod for RFTools  and Deep Resonance
it ships with 1.8.9R1.2.0B1 and removing the "cofh"part from it fixes the crash.

Is there a way to make mekanism have priority on loading the cofh api it needs?

**Comment by drewbit** [comment]
Just open an issue on McJty's github and link it to this one, see if he can do anything.
