### ISSUE TITLE
mekanism/common/tile/TileEntitySolarEvaporationController

### ISSUE THREAD

**Issue by chezpaul** [aidancbrady/Mekanism#3482]
I get this FATAL error:
Running 1.7.10-9.0.3.277
9.0.2 was fine before.

[10:06:39 FATAL]: Plugin Mekanism threw an error on init. Skipping...
[10:06:39 WARN]: java.lang.NoClassDefFoundError: mekanism/common/tile/TileEntitySolarEvaporationController
[10:06:39 WARN]: 	at tterrag.wailaplugins.plugins.PluginMekanism.load(PluginMekanism.java:36)
[10:06:39 WARN]: 	at tterrag.wailaplugins.plugins.PluginRegistrar.preInit(PluginRegistrar.java:146)
[10:06:39 WARN]: 	at tterrag.wailaplugins.WailaPlugins.preInit(WailaPlugins.java:41)
[10:06:39 WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:06:39 WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[10:06:39 WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10:06:39 WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[10:06:39 WARN]: 	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
[10:06:39 WARN]: 	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
[10:06:39 WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10:06:39 WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[10:06:39 WARN]: 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[10:06:39 WARN]: 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[10:06:39 WARN]: 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[10:06:39 WARN]: 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[10:06:39 WARN]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[10:06:39 WARN]: 	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
[10:06:39 WARN]: 	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
[10:06:39 WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:06:39 WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[10:06:39 WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10:06:39 WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[10:06:39 WARN]: 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[10:06:39 WARN]: 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[10:06:39 WARN]: 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[10:06:39 WARN]: 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[10:06:39 WARN]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[10:06:39 WARN]: 	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
[10:06:39 WARN]: 	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
[10:06:39 WARN]: 	at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:88)
[10:06:39 WARN]: 	at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:320)
[10:06:39 WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:176)
[10:06:39 WARN]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631)
[10:06:39 WARN]: 	at java.lang.Thread.run(Thread.java:745)
[10:06:39 WARN]: Caused by: java.lang.ClassNotFoundException: mekanism.common.tile.TileEntitySolarEvaporationController
[10:06:39 WARN]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[10:06:39 WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[10:06:39 WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[10:06:39 WARN]: 	... 34 more
[10:06:39 WARN]: Caused by: java.lang.NullPointerException

**Comment by aidancbrady** [comment]
WailaPlugins has outdated support for Mekanism.  Tell them to update :)
