### ISSUE TITLE
[1.7.10+] Portable Teleporter Crash

### ISSUE THREAD

**Issue by aidancbrady** [aidancbrady/Mekanism#3488]
java.lang.NullPointerException
	at mekanism.common.network.PacketPortableTeleporter.onMessage(PacketPortableTeleporter.java:104) ~[PacketPortableTeleporter.class:?]
	at mekanism.common.network.PacketPortableTeleporter.onMessage(PacketPortableTeleporter.java:30) ~[PacketPortableTeleporter.class:?]
	at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:37) ~[SimpleChannelHandlerWrapper.class:?]
	at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:17) ~[SimpleChannelHandlerWrapper.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:101) [SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]

**Comment by aidancbrady** [comment]
Line 104 in PacketPortableTeleporter, add null check for getClosestCoords()
