### ISSUE TITLE
Crash when saving filter with replace block

### ISSUE THREAD

**Issue by pupaxxo** [aidancbrady/Mekanism#3495]
```
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_91]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_91]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NullPointerException
        at net.minecraft.item.ItemStack.func_77952_i(ItemStack.java:240) ~[adz.class:?]
        at mekanism.common.content.miner.MinerFilter.write(MinerFilter.java:50) ~[MinerFilter.class:?]
        at mekanism.common.content.miner.MMaterialFilter.write(MMaterialFilter.java:60) ~[MMaterialFilter.class:?]
        at mekanism.common.tile.TileEntityDigitalMiner.getNetworkedData(TileEntityDigitalMiner.java:936) ~[TileEntityDigitalMiner.class:?]
        at mekanism.common.tile.TileEntityDigitalMiner.func_174889_b(TileEntityDigitalMiner.java:646) ~[TileEntityDigitalMiner.class:?]
        at mekanism.common.inventory.container.ContainerNull.<init>(ContainerNull.java:18) ~[ContainerNull.class:?]
        at mekanism.common.network.PacketDigitalMinerGui$DigitalMinerGuiMessage.openServerGui(PacketDigitalMinerGui.java:127) ~[PacketDigitalMinerGui$DigitalMinerGuiMessage.class:?]
        at mekanism.common.network.PacketDigitalMinerGui$1.run(PacketDigitalMinerGui.java:54) ~[PacketDigitalMinerGui$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_91]
        at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
        ... 5 more
```

**Comment by aidancbrady** [comment]
Fixed, thanks!
