### ISSUE TITLE
[1.10.2] Crash when breaking a universal cable 

### ISSUE THREAD

**Issue by Eufranio** [aidancbrady/Mekanism#3529]
When i break Universal Cables with a pickaxe, i get that crash:

```
java.lang.IllegalArgumentException: Cannot get property PropertyBool{name=ticking, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in ExtendedBlockState{block=mcmultipart:multipart, properties=[ticking]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:196)
	at mcmultipart.block.BlockMultipartContainer.func_176201_c(BlockMultipartContainer.java:408)
	at net.minecraft.block.Block.getHarvestTool(Block.java:1927)
	at net.minecraft.block.Block.isToolEffective(Block.java:1950)
	at net.minecraft.item.ItemTool.func_150893_a(ItemTool.java:59)
	at mekanism.tools.item.ItemMekanismPickaxe.func_150893_a(ItemMekanismPickaxe.java:78)
	at net.minecraft.item.ItemStack.func_150997_a(ItemStack.java:157)
	at net.minecraft.entity.player.InventoryPlayer.func_184438_a(InventoryPlayer.java:522)
	at net.minecraft.entity.player.EntityPlayer.getDigSpeed(EntityPlayer.java:808)
	at mcmultipart.multipart.Multipart.getStrength(Multipart.java:205)
	at mcmultipart.multipart.MultipartContainer.getHardness(MultipartContainer.java:350)
	at mcmultipart.block.BlockMultipartContainer.func_180647_a(BlockMultipartContainer.java:175)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185903_a(BlockStateContainer.java:395)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_180511_b(PlayerControllerMP.java:240)
	at PlayerControllerOF.func_180511_b(PlayerControllerOF.java:43)
	at net.minecraft.client.Minecraft.func_147116_af(Minecraft.java:1459)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2179)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1961)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1749)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

Full crash-report: http://hastebin.com/anobaxohoc.coffee

**Comment by aidancbrady** [comment]
McMultipart issue.
