### ISSUE TITLE
[1.10.2] Crash when trying break a cable with RFTools wrench

### ISSUE THREAD

**Issue by Eufranio** [aidancbrady/Mekanism#3530]
When i try to use the RFTools wrench in Universal Cables, i get that crash:

```
Description: Unexpected error

java.lang.AbstractMethodError: mcjty.rftools.items.smartwrench.SmartWrenchItem.isUsable(Lnet/minecraft/item/ItemStack;Lnet/minecraft/entity/EntityLivingBase;Lnet/minecraft/util/math/BlockPos;)Z
	at mekanism.common.util.MekanismUtils.hasUsableWrench(MekanismUtils.java:1509)
	at mekanism.common.multipart.PartSidedPipe.onActivated(PartSidedPipe.java:596)
	at mcmultipart.multipart.MultipartContainer.onActivated(MultipartContainer.java:369)
	at mcmultipart.block.BlockMultipartContainer.func_180639_a(BlockMultipartContainer.java:184)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:410)
	at PlayerControllerOF.func_187099_a(PlayerControllerOF.java:88)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1518)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2184)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1961)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1749)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

Full crash-report: http://hastebin.com/yawoqatipi.coffee

**Comment by aidancbrady** [comment]
Fixed in dev, I added a few extra checks.
