### ISSUE TITLE
CME caused by ticking Assemblicator

### ISSUE THREAD

**Issue by cobra** [aidancbrady/Mekanism#3536]
(Re)loading a previously loaded and working world after adding and configuring some automated Formulaic Assemblicators (one for 4 stone→stone bricks, one for 4 sand→sandstone) crashes the server each time.

I successfully hacked a hotfix to save this world by constructing a `CopyOnWriteArrayList` from the `getRecipeList()` result before looping over it at `mekanism.common.util.MekanismUtils.findMatchingRecipe(MekanismUtils.java:1470)`.

Stacktrace:
````
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at mekanism.common.util.MekanismUtils.findMatchingRecipe(MekanismUtils.java:1470)
	at mekanism.common.tile.TileEntityFormulaicAssemblicator.doSingleCraft(TileEntityFormulaicAssemblicator.java:239)
	at mekanism.common.tile.TileEntityFormulaicAssemblicator.onUpdate(TileEntityFormulaicAssemblicator.java:150)
	at mekanism.common.tile.TileEntityBasicBlock.func_145845_h(TileEntityBasicBlock.java:75)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
````

Version: Mekanism-1.7.10-9.1.0.281

**Comment by aidancbrady** [comment]
Fixed in dev, thanks!
