### ISSUE TITLE
NullPointerException in BlockMachine.isSideSolid()

### ISSUE THREAD

**Issue by tipeon** [aidancbrady/Mekanism#3538]
In Mekanism 9.1.0.281 (minecraft 1.7.10), I see this error quite often:
```
[17:51:38] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.reflect.InvocationTargetException
[17:51:38] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.GeneratedMethodAccessor36.invoke(Unknown Source)
[17:51:38] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:51:38] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[17:51:38] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at Reflector.callBoolean(Reflector.java:391)
[17:51:38] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.world.SpawnerAnimals.func_77190_a(SpawnerAnimals.java:318)
[17:51:38] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.world.SpawnerAnimals.func_77192_a(SpawnerAnimals.java:178)
[17:51:38] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:161)
[17:51:38] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at WorldServerOF.func_72835_b(WorldServerOF.java:234)
[17:51:38] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625)
[17:51:38] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[17:51:38] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
[17:51:38] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
[17:51:38] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[17:51:38] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.lang.NullPointerException
[17:51:38] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at mekanism.common.block.BlockMachine.isSideSolid(BlockMachine.java:1154)
[17:51:38] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.block.Block.canCreatureSpawn(Block.java:1533)
[17:51:38] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	... 13 more
```

Other than flooding the logs, it does not seem to have a bad effect.

Possibly related to this (or may be just a coincidence): I saw a skeleton spawn inside the industrial turbine once.

**Comment by aidancbrady** [comment]
Not sure how this would be occurring. Regardless, shouldn't be an issue in the 1.10.2 builds.
