### ISSUE TITLE
Digital Miner filter crashes the game 1.10

### ISSUE THREAD

**Issue by 0blu** [aidancbrady/Mekanism#3559]
If you create a new filter with no ore but a name and after this you put a ore in it the game will crash

See https://gifyu.com/image/Yre

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  IC2core (industrialcraft-2-2.6.16-ex110.jar)
  LoadingPlugin (RandomThings-MC1.10-3.7.4.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.41-beta.jar)
  LoadingHook (Mekanism-1.10.2-9.1.0.286.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
Contact their authors BEFORE contacting forge

// Who set us up the TNT?

Time: 28.07.16 17:59
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at net.minecraft.item.ItemStack.func_77952_i(ItemStack.java:240)
	at mekanism.common.content.miner.MinerFilter.write(MinerFilter.java:50)
	at mekanism.common.content.miner.MOreDictFilter.write(MOreDictFilter.java:52)
	at mekanism.common.tile.TileEntityDigitalMiner.getNetworkedData(TileEntityDigitalMiner.java:936)
	at mekanism.common.tile.TileEntityBasicBlock.func_73660_a(TileEntityBasicBlock.java:86)
	at net.minecraft.world.World.func_72939_s(World.java:1802)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:618)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.item.ItemStack.func_77952_i(ItemStack.java:240)
	at mekanism.common.content.miner.MinerFilter.write(MinerFilter.java:50)
	at mekanism.common.content.miner.MOreDictFilter.write(MOreDictFilter.java:52)
	at mekanism.common.tile.TileEntityDigitalMiner.getNetworkedData(TileEntityDigitalMiner.java:936)
	at mekanism.common.tile.TileEntityBasicBlock.func_73660_a(TileEntityBasicBlock.java:86)

-- Block entity being ticked --
Details:
	Name: DigitalMiner // mekanism.common.tile.TileEntityDigitalMiner
	Block type: ID #908 (tile.MachineBlock // null)
	Block data value: 4 / 0x4 / 0b0100
	Block location: World: (-787,4,1163), Chunk: (at 13,0,11 in -50,72; contains blocks -800,0,1152 to -785,255,1167), Region: (-2,2; contains chunks -64,64 to -33,95, blocks -1024,0,1024 to -513,255,1535)
	Actual block type: ID #908 (tile.MachineBlock // null)
	Actual block data value: 4 / 0x4 / 0b0100
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1802)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:618)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [EntityPlayerMP['lassdas'/2346, l='New World', x=-786,47, y=4,29, z=1166,28]]
	Chunk stats: ServerChunkCache: 441 Drop: 0
	Level seed: -8287329572425568365
	Level generator: ID 01 - flat, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-754,4,1185), Chunk: (at 14,0,1 in -48,74; contains blocks -768,0,1184 to -753,255,1199), Region: (-2,2; contains chunks -64,64 to -33,95, blocks -1024,0,1024 to -513,255,1535)
	Level time: 11038 game time, 11038 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 52022 (now: false), thunder time: 107422 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 836551344 bytes (797 MB) / 2944401408 bytes (2808 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.32 Powered by Forge 12.18.1.2014 Optifine OptiFine_1.10.2_HD_U_C2 62 mods loaded, 62 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.1.2014.jar) 
	UCHIJAAAA	Forge{12.18.1.2014} [Minecraft Forge] (forge-1.10.2-12.18.1.2014.jar) 
	UCHIJAAAA	actuallyadditions{1.10.2-r56} [Actually Additions] (ActuallyAdditions-1.10.2-r56.jar) 
	UCHIJAAAA	Baubles{1.2.1.0} [Baubles] (Baubles-1.9.4-1.2.1.0.jar) 
	UCHIJAAAA	bdlib{1.12.0.2} [BD Lib] (bdlib-1.12.0.2-mc1.10.2.jar) 
	UCHIJAAAA	BetterAchievements{0.3.0.30} [Better Achievements] (BetterAchievements-1.10.2-0.3.0.30.jar) 
	UCHIJAAAA	betterbuilderswands{0.6.5} [Better Builder's Wands] (BetterBuildersWands-0.6.5-1.10r138+8595fc7.jar) 
	UCHIJAAAA	Chameleon{1.9.4-2.1.6} [Chameleon] (Chameleon-1.9.4-2.1.6.jar) 
	UCHIJAAAA	chisel{MC1.9.4-0.0.6.33} [Chisel] (Chisel-MC1.9.4-0.0.6.33.jar) 
	UCHIJAAAA	IC2{2.6.16-ex110} [IndustrialCraft 2] (industrialcraft-2-2.6.16-ex110.jar) 
	UCHIJAAAA	CompactSolars{5.0.4.328} [Compact Solar Arrays] (CompactSolars-1.10.2-5.0.4.328-universal.jar) 
	UCHIJAAAA	ElecCore{1.5.292} [ElecCore] (ElecCore-1.9.4-1.5.292.jar) 
	UCHIJAAAA	deepresonance{1.2.0beta35} [DeepResonance] (deepresonance-1.9.4-1.2.0beta35.jar) 
	UCHIJAAAA	endercore{1.10.2-0.4.1.41-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.41-beta.jar) 
	UCHIJAAAA	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UCHIJAAAA	EnderIO{1.10.2-3.0.1.75_beta} [Ender IO] (EnderIO-1.10.2-3.0.1.75_beta.jar) 
	UCHIJAAAA	enderutilities{0.6.5} [Ender Utilities] (enderutilities-1.10.2-0.6.5.jar) 
	UCHIJAAAA	EnderZoo{1.10-1.2.3.43} [Ender Zoo] (EnderZoo-1.10-1.2.3.43.jar) 
	UCHIJAAAA	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.10.2-alpha-1.0.1.jar) 
	UCHIJAAAA	fastleafdecay{v11} [Fast Leaf Decay] (FastLeafDecay-v11.jar) 
	UCHIJAAAA	JEI{3.7.8.234} [Just Enough Items] (jei_1.10.2-3.7.8.234.jar) 
	UCHIJAAAA	FloodLights{1.2.7-145} [Flood Lights] (FloodLights-1.9.4-1.2.7-145.jar) 
	UCHIJAAAA	forestry{5.2.3.213} [Forestry] (forestry_1.10.2-5.2.3.213.jar) 
	UCHIJAAAA	ftbl{2.1.0} [FTBLib] (FTBLib-1.9.4-2.1.0-pre2.jar) 
	UCHIJAAAA	ftbu{2.1.0} [FTBUtilities] (FTBUtilities-1.9.4-2.1.0-pre2.jar) 
	UCHIJAAAA	advgenerators{0.9.20.4} [Advanced Generators] (generators-0.9.20.4-mc1.10.2.jar) 
	UCHIJAAAA	gravestone{1.5.4} [Gravestone] (GraveStone Mod 1.5.4.jar) 
	UCHIJAAAA	hopperducts{1.4.7} [Hopper Ducts] (hopperducts-mc1.9.4-1.4.7.jar) 
	UCHIJAAAA	InventoryPets{1.4.8} [Inventory Pets] (inventorypets-1.10-1.4.8.jar) 
	UCHIJAAAA	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
	UCHIJAAAA	IronChest{7.0.7.795} [Iron Chest] (ironchest-1.10.2-7.0.7.795.jar) 
	UCHIJAAAA	JEFB{1.0.3} [Just Enough Forestry Bees] (jefb_1.10.2-1.0.3.jar) 
	UCHIJAAAA	journeymap{1.10.2-5.2.4} [JourneyMap] (journeymap-1.10.2-5.2.4-unlimited.jar) 
	UCHIJAAAA	jeresources{0.4.6.42} [Just Enough Resources] (JustEnoughResources-1.10.2-0.4.6.42.jar) 
	UCHIJAAAA	mantle{1.10-0.10.3.jenkins156} [Mantle] (Mantle-1.10-0.10.3.jar) 
	UCHIJAAAA	mcmultipart{1.2.0_72} [MCMultiPart] (MCMultiPart-experimental-1.2.0_72-universal.jar) 
	UCHIJAAAA	Mekanism{9.1.0} [Mekanism] (Mekanism-1.10.2-9.1.0.286.jar) 
	UCHIJAAAA	MekanismGenerators{9.1.0} [MekanismGenerators] (MekanismGenerators-1.10.2-9.1.0.286.jar) 
	UCHIJAAAA	MekanismTools{9.1.0} [MekanismTools] (MekanismTools-1.10.2-9.1.0.286.jar) 
	UCHIJAAAA	testdummy{1.11} [MmmMmmMmmMmm] (MmmMmmMmmMmm-1.11.jar) 
	UCHIJAAAA	Neat{1.3-11} [Neat] (Neat 1.3-11.jar) 
	UCHIJAAAA	OpenComputers{1.6.0.2-beta.4} [OpenComputers] (OpenComputers-MC1.10-1.6.0.2-beta.4.jar) 
	UCHIJAAAA	openprinter{0.1.0.2} [OpenPrinter] (OpenPrinter-1.9.4-0.1.0.2.jar) 
	UCHIJAAAA	openradio{0.8.1} [OpenRadio] (OpenRadio-0.8.1-MC1.9.4.jar) 
	UCHIJAAAA	fodc{1.9.1} [Ore Dictionary Converter] (OreDictionaryConverter-1.9.1.jar) 
	UCHIJAAAA	harvestcraft{1.9.4-pre} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4-1.10.2a.jar) 
	UCHIJAAAA	randomthings{3.7.4} [Random Things] (RandomThings-MC1.10-3.7.4.jar) 
	UCHIJAAAA	StorageDrawers{1.9.4-3.2.1} [Storage Drawers] (StorageDrawers-1.9.4-3.2.1.jar) 
	UCHIJAAAA	refinedstorage{0.8.12} [Refined Storage] (refinedstorage-0.8.12.jar) 
	UCHIJAAAA	rftools{5.08} [RFTools] (rftools-1.10-5.08.jar) 
	UCHIJAAAA	rftoolsdim{4.30beta46} [RFTools Dimensions] (rftoolsdim-1.10-4.30beta46.jar) 
	UCHIJAAAA	Roguelike{1.5.4} [Roguelike Dungeons] (RoguelikeDungeons-1.10.2-1.5.4.jar) 
	UCHIJAAAA	routerreborn{1.10.2-4.0.1.14b_universal} [Router Reborn] (RouterReborn-1.10.2-4.0.1.14b_universal.jar) 
	UCHIJAAAA	tconstruct{1.10-2.3.3a.jenkins271} [Tinkers' Construct] (TConstruct-1.10-2.3.3a.jar) 
	UCHIJAAAA	tinker_io{beta 2.3.2b} [Tinker I/O] (tinker_io-1.10.2-beta 2.3.2b.jar) 
	UCHIJAAAA	TinkersAddons{1.0.3} [Tinkers' Addons] (Tinkers' Addons-1.10.x-1.0.3.jar) 
	UCHIJAAAA	WailaHarvestability{1.1.7} [Waila Harvestability] (WailaHarvestability-mc1.10-1.1.7.jar) 
	UCHIJAAAA	waterstrainer{1.1.0} [Water Strainer] (WaterStrainer-1.9.4-1.1.0.jar) 
	UCHIJAAAA	ICSE{1.1.0.0} [I Can See Everything] (Wawla-1.10.2-2.3.0.197.jar) 
	UCHIJAAAA	wawla{2.3.0.194} [What Are We Looking At] (Wawla-1.10.2-2.3.0.197.jar) 
	UCHIJAAAA	xprings{1.2.0} [Experience Rings] (xprings-1.2.0.jar) 
	Loaded coremods (and transformers): 
IC2core (industrialcraft-2-2.6.16-ex110.jar)
  
LoadingPlugin (RandomThings-MC1.10-3.7.4.jar)
  lumien.randomthings.asm.ClassTransformer
EnderCorePlugin (EnderCore-1.10.2-0.4.1.41-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
LoadingHook (Mekanism-1.10.2-9.1.0.286.jar)
  
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- WailaIntegration (Enabled/Not Forced)

	List of loaded APIs: 
		* actuallyadditionsapi (18) from ActuallyAdditions-1.10.2-r56.jar
		* Baubles|API (1.1.1.0) from xprings-1.2.0.jar
		* BetterAchievements|API (0.3.0.30) from BetterAchievements-1.10.2-0.3.0.30.jar
		* ChiselAPI (0.0.1) from Chisel-MC1.9.4-0.0.6.33.jar
		* ChiselAPI|Carving (0.0.1) from Chisel-MC1.9.4-0.0.6.33.jar
		* CoFHAPI (1.8.9R1.2.0B1) from FloodLights-1.9.4-1.2.7-145.jar
		* CoFHAPI|energy (1.8.9R1.2.0B1) from FloodLights-1.9.4-1.2.7-145.jar
		* CoFHAPI|item (1.8.9R1.2.0B1) from Mekanism-1.10.2-9.1.0.286.jar
		* DR-API (1.0.4-Beta) from deepresonance-1.9.4-1.2.0beta35.jar
		* ElecCore|Abilities (#API_VER#) from ElecCore-1.9.4-1.5.292.jar
		* EnderIOAPI (0.0.2) from EnderIO-1.10.2-3.0.1.75_beta.jar
		* EnderIOAPI|Redstone (0.0.2) from EnderIO-1.10.2-3.0.1.75_beta.jar
		* EnderIOAPI|Teleport (0.0.2) from EnderIO-1.10.2-3.0.1.75_beta.jar
		* EnderIOAPI|Tools (0.0.2) from EnderIO-1.10.2-3.0.1.75_beta.jar
		* ForestryAPI|apiculture (4.8.0) from forestry_1.10.2-5.2.3.213.jar
		* ForestryAPI|arboriculture (4.2.1) from forestry_1.10.2-5.2.3.213.jar
		* ForestryAPI|circuits (3.1.0) from forestry_1.10.2-5.2.3.213.jar
		* ForestryAPI|core (5.0.0) from forestry_1.10.2-5.2.3.213.jar
		* ForestryAPI|farming (2.1.0) from forestry_1.10.2-5.2.3.213.jar
		* ForestryAPI|food (1.1.0) from forestry_1.10.2-5.2.3.213.jar
		* ForestryAPI|fuels (2.0.1) from forestry_1.10.2-5.2.3.213.jar
		* ForestryAPI|genetics (4.7.1) from forestry_1.10.2-5.2.3.213.jar
		* ForestryAPI|greenhouse (5.0.0) from forestry_1.10.2-5.2.3.213.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.10.2-5.2.3.213.jar
		* ForestryAPI|lepidopterology (1.3.0) from forestry_1.10.2-5.2.3.213.jar
		* ForestryAPI|mail (3.0.0) from forestry_1.10.2-5.2.3.213.jar
		* ForestryAPI|multiblock (3.0.0) from forestry_1.10.2-5.2.3.213.jar
		* ForestryAPI|recipes (5.4.0) from forestry_1.10.2-5.2.3.213.jar
		* ForestryAPI|storage (5.0.0) from forestry_1.10.2-5.2.3.213.jar
		* ForestryAPI|world (2.1.0) from forestry_1.10.2-5.2.3.213.jar
		* IC2API (1.0) from industrialcraft-2-2.6.16-ex110.jar
		* jeresources|API (0.4.6.42) from JustEnoughResources-1.10.2-0.4.6.42.jar
		* journeymap|client-api (1.2) from journeymap-1.10.2-5.2.4-unlimited.jar
		* journeymap|client-api-display (1.2) from journeymap-1.10.2-5.2.4-unlimited.jar
		* journeymap|client-api-event (1.2) from journeymap-1.10.2-5.2.4-unlimited.jar
		* journeymap|client-api-model (1.2) from journeymap-1.10.2-5.2.4-unlimited.jar
		* journeymap|client-api-util (1.2) from journeymap-1.10.2-5.2.4-unlimited.jar
		* JustEnoughItemsAPI (4.0.0) from jei_1.10.2-3.7.8.234.jar
		* McJtyLib (1.10-1.9.9) from mcjtylib-1.10-1.9.9.jar
		* MekanismAPI|core (9.0.0) from Mekanism-1.10.2-9.1.0.286.jar
		* MekanismAPI|energy (9.0.0) from Mekanism-1.10.2-9.1.0.286.jar
		* MekanismAPI|gas (9.0.0) from Mekanism-1.10.2-9.1.0.286.jar
		* MekanismAPI|infuse (9.0.0) from Mekanism-1.10.2-9.1.0.286.jar
		* MekanismAPI|laser (9.0.0) from Mekanism-1.10.2-9.1.0.286.jar
		* MekanismAPI|reactor (9.0.0) from Mekanism-1.10.2-9.1.0.286.jar
		* MekanismAPI|recipe (9.0.0) from Mekanism-1.10.2-9.1.0.286.jar
		* MekanismAPI|transmitter (9.0.0) from Mekanism-1.10.2-9.1.0.286.jar
		* MekanismAPI|util (9.0.0) from Mekanism-1.10.2-9.1.0.286.jar
		* OpenComputersAPI|Component (6.0.0-alpha) from OpenComputers-MC1.10-1.6.0.2-beta.4.jar
		* OpenComputersAPI|Core (6.0.0-alpha) from OpenComputers-MC1.10-1.6.0.2-beta.4.jar
		* OpenComputersAPI|Driver (6.0.0-alpha) from OpenComputers-MC1.10-1.6.0.2-beta.4.jar
		* OpenComputersAPI|Driver|Item (6.0.0-alpha) from OpenComputers-MC1.10-1.6.0.2-beta.4.jar
		* OpenComputersAPI|Event (6.0.0-alpha) from OpenComputers-MC1.10-1.6.0.2-beta.4.jar
		* OpenComputersAPI|FileSystem (6.0.0-alpha) from OpenComputers-MC1.10-1.6.0.2-beta.4.jar
		* OpenComputersAPI|Internal (6.0.0-alpha) from OpenComputers-MC1.10-1.6.0.2-beta.4.jar
		* OpenComputersAPI|Machine (6.0.0-alpha) from OpenComputers-MC1.10-1.6.0.2-beta.4.jar
		* OpenComputersAPI|Manual (6.0.0-alpha) from OpenComputers-MC1.10-1.6.0.2-beta.4.jar
		* OpenComputersAPI|Network (6.0.0-alpha) from OpenComputers-MC1.10-1.6.0.2-beta.4.jar
		* OpenComputersAPI|Prefab (6.0.0-alpha) from OpenComputers-MC1.10-1.6.0.2-beta.4.jar
		* StorageDrawersAPI (1.7.10-1.2.0) from refinedstorage-0.8.12.jar
		* StorageDrawersAPI|config (1.7.10-1.2.0) from refinedstorage-0.8.12.jar
		* StorageDrawersAPI|event (1.7.10-1.2.0) from refinedstorage-0.8.12.jar
		* StorageDrawersAPI|inventory (1.7.10-1.2.0) from StorageDrawers-1.9.4-3.2.1.jar
		* StorageDrawersAPI|pack (1.7.10-1.2.0) from refinedstorage-0.8.12.jar
		* StorageDrawersAPI|registry (1.7.10-1.2.0) from refinedstorage-0.8.12.jar
		* StorageDrawersAPI|render (1.7.10-1.2.0) from refinedstorage-0.8.12.jar
		* StorageDrawersAPI|storage (1.7.10-1.2.0) from refinedstorage-0.8.12.jar
		* StorageDrawersAPI|storage-attribute (1.7.10-1.2.0) from refinedstorage-0.8.12.jar
		* WailaAPI (1.3) from Waila-1.7.0-B3_1.9.4.jar
	EnderIO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker.):
                  * Optifine is installed. This is NOT supported.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Detailed RF API diagnostics:
                  * RF API class 'EnergyStorage' is loaded from: jar:file:/C:/MC/pack0/mods/Mekanism-1.10.2-9.1.0.286.jar!/cofh/api/energy/EnergyStorage.class
                  * RF API class 'IEnergyConnection' is loaded from: jar:file:/C:/MC/pack0/mods/Mekanism-1.10.2-9.1.0.286.jar!/cofh/api/energy/IEnergyConnection.class
                  * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/C:/MC/pack0/mods/Mekanism-1.10.2-9.1.0.286.jar!/cofh/api/energy/IEnergyContainerItem.class
                  * RF API class 'IEnergyHandler' is loaded from: jar:file:/C:/MC/pack0/mods/Mekanism-1.10.2-9.1.0.286.jar!/cofh/api/energy/IEnergyHandler.class
                  * RF API class 'IEnergyProvider' is loaded from: jar:file:/C:/MC/pack0/mods/Mekanism-1.10.2-9.1.0.286.jar!/cofh/api/energy/IEnergyProvider.class
                  * RF API class 'IEnergyReceiver' is loaded from: jar:file:/C:/MC/pack0/mods/Mekanism-1.10.2-9.1.0.286.jar!/cofh/api/energy/IEnergyReceiver.class
                  * RF API class 'IEnergyStorage' is loaded from: jar:file:/C:/MC/pack0/mods/Mekanism-1.10.2-9.1.0.286.jar!/cofh/api/energy/IEnergyStorage.class
                  * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/C:/MC/pack0/mods/Mekanism-1.10.2-9.1.0.286.jar!/cofh/api/energy/ItemEnergyContainer.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/C:/MC/pack0/mods/Mekanism-1.10.2-9.1.0.286.jar!/cofh/api/energy/TileEnergyHandler.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/C:/MC/pack0/mods/Mekanism-1.10.2-9.1.0.286.jar!/cofh/api/energy/TileEnergyHandler.class

	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['lassdas'/2346, l='New World', x=-786,47, y=4,29, z=1166,28]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.10.2_HD_U_C2
	Render Distance Chunks: 10
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 361.91
	OpenGlRenderer: GeForce GTX 960/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8
```

**Comment by aidancbrady** [comment]
Fixed, thanks!
