### ISSUE TITLE
[Crash] Mechanical Pipe Render

### ISSUE THREAD

**Issue by Utildayael** [aidancbrady/Mekanism#3567]
Made new world. Placed some Mekanism items [ironically the setup I used to report the dirty iron dust not working on enrichment chamber] .... quit to jump on server.

Left server to test something in creative so jumped back on said test world which was brand new and only had Mek stuff on it... and.. crash to desktop. World starts to load, looked at my machine setup and bam crash.

Crash log pastebin link below:
http://pastebin.com/AeTzBgKW

Mekanism-1.10.2-9.1.0.288

Relevant bits:

```
Description: Rendering Block Entity

java.lang.IllegalStateException: Not building!
	at net.minecraft.client.renderer.VertexBuffer.func_178977_d(VertexBuffer.java:538)
	at net.minecraft.client.renderer.Tessellator.func_78381_a(SourceFile:21)
	at mekanism.client.render.transmitter.RenderMechanicalPipe.renderMultipartAt(RenderMechanicalPipe.java:109)
	at mekanism.client.render.transmitter.RenderMechanicalPipe.renderMultipartAt(RenderMechanicalPipe.java:22)
	at mcmultipart.client.multipart.MultipartContainerSpecialRenderer.renderMultipartContainerAt(MultipartContainerSpecialRenderer.java:91)
	at mcmultipart.client.multipart.MultipartContainerSpecialRenderer$TileMultipartSpecialRenderer.renderTileEntityAt(MultipartContainerSpecialRenderer.java:194)
	at mcmultipart.client.multipart.MultipartContainerSpecialRenderer$TileMultipartSpecialRenderer.func_180535_a(MultipartContainerSpecialRenderer.java:189)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_178469_a(TileEntityRendererDispatcher.java:147)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:125)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:700)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1315)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1038)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

```

**Comment by aidancbrady** [comment]
Fixed in development.

**Comment by Utildayael** [comment]
Thank you sir!
