### ISSUE TITLE
Rendering Block Entity crashed.

### ISSUE THREAD

**Issue by papa3boyz** [aidancbrady/Mekanism#3603]
Description: Rendering Block Entity

java.lang.IllegalStateException: Not building!
	at net.minecraft.client.renderer.VertexBuffer.func_178977_d(VertexBuffer.java:713)
	at net.minecraft.client.renderer.Tessellator.func_78381_a(SourceFile:21)
	at mekanism.client.render.transmitter.RenderMechanicalPipe.renderMultipartAt(RenderMechanicalPipe.java:109)
	at mekanism.client.render.transmitter.RenderMechanicalPipe.renderMultipartAt(RenderMechanicalPipe.java:22)
	at mcmultipart.client.multipart.MultipartContainerSpecialRenderer.renderMultipartContainerAt(MultipartContainerSpecialRenderer.java:91)
	at mcmultipart.client.multipart.MultipartContainerSpecialRenderer$TileMultipartSpecialRenderer.renderTileEntityAt(MultipartContainerSpecialRenderer.java:194)
	at mcmultipart.client.multipart.MultipartContainerSpecialRenderer$TileMultipartSpecialRenderer.func_180535_a(MultipartContainerSpecialRenderer.java:189)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_178469_a(TileEntityRendererDispatcher.java:147)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:125)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:989)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1727)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1556)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1335)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.renderer.VertexBuffer.func_178977_d(VertexBuffer.java:713)
	at net.minecraft.client.renderer.Tessellator.func_78381_a(SourceFile:21)
	at mekanism.client.render.transmitter.RenderMechanicalPipe.renderMultipartAt(RenderMechanicalPipe.java:109)
	at mekanism.client.render.transmitter.RenderMechanicalPipe.renderMultipartAt(RenderMechanicalPipe.java:22)
	at mcmultipart.client.multipart.MultipartContainerSpecialRenderer.renderMultipartContainerAt(MultipartContainerSpecialRenderer.java:91)
	at mcmultipart.client.multipart.MultipartContainerSpecialRenderer$TileMultipartSpecialRenderer.renderTileEntityAt(MultipartContainerSpecialRenderer.java:194)
	at mcmultipart.client.multipart.MultipartContainerSpecialRenderer$TileMultipartSpecialRenderer.func_180535_a(MultipartContainerSpecialRenderer.java:189)

-- Block Entity Details --
Details:
	Name: mcmultipart:multipart.ticking // mcmultipart.block.TileMultipartContainer.Ticking
	Block type: ID #2422 (tile.null // mcmultipart.block.BlockMultipartContainer)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-371,62,-475), Chunk: (at 13,3,5 in -24,-30; contains blocks -384,0,-480 to -369,255,-465), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Actual block type: ID #2422 (tile.null // mcmultipart.block.BlockMultipartContainer)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_178469_a(TileEntityRendererDispatcher.java:147)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:125)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:989)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1727)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1556)

I also reporting to multipart owner..TQ

**Comment by aidancbrady** [comment]
Fixed in dev, should have a release out soon :)

**Comment by Stuart74** [comment]
having the same issue running now i have players that are unable to even play due to this issue is there any idea of an ETA regarding this dev release that fixes this.

Mekanism version 9.1.1.290 for 1.10.2
Forge Version 2056
