### ISSUE TITLE
[Bug] Thermoelectric Boiler Rendering Crash 

### ISSUE THREAD

**Issue by Egglanoir** [aidancbrady/Mekanism#3604]
The Thermoelectric boiler crashes the game when water is inserted. This looks like it may be cause by something from MrTJP, but I will also add, this problem seems to occur after defense tech is installed, it never used to occur before then. Also, the crash doesn't always happen with every boiler, but it will continuously crash until its destroyed. I am not entirely sure why this happens. It may have something to do getting heat from a fusion reactor to power it, but I can get that to work sometimes. Also if I remove Defense Tech, load the world, then re-add Defense Tech, then re-load the world, it can fix the issue in single player, but it won't help on a server. This is a very annoying issue, as in a multiplayer server I play on, I use the boiler heated by a fusion reactor to power an industrial turbine, which as you can imagine, can generate massive amounts of energy. I have tried changing the input pipes and how the water is retrieved, nothing really fixes it. This problem doesn't always occur in single player, which is rather strange. I never used to have problems with the boiler before Defense Tech was installed on the the server, but now I can't to get it to work without crashing me, and any other player who gets to close to the boiler. I have even tried rebuilding the boiler with new boiler blocks, it still crashes.

**Here is some pictures of the latest setup for it**

![2016-08-07_17 24 55](https://cloud.githubusercontent.com/assets/20405308/17465406/1fddafa4-5cc4-11e6-9039-757d3025a67d.png)
![2016-08-07_17 25 20](https://cloud.githubusercontent.com/assets/20405308/17465407/258096a6-5cc4-11e6-9d89-58249e04f55c.png)

**Here is the report**

```
[00:40:45] [Client thread/INFO] [STDOUT/]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
// Oops.

Time: 8/7/16 12:40 AM
Description: Rendering Block Entity

java.lang.NullPointerException: Rendering Block Entity
	at net.minecraft.client.renderer.RenderBlocks.func_147768_a(RenderBlocks.java:7021)
	at mekanism.client.render.MekanismRenderer.renderObject(MekanismRenderer.java:337)
	at mekanism.client.render.tileentity.RenderThermoelectricBoiler.getUpperDisplay(RenderThermoelectricBoiler.java:216)
	at mekanism.client.render.tileentity.RenderThermoelectricBoiler.renderAModelAt(RenderThermoelectricBoiler.java:121)
	at mekanism.client.render.tileentity.RenderThermoelectricBoiler.func_147500_a(RenderThermoelectricBoiler.java:40)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147549_a(SourceFile:100)
	at mrtjp.relocation.ASMHacks$.renderTileEntityAt(hacks.scala:30)
	at mrtjp.relocation.ASMHacks.renderTileEntityAt(hacks.scala)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147544_a(SourceFile:92)
	at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:483)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1224)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1015)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.renderer.RenderBlocks.func_147768_a(RenderBlocks.java:7021)
	at mekanism.client.render.MekanismRenderer.renderObject(MekanismRenderer.java:337)
	at mekanism.client.render.tileentity.RenderThermoelectricBoiler.getUpperDisplay(RenderThermoelectricBoiler.java:216)
	at mekanism.client.render.tileentity.RenderThermoelectricBoiler.renderAModelAt(RenderThermoelectricBoiler.java:121)
	at mekanism.client.render.tileentity.RenderThermoelectricBoiler.func_147500_a(RenderThermoelectricBoiler.java:40)

-- Block Entity Details --
Details:
	Name: BoilerCasing // mekanism.common.tile.TileEntityBoilerCasing
	Block type: ID #854 (tile.BasicBlock2 // mekanism.common.block.BlockBasic)
	Block data value: 7 / 0x7 / 0b0111
	Block location: World: (9559,12,-330), Chunk: (at 7,0,6 in 597,-21; contains blocks 9552,0,-336 to 9567,255,-321), Region: (18,-1; contains chunks 576,-32 to 607,-1, blocks 9216,0,-512 to 9727,255,-1)
	Actual block type: ID #854 (tile.BasicBlock2 // mekanism.common.block.BlockBasic)
	Actual block data value: 7 / 0x7 / 0b0111
Stacktrace:
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147549_a(SourceFile:100)
	at mrtjp.relocation.ASMHacks$.renderTileEntityAt(hacks.scala:30)
	at mrtjp.relocation.ASMHacks.renderTileEntityAt(hacks.scala)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147544_a(SourceFile:92)
	at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:483)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1224)

-- Affected level --
Details:
	Level name: MpServer
	All players: 2 total; [EntityClientPlayerMP['Egglanoir'/4557, l='MpServer', x=9560.78, y=18.62, z=-332.41], GCEntityOtherPlayerMP['Xazar'/11028, l='MpServer', x=9561.59, y=91.22, z=-331.03]]
	Chunk stats: MultiplayerChunkCache: 395, 395
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (9458,5,-357), Chunk: (at 2,0,11 in 591,-23; contains blocks 9456,0,-368 to 9471,255,-353), Region: (18,-1; contains chunks 576,-32 to 607,-1, blocks 9216,0,-512 to 9727,255,-1)
	Level time: 333263994 game time, 25897286 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 29 total; [EntityPig['Pig'/15759, l='MpServer', x=9544.81, y=65.00, z=-394.69], EntityZombie['Zombie'/15760, l='MpServer', x=9551.70, y=30.07, z=-365.30], EntityZombie['Zombie'/15761, l='MpServer', x=9537.69, y=23.00, z=-372.50], GCEntityOtherPlayerMP['Xazar'/11028, l='MpServer', x=9561.59, y=91.22, z=-331.03], EntitySpider['Spider'/2742582, l='MpServer', x=-23.58, y=-19.62, z=29.65], EntitySkeleton['Skeleton'/18721, l='MpServer', x=9568.50, y=50.00, z=-328.50], EntityCow['Cow'/3112, l='MpServer', x=9586.53, y=74.00, z=-363.53], EntityClientPlayerMP['Egglanoir'/4557, l='MpServer', x=9560.78, y=18.62, z=-332.41], EntityBlock['unknown'/2798570, l='MpServer', x=2147483647.00, y=2147483647.00, z=2147483647.00], EntityBlock['unknown'/2798571, l='MpServer', x=2147483647.00, y=2147483647.00, z=2147483647.00], EntityBlock['unknown'/2798568, l='MpServer', x=2147483647.00, y=2147483647.00, z=2147483647.00], EntityBlock['unknown'/2798569, l='MpServer', x=2147483647.00, y=2147483647.00, z=2147483647.00], EntityBlock['unknown'/2798572, l='MpServer', x=2147483647.00, y=2147483647.00, z=2147483647.00], EntityBlock['unknown'/2798573, l='MpServer', x=2147483647.00, y=2147483647.00, z=2147483647.00], EntityBlock['unknown'/2798562, l='MpServer', x=2147483647.00, y=2147483647.00, z=2147483647.00], EntityCreeper['Creeper'/18632, l='MpServer', x=9593.50, y=51.00, z=-295.50], EntityBlock['unknown'/2798563, l='MpServer', x=2147483647.00, y=2147483647.00, z=2147483647.00], EntityBlock['unknown'/2798566, l='MpServer', x=2147483647.00, y=2147483647.00, z=2147483647.00], EntityBlock['unknown'/2801894, l='MpServer', x=9608.25, y=26.90, z=-434.75], EntityBlock['unknown'/2798567, l='MpServer', x=2147483647.00, y=2147483647.00, z=2147483647.00], EntityBlock['unknown'/2798564, l='MpServer', x=2147483647.00, y=2147483647.00, z=2147483647.00], EntityBlock['unknown'/2798565, l='MpServer', x=2147483647.00, y=2147483647.00, z=2147483647.00], EntityCreeper['Creeper'/18640, l='MpServer', x=9573.97, y=37.00, z=-304.53], EntitySkeleton['Skeleton'/18131, l='MpServer', x=9586.50, y=48.00, z=-340.50], EntitySkeleton['Skeleton'/18132, l='MpServer', x=9585.50, y=48.00, z=-339.50], GCEntityOtherPlayerMP['Xazar'/11028, l='MpServer', x=9519.97, y=6.27, z=-323.84], EntitySkeleton['Skeleton'/17382, l='MpServer', x=9543.50, y=47.00, z=-352.50], EntitySkeleton['Skeleton'/17914, l='MpServer', x=9615.50, y=46.00, z=-286.50], GCEntityOtherPlayerMP['Xazar'/11028, l='MpServer', x=9561.59, y=91.22, z=-331.03]]
	Retry entities: 0 total; []
	Server brand: kcauldron,cauldron,craftbukkit,mcpc,fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_66, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4727416864 bytes (4508 MB) / 6442450944 bytes (6144 MB) up to 6442450944 bytes (6144 MB)
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms6144m -Xmx6144m -XX:+UseG1GC -XX:MaxGCPauseMillis=4
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 102 mods loaded, 94 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{7.10.99.99} [Forge Mod Loader] (modpack.jar) 
	UCHIJA	Forge{10.13.4.1614} [Minecraft Forge] (modpack.jar) 
	UCHIJA	AM2-Preloader{0.0.3} [AMCore] (minecraft.jar) 
	UCHIJA	appliedenergistics2-core{rv3-beta-6} [Applied Energistics 2 Core] (minecraft.jar) 
	UCHIJA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJA	PlayerAPI{1.4} [Player API] (minecraft.jar) 
	UCHIJA	OpenModsCore{0.9.1} [OpenModsCore] (minecraft.jar) 
	UCHIJA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJA	mod_ThreadedLighting{1.7.10-1.0} [Threaded Lighting] (minecraft.jar) 
	UCHIJA	gilded-games-util{1.7.10-1.2} [Gilded Games Utility] (gilded-games-util-1.7.10-1.9.jar) 
	UCHIJA	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) 
	UCHIJA	arsmagica2{1.4.0.009} [Ars Magica 2] (1.7.10_AM2-1.4.0.009.jar) 
	UCHIJA	aether{1.7.10-1.6} [Aether II] (aether-1.7.10-1.6.jar) 
	UCHIJA	appliedenergistics2{rv3-beta-6} [Applied Energistics 2] (appliedenergistics2-rv3-beta-6.jar) 
	UCHIJA	MovingWorld{1.7.10-1.8.1} [Moving World] (movingworld-1.7.10-1.8.1.jar) 
	UCHIJA	ArchimedesShipsPlus{1.7.10-1.8.1} [Archimedes' Ships Plus] (archimedesshipsplus-1.7.10-1.8.1.jar) 
	UCHIJA	Backpack{2.0.1} [Backpack] (backpack-2.0.1-1.7.x.jar) 
	UCHIJA	XaeroBetterPvP{1.9.1.1} [Better PVP Mod] (BetterPvP_1.9.1.1_Forge_1.7.10.jar) 
	UCHIJA	BiblioCraft{1.11.5} [BiblioCraft] (BiblioCraft[v1.11.5][MC1.7.10].jar) 
	UCHIJA	CoFHCore{1.7.10R3.1.3} [CoFH Core] (CoFHCore-[1.7.10]3.1.3-327.jar) 
	UCHIJA	BuildCraft|Core{7.1.16} [BuildCraft] (buildcraft-7.1.16.jar) 
	UCHIJA	BuildCraft|Builders{7.1.16} [BC Builders] (buildcraft-7.1.16.jar) 
	UCHIJA	BuildCraft|Transport{7.1.16} [BC Transport] (buildcraft-7.1.16.jar) 
	UCHIJA	BuildCraft|Energy{7.1.16} [BC Energy] (buildcraft-7.1.16.jar) 
	UCHIJA	BuildCraft|Silicon{7.1.16} [BC Silicon] (buildcraft-7.1.16.jar) 
	UCHIJA	BuildCraft|Robotics{7.1.16} [BC Robotics] (buildcraft-7.1.16.jar) 
	UCHIJA	BuildCraft|Factory{7.1.16} [BC Factory] (buildcraft-7.1.16.jar) 
	UCHIJA	CarpentersBlocks{3.3.8} [Carpenter's Blocks] (Carpenter's Blocks v3.3.8 - MC 1.7.10.jar) 
	UCHIJA	chisel{1.5.7} [Chisel] (Chisel-1.7.10-1.5.7.jar) 
	UCHIJA	ComputerCraft{1.75} [ComputerCraft] (ComputerCraft1.75.jar) 
	UCHIJA	MineTweaker3{3.0.10} [MineTweaker 3] (CraftTweaker-1.7.10-3.0.10.jar) 
	UCHIJA	customnpcs{1.7.10d} [CustomNpcs] (CustomNPCs_1.7.10d(21feb16).jar) 
	UCHIJA	PTRModelLib{1.0.0} [PTRModelLib] (Decocraft-2.3.3_1.7.10.jar) 
	UCHIJA	props{2.3.3} [Decocraft] (Decocraft-2.3.3_1.7.10.jar) 
	UCHIJA	IC2{2.2.823-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.823-experimental.jar) 
	UCHIJA	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJA	GalacticraftCore{3.0.12} [Galacticraft Core] (GalacticraftCore-1.7-3.0.12.463.jar) 
	UCHIJA	Mekanism{9.1.0} [Mekanism] (Mekanism-1.7.10-9.1.0.281.jar) 
	UCHIJA	DefenseTech{1.0.1} [DefenseTech] (DefenseTech-1.7.10-1.0.1.46.jar) 
	UCHIJA	DragonsRadioMod{1.7.1} [Dragon's Radio Mod] (Dragon's Radio Mod-MC1.7.10-1.7.1.jar) 
	UCHIJA	endercore{1.7.10-0.2.0.36_beta} [EnderCore] (EnderCore-1.7.10-0.2.0.36_beta.jar) 
	UCHIJA	MineFactoryReloaded{1.7.10R2.8.2B1} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.2B1-196.jar) 
	UCHIJA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJA	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
	UCHIJA	EnderIO{1.7.10-2.3.0.428_beta} [Ender IO] (EnderIO-1.7.10-2.3.0.428_beta.jar) 
	UCHIJA	EnderStorage{1.4.7.37} [EnderStorage] (EnderStorage-1.7.10-1.4.7.37-universal.jar) 
	UCHIJA	EnderZoo{1.7.10-1.0.15.32} [Ender Zoo] (EnderZoo-1.7.10-1.0.15.32.jar) 
	UCHIJA	extracells{2.3.14} [Extra Cells 2] (ExtraCells-1.7.10-2.3.14b197.jar) 
	UCHIJA	ExtraUtilities{1.2.12} [Extra Utilities] (extrautilities-1.2.12.jar) 
	UCHIJA	flansmod{4.10.0} [Flan's Mod] (Flans Mod-1.7.10-4.10.0.jar) 
	UCHIJA	GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.12.463.jar) 
	UCHIJA	IGWMod{1.1.12-34} [In-Game wiki Mod] (IGW-Mod-1.7.10-1.1.12-34-universal.jar) 
	UCHIJA	IronChest{6.0.60.741} [Iron Chest] (ironchest-1.7.10-6.0.60.741-universal.jar) 
	UCHIJA	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
	UCHIJA	MekanismGenerators{9.1.0} [MekanismGenerators] (MekanismGenerators-1.7.10-9.1.0.281.jar) 
	UCHIJA	MekanismTools{9.1.0} [MekanismTools] (MekanismTools-1.7.10-9.1.0.281.jar) 
	UCHIJA	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.2B1} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.2B1-196.jar) 
	UCHIJA	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.2B1} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.2B1-196.jar) 
	UCHIJA	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.2B1} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.2B1-196.jar) 
	UCHIJA	MineFactoryReloaded|CompatIC2{1.7.10R2.8.2B1} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.2B1-196.jar) 
	UCHIJA	MrTJPCoreMod{1.1.0.33} [MrTJPCore] (MrTJPCore-1.7.10-1.1.0.33-universal.jar) 
	UCHIJA	ProjRed|Core{4.7.0pre12.95} [ProjectRed Core] (ProjectRed-1.7.10-4.7.0pre12.95-Base.jar) 
	UCHIJA	ProjRed|Exploration{4.7.0pre12.95} [ProjectRed Exploration] (ProjectRed-1.7.10-4.7.0pre12.95-World.jar) 
	UCHIJA	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.2B1} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.2B1-196.jar) 
	UCHIJA	Railcraft{9.12.2.0} [Railcraft] (Railcraft_1.7.10-9.12.2.0.jar) 
	UCHIJA	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.2B1} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.2B1-196.jar) 
	UCHIJA	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.2B1} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.2B1-196.jar) 
	UCHIJA	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.jar) 
	UCHIJA	MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.2B1} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.2B1-196.jar) 
	UCHIJA	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.2B1} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.2B1-196.jar) 
	UCHIJA	modtweaker2{0.9.6} [Mod Tweaker 2] (ModTweaker2-0.9.6.jar) 
	UCHIJA	OpenMods{0.9.1} [OpenMods] (OpenModsLib-1.7.10-0.9.1.jar) 
	UCHIJA	OpenBlocks{1.5.1} [OpenBlocks] (OpenBlocks-1.7.10-1.5.1.jar) 
	UCHIJA	PneumaticCraft{1.12.7-150} [PneumaticCraft] (PneumaticCraft-1.7.10-1.12.7-150-universal.jar) 
	UCHIJA	ProjRed|Transmission{4.7.0pre12.95} [ProjectRed Transmission] (ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar) 
	UCHIJA	ProjRed|Transportation{4.7.0pre12.95} [ProjectRed Transportation] (ProjectRed-1.7.10-4.7.0pre12.95-Mechanical.jar) 
	UCHIJA	ProjRed|Compatibility{4.7.0pre12.95} [ProjectRed Compatibility] (ProjectRed-1.7.10-4.7.0pre12.95-Compat.jar) 
	UCHIJA	ProjRed|Integration{4.7.0pre12.95} [ProjectRed Integration] (ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar) 
	UCHIJA	ProjRed|Fabrication{4.7.0pre12.95} [ProjectRed Fabrication] (ProjectRed-1.7.10-4.7.0pre12.95-Fabrication.jar) 
	UCHIJA	ProjRed|Illumination{4.7.0pre12.95} [ProjectRed Illumination] (ProjectRed-1.7.10-4.7.0pre12.95-Lighting.jar) 
	UCHIJA	ProjRed|Expansion{4.7.0pre12.95} [ProjectRed Expansion] (ProjectRed-1.7.10-4.7.0pre12.95-Mechanical.jar) 
	UCHIJA	TMechworks{0.2.15.106} [Tinkers' Mechworks] (TMechworks-1.7.10-0.2.15.106.jar) 
	UCHIJA	witchery{0.24.1} [Witchery] (witchery-1.7.10-0.24.1.jar) 
	UCHIJA	WR-CBE|Core{1.4.1.9} [WR-CBE Core] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
	UCHIJA	WR-CBE|Addons{1.4.1.9} [WR-CBE Addons] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
	UCHIJA	WR-CBE|Logic{1.4.1.9} [WR-CBE Logic] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
	UCHIJA	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJA	ForgeRelocation{0.0.1.4} [ForgeRelocation] (ForgeRelocation-1.7.10-0.0.1.4-universal.jar) 
	UCHIJA	MCFrames{1.0} [MCFrames] (ForgeRelocation-1.7.10-0.0.1.4-universal.jar) 
	UCHIJA	RelocationFMP{0.0.1.2} [RelocationFMP] (ForgeRelocationFMP-1.7.10-0.0.1.2-universal.jar) 
	UCHIJA	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UD	MineFactoryReloaded|CompatAtum{1.7.10R2.8.2B1} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.2B1-196.jar) 
	UD	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.2B1} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.2B1-196.jar) 
	UD	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.2B1} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.2B1-196.jar) 
	UD	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.2B1} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.2B1-196.jar) 
	UD	MineFactoryReloaded|CompatForestry{1.7.10R2.8.2B1} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.2B1-196.jar) 
	UD	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.2B1} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.2B1-196.jar) 
	UD	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.2B1} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.2B1-196.jar) 
	UD	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.2B1} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.2B1-196.jar) 
	OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:ACTIVATED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
	Class transformer null safety: all safe
	AE2 Version: beta rv3-beta-6 for Forge 10.13.4.1448
	CoFHCore: -[1.7.10]3.1.3-327
	MineFactoryReloaded: -[1.7.10]2.8.2B1-196
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
	EnderIO: Found the following problem(s) with your installation:
                  * The RF API that is being used (1.7.10R1.3.1 from <unknown>) differes from that that is reported as being loaded (1.7.10R1.0.2 from Railcraft_1.7.10-9.12.2.0.jar).
                    It is a supported version, but that difference may lead to problems.
                  * An unknown AE2 API is installed (rv3 from appliedenergistics2-rv3-beta-6.jar).
                    Ender IO was build against API version rv2 and may or may not work with a newer version.
                 This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Stencil buffer state: Function set: GL30, pool: forge, bits: 8
	AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:ON, BuildCraftCore:ON, BuildCraftTransport:ON, BuildCraftBuilder:ON, RF:ON, RFItem:ON, MFR:ON, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:OFF, InvTweaks:OFF, NEI:ON, CraftGuide:OFF, Mekanism:ON, ImmibisMicroblocks:OFF, BetterStorage:OFF, OpenComputers:OFF, PneumaticCraft:ON
	Launched Version: 1.7.10-Forge10.13.4.1614-1.7.10
	LWJGL: 2.9.1
	OpenGL: ATI Radeon HD 4800 Series GL version 3.3.11672 Compatibility Profile Context, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [Old Mekanism Blocks.zip]
	Current Language: English (UK)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
[00:40:45] [Client thread/INFO] [STDOUT/]: [net.minecraft.client.Minecraft:func_71377_b:359]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Egglanoir\AppData\Roaming\.technic\modpacks\the-end-of-minecraft\crash-reports\crash-2016-08-07_00.40.45-client.txt

```

**Comment by aidancbrady** [comment]
Yeah, I saw this issue before and I'm confident it's not on my end.  I do not see how DT could have anything to do with this either, but I'll keep that in mind.  Thanks for the report!
