### ISSUE TITLE
PartPressurizedTube.getCachedAcceptor casting TE to capability

### ISSUE THREAD

**Issue by bdew** [aidancbrady/Mekanism#3648]
java.lang.ClassCastException: net.bdew.pressure.blocks.gas.TileTankGasInput cannot be cast to mekanism.api.gas.IGasHandler
      at mekanism.common.multipart.PartPressurizedTube.getCachedAcceptor(PartPressurizedTube.java:270)
      at mekanism.common.multipart.PartPressurizedTube.getCachedAcceptor(PartPressurizedTube.java:24)
      at mekanism.common.multipart.MultipartTransmitter.getAcceptor(MultipartTransmitter.java:72)
      at mekanism.api.transmitters.DynamicNetwork.updateTransmitterOnSide(DynamicNetwork.java:109)
      at mekanism.api.transmitters.DynamicNetwork.commit(DynamicNetwork.java:71)
      at mekanism.api.transmitters.TransmitterNetworkRegistry.commitChanges(TransmitterNetworkRegistry.java:202)
      at mekanism.api.transmitters.TransmitterNetworkRegistry.tickEnd(TransmitterNetworkRegistry.java:101)
      at mekanism.api.transmitters.TransmitterNetworkRegistry.onTick(TransmitterNetworkRegistry.java:91)
      at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_200_TransmitterNetworkRegistry_onTick_ServerTickEvent.invoke(.dynamic)
      at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:72)
      at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:168)
      at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:261)
      at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:731)
      at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:156)
      at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:536)
      at java.lang.Thread.run(Thread.java:745)

This seems to cast my TileEntity to a capability interface (IGasHandler), instead of getting it via getCapability?..

**Comment by aidancbrady** [comment]
Should be fixed, thanks!
