### ISSUE TITLE
Cardboard box crash

### ISSUE THREAD

**Issue by AlphaWHH** [aidancbrady/Mekanism#3691]
Cardboard box with a redstone block inside it crashes to desktop

[18:30:59] [Client thread/INFO] [STDOUT/]: [net.minecraft.init.Bootstrap:func_179870_a:560]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingHook (Mekanism-1.10.2-9.1.1.290.jar)
  CXLibraryCore (cxlibrary-1.10.2-1.2.2.jar)
  NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  DepLoader (BrandonsCore-1.10.2-2.1.0.36-universal.jar)
  CodeChickenCorePlugin (CodeChickenCore-1.10.2-2.1.8.79-universal.jar)
  MalisisCorePlugin (malisiscore-1.9.4-4.1.1.jar)
  IC2core (industrialcraft-2-2.6.44-ex110.jar)
  CorePlugin (FluxedRedstone-2.3.0.48.jar)
  CCCDeobfPlugin (unknown)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  TransformerLoader (OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.2.3.60-universal.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.51-beta.jar)
  ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.0.jar)
Contact their authors BEFORE contacting forge

// Would you like a cupcake?

Time: 8/23/16 6:30 PM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
    at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:503)
    at mekanism.common.item.ItemBlockCardboardBox.func_77624_a(ItemBlockCardboardBox.java:55)
    at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:610)
    at net.minecraft.client.gui.GuiScreen.func_146285_a(GuiScreen.java:136)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:166)
    at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
    at net.minecraft.client.gui.inventory.GuiInventory.func_73863_a(SourceFile:47)
    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
    at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by VexedPanda** [comment]
I'm getting the same crash in AllTheMods when mousing over a box that contains a skeleton spawner, and one that contains a door (not sure what type)

**Comment by VexedPanda** [comment]
I updated All The Mods and this seems to have stopped happening. The tooltip now shows normally.

**Comment by JaSpr** [comment]
Box with a fishing net (from Fishing Net Mod) causes crash.  If it's not in your hotbar, then there is no way to get rid of it because mousing over it causes a client crash.
