### ISSUE TITLE
[1.10.2-9.2.0.292] Crash fusion reactor pressure pipe extract

### ISSUE THREAD

**Issue by mainframecn** [aidancbrady/Mekanism#3769]
Connecting a pressure pipe to the reactor port and setting it to pull crashes the client.
This was in an attempt to extract steam from the reactor.

Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
    at mekanism.generators.common.tile.reactor.TileEntityReactorPort.drawGas(TileEntityReactorPort.java:205)
    at mekanism.common.multipart.PartPressurizedTube.func_73660_a(PartPressurizedTube.java:61)
    at mcmultipart.block.TileMultipartContainer$Ticking.func_73660_a(TileMultipartContainer.java:311)

**Comment by thommy101** [comment]
Fixed in 70b9c5de2ef7d74b085863d11c086f0d4f2922f1
