### ISSUE TITLE
[1.10.2] Outdated version of MCMultiPart

### ISSUE THREAD

**Issue by TheRandomLabs** [aidancbrady/Mekanism#3779]
Mekanism is incompatible with [Refined Storage](https://minecraft.curseforge.com/projects/refined-storage) due to an outdated version of MCMultiPart. Relevant part of the crash log:
```
Missing Mods:
	mcmultipart : [1.2.1,)

net.minecraftforge.fml.common.MissingModsException: Mod refinedstorage (Refined Storage) requires [mcmultipart@[1.2.1,)]
	at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:274)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:525)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:97)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:328)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by thiakil** [comment]
How exactly is this Mekanism's issue? The error seems to be saying you forgot to install MCMultipart.

I'm using these mods together just fine.

**Comment by aidancbrady** [comment]
I've bumped up the default McMultipart version, should no longer be an issue.
