### ISSUE TITLE
Ticking block entity

### ISSUE THREAD

**Issue by ShadowDrakken** [aidancbrady/Mekanism#3784]
Forge: 2076
Mekanism: every 1.10.2 compat build through 9/11/2016

Description: Ticking block entity

java.lang.ClassCastException: mekanism.common.EnergyNetwork cannot be cast to mekanism.api.gas.GasNetwork
	at mekanism.common.multipart.PartPressurizedTube.func_73660_a(PartPressurizedTube.java:69)
	at mcmultipart.block.TileMultipartContainer$Ticking.func_73660_a(TileMultipartContainer.java:311)
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1789)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by aidancbrady** [comment]
Seems to be an edge case; unable to reproduce anything similar on my end.

**Comment by ShadowDrakken** [comment]
Edge case that happens nearly daily because your pipes get each other mixed
up, especially if they're anywhere remotely near EnderIO ... Thanks for
nothing, pretty typical of Mekanism's bug resolution though to be honest.
You should join ForgeCraft so that maybe a bug or two gets fixed.
