### ISSUE TITLE
[1.10.2]Minecraft crash on pumping items to colossal chest

### ISSUE THREAD

**Issue by MerryYukari** [aidancbrady/Mekanism#3791]
Hello there.
My Minecraft crashed while I'm trying to pumping ores from diamond chest to a colossal chest by using logistical transporter through chest's interface.
Also reported it to colossal chest author.
Crash report is:

# Description: Ticking block entity

java.lang.ArrayIndexOutOfBoundsException: 5623
	at mekanism.common.content.transporter.TransporterManager.copyInvFromSide(TransporterManager.java:104)
	at mekanism.common.content.transporter.TransporterManager.getPredictedInsert(TransporterManager.java:334)
	at mekanism.common.InventoryNetwork.calculateAcceptors(InventoryNetwork.java:64)
	at mekanism.common.content.transporter.TransporterPathfinder.getPaths(TransporterPathfinder.java:242)
	at mekanism.common.content.transporter.TransporterPathfinder.getNewBasePath(TransporterPathfinder.java:316)
	at mekanism.common.content.transporter.TransporterStack.recalculatePath(TransporterStack.java:193)
	at mekanism.common.multipart.MultipartTransporter.insert_do(MultipartTransporter.java:281)
	at mekanism.common.multipart.MultipartTransporter.insert(MultipartTransporter.java:263)
	at mekanism.common.util.TransporterUtils.insert(TransporterUtils.java:52)
	at mekanism.common.multipart.PartLogisticalTransporter.pullItems(PartLogisticalTransporter.java:147)
	at mekanism.common.multipart.MultipartTransporter.update(MultipartTransporter.java:62)
	at mekanism.common.multipart.PartLogisticalTransporter.func_73660_a(PartLogisticalTransporter.java:127)
	at mcmultipart.block.TileMultipartContainer$Ticking.func_73660_a(TileMultipartContainer.java:311)
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)

**Comment by aidancbrady** [comment]
Already reported
