### ISSUE TITLE
Server Crash on altering universal cable mode

### ISSUE THREAD

**Issue by WarMind666** [aidancbrady/Mekanism#3794]
connecting an ultimate universal cable from an industrial turbine to an induction matrix, and switching the mode from PULL to PUSH on the turbine side, caused the server to crash.  I was attempting to send the power from the turbine to the matrix, and the cables were not transmitting the power, so I thought to change mode, and it caused a ticking entity crash.  The crash log from the initial crash is pasted below, and also upon attempting to restart the server, the same crash occurs before the server can fully start.

http://pastebin.com/dmAXLV4P

**Comment by jco2641** [comment]
I jsut had the same thing happen, trying to figure out why it didn't seem like my turbine was outputting power, so I started cycling the cable mode at the turbine connection point and it crashed.  

http://pastebin.com/KNCE8ibF

**Comment by timrourke** [comment]
I just witnessed the same behavior on the server I was playing on. Appears to have caused the server to go into an infinite restart loop. Will provide a crash log if I can get one from the server admin. @WarMind666's description was exactly what I was doing-attaching a turbine to an induction matrix.

**Comment by timrourke** [comment]
Here is the relevant crash log as promised:

```
Time: 2/13/17 2:08 AM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at mekanism.common.multipart.PartUniversalCable.func_73660_a(PartUniversalCable.java:87)
	at mcmultipart.block.TileMultipartContainer$Ticking.func_73660_a(TileMultipartContainer.java:328)
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by thommy101** [comment]
A crashlog is relevant when you post the whole log. You're missing essential information about your setup. Forge version, mekanism version, 1.10/1.7.10, maybe more errors leafing to this.
