### ISSUE TITLE
1.10.2 - [Dev Build 9.2.56] - Crash when breaking energy or item pipes

### ISSUE THREAD

**Issue by viper2g1** [aidancbrady/Mekanism#3804]
MC: 1.10.2
Forge: 12.18.1.2086
Mekanism: 9.2.56

Crash Log:
https://gist.github.com/viper2g1/3dd3a9db62649adae38a3d52dd752002

When starting to break the pipes a client crash occurs.

**Comment by deeno** [comment]
I also get this error.
MC: 1.10.2
Forge: 12.18.1.2088
Mekanism: 9.2.1.56

Crash Report:
https://gist.github.com/deeno/110bf5fd3d7686c9fb6a1a43dee97b0b

On attempting to break any kind of pipe (energy, liquid, gas) the screen goes white and then the client crashes with NPE: Rendering Block Entity at mekanism.common.multipart.ConnectionProperty.valueToString(ConnectionProperty.java:48).

**Comment by squarism** [comment]
I have the same problem.  I created a creative world after my server play-through died (unable to load because some block is in some state that causes this ... no worries, I have backups).

But this was very easy to reproduce.
- Start a new world (forge 1.10.2-12.18.1.2065)
- Place down a generator.  Put a basic energy cube next to it.
- Place a biogenerator down.  Put a crusher down.  Connect the two with a basic mechanical pipe.  It crashes with an NPE.  Even in creative mode.

```
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_102]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_102]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240) [bzl.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_102]
Caused by: java.lang.NullPointerException
	at net.minecraftforge.fluids.capability.FluidTankProperties.convert(FluidTankProperties.java:34) ~[FluidTankProperties.class:?]
	at mekanism.common.base.FluidHandlerWrapper.getTankProperties(FluidHandlerWrapper.java:24) ~[FluidHandlerWrapper.class:?]
	at mekanism.common.util.PipeUtils.isValidAcceptorOnSide(PipeUtils.java:39) ~[PipeUtils.class:?]
	at mekanism.common.multipart.PartMechanicalPipe.isValidAcceptor(PartMechanicalPipe.java:183) ~[PartMechanicalPipe.class:?]
	at mekanism.common.multipart.PartSidedPipe.getPossibleAcceptorConnections(PartSidedPipe.java:317) ~[PartSidedPipe.class:?]
	at mekanism.common.multipart.PartSidedPipe.refreshConnections(PartSidedPipe.java:639) ~[PartSidedPipe.class:?]
	at mekanism.common.multipart.PartSidedPipe.onAdded(PartSidedPipe.java:704) ~[PartSidedPipe.class:?]
	at mcmultipart.multipart.MultipartContainer.addPart(MultipartContainer.java:190) ~[MultipartContainer.class:?]
	at mcmultipart.multipart.MultipartContainer.addPart(MultipartContainer.java:163) ~[MultipartContainer.class:?]
	at mcmultipart.block.TileMultipartContainer.addPart(TileMultipartContainer.java:98) ~[TileMultipartContainer.class:?]
	at mcmultipart.multipart.MultipartHelper.addPart(MultipartHelper.java:101) ~[MultipartHelper.class:?]
	at mcmultipart.multipart.MultipartHelper.addPart(MultipartHelper.java:81) ~[MultipartHelper.class:?]
	at mcmultipart.item.ItemMultiPart.place(ItemMultiPart.java:34) ~[ItemMultiPart.class:?]
	at mcmultipart.item.ItemMultiPart.func_180614_a(ItemMultiPart.java:60) ~[ItemMultiPart.class:?]
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:755) ~[ForgeHooks.class:?]
	at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:144) ~[adz.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:483) ~[lv.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:679) ~[me.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[jj.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[jj.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_102]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_102]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
	... 5 more
```

I updated forge and it seemed to fix this problem and also the textures for the held item icon (biogenerator and other things).  I moved up and down mekanism versions but updating forge is what did it.  `2065` had the NPE (latest when I started this playthrough, very arbitrary).  `forge-1.10.2-12.18.1.2094-universal.jar` worked.

I guess this stacktrace makes sense because forge is responsible for multipart?

**Comment by ProsperCraft** [comment]
https://github.com/aidancbrady/Mekanism/issues/3887
