### ISSUE TITLE
[1.10.2, critical bug] client crash when trying to open the chest of robit when he's too far away

### ISSUE THREAD

**Issue by rapus95** [aidancbrady/Mekanism#3817]
in the homebase enable anyone else's robits follow mode -> the robo teleports away but the gui is still open -> try to open the chest tab, then you encounter a total client crash

Stacktrace:

```
java.lang.NullPointerException: Updating screen events
    at mekanism.common.inventory.container.ContainerChemicalOxidizer.<init>(ContainerChemicalOxidizer.java:42)
    at mekanism.client.gui.GuiChemicalOxidizer.<init>(GuiChemicalOxidizer.java:39)
    at mekanism.client.ClientProxy.getClientGui(ClientProxy.java:769)
    at mekanism.client.ClientProxy.getClientGui(ClientProxy.java:249)
    at mekanism.common.CoreGuiHandler.getClientGuiElement(CoreGuiHandler.java:25)
    at net.minecraftforge.fml.common.network.NetworkRegistry.getLocalGuiContainer(NetworkRegistry.java:273)
    at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:110)
    at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2494)
    at mekanism.client.gui.GuiRobitMain.func_73864_a(GuiRobitMain.java:284)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:548)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:517)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1700)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

Full report can be seen there: https://gist.github.com/rapus95/9ac24ba4585c1bedb5b2637ddb1ab4ee

**Comment by aidancbrady** [comment]
Fixed, thanks!
