### ISSUE TITLE
[bug, critical, 1.10.2, multipart-related] multipart index out of bounds

### ISSUE THREAD

**Issue by rapus95** [aidancbrady/Mekanism#3822]
after dieing and trying to respawn the client crashes and produces this output

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  LoadingHook (Mekanism-1.10.2-9.2.0.292.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 22.09.16 14:59
Description: Rendering Block Entity

java.lang.ArrayIndexOutOfBoundsException: 100
    at mekanism.client.render.transmitter.RenderMechanicalPipe.renderMultipartAt(RenderMechanicalPipe.java:95)
    at mekanism.client.render.transmitter.RenderMechanicalPipe.renderMultipartAt(RenderMechanicalPipe.java:22)
    at mcmultipart.client.multipart.MultipartContainerSpecialRenderer.renderMultipartContainerAt(MultipartContainerSpecialRenderer.java:91)
    at mcmultipart.client.multipart.MultipartContainerSpecialRenderer$TileMultipartSpecialRenderer.renderTileEntityAt(MultipartContainerSpecialRenderer.java:194)
    at mcmultipart.client.multipart.MultipartContainerSpecialRenderer$TileMultipartSpecialRenderer.func_180535_a(MultipartContainerSpecialRenderer.java:189)
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_178469_a(TileEntityRendererDispatcher.java:147)
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:125)
    at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:992)
    at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1727)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1556)
    at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1335)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
    at mekanism.client.render.transmitter.RenderMechanicalPipe.renderMultipartAt(RenderMechanicalPipe.java:95)
    at mekanism.client.render.transmitter.RenderMechanicalPipe.renderMultipartAt(RenderMechanicalPipe.java:22)
    at mcmultipart.client.multipart.MultipartContainerSpecialRenderer.renderMultipartContainerAt(MultipartContainerSpecialRenderer.java:91)
    at mcmultipart.client.multipart.MultipartContainerSpecialRenderer$TileMultipartSpecialRenderer.renderTileEntityAt(MultipartContainerSpecialRenderer.java:194)
    at mcmultipart.client.multipart.MultipartContainerSpecialRenderer$TileMultipartSpecialRenderer.func_180535_a(MultipartContainerSpecialRenderer.java:189)

-- Block Entity Details --
Details:
    Name: mcmultipart:multipart.ticking // mcmultipart.block.TileMultipartContainer.Ticking
    Block type: ID #0 (tile.air // net.minecraft.block.BlockAir)
    Block data value: 0 / 0x0 / 0b0000
    Block location: World: (89,41,-169), Chunk: (at 9,2,7 in 5,-11; contains blocks 80,0,-176 to 95,255,-161), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
    Actual block type: ID #0 (tile.air // net.minecraft.block.BlockAir)
    Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_178469_a(TileEntityRendererDispatcher.java:147)
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:125)
    at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:992)
    at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1727)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1556)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['rapus95'/1571378, l='MpServer', x=90,50, y=52,10, z=-188,50]]
    Chunk stats: MultiplayerChunkCache: 44, 44
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (128,64,-22), Chunk: (at 0,4,10 in 8,-2; contains blocks 128,0,-32 to 143,255,-17), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
    Level time: 8788737 game time, 9877683 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 77 total; [EntityRobit['Richi=Penis'/1, l='MpServer', x=101,50, y=55,00, z=-184,50], EntityRobit['(??_?)'/2, l='MpServer', x=100,50, y=55,00, z=-184,25], EntityRobit['Bonny'/3, l='MpServer', x=102,50, y=55,00, z=-184,50], EntityRobit['Kasper'/4, l='MpServer', x=103,50, y=55,00, z=-184,50], EntityEnderman['Enderman'/1573399, l='MpServer', x=146,50, y=28,00, z=-108,50], EntityCreeper['Creeper'/1574412, l='MpServer', x=129,48, y=42,00, z=-208,18], EntityCreeper['Creeper'/1577530, l='MpServer', x=68,51, y=87,00, z=-210,16], EntityChicken['Chicken'/1571376, l='MpServer', x=69,50, y=88,00, z=-218,09], EntityZombie['Husk'/1577520, l='MpServer', x=123,50, y=67,00, z=-117,50], EntitySkeleton['Skeleton'/1575473, l='MpServer', x=83,50, y=23,00, z=-231,31], EntityCreeper['Creeper'/1570878, l='MpServer', x=154,50, y=28,00, z=-120,50], EntitySquid['Squid'/1571374, l='MpServer', x=58,48, y=60,58, z=-180,41], EntityChicken['Chicken'/1571886, l='MpServer', x=153,81, y=65,00, z=-163,57], EntitySquid['Squid'/1571372, l='MpServer', x=64,24, y=62,08, z=-173,60], EntityZombie['Zombie'/1575974, l='MpServer', x=162,49, y=19,00, z=-225,20], EntityZombie['Zombie'/1571880, l='MpServer', x=158,50, y=19,00, z=-185,50], EntityTippedArrow['Arrow'/76, l='MpServer', x=95,13, y=64,64, z=-92,87], EntityItem['item.item.egg'/1572473, l='MpServer', x=42,18, y=85,00, z=-187,77], EntityCreeper['Creeper'/1577569, l='MpServer', x=18,50, y=64,00, z=-117,50], EntityCreeper['Creeper'/1577571, l='MpServer', x=20,50, y=64,00, z=-111,50], EntityBat['Bat'/1577626, l='MpServer', x=144,51, y=42,63, z=-99,57], EntityWitch['Witch'/1574555, l='MpServer', x=153,50, y=40,00, z=-95,50], EntityChicken['Chicken'/1571487, l='MpServer', x=96,61, y=66,00, z=-225,13], EntitySkeleton['Skeleton'/1577110, l='MpServer', x=105,50, y=63,00, z=-179,50], EntitySheep['Sheep'/1571461, l='MpServer', x=9,79, y=92,00, z=-227,81], EntityChicken['Chicken'/1571468, l='MpServer', x=41,20, y=86,00, z=-188,50], EntitySheep['Sheep'/1571467, l='MpServer', x=36,84, y=88,00, z=-189,16], EntitySheep['Sheep'/1571466, l='MpServer', x=40,26, y=87,00, z=-188,79], EntitySheep['Sheep'/1571465, l='MpServer', x=33,73, y=80,00, z=-169,48], EntityPlayerSP['rapus95'/1571378, l='MpServer', x=89,30, y=53,00, z=-154,30], EntityCreeper['Creeper'/1576635, l='MpServer', x=133,50, y=39,00, z=-92,50], EntityCreeper['Creeper'/1572018, l='MpServer', x=166,50, y=28,00, z=-119,50], EntityBat['Bat'/1575613, l='MpServer', x=150,84, y=13,86, z=-108,45], EntitySkeleton['Skeleton'/1576627, l='MpServer', x=154,50, y=17,00, z=-155,50], EntitySkeleton['Skeleton'/1576628, l='MpServer', x=152,30, y=16,00, z=-155,52], EntityCreeper['Creeper'/1577632, l='MpServer', x=86,50, y=51,00, z=-227,50], EntityCreeper['Creeper'/1574564, l='MpServer', x=164,50, y=29,00, z=-196,50], EntityItem['item.item.egg'/1576640, l='MpServer', x=153,26, y=65,00, z=-163,68], EntityCreeper['Creeper'/1576129, l='MpServer', x=130,50, y=45,00, z=-110,50], EntityTippedArrow['Arrow'/1576641, l='MpServer', x=96,73, y=52,05, z=-187,75], EntitySpider['Spider'/1577208, l='MpServer', x=162,50, y=18,00, z=-114,50], EntityCreeper['Creeper'/1576684, l='MpServer', x=128,50, y=48,00, z=-158,50], EntityBat['Bat'/1577198, l='MpServer', x=134,83, y=28,03, z=-154,12], EntityBat['Bat'/1576725, l='MpServer', x=143,43, y=45,05, z=-115,30], EntitySkeleton['Skeleton'/1577225, l='MpServer', x=118,50, y=67,00, z=-120,50], EntitySquid['Squid'/1555203, l='MpServer', x=90,63, y=62,35, z=-165,77], EntitySquid['Squid'/1555202, l='MpServer', x=96,60, y=61,05, z=-161,40], EntityTippedArrow['Arrow'/1576740, l='MpServer', x=93,34, y=52,02, z=-183,97], EntitySkeleton['Skeleton'/1576284, l='MpServer', x=159,50, y=29,00, z=-108,50], EntityCreeper['Creeper'/1575235, l='MpServer', x=133,50, y=39,00, z=-91,50], EntityPlayerSP['rapus95'/1571378, l='MpServer', x=90,50, y=52,10, z=-188,50], EntityItem['item.item.shield'/1576830, l='MpServer', x=98,27, y=52,00, z=-188,88], EntityCreeper['Creeper'/1576319, l='MpServer', x=97,50, y=19,00, z=-161,50], EntityZombie['Zombie'/1576812, l='MpServer', x=160,50, y=42,00, z=-202,50], EntityItem['item.item.melon'/1572244, l='MpServer', x=91,04, y=47,00, z=-156,13], EntityCreeper['Creeper'/1576861, l='MpServer', x=134,18, y=46,00, z=-109,58], EntityZombie['Zombie'/1572241, l='MpServer', x=163,50, y=29,00, z=-178,50], EntitySkeleton['Skeleton'/1576862, l='MpServer', x=132,50, y=46,00, z=-111,50], EntityZombie['Zombie'/1572253, l='MpServer', x=164,50, y=41,00, z=-202,50], EntitySkeleton['Skeleton'/1576842, l='MpServer', x=45,50, y=20,00, z=-143,50], EntityCreeper['Creeper'/1577868, l='MpServer', x=153,50, y=20,00, z=-165,50], EntitySkeleton['Skeleton'/1577869, l='MpServer', x=158,50, y=16,00, z=-103,50], EntityCreeper['Creeper'/1576320, l='MpServer', x=97,50, y=19,00, z=-163,50], EntitySkeleton['Skeleton'/1576837, l='MpServer', x=165,50, y=38,00, z=-128,50], EntitySpider['Spider'/1577384, l='MpServer', x=29,72, y=92,00, z=-180,28], EntityCreeper['Creeper'/1575841, l='MpServer', x=100,96, y=41,00, z=-142,50], EntityZombie['Zombie'/1575330, l='MpServer', x=168,50, y=29,00, z=-206,50], EntityCreeper['Creeper'/1575843, l='MpServer', x=95,50, y=42,00, z=-141,50], EntitySkeleton['Skeleton'/1575844, l='MpServer', x=98,50, y=42,00, z=-140,50], EntitySpider['Spider'/1577382, l='MpServer', x=31,00, y=91,00, z=-186,05], EntityZombie['Zombie'/1576404, l='MpServer', x=152,50, y=43,00, z=-119,50], EntityZombie['Zombie'/1576905, l='MpServer', x=161,50, y=18,00, z=-224,50], EntityZombie['Zombie'/1576906, l='MpServer', x=161,50, y=18,00, z=-223,50], EntitySkeleton['Skeleton'/1573835, l='MpServer', x=91,45, y=54,00, z=-155,20], EntityZombie['Zombie'/1576907, l='MpServer', x=163,50, y=18,00, z=-223,50], EntityZombie['Zombie'/1576903, l='MpServer', x=153,50, y=29,00, z=-160,50], EntityCreeper['Creeper'/1576437, l='MpServer', x=165,50, y=18,00, z=-129,50]]
    Retry entities: 75 total; [EntityRobit['Richi=Penis'/1, l='MpServer', x=101,50, y=55,00, z=-184,50], EntityRobit['(??_?)'/2, l='MpServer', x=100,50, y=55,00, z=-184,25], EntityBat['Bat'/1577626, l='MpServer', x=144,51, y=42,63, z=-99,57], EntityItem['item.item.melon'/1572244, l='MpServer', x=91,04, y=47,00, z=-156,13], EntityRobit['Bonny'/3, l='MpServer', x=102,50, y=55,00, z=-184,50], EntityWitch['Witch'/1574555, l='MpServer', x=153,50, y=40,00, z=-95,50], EntityRobit['Kasper'/4, l='MpServer', x=103,50, y=55,00, z=-184,50], EntityCreeper['Creeper'/1576861, l='MpServer', x=134,18, y=46,00, z=-109,58], EntitySkeleton['Skeleton'/1576862, l='MpServer', x=132,50, y=46,00, z=-111,50], EntityZombie['Zombie'/1572241, l='MpServer', x=163,50, y=29,00, z=-178,50], EntityChicken['Chicken'/1571487, l='MpServer', x=96,61, y=66,00, z=-225,13], EntityZombie['Zombie'/1572253, l='MpServer', x=164,50, y=41,00, z=-202,50], EntityBat['Bat'/1576725, l='MpServer', x=143,43, y=45,05, z=-115,30], EntitySkeleton['Skeleton'/1577110, l='MpServer', x=105,50, y=63,00, z=-179,50], EntityEnderman['Enderman'/1573399, l='MpServer', x=146,50, y=28,00, z=-108,50], EntitySkeleton['Skeleton'/1577225, l='MpServer', x=118,50, y=67,00, z=-120,50], EntitySheep['Sheep'/1571461, l='MpServer', x=9,79, y=92,00, z=-227,81], EntitySkeleton['Skeleton'/1576842, l='MpServer', x=45,50, y=20,00, z=-143,50], EntitySquid['Squid'/1555203, l='MpServer', x=90,63, y=62,35, z=-165,77], EntityCreeper['Creeper'/1574412, l='MpServer', x=129,48, y=42,00, z=-208,18], EntityCreeper['Creeper'/1577868, l='MpServer', x=153,50, y=20,00, z=-165,50], EntitySquid['Squid'/1555202, l='MpServer', x=96,60, y=61,05, z=-161,40], EntitySkeleton['Skeleton'/1577869, l='MpServer', x=158,50, y=16,00, z=-103,50], EntityCreeper['Creeper'/1576320, l='MpServer', x=97,50, y=19,00, z=-163,50], EntityChicken['Chicken'/1571468, l='MpServer', x=41,20, y=86,00, z=-188,50], EntitySheep['Sheep'/1571467, l='MpServer', x=36,84, y=88,00, z=-189,16], EntitySheep['Sheep'/1571466, l='MpServer', x=40,26, y=87,00, z=-188,79], EntitySkeleton['Skeleton'/1576837, l='MpServer', x=165,50, y=38,00, z=-128,50], EntitySheep['Sheep'/1571465, l='MpServer', x=33,73, y=80,00, z=-169,48], EntityCreeper['Creeper'/1577530, l='MpServer', x=68,51, y=87,00, z=-210,16], EntityCreeper['Creeper'/1576635, l='MpServer', x=133,50, y=39,00, z=-92,50], EntityBat['Bat'/1575613, l='MpServer', x=150,84, y=13,86, z=-108,45], EntityCreeper['Creeper'/1572018, l='MpServer', x=166,50, y=28,00, z=-119,50], EntityChicken['Chicken'/1571376, l='MpServer', x=69,50, y=88,00, z=-218,09], EntityZombie['Husk'/1577520, l='MpServer', x=123,50, y=67,00, z=-117,50], EntitySkeleton['Skeleton'/1575473, l='MpServer', x=83,50, y=23,00, z=-231,31], EntityCreeper['Creeper'/1570878, l='MpServer', x=154,50, y=28,00, z=-120,50], EntitySkeleton['Skeleton'/1576627, l='MpServer', x=154,50, y=17,00, z=-155,50], EntitySkeleton['Skeleton'/1576628, l='MpServer', x=152,30, y=16,00, z=-155,52], EntitySpider['Spider'/1577384, l='MpServer', x=29,72, y=92,00, z=-180,28], EntityCreeper['Creeper'/1577632, l='MpServer', x=86,50, y=51,00, z=-227,50], EntitySquid['Squid'/1571374, l='MpServer', x=58,48, y=60,58, z=-180,41], EntityCreeper['Creeper'/1575841, l='MpServer', x=100,96, y=41,00, z=-142,50], EntityChicken['Chicken'/1571886, l='MpServer', x=153,81, y=65,00, z=-163,57], EntityZombie['Zombie'/1575330, l='MpServer', x=168,50, y=29,00, z=-206,50], EntitySquid['Squid'/1571372, l='MpServer', x=64,24, y=62,08, z=-173,60], EntityCreeper['Creeper'/1575843, l='MpServer', x=95,50, y=42,00, z=-141,50], EntityTippedArrow['Arrow'/1576740, l='MpServer', x=93,34, y=52,02, z=-183,97], EntitySkeleton['Skeleton'/1575844, l='MpServer', x=98,50, y=42,00, z=-140,50], EntityCreeper['Creeper'/1574564, l='MpServer', x=164,50, y=29,00, z=-196,50], EntitySpider['Spider'/1577382, l='MpServer', x=31,00, y=91,00, z=-186,05], EntityZombie['Zombie'/1575974, l='MpServer', x=162,49, y=19,00, z=-225,20], EntityZombie['Zombie'/1571880, l='MpServer', x=158,50, y=19,00, z=-185,50], EntitySkeleton['Skeleton'/1576284, l='MpServer', x=159,50, y=29,00, z=-108,50], EntityTippedArrow['Arrow'/76, l='MpServer', x=95,13, y=64,64, z=-92,87], EntityZombie['Zombie'/1576404, l='MpServer', x=152,50, y=43,00, z=-119,50], EntityZombie['Zombie'/1576905, l='MpServer', x=161,50, y=18,00, z=-224,50], EntityZombie['Zombie'/1576906, l='MpServer', x=161,50, y=18,00, z=-223,50], EntitySkeleton['Skeleton'/1573835, l='MpServer', x=91,45, y=54,00, z=-155,20], EntityZombie['Zombie'/1576907, l='MpServer', x=163,50, y=18,00, z=-223,50], EntityItem['item.item.egg'/1576640, l='MpServer', x=153,26, y=65,00, z=-163,68], EntityTippedArrow['Arrow'/1576641, l='MpServer', x=96,73, y=52,05, z=-187,75], EntityCreeper['Creeper'/1576129, l='MpServer', x=130,50, y=45,00, z=-110,50], EntityCreeper['Creeper'/1575235, l='MpServer', x=133,50, y=39,00, z=-91,50], EntityZombie['Zombie'/1576903, l='MpServer', x=153,50, y=29,00, z=-160,50], EntitySpider['Spider'/1577208, l='MpServer', x=162,50, y=18,00, z=-114,50], EntityItem['item.item.shield'/1576830, l='MpServer', x=98,27, y=52,00, z=-188,88], EntityCreeper['Creeper'/1576319, l='MpServer', x=97,50, y=19,00, z=-161,50], EntityCreeper['Creeper'/1576437, l='MpServer', x=165,50, y=18,00, z=-129,50], EntityItem['item.item.egg'/1572473, l='MpServer', x=42,18, y=85,00, z=-187,77], EntityCreeper['Creeper'/1576684, l='MpServer', x=128,50, y=48,00, z=-158,50], EntityZombie['Zombie'/1576812, l='MpServer', x=160,50, y=42,00, z=-202,50], EntityBat['Bat'/1577198, l='MpServer', x=134,83, y=28,03, z=-154,12], EntityCreeper['Creeper'/1577569, l='MpServer', x=18,50, y=64,00, z=-117,50], EntityCreeper['Creeper'/1577571, l='MpServer', x=20,50, y=64,00, z=-111,50]]
    Server brand: fml,forge
    Server type: Non-integrated multiplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:498)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:392)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.10.2
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 291941432 bytes (278 MB) / 932073472 bytes (888 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
    FML: MCP 9.32 Powered by Forge 12.18.1.2088 Optifine OptiFine_1.10.2_HD_U_C3 9 mods loaded, 9 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJA  mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
    UCHIJA  FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.1.2088.jar) 
    UCHIJA  Forge{12.18.1.2088} [Minecraft Forge] (forge-1.10.2-12.18.1.2088.jar) 
    UCHIJA  inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
    UCHIJA  JEI{3.9.5.257} [Just Enough Items] (jei_1.10.2-3.9.5.257.jar) 
    UCHIJA  mcmultipart{1.2.0_74} [MCMultiPart] (MCMultiPart-experimental-1.2.0_74-universal.jar) 
    UCHIJA  Mekanism{9.2.0} [Mekanism] (Mekanism-1.10.2-9.2.0.292.jar) 
    UCHIJA  MekanismGenerators{9.2.0} [MekanismGenerators] (MekanismGenerators-1.10.2-9.2.0.292.jar) 
    UCHIJA  MekanismTools{9.2.0} [MekanismTools] (MekanismTools-1.10.2-9.2.0.292.jar) 
    Loaded coremods (and transformers): 
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
LoadingHook (Mekanism-1.10.2-9.2.0.292.jar)

    GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 372.70' Renderer: 'GeForce GTX 860M/PCIe/SSE2'
    Launched Version: 1.10.2-forge1.10.2-12.18.1.2088
    LWJGL: 2.9.4
    OpenGL: GeForce GTX 860M/PCIe/SSE2 GL version 4.5.0 NVIDIA 372.70, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

    Using VBOs: Yes
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Packs: 
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    CPU: 8x Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz
    OptiFine Version: OptiFine_1.10.2_HD_U_C3
    Render Distance Chunks: 8
    Mipmaps: 4
    Anisotropic Filtering: 1
    Antialiasing: 0
    Multitexture: false
    Shaders: null
    OpenGlVersion: 4.5.0 NVIDIA 372.70
    OpenGlRenderer: GeForce GTX 860M/PCIe/SSE2
    OpenGlVendor: NVIDIA Corporation
    CpuCount: 8
```

**Comment by 3Pixel** [comment]
we have the same crash here on our server: http://pastebin.com/uaB75HJM

**Comment by ProsperCraft** [comment]
Same client crashes here as well http://pastebin.com/Twa03V2h

**Comment by aidancbrady** [comment]
Should be fixed.
