### ISSUE TITLE
[1.10.2, bug, crashing/critical]

### ISSUE THREAD

**Issue by rapus95** [aidancbrady/Mekanism#3849]
happens (seemingly) randomly

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  LoadingHook (Mekanism-1.10.2-9.2.0.292.jar)
Contact their authors BEFORE contacting forge

// Quite honestly, I wouldn't worry myself about that.

Time: 30.09.16 01:39
Description: Tesselating block in world

java.util.ConcurrentModificationException
    at com.google.common.collect.HashBiMap$Itr.checkForConcurrentModification(HashBiMap.java:339)
    at com.google.common.collect.HashBiMap$Itr.hasNext(HashBiMap.java:345)
    at mcmultipart.multipart.MultipartContainer.getExtendedStates(MultipartContainer.java:484)
    at mcmultipart.block.BlockMultipartContainer.getExtendedState(BlockMultipartContainer.java:402)
    at mcmultipart.block.BlockMultipartContainer.getExtendedState(BlockMultipartContainer.java:66)
    at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:80)
    at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:278)
    at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(ChunkRenderWorker.java:119)
    at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(ChunkRenderWorker.java:47)
    at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
    at com.google.common.collect.HashBiMap$Itr.checkForConcurrentModification(HashBiMap.java:339)
    at com.google.common.collect.HashBiMap$Itr.hasNext(HashBiMap.java:345)
    at mcmultipart.multipart.MultipartContainer.getExtendedStates(MultipartContainer.java:484)
    at mcmultipart.block.BlockMultipartContainer.getExtendedState(BlockMultipartContainer.java:402)
    at mcmultipart.block.BlockMultipartContainer.getExtendedState(BlockMultipartContainer.java:66)

-- Block being tesselated --
Details:
    Block type: ID #218 (tile.null // mcmultipart.block.BlockMultipartContainer)
    Block data value: 0 / 0x0 / 0b0000
    Block location: World: (12,31,-87), Chunk: (at 12,1,9 in 0,-6; contains blocks 0,0,-96 to 15,255,-81), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
Stacktrace:
    at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:80)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['rapus95'/827287, l='MpServer', x=-0,58, y=38,86, z=-85,44]]
    Chunk stats: MultiplayerChunkCache: 441, 441
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 21649692 game time, 22775960 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 48 total; [EntityPigZombie['Zombie'/955404, l='MpServer', x=18,50, y=68,00, z=-9,50], EntityPigZombie['Zombie'/955402, l='MpServer', x=30,50, y=78,00, z=-92,81], EntityPigZombie['Zombie'/955143, l='MpServer', x=10,32, y=65,88, z=-16,94], EntityPigZombie['Zombie'/954883, l='MpServer', x=-52,50, y=37,00, z=-78,50], EntityPigZombie['Zombie'/955409, l='MpServer', x=4,50, y=46,00, z=-151,50], EntityPigZombie['Zombie'/955174, l='MpServer', x=-50,50, y=3,00, z=-155,50], EntityPlayerSP['rapus95'/827287, l='MpServer', x=-0,33, y=39,26, z=-85,39], EntityPigZombie['Zombie'/955455, l='MpServer', x=14,50, y=14,00, z=-131,50], EntityPigZombie['Zombie'/955452, l='MpServer', x=20,29, y=68,00, z=-6,48], EntityPigZombie['Zombie'/955450, l='MpServer', x=51,50, y=44,00, z=-81,50], EntityPigZombie['Zombie'/954934, l='MpServer', x=60,53, y=45,00, z=-96,29], EntityPigZombie['Zombie'/955189, l='MpServer', x=7,83, y=38,00, z=-80,31], EntityPigZombie['Zombie'/896305, l='MpServer', x=-8,49, y=56,00, z=-86,20], EntityPigZombie['Zombie'/896304, l='MpServer', x=7,36, y=55,00, z=-66,50], EntityPigZombie['Zombie'/896307, l='MpServer', x=-9,10, y=56,00, z=-84,52], EntityPigZombie['Zombie'/955203, l='MpServer', x=-28,50, y=12,00, z=-29,50], EntityPigZombie['Zombie'/955200, l='MpServer', x=71,50, y=117,00, z=-106,50], EntityPigZombie['Zombie'/955456, l='MpServer', x=11,50, y=71,00, z=-139,50], EntityPigZombie['Zombie'/955201, l='MpServer', x=-28,50, y=12,00, z=-29,50], EntityPigZombie['Zombie'/955613, l='MpServer', x=-41,50, y=10,00, z=-32,50], EntityPigZombie['Zombie'/955610, l='MpServer', x=49,53, y=14,00, z=-155,27], EntityPigZombie['Zombie'/955611, l='MpServer', x=26,78, y=37,00, z=-75,29], EntityPigZombie['Zombie'/955609, l='MpServer', x=54,22, y=14,00, z=-155,09], EntityPigZombie['Zombie'/954967, l='MpServer', x=-62,50, y=72,00, z=-138,50], EntityPigZombie['Zombie'/955348, l='MpServer', x=-26,50, y=49,00, z=-94,50], EntityPigZombie['Zombie'/955476, l='MpServer', x=7,50, y=65,88, z=-23,50], EntityPigZombie['Zombie'/955474, l='MpServer', x=4,50, y=65,88, z=-20,50], EntityPigZombie['Zombie'/954963, l='MpServer', x=63,23, y=45,00, z=-100,15], EntityPigZombie['Zombie'/955347, l='MpServer', x=-22,59, y=50,00, z=-84,30], EntityPigZombie['Zombie'/955475, l='MpServer', x=7,09, y=65,88, z=-26,15], EntityPigZombie['Zombie'/955472, l='MpServer', x=7,50, y=65,88, z=-19,50], EntityPigZombie['Zombie'/955630, l='MpServer', x=19,19, y=71,00, z=-69,50], EntityPigZombie['Zombie'/955628, l='MpServer', x=15,58, y=69,00, z=-73,31], EntityPigZombie['Zombie'/955629, l='MpServer', x=15,51, y=69,00, z=-72,30], EntityPigZombie['Zombie'/955115, l='MpServer', x=-59,50, y=37,00, z=-23,50], EntityPigZombie['Zombie'/955627, l='MpServer', x=14,50, y=69,00, z=-74,50], EntityPigZombie['Zombie'/955368, l='MpServer', x=-51,50, y=37,00, z=-78,50], EntityPigZombie['Zombie'/955625, l='MpServer', x=-73,53, y=33,00, z=-16,78], EntityPigZombie['Zombie'/955622, l='MpServer', x=-66,77, y=33,00, z=-25,50], EntityPigZombie['Zombie'/955364, l='MpServer', x=-48,50, y=37,00, z=-82,50], EntityPigZombie['Zombie'/955109, l='MpServer', x=-19,81, y=57,00, z=-45,51], EntityPigZombie['Zombie'/955621, l='MpServer', x=-78,50, y=33,00, z=-23,50], EntityPigZombie['Zombie'/955619, l='MpServer', x=-23,50, y=42,00, z=-133,50], EntityPigZombie['Zombie'/955360, l='MpServer', x=16,43, y=19,00, z=-162,76], EntityPigZombie['Zombie'/955646, l='MpServer', x=73,50, y=94,00, z=-23,50], EntityPigZombie['Zombie'/955128, l='MpServer', x=10,50, y=87,00, z=-159,50], EntityPigZombie['Zombie'/955129, l='MpServer', x=-42,50, y=47,00, z=-40,50], EntityPigZombie['Zombie'/955121, l='MpServer', x=-36,50, y=34,00, z=-86,50]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Non-integrated multiplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:498)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
    at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(ChunkRenderWorker.java:57)
    at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
    Minecraft Version: 1.10.2
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_91, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 819963736 bytes (781 MB) / 2040070144 bytes (1945 MB) up to 2040135680 bytes (1945 MB)
    JVM Flags: 7 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -Xms1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn1G
    IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
    FML: MCP 9.32 Powered by Forge 12.18.1.2094 Optifine OptiFine_1.10.2_HD_U_C3 9 mods loaded, 9 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJA  mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
    UCHIJA  FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.1.2094.jar) 
    UCHIJA  Forge{12.18.1.2094} [Minecraft Forge] (forge-1.10.2-12.18.1.2094.jar) 
    UCHIJA  inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
    UCHIJA  JEI{3.9.5.257} [Just Enough Items] (jei_1.10.2-3.9.5.257.jar) 
    UCHIJA  mcmultipart{1.2.0_74} [MCMultiPart] (MCMultiPart-experimental-1.2.0_74-universal.jar) 
    UCHIJA  Mekanism{9.2.0} [Mekanism] (Mekanism-1.10.2-9.2.0.292.jar) 
    UCHIJA  MekanismGenerators{9.2.0} [MekanismGenerators] (MekanismGenerators-1.10.2-9.2.0.292.jar) 
    UCHIJA  MekanismTools{9.2.0} [MekanismTools] (MekanismTools-1.10.2-9.2.0.292.jar) 
    Loaded coremods (and transformers): 
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
LoadingHook (Mekanism-1.10.2-9.2.0.292.jar)

    GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
    Launched Version: 1.10.2-forge1.10.2-12.18.1.2094
    LWJGL: 2.9.4
    OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
    GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

    Using VBOs: Yes
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Packs: 
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    CPU: 8x Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz
    OptiFine Version: OptiFine_1.10.2_HD_U_C3
    Render Distance Chunks: 10
    Mipmaps: 4
    Anisotropic Filtering: 1
    Antialiasing: 0
    Multitexture: false
    Shaders: null
    OpenGlVersion: 4.5.0 NVIDIA 372.70
    OpenGlRenderer: GeForce GTX 860M/PCIe/SSE2
    OpenGlVendor: NVIDIA Corporation
    CpuCount: 8
```

**Comment by VT-14** [comment]
Looks like a render crash (.renderer. in the stack trace), and you have Optifine.  Most mods don't support Optifine due to it making unexpected changes to vanilla rendering so frequently and/or majorly that they simply can't keep up with it.
