### ISSUE TITLE
1.10.2 Server Crash mekanism.common.tile.component.TileComponentConfig.getSidesForData(

### ISSUE THREAD

**Issue by ProsperCraft** [aidancbrady/Mekanism#3859]
Multiplayer server, don't know what the players were doing to cause this.

http://pastebin.com/5t7sr806

Versions in the crash report.

java.lang.Error
    at java.util.EnumSet.noneOf(EnumSet.java:115)
    at mekanism.common.tile.component.TileComponentConfig.getSidesForData(TileComponentConfig.java:69)
    at mekanism.common.tile.TileEntityFactory.getConsumingSides(TileEntityFactory.java:423)
    at mekanism.common.tile.TileEntityElectricBlock.canReceiveEnergy(TileEntityElectricBlock.java:369)
    at mekanism.common.base.EnergyAcceptorWrapper$MekanismAcceptor.canReceiveEnergy(EnergyAcceptorWrapper.java:80)
    at mekanism.common.EnergyNetwork.getAcceptors(EnergyNetwork.java:222)
    at mekanism.common.EnergyNetwork.doEmit(EnergyNetwork.java:157)
    at mekanism.common.EnergyNetwork.tickEmit(EnergyNetwork.java:125)
    at mekanism.common.EnergyNetwork.onUpdate(EnergyNetwork.java:278)
    at mekanism.api.transmitters.DynamicNetwork.tick(DynamicNetwork.java:344)
    at mekanism.api.transmitters.TransmitterNetworkRegistry.tickEnd(TransmitterNetworkRegistry.java:108)
    at mekanism.api.transmitters.TransmitterNetworkRegistry.onTick(TransmitterNetworkRegistry.java:94)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_858_TransmitterNetworkRegistry_onTick_ServerTickEvent.invoke(.dynamic)

**Comment by aidancbrady** [comment]
Fixed for 1.11.2
