### ISSUE TITLE
Player disconnect on trying to connect to server 1.7.10

### ISSUE THREAD

**Issue by cauliflower69** [aidancbrady/Mekanism#3872]
http://requiemofapickaxe.com/modpack/fml-server-latest.log

That's a direct link to the latest log 

[Server thread/ERROR] [FML/]: SimpleChannelHandlerWrapper exception
java.lang.NullPointerException
    at mekanism.generators.common.tile.turbine.TileEntityTurbineCasing.getMaxEnergy(TileEntityTurbineCasing.java:150) ~[TileEntityTurbineCasing.class:?]
    at mcjty.rftools.apideps.MekanismCompatibility.getMaxEnergyLevel(MekanismCompatibility.java:18) ~[MekanismCompatibility.class:?]
    at mcjty.rftools.varia.EnergyTools.getEnergyLevelMulti(EnergyTools.java:66) ~[EnergyTools.class:?]
    at mcjty.rftools.blocks.screens.modules.EnergyBarScreenModule.getData(EnergyBarScreenModule.java:31) ~[EnergyBarScreenModule.class:?]
    at mcjty.rftools.blocks.screens.ScreenTileEntity.getScreenData(ScreenTileEntity.java:490) ~[ScreenTileEntity.class:?]
    at mcjty.rftools.blocks.screens.network.PacketGetScreenData.onMessage(PacketGetScreenData.java:54) ~[PacketGetScreenData.class:?]
    at mcjty.rftools.blocks.screens.network.PacketGetScreenData.onMessage(PacketGetScreenData.java:13) ~[PacketGetScreenData.class:?]
    at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:37) ~[SimpleChannelHandlerWrapper.class:?]
    at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:17) ~[SimpleChannelHandlerWrapper.class:?]
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:101) [SimpleChannelInboundHandler.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:101) [SimpleChannelInboundHandler.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:101) [SimpleChannelInboundHandler.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [MessageToMessageDecoder.class:?]
    at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [MessageToMessageCodec.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
    at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
    at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
    at fastcraft.at.a(F:978) [fastcraft-1.23.jar:?]
    at fastcraft.H.aq(F:36) [fastcraft-1.23.jar:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[22:03:55] [Server thread/ERROR] [FML/]: SimpleChannelHandlerWrapper exception

That or similar is being spammed on the log

**Comment by cauliflower69** [comment]
Nbtedit the login coords to 0 0 fixed the issue if anyone experiences similar
