### ISSUE TITLE
cpu load and some warning messages

### ISSUE THREAD

**Issue by tymop** [aidancbrady/Mekanism#3878]
Hello, I have a problem:
When mekanism is activated on my server, with a map containing some circuits, the CPU load reach 99% (only for the minecraft application)

additionaly, during the loading of the server, I have some messages like that:
`[11:26:09] [Server thread/WARN] [FML/]: * **The modid Mekanism is not the same as it's lowercase version. Lowercasing will be enforced in 1.11**
[11:26:09] [Server thread/WARN] [FML/]: *  at net.minecraftforge.fml.common.FMLModContainer.sanityCheckModId(FMLModContainer.java:139)
[11:26:09] [Server thread/WARN] [FML/]: *  at net.minecraftforge.fml.common.FMLModContainer.<init>(FMLModContainer.java:124)
[11:26:09] [Server thread/WARN] [FML/]: *  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[11:26:09] [Server thread/WARN] [FML/]: *  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[11:26:09] [Server thread/WARN] [FML/]: *  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[11:26:09] [Server thread/WARN] [FML/]: *  at java.lang.reflect.Constructor.newInstance(Constructor.java:423)...`
## Why is my CPU overloaded ?

 Now, it is so loaded than it is impossible to login on the server.

more informations:
CPUconfig:
`processor  : 0
vendor_id   : AuthenticAMD
cpu family  : 15
model       : 127
model name  : AMD Sempron(tm) Processor LE-1250
stepping    : 2
cpu MHz     : 2200.000
cache size  : 512 KB
physical id : 0
siblings    : 1
core id     : 0
cpu cores   : 1
apicid      : 0
initial apicid  : 0
fpu     : yes
fpu_exception   : yes
cpuid level : 1
wp      : yes
flags       : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 syscall nx mmxext fxsr_opt rdtscp lm 3dnowext 3dnow rep_good nopl extd_apicid pni cx16 lahf_lm extapic cr8_legacy 3dnowprefetch vmmcall
bugs        : apic_c1e fxsave_leak sysret_ss_attrs
bogomips    : 4420.25
TLB size    : 1024 4K pages
clflush size    : 64
cache_alignment : 64
address sizes   : 40 bits physical, 48 bits virtual
power management: ts fid vid ttp tm stc 100mhzsteps`

Full datalog of the server : [log](http://paste.ee/r/uWeFR)

**Comment by jburrows82** [comment]
Remove sponge and compare results without it.

**Comment by tymop** [comment]
I already tried. It reduce thé  load of some percent (around 10%).  
So i could play on the server. I walked all around the World where there are some Mekanism machin, i used them, and all was good; no problème.

Then, I added some pump, and à Solar évaporation plant. At this moment, the cpu load reached the 100%, and i am now unable to login on the server .

**Comment by tymop** [comment]
I also tried without Mekanism. The cpu load is around 8%
I tried a new World with Mekanism = 50%

**Comment by aidancbrady** [comment]
1.11.2 should help fix this.
