### ISSUE TITLE
Mekanism and Extreme Reactor crash

### ISSUE THREAD

**Issue by worgenice** [aidancbrady/Mekanism#3891]
The game crash when i place a universal cable to a output reactor/turbin block (btw it's a multiblock) and i have only two mod in minecraft

---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingHook (Mekanism-1.10.2-9.2.0.292.jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 15/10/16 12:48
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
    at mekanism.common.multipart.PartSidedPipe.canConnectMutual(PartSidedPipe.java:473)
    at mekanism.common.multipart.PartSidedPipe.getPossibleTransmitterConnections(PartSidedPipe.java:225)
    at mekanism.common.multipart.PartSidedPipe.refreshConnections(PartSidedPipe.java:610)
    at mekanism.common.multipart.PartSidedPipe.func_73660_a(PartSidedPipe.java:187)
    at mekanism.common.multipart.PartTransmitter.func_73660_a(PartTransmitter.java:59)
    at mekanism.common.multipart.PartUniversalCable.func_73660_a(PartUniversalCable.java:144)
    at mcmultipart.block.TileMultipartContainer$Ticking.func_73660_a(TileMultipartContainer.java:311)
    at net.minecraft.world.World.func_72939_s(World.java:1804)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
    at java.lang.Thread.run(Unknown Source)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Thread: Server thread
Stacktrace:
    at mekanism.common.multipart.PartSidedPipe.canConnectMutual(PartSidedPipe.java:473)
    at mekanism.common.multipart.PartSidedPipe.getPossibleTransmitterConnections(PartSidedPipe.java:225)
    at mekanism.common.multipart.PartSidedPipe.refreshConnections(PartSidedPipe.java:610)
    at mekanism.common.multipart.PartSidedPipe.func_73660_a(PartSidedPipe.java:187)
    at mekanism.common.multipart.PartTransmitter.func_73660_a(PartTransmitter.java:59)
    at mekanism.common.multipart.PartUniversalCable.func_73660_a(PartUniversalCable.java:144)
    at mcmultipart.block.TileMultipartContainer$Ticking.func_73660_a(TileMultipartContainer.java:311)

-- Block entity being ticked --
Details:
    Name: mcmultipart:multipart.ticking // mcmultipart.block.TileMultipartContainer.Ticking
    Block type: ID #246 (tile.null // mcmultipart.block.BlockMultipartContainer)
    Block data value: 0 / 0x0 / 0b0000
    Block location: World: (-202,73,142), Chunk: (at 6,4,14 in -13,8; contains blocks -208,0,128 to -193,255,143), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Actual block type: ID #246 (tile.null // mcmultipart.block.BlockMultipartContainer)
    Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:1804)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619)

-- Affected level --
Details:
    Level name: New World
    All players: 1 total; [EntityPlayerMP['worgenice'/1044, l='New World', x=-203,45, y=73,00, z=142,94]]
    Chunk stats: ServerChunkCache: 507 Drop: 0
    Level seed: 3116485107172151441
    Level generator: ID 00 - default, ver 1. Features enabled: true
    Level generator options: 
    Level spawn location: World: (-220,64,240), Chunk: (at 4,4,0 in -14,15; contains blocks -224,0,240 to -209,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Level time: 472 game time, 472 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 39774 (now: false), thunder time: 24622 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
    at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
    Minecraft Version: 1.10.2
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_101, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 430353984 bytes (410 MB) / 958406656 bytes (914 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
    FML: MCP 9.32 Powered by Forge 12.18.2.2099 7 mods loaded, 7 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader](forge-1.10.2-12.18.2.2099.jar) 
    UCHIJAAAA   Forge{12.18.2.2099} [Minecraft Forge](forge-1.10.2-12.18.2.2099.jar) 
    UCHIJAAAA   zerocore{1.10.2-0.0.8.0} [Zero CORE](zerocore-1.10.2-0.0.8.0.jar) 
    UCHIJAAAA   bigreactors{0.4.5.17} [Extreme Reactors](ExtremeReactors-1.10.2-0.4.5.17.jar) 
    UCHIJAAAA   mcmultipart{1.2.0_74} [MCMultiPart](MCMultiPart-experimental-1.2.0_74-universal.jar) 
    UCHIJAAAA   Mekanism{9.2.0} [Mekanism](Mekanism-1.10.2-9.2.0.292.jar) 
    Loaded coremods (and transformers): 
LoadingHook (Mekanism-1.10.2-9.2.0.292.jar)

```
GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
Profiler Position: N/A (disabled)
Player Count: 1 / 8; [EntityPlayerMP['worgenice'/1044, l='New World', x=-203,45, y=73,00, z=142,94]]
Type: Integrated Server (map_client.txt)
Is Modded: Definitely; Client brand changed to 'fml,forge'
```

**Comment by hron84** [comment]
Do you attach the cable to the power tap blocks or the cable just barely touching a casing block? Could you please upload some screenshot about your reactor setup?

**Comment by worgenice** [comment]
Hey, so the crash happen when i attache an universal cable to the power block but it can touch the other block without crash

**Comment by scalda** [comment]
heres a video of it happening [https://www.youtube.com/watch?v=M4lAiLPUdSQ&feature=youtu.be](url)

**Comment by aidancbrady** [comment]
Should be fixed
