### ISSUE TITLE
Mekanism Paxel and a Werewolf

### ISSUE THREAD

**Issue by MeinKraft** [aidancbrady/Mekanism#3897]
Forge: 2107
Minecraft: 1.10.2
Mekanism: 1.10.2-9.2.0.292

So I attacked a Werewolf from DrZharks Mo Creatures mod using an Obsidian Paxel from Mekanism and the game crashed

thank you for your time and creating a great mod !

this is the error

[17:46:07] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.ClassCastException: **mekanism.tools.item.ItemMekanismPaxel cannot be cast to net.minecraft.item.ItemSword**
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_101]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_101]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
**Caused by: java.lang.ClassCastException: mekanism.tools.item.ItemMekanismPaxel cannot be cast to net.minecraft.item.ItemSword**
	at drzhark.mocreatures.entity.monster.MoCEntityWerewolf.func_70097_a(MoCEntityWerewolf.java:180) ~[MoCEntityWerewolf.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1293) ~[zs.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_71059_n(EntityPlayerMP.java:1226) ~[lu.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:1040) ~[me.class:?]
	at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:68) ~[iu.class:?]
	at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:12) ~[iu.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_101]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_101]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]

**Comment by Ricket** [comment]
This is a Mo Creatures bug. The Mo Creatures code is assuming the thing causing damage is a sword instead of a tool. They need to add an instanceof check, since the paxel derives from ItemTool, not ItemSword.
