### ISSUE TITLE
crash error induction casing mekanism

### ISSUE THREAD

**Issue by bloodybaron76** [aidancbrady/Mekanism#3912]
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 10/22/16 12:19 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
    at mekanism.common.multiblock.UpdateProtocol.loopThrough(UpdateProtocol.java:39)
    at mekanism.common.multiblock.UpdateProtocol.loopThrough(UpdateProtocol.java:232)
    at mekanism.common.multiblock.UpdateProtocol.loopThrough(UpdateProtocol.java:232)
    at mekanism.common.multiblock.UpdateProtocol.doUpdate(UpdateProtocol.java:439)
    at mekanism.common.tile.TileEntityMultiblock.update(TileEntityMultiblock.java:142)
    at mekanism.common.tile.TileEntityMultiblock.onUpdate(TileEntityMultiblock.java:96)
    at mekanism.common.tile.TileEntityInductionCasing.onUpdate(TileEntityInductionCasing.java:42)
    at mekanism.common.tile.TileEntityBasicBlock.func_145845_h(TileEntityBasicBlock.java:75)
    at net.minecraft.world.World.func_72939_s(World.java:1939)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at mekanism.common.multiblock.UpdateProtocol.loopThrough(UpdateProtocol.java:39)
    at mekanism.common.multiblock.UpdateProtocol.loopThrough(UpdateProtocol.java:232)
    at mekanism.common.multiblock.UpdateProtocol.loopThrough(UpdateProtocol.java:232)
    at mekanism.common.multiblock.UpdateProtocol.doUpdate(UpdateProtocol.java:439)
    at mekanism.common.tile.TileEntityMultiblock.update(TileEntityMultiblock.java:142)
    at mekanism.common.tile.TileEntityMultiblock.onUpdate(TileEntityMultiblock.java:96)
    at mekanism.common.tile.TileEntityInductionCasing.onUpdate(TileEntityInductionCasing.java:42)
    at mekanism.common.tile.TileEntityBasicBlock.func_145845_h(TileEntityBasicBlock.java:75)
    at net.minecraft.world.World.func_72939_s(World.java:1939)

-- Block entity being ticked --
Details:
    Name: InductionCasing // mekanism.common.tile.TileEntityInductionCasing
    Block type: ID #2254 (tile.BasicBlock2 // mekanism.common.block.BlockBasic)
    Block data value: 1 / 0x1 / 0b0001
    Block location: World: (578,24,1633), Chunk: (at 2,1,1 in 36,102; contains blocks 576,0,1632 to 591,255,1647), Region: (1,3; contains chunks 32,96 to 63,127, blocks 512,0,1536 to 1023,255,2047)
    Actual block type: ID #2254 (tile.BasicBlock2 // mekanism.common.block.BlockBasic)
    Actual block data value: 1 / 0x1 / 0b0001
Stacktrace:
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)

-- Affected level --
Details:
    Level name: world
    All players: 1 total; [EntityPlayerMP['X_warfighter_X'/346819, l='world', x=426.29, y=106.61, z=1437.25]]
    Chunk stats: ServerChunkCache: 1257 Drop: 0
    Level seed: -4322616782757223656
    Level generator: ID 00 - default, ver 1. Features enabled: true
    Level generator options: 
    Level spawn location: World: (-14,64,-127), Chunk: (at 2,4,1 in -1,-8; contains blocks -16,0,-128 to -1,255,-113), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
    Level time: 23592194 game time, 29092198 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 36381 (now: false), thunder time: 69415 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by celiandu61** [comment]
Me to since i increase the size of my inudction matrix

**Comment by bloodybaron76** [comment]
I found the problem with this issue , you'r induction need to be on only 1 chunk and not on the edge of 2 chunk .

Sorry for my bad english , i am not  ; )

**Comment by drysdan** [comment]
But the Matrix can be 18x18x18. That's bigger than a chunk...

**Comment by ktole1999** [comment]
just because it can be that size doesnt mean it will always work. I never build multiblock machines/storage across a chunk boundary for that reason.

**Comment by drysdan** [comment]
No criticism here, but if it wont reliably work across boundaries, why make it so it can be bigger?

**Comment by ktole1999** [comment]
because its not the mod thats breaking it. As you know minecraft doesnt always work as its supposed to. does that stop devs? No. You can have multi chunk reactors, fluid storage, etc. can it be done? yes. Is it advisable? depends on who you talk to. It is what it is.

**Comment by ktole1999** [comment]
if you cant get an 18x18x18 to work then dont build it
