### ISSUE TITLE
crashes on openning world

### ISSUE THREAD

**Issue by monkeybutt32** [aidancbrady/Mekanism#3916]
also made new world, and eventually crashes there also.
i can play at first fine. then game crashes. Happens randomly. Some times while walking.
But I notice it most when crafting mekanism parts on a tinker construct crafting table with large chest on side.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  IC2core (industrialcraft-2-2.6.92-ex110.jar)
  LoadingHook (Mekanism-1.10.2-9.2.0.292.jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 10/23/16 10:04 AM
Description: Rendering item

java.lang.IllegalStateException: Not building!
    at net.minecraft.client.renderer.VertexBuffer.func_178977_d(VertexBuffer.java:720)
    at net.minecraft.client.renderer.Tessellator.func_78381_a(SourceFile:21)
    at net.minecraft.client.renderer.RenderItem.func_175045_a(RenderItem.java:164)
    at net.minecraft.client.renderer.RenderItem.func_175036_a(RenderItem.java:135)
    at net.minecraft.client.renderer.RenderItem.func_180454_a(RenderItem.java:198)
    at net.minecraft.client.renderer.RenderItem.func_184390_a(RenderItem.java:439)
    at net.minecraft.client.renderer.RenderItem.func_184391_a(RenderItem.java:478)
    at net.minecraft.client.renderer.RenderItem.func_180450_b(RenderItem.java:467)
    at com.pvp.interfaces.InterfaceHandler.drawItemWithName(InterfaceHandler.java:962)
    at com.pvp.interfaces.InterfaceHandler.drawItemWithEnchants(InterfaceHandler.java:947)
    at com.pvp.interfaces.InterfaceHandler.drawCenteredArmour(InterfaceHandler.java:857)
    at com.pvp.interfaces.InterfaceHandler$2.drawInterface(InterfaceHandler.java:150)
    at com.pvp.interfaces.InterfaceHandler.drawInterfaces(InterfaceHandler.java:1063)
    at com.pvp.events.Events.drawPre(Events.java:79)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_77_Events_drawPre_Pre.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
    at net.minecraftforge.client.GuiIngameForge.pre(GuiIngameForge.java:884)
    at net.minecraftforge.client.GuiIngameForge.func_180479_a(GuiIngameForge.java:321)
    at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:140)
    at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1369)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Thread: Client thread
Stacktrace:
    at net.minecraft.client.renderer.VertexBuffer.func_178977_d(VertexBuffer.java:720)
    at net.minecraft.client.renderer.Tessellator.func_78381_a(SourceFile:21)
    at net.minecraft.client.renderer.RenderItem.func_175045_a(RenderItem.java:164)
    at net.minecraft.client.renderer.RenderItem.func_175036_a(RenderItem.java:135)
    at net.minecraft.client.renderer.RenderItem.func_180454_a(RenderItem.java:198)
    at net.minecraft.client.renderer.RenderItem.func_184390_a(RenderItem.java:439)

-- Item being rendered --
Details:
    Item Type: mekanism.common.multipart.ItemPartTransmitter@291bd851
    Item Aux: 8
    Item NBT: null
    Item Foil: false
Stacktrace:
    at net.minecraft.client.renderer.RenderItem.func_184391_a(RenderItem.java:478)
    at net.minecraft.client.renderer.RenderItem.func_180450_b(RenderItem.java:467)
    at com.pvp.interfaces.InterfaceHandler.drawItemWithName(InterfaceHandler.java:962)
    at com.pvp.interfaces.InterfaceHandler.drawItemWithEnchants(InterfaceHandler.java:947)
    at com.pvp.interfaces.InterfaceHandler.drawCenteredArmour(InterfaceHandler.java:857)
    at com.pvp.interfaces.InterfaceHandler$2.drawInterface(InterfaceHandler.java:150)
    at com.pvp.interfaces.InterfaceHandler.drawInterfaces(InterfaceHandler.java:1063)
    at com.pvp.events.Events.drawPre(Events.java:79)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_77_Events_drawPre_Pre.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
    at net.minecraftforge.client.GuiIngameForge.pre(GuiIngameForge.java:884)
    at net.minecraftforge.client.GuiIngameForge.func_180479_a(GuiIngameForge.java:321)
    at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:140)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['monkeybutt_32'/351, l='MpServer', x=211.90, y=11.33, z=332.18]]
    Chunk stats: MultiplayerChunkCache: 189, 189
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (144,64,256), Chunk: (at 0,4,0 in 9,16; contains blocks 144,0,256 to 159,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 6832349 game time, 7159402 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 59 total; [EntitySheep['Sheep'/133, l='MpServer', x=169.40, y=78.00, z=386.50], EntityBat['Bat'/261, l='MpServer', x=290.78, y=28.06, z=381.44], EntitySheep['Sheep'/134, l='MpServer', x=167.62, y=68.00, z=398.80], EntityBat['Bat'/267, l='MpServer', x=285.75, y=26.02, z=384.23], EntitySheep['Sheep'/147, l='MpServer', x=176.72, y=70.00, z=373.46], EntitySkeleton['Skeleton'/148, l='MpServer', x=181.50, y=27.00, z=388.50], EntitySheep['Sheep'/149, l='MpServer', x=183.31, y=62.23, z=404.66], EntitySheep['Sheep'/150, l='MpServer', x=181.98, y=62.10, z=401.12], EntitySkeleton['Skeleton'/171, l='MpServer', x=196.50, y=52.00, z=256.50], EntityItem['item.item.reeds'/172, l='MpServer', x=207.98, y=13.00, z=357.22], EntitySheep['Sheep'/173, l='MpServer', x=202.45, y=67.00, z=386.45], EntityCow['Cow'/179, l='MpServer', x=212.55, y=78.00, z=313.46], EntityCow['Cow'/180, l='MpServer', x=210.52, y=78.00, z=315.55], EntityCow['Cow'/181, l='MpServer', x=211.53, y=78.00, z=314.33], EntityCow['Cow'/182, l='MpServer', x=209.64, y=78.00, z=313.59], EntityCow['Cow'/183, l='MpServer', x=212.55, y=78.00, z=312.38], EntityCow['Cow'/184, l='MpServer', x=209.45, y=78.00, z=311.45], EntityCow['Cow'/185, l='MpServer', x=211.64, y=78.00, z=311.45], EntityCow['Cow'/186, l='MpServer', x=210.80, y=78.00, z=311.45], EntityCow['Cow'/187, l='MpServer', x=210.36, y=78.00, z=312.55], EntityCow['Cow'/188, l='MpServer', x=209.45, y=78.00, z=314.53], EntityCow['Cow'/189, l='MpServer', x=211.55, y=78.00, z=313.40], EntityCow['Cow'/190, l='MpServer', x=210.52, y=78.00, z=314.54], EntityCow['Cow'/191, l='MpServer', x=210.80, y=78.00, z=312.32], EntityCow['Cow'/192, l='MpServer', x=212.55, y=78.00, z=315.36], EntityCow['Cow'/193, l='MpServer', x=211.66, y=78.00, z=312.38], EntityCow['Cow'/194, l='MpServer', x=210.59, y=78.00, z=313.57], EntityCow['Cow'/195, l='MpServer', x=209.45, y=78.00, z=312.65], EntityCow['Cow'/196, l='MpServer', x=212.55, y=78.00, z=311.45], EntityCow['Cow'/197, l='MpServer', x=209.74, y=78.00, z=315.45], EntityCow['Cow'/198, l='MpServer', x=209.91, y=78.00, z=311.45], EntityCow['Cow'/199, l='MpServer', x=211.49, y=78.00, z=314.61], EntityCow['Cow'/200, l='MpServer', x=212.55, y=78.00, z=314.20], EntityCow['Cow'/201, l='MpServer', x=211.55, y=78.00, z=315.55], EntityCow['Cow'/202, l='MpServer', x=209.45, y=78.00, z=315.55], IndestructibleEntityItem['item.item.tconstruct.hatchet'/203, l='MpServer', x=221.88, y=4.00, z=339.88], IndestructibleEntityItem['item.item.tconstruct.broadsword'/204, l='MpServer', x=221.88, y=4.00, z=339.88], EntityItem['item.item.reeds'/205, l='MpServer', x=208.92, y=12.00, z=350.66], EntityItem['item.item.reeds'/206, l='MpServer', x=208.76, y=13.00, z=359.19], EntityItem['item.item.reeds'/207, l='MpServer', x=208.11, y=13.00, z=354.37], EntitySheep['Sheep'/208, l='MpServer', x=217.50, y=74.00, z=373.90], EntitySheep['Sheep'/209, l='MpServer', x=220.64, y=70.00, z=391.43], EntityCreeper['Creeper'/221, l='MpServer', x=237.50, y=7.00, z=389.50], EntitySheep['Sheep'/223, l='MpServer', x=231.70, y=65.00, z=404.50], EntityPlayerSP['monkeybutt_32'/351, l='MpServer', x=211.90, y=11.33, z=332.18], EntityZombie['Zombie'/232, l='MpServer', x=252.50, y=28.00, z=354.50], EntityPig['Pig'/237, l='MpServer', x=257.37, y=76.00, z=294.06], EntitySkeleton['Skeleton'/238, l='MpServer', x=270.50, y=23.00, z=371.50], EntityCreeper['Creeper'/239, l='MpServer', x=265.50, y=16.00, z=408.50], EntityCreeper['Creeper'/240, l='MpServer', x=263.50, y=16.00, z=408.50], EntitySkeleton['Skeleton'/113, l='MpServer', x=138.96, y=51.00, z=307.15], EntityCreeper['Creeper'/241, l='MpServer', x=265.50, y=16.00, z=408.50], EntitySkeleton['Skeleton'/114, l='MpServer', x=140.50, y=51.00, z=308.50], EntityChicken['Chicken'/115, l='MpServer', x=133.64, y=78.00, z=395.81], EntityChicken['Chicken'/116, l='MpServer', x=142.20, y=93.00, z=392.51], EntityPig['Pig'/249, l='MpServer', x=283.29, y=64.00, z=347.23], EntityCreeper['Creeper'/122, l='MpServer', x=147.50, y=43.00, z=296.50], EntitySkeleton['Skeleton'/250, l='MpServer', x=273.67, y=23.00, z=377.70], EntityBat['Bat'/251, l='MpServer', x=282.96, y=18.92, z=391.48]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:498)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:392)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.10.2
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_111, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 630393936 bytes (601 MB) / 1819803648 bytes (1735 MB) up to 3817865216 bytes (3641 MB)
    JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G
    IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
    FML: MCP 9.32 Powered by Forge 12.18.2.2107 Optifine OptiFine_1.10.2_HD_U_D1 16 mods loaded, 16 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader](forge-1.10.2-12.18.2.2107.jar) 
    UCHIJAAAA   Forge{12.18.2.2107} [Minecraft Forge](forge-1.10.2-12.18.2.2107.jar) 
    UCHIJAAAA   XaeroBetterPvP{1.11.1} [Better PVP Mod](BetterPvP_1.11.1_Forge_1.10.2.jar) 
    UCHIJAAAA   zerocore{1.10.2-0.0.8.0} [Zero CORE](zerocore-1.10.2-0.0.8.0.jar) 
    UCHIJAAAA   bigreactors{0.4.5.15} [Extreme Reactors](ExtremeReactors-1.10.2-0.4.5.15.jar) 
    UCHIJAAAA   IC2{2.6.92-ex110} [IndustrialCraft 2](industrialcraft-2-2.6.92-ex110.jar) 
    UCHIJAAAA   JEI{3.12.8.328} [Just Enough Items](jei_1.10.2-3.12.8.328.jar) 
    UCHIJAAAA   mantle{1.10.2-1.1.0.188} [Mantle](Mantle-1.10.2-1.1.0.jar) 
    UCHIJAAAA   mcmultipart{1.2.0_74} [MCMultiPart](MCMultiPart-experimental-1.2.0_74-universal.jar) 
    UCHIJAAAA   Mekanism{9.2.0} [Mekanism](Mekanism-1.10.2-9.2.0.292.jar) 
    UCHIJAAAA   MekanismGenerators{9.2.0} [MekanismGenerators](MekanismGenerators-1.10.2-9.2.0.292.jar) 
    UCHIJAAAA   MekanismTools{9.2.0} [MekanismTools](MekanismTools-1.10.2-9.2.0.292.jar) 
    UCHIJAAAA   tconstruct{1.10.2-2.5.6b.jenkins424} [Tinkers' Construct](TConstruct-1.10.2-2.5.6b.jar) 
    UCHIJAAAA   VeinMiner{0.34.1_1.9-73be663} [Vein Miner](VeinMiner-0.34.1-1.9r571+73be663.jar) 
    UCHIJAAAA   VeinMinerModSupport{0.34.1_1.9-73be663} [Mod Support](VeinMiner-0.34.1-1.9r571+73be663.jar) 
    Loaded coremods (and transformers): 
IC2core (industrialcraft-2-2.6.92-ex110.jar)

LoadingHook (Mekanism-1.10.2-9.2.0.292.jar)

```
GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 359.06' Renderer: 'GeForce 840M/PCIe/SSE2'
Pulsar/tconstruct loaded Pulses: 
    - TinkerCommons (Enabled/Forced)
    - TinkerWorld (Enabled/Not Forced)
    - TinkerTools (Enabled/Not Forced)
    - TinkerHarvestTools (Enabled/Forced)
    - TinkerMeleeWeapons (Enabled/Forced)
    - TinkerRangedWeapons (Enabled/Forced)
    - TinkerModifiers (Enabled/Forced)
    - TinkerSmeltery (Enabled/Not Forced)
    - TinkerGadgets (Enabled/Not Forced)
    - TinkerOredict (Enabled/Forced)
    - TinkerIntegration (Enabled/Forced)
    - TinkerFluids (Enabled/Forced)
    - TinkerMaterials (Enabled/Forced)
    - TinkerModelRegister (Enabled/Forced)

Launched Version: 1.10.2-forge1.10.2-12.18.2.2107
LWJGL: 2.9.4
OpenGL: GeForce 840M/PCIe/SSE2 GL version 4.5.0 NVIDIA 359.06, NVIDIA Corporation
GL Caps: Using GL 1.3 multitexturing.
```

Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

```
Using VBOs: Yes
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: 
Current Language: English (US)
Profiler Position: N/A (disabled)
CPU: 4x Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz
OptiFine Version: OptiFine_1.10.2_HD_U_D1
Render Distance Chunks: 7
Mipmaps: 4
Anisotropic Filtering: 1
Antialiasing: 0
Multitexture: false
Shaders: null
OpenGlVersion: 4.5.0 NVIDIA 359.06
OpenGlRenderer: GeForce 840M/PCIe/SSE2
OpenGlVendor: NVIDIA Corporation
CpuCount: 4
```

**Comment by aidancbrady** [comment]
Not Mekanism related
