### ISSUE TITLE
Crash on startup due to InductionCasing

### ISSUE THREAD

**Issue by Bysokar** [aidancbrady/Mekanism#3927]
Hi Aidan,

This is a 1.7.10 crash on the last official build. Just posting it here as an FYI as I know you dont support it.... it might be broken in newer builds also.

Regards,
Bysokar

---- Minecraft Crash Report ----
// My bad.

Time: 29/10/16 20:15
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
        at mekanism.common.multiblock.UpdateProtocol.loopThrough(UpdateProtocol.java:39)
        at mekanism.common.multiblock.UpdateProtocol.loopThrough(UpdateProtocol.java:232)
        at mekanism.common.multiblock.UpdateProtocol.loopThrough(UpdateProtocol.java:232)
        at mekanism.common.multiblock.UpdateProtocol.loopThrough(UpdateProtocol.java:232)
        at mekanism.common.multiblock.UpdateProtocol.doUpdate(UpdateProtocol.java:439)
        at mekanism.common.tile.TileEntityMultiblock.update(TileEntityMultiblock.java:142)
        at mekanism.common.tile.TileEntityMultiblock.onUpdate(TileEntityMultiblock.java:96)
        at mekanism.common.tile.TileEntityInductionCasing.onUpdate(TileEntityInductionCasing.java:42)
        at mekanism.common.tile.TileEntityBasicBlock.func_145845_h(TileEntityBasicBlock.java:75)
        at net.minecraft.world.World.func_72939_s(World.java:2548)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:673)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:976)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:831)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:683)
        at java.lang.Thread.run(Thread.java:745)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
        at mekanism.common.multiblock.UpdateProtocol.loopThrough(UpdateProtocol.java:39)
        at mekanism.common.multiblock.UpdateProtocol.loopThrough(UpdateProtocol.java:232)
        at mekanism.common.multiblock.UpdateProtocol.loopThrough(UpdateProtocol.java:232)
        at mekanism.common.multiblock.UpdateProtocol.loopThrough(UpdateProtocol.java:232)
        at mekanism.common.multiblock.UpdateProtocol.doUpdate(UpdateProtocol.java:439)
        at mekanism.common.tile.TileEntityMultiblock.update(TileEntityMultiblock.java:142)
        at mekanism.common.tile.TileEntityMultiblock.onUpdate(TileEntityMultiblock.java:96)
        at mekanism.common.tile.TileEntityInductionCasing.onUpdate(TileEntityInductionCasing.java:42)
        at mekanism.common.tile.TileEntityBasicBlock.func_145845_h(TileEntityBasicBlock.java:75)

-- Block entity being ticked --
Details:
        Name: InductionCasing // mekanism.common.tile.TileEntityInductionCasing
        Block type: ID #1321 (tile.BasicBlock2 // mekanism.common.block.BlockBasic)
        Block data value: 1 / 0x1 / 0b0001
        Block location: World: (-367,63,-241), Chunk: (at 1,3,15 in -23,-16; contains blocks -368,0,-256 to -353,255,-241), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
        Actual block type: ID #1321 (tile.BasicBlock2 // mekanism.common.block.BlockBasic)
        Actual block data value: 1 / 0x1 / 0b0001
Stacktrace:
        at net.minecraft.world.World.func_72939_s(World.java:2548)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:673)

**Comment by aidancbrady** [comment]
1.7.10 is no longer supported
