### ISSUE TITLE
NoSuchMethodException crashes game

### ISSUE THREAD

**Issue by Binero** [aidancbrady/Mekanism#3933]
Might or might not be related to #3924. Crashes game within minute when wearing jetpack. Not entirely positive the latter is significant. 

```
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: java.lang.NoSuchMethodException: mekanism.common.integration.TeslaIntegration.<init>(mekanism.common.base.IEnergyWrapper, net.minecraft.util.EnumFacing)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at java.lang.Class.getConstructor0(Class.java:3074)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at java.lang.Class.getConstructor(Class.java:1817)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at mekanism.common.capabilities.CapabilityWrapperManager.getWrapper(CapabilityWrapperManager.java:26)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at mekanism.common.tile.TileEntityElectricBlock.getCapability(TileEntityElectricBlock.java:455)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at mekanism.common.tile.TileEntityElectricPump.getCapability(TileEntityElectricPump.java:548)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at crazypants.enderio.power.tesla.TeslaAdapter.getCapability(TeslaAdapter.java:55)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at crazypants.enderio.power.tesla.TeslaAdapter.getPowerInterface(TeslaAdapter.java:41)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at crazypants.enderio.power.PowerHandlerUtil.getPowerInterface(PowerHandlerUtil.java:42)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at crazypants.enderio.conduit.power.PowerConduit.getExternalPowerReceptor(PowerConduit.java:458)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at crazypants.enderio.conduit.power.PowerConduit.canConnectToExternal(PowerConduit.java:404)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at crazypants.enderio.conduit.AbstractConduit.onNeighborBlockChange(AbstractConduit.java:526)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at crazypants.enderio.conduit.power.PowerConduit.onNeighborBlockChange(PowerConduit.java:343)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at crazypants.enderio.conduit.AbstractConduit.onNeighborChange(AbstractConduit.java:553)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at crazypants.enderio.conduit.TileConduitBundle.onNeighborChange(TileConduitBundle.java:331)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at crazypants.enderio.conduit.BlockConduitBundle.onNeighborChange(BlockConduitBundle.java:882)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at net.minecraft.world.World.func_175666_e(World.java:3750)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at net.minecraft.world.World.func_175690_a(World.java:2463)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at net.minecraft.world.chunk.Chunk.func_177424_a(Chunk.java:785)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at net.minecraft.world.World.func_175625_s(World.java:2402)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at net.minecraft.client.network.NetHandlerPlayClient.func_147263_a(NetHandlerPlayClient.java:724)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at net.minecraft.network.play.server.SPacketChunkData.func_148833_a(SourceFile:96)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at net.minecraft.network.play.server.SPacketChunkData.func_148833_a(SourceFile:18)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at net.minecraft.util.Util.func_181617_a(SourceFile:45)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1045)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at net.minecraft.client.main.Main.main(SourceFile:124)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at java.lang.reflect.Method.invoke(Method.java:483)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: java.lang.NoSuchMethodException: mekanism.common.integration.TeslaIntegration.<init>(mekanism.common.base.IEnergyWrapper, net.minecraft.util.EnumFacing)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at java.lang.Class.getConstructor0(Class.java:3074)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at java.lang.Class.getConstructor(Class.java:1817)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at mekanism.common.capabilities.CapabilityWrapperManager.getWrapper(CapabilityWrapperManager.java:26)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at mekanism.common.tile.TileEntityElectricBlock.getCapability(TileEntityElectricBlock.java:455)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at mekanism.common.tile.TileEntityElectricPump.getCapability(TileEntityElectricPump.java:548)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at crazypants.enderio.power.tesla.TeslaAdapter.getCapability(TeslaAdapter.java:55)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at crazypants.enderio.power.tesla.TeslaAdapter.getPowerInterface(TeslaAdapter.java:41)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at crazypants.enderio.power.PowerHandlerUtil.getPowerInterface(PowerHandlerUtil.java:42)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at crazypants.enderio.conduit.power.PowerConduit.getExternalPowerReceptor(PowerConduit.java:458)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at crazypants.enderio.conduit.power.PowerConduit.canConnectToExternal(PowerConduit.java:404)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at crazypants.enderio.conduit.AbstractConduit.onNeighborBlockChange(AbstractConduit.java:526)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at crazypants.enderio.conduit.power.PowerConduit.onNeighborBlockChange(PowerConduit.java:343)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at crazypants.enderio.conduit.AbstractConduit.onNeighborChange(AbstractConduit.java:553)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at crazypants.enderio.conduit.TileConduitBundle.onNeighborChange(TileConduitBundle.java:331)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at crazypants.enderio.conduit.BlockConduitBundle.onNeighborChange(BlockConduitBundle.java:882)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at net.minecraft.world.World.func_175666_e(World.java:3750)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at net.minecraft.world.World.func_175690_a(World.java:2463)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at net.minecraft.world.chunk.Chunk.func_177424_a(Chunk.java:785)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at net.minecraft.world.World.func_175625_s(World.java:2402)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at net.minecraft.client.network.NetHandlerPlayClient.func_147263_a(NetHandlerPlayClient.java:724)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at net.minecraft.network.play.server.SPacketChunkData.func_148833_a(SourceFile:96)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at net.minecraft.network.play.server.SPacketChunkData.func_148833_a(SourceFile:18)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at net.minecraft.util.Util.func_181617_a(SourceFile:45)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1045)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at net.minecraft.client.main.Main.main(SourceFile:124)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at java.lang.reflect.Method.invoke(Method.java:483)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: java.lang.NoSuchMethodException: mekanism.common.integration.TeslaIntegration.<init>(mekanism.common.base.IEnergyWrapper, net.minecraft.util.EnumFacing)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at java.lang.Class.getConstructor0(Class.java:3074)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at java.lang.Class.getConstructor(Class.java:1817)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at mekanism.common.capabilities.CapabilityWrapperManager.getWrapper(CapabilityWrapperManager.java:26)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at mekanism.common.tile.TileEntityElectricBlock.getCapability(TileEntityElectricBlock.java:455)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at mekanism.generators.common.tile.TileEntityAdvancedSolarGenerator.getCapability(TileEntityAdvancedSolarGenerator.java:80)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at crazypants.enderio.power.tesla.TeslaAdapter.getCapability(TeslaAdapter.java:55)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at crazypants.enderio.power.tesla.TeslaAdapter.getPowerInterface(TeslaAdapter.java:41)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at crazypants.enderio.power.PowerHandlerUtil.getPowerInterface(PowerHandlerUtil.java:42)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at crazypants.enderio.conduit.power.PowerConduit.getExternalPowerReceptor(PowerConduit.java:458)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at crazypants.enderio.conduit.power.PowerConduit.canConnectToExternal(PowerConduit.java:404)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at crazypants.enderio.conduit.AbstractConduit.onNeighborBlockChange(AbstractConduit.java:526)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at crazypants.enderio.conduit.power.PowerConduit.onNeighborBlockChange(PowerConduit.java:343)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at crazypants.enderio.conduit.AbstractConduit.onNeighborChange(AbstractConduit.java:553)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at crazypants.enderio.conduit.TileConduitBundle.onNeighborChange(TileConduitBundle.java:331)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at crazypants.enderio.conduit.BlockConduitBundle.onNeighborChange(BlockConduitBundle.java:882)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at net.minecraft.world.World.func_175666_e(World.java:3750)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at net.minecraft.world.World.func_175690_a(World.java:2463)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at net.minecraft.world.chunk.Chunk.func_177424_a(Chunk.java:785)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at net.minecraft.world.World.func_175625_s(World.java:2402)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at net.minecraft.client.network.NetHandlerPlayClient.func_147263_a(NetHandlerPlayClient.java:724)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at net.minecraft.network.play.server.SPacketChunkData.func_148833_a(SourceFile:96)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at net.minecraft.network.play.server.SPacketChunkData.func_148833_a(SourceFile:18)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at net.minecraft.util.Util.func_181617_a(SourceFile:45)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1045)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at net.minecraft.client.main.Main.main(SourceFile:124)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at java.lang.reflect.Method.invoke(Method.java:483)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[12:43:29] [Client thread/INFO] [STDERR]: [mekanism.common.capabilities.CapabilityWrapperManager:getWrapper:30]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by Binero** [comment]
Crash seems to happen when rendering solar generators or Jetpacks. It isn't instantly however. Solar generators crash the game not when placed down but only during crafting or while holding them.

**Comment by Binero** [comment]
Seems to crash not when holding the items but when they are placed in a TC Crafting Station. It's hard to diagnose because crashes aren't instant.
