### ISSUE TITLE
MC 1.10.2 Crashes when I try to break Universal Cables or Basic Logistical Transporters

### ISSUE THREAD

**Issue by clmurphy74** [aidancbrady/Mekanism#3935]
Am having the trouble stated in the title.  Other mods are installed through Curse App.

Here is the crash report for tonight's crash:   

---- Minecraft Crash Report ----

WARNING: coremods are present:
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.58-beta.jar)
  LoadingHook (Mekanism-1.10.2-9.2.0.292.jar)
Contact their authors BEFORE contacting forge

// I feel sad now :(

Time: 11/1/16 8:22 PM
Description: Rendering Block Entity

java.lang.NullPointerException: Rendering Block Entity
	at mekanism.common.multipart.ConnectionProperty.valueToString(ConnectionProperty.java:48)
	at mekanism.client.render.obj.TransmitterModel.func_188616_a(TransmitterModel.java:135)
	at net.minecraft.client.renderer.block.model.SimpleBakedModel$Builder.func_188645_a(SourceFile:119)
	at net.minecraft.client.renderer.block.model.SimpleBakedModel$Builder.<init>(SourceFile:102)
	at mcmultipart.client.multipart.MultipartContainerSpecialRenderer.renderBreaking(MultipartContainerSpecialRenderer.java:159)
	at mcmultipart.client.multipart.MultipartContainerSpecialRenderer.renderMultipartContainerAt(MultipartContainerSpecialRenderer.java:53)
	at mcmultipart.client.multipart.MultipartContainerSpecialRenderer$TileMultipartSpecialRenderer.renderTileEntityAt(MultipartContainerSpecialRenderer.java:202)
	at mcmultipart.client.multipart.MultipartContainerSpecialRenderer$TileMultipartSpecialRenderer.func_180535_a(MultipartContainerSpecialRenderer.java:197)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_178469_a(TileEntityRendererDispatcher.java:147)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:125)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:743)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1381)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1038)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at mekanism.common.multipart.ConnectionProperty.valueToString(ConnectionProperty.java:48)
	at mekanism.client.render.obj.TransmitterModel.func_188616_a(TransmitterModel.java:135)
	at net.minecraft.client.renderer.block.model.SimpleBakedModel$Builder.func_188645_a(SourceFile:119)
	at net.minecraft.client.renderer.block.model.SimpleBakedModel$Builder.<init>(SourceFile:102)
	at mcmultipart.client.multipart.MultipartContainerSpecialRenderer.renderBreaking(MultipartContainerSpecialRenderer.java:159)
	at mcmultipart.client.multipart.MultipartContainerSpecialRenderer.renderMultipartContainerAt(MultipartContainerSpecialRenderer.java:53)
	at mcmultipart.client.multipart.MultipartContainerSpecialRenderer$TileMultipartSpecialRenderer.renderTileEntityAt(MultipartContainerSpecialRenderer.java:202)
	at mcmultipart.client.multipart.MultipartContainerSpecialRenderer$TileMultipartSpecialRenderer.func_180535_a(MultipartContainerSpecialRenderer.java:197)

-- Block Entity Details --
Details:
	Name: mcmultipart:multipart.ticking // mcmultipart.block.TileMultipartContainer.Ticking
	Block type: ID #218 (tile.null // mcmultipart.block.BlockMultipartContainer)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-84,47,257), Chunk: (at 12,2,1 in -6,16; contains blocks -96,0,256 to -81,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Actual block type: ID #218 (tile.null // mcmultipart.block.BlockMultipartContainer)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_178469_a(TileEntityRendererDispatcher.java:147)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:125)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:743)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1381)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['AskingBard93116'/351, l='MpServer', x=-83.96, y=48.00, z=257.14]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 4198637 game time, 4344760 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 4 total; [EntityPlayerSP['AskingBard93116'/351, l='MpServer', x=-83.96, y=48.00, z=257.14], EntityChicken['Chicken'/120, l='MpServer', x=-160.87, y=69.00, z=225.55], EntityPig['Pig'/181, l='MpServer', x=-113.28, y=64.00, z=295.24], EntityZombie['Zombie'/38382, l='MpServer', x=-122.09, y=46.00, z=193.47]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:392)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 211711016 bytes (201 MB) / 1913651200 bytes (1825 MB) up to 1913651200 bytes (1825 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2048m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.32 Powered by Forge 12.18.2.2116 21 mods loaded, 21 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.2.2116.jar) 
	UCHIJAAAA	Forge{12.18.2.2116} [Minecraft Forge] (forge-1.10.2-12.18.2.2116.jar) 
	UCHIJAAAA	Baubles{1.3.0} [Baubles] (Baubles-1.10.2-1.3.0.jar) 
	UCHIJAAAA	endercore{1.10.2-0.4.1.58-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.58-beta.jar) 
	UCHIJAAAA	JEI{3.13.0.338} [Just Enough Items] (jei_1.10.2-3.13.0.338.jar) 
	UCHIJAAAA	EnderIO{1.10.2-3.0.1.125_beta} [Ender IO] (EnderIO-1.10.2-3.0.1.125_beta.jar) 
	UCHIJAAAA	mcmultipart{1.3.0} [MCMultiPart] (MCMultiPart-1.3.0-universal.jar) 
	UCHIJAAAA	ftbl{0.0.0} [FTBLib] (FTBLib-1.10.2-3.1.1.jar) 
	UCHIJAAAA	ftbu{0.0.0} [FTBUtilities] (FTBUtilities-1.10.2-3.1.1.jar) 
	UCHIJAAAA	journeymap{1.10.2-5.3.0b2} [JourneyMap] (journeymap-1.10.2-5.3.0b2-unlimited.jar) 
	UCHIJAAAA	jeresources{0.5.3.65} [Just Enough Resources] (JustEnoughResources-1.10.2-0.5.3.65.jar) 
	UCHIJAAAA	mantle{1.10.2-1.1.1.194} [Mantle] (Mantle-1.10.2-1.1.1.jar) 
	UCHIJAAAA	Mekanism{9.2.0} [Mekanism] (Mekanism-1.10.2-9.2.0.292.jar) 
	UCHIJAAAA	MekanismGenerators{9.2.0} [MekanismGenerators] (MekanismGenerators-1.10.2-9.2.0.292.jar) 
	UCHIJAAAA	MekanismTools{9.2.0} [MekanismTools] (MekanismTools-1.10.2-9.2.0.292.jar) 
	UCHIJAAAA	refinedstorage{1.2-beta5} [Refined Storage] (refinedstorage-1.2-beta5.jar) 
	UCHIJAAAA	rftools{5.57} [RFTools] (rftools-1.10-5.57.jar) 
	UCHIJAAAA	tconstruct{1.10.2-2.5.6b.jenkins424} [Tinkers' Construct] (TConstruct-1.10.2-2.5.6b.jar) 
	UCHIJAAAA	TinkersAddons{1.0.3} [Tinkers' Addons] (Tinkers' Addons-1.10.x-1.0.3.jar) 
	UCHIJAAAA	tinkertoolleveling{1.10.2-1.0.1.DEV.f5def58} [Tinkers Tool Leveling] (TinkerToolLeveling-1.10.2-1.0.1.jar) 
	Loaded coremods (and transformers): 
EnderCorePlugin (EnderCore-1.10.2-0.4.1.58-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
LoadingHook (Mekanism-1.10.2-9.2.0.292.jar)
  
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 15.201.1101.0' Renderer: 'AMD Radeon(TM) R5 Graphics'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	EnderIO: No known problems detected.
	Detailed RF API diagnostics:
                  * RF API class 'EnergyStorage' is loaded from: jar:file:/C:/Users/User/Documents/Curse/Minecraft/Instances/Mekanism/mods/Mekanism-1.10.2-9.2.0.292.jar!/cofh/api/energy/EnergyStorage.class
                  * RF API class 'IEnergyConnection' is loaded from: jar:file:/C:/Users/User/Documents/Curse/Minecraft/Instances/Mekanism/mods/Mekanism-1.10.2-9.2.0.292.jar!/cofh/api/energy/IEnergyConnection.class
                  * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/C:/Users/User/Documents/Curse/Minecraft/Instances/Mekanism/mods/Mekanism-1.10.2-9.2.0.292.jar!/cofh/api/energy/IEnergyContainerItem.class
                  * RF API class 'IEnergyHandler' is loaded from: jar:file:/C:/Users/User/Documents/Curse/Minecraft/Instances/Mekanism/mods/Mekanism-1.10.2-9.2.0.292.jar!/cofh/api/energy/IEnergyHandler.class
                  * RF API class 'IEnergyProvider' is loaded from: jar:file:/C:/Users/User/Documents/Curse/Minecraft/Instances/Mekanism/mods/Mekanism-1.10.2-9.2.0.292.jar!/cofh/api/energy/IEnergyProvider.class
                  * RF API class 'IEnergyReceiver' is loaded from: jar:file:/C:/Users/User/Documents/Curse/Minecraft/Instances/Mekanism/mods/Mekanism-1.10.2-9.2.0.292.jar!/cofh/api/energy/IEnergyReceiver.class
                  * RF API class 'IEnergyStorage' is loaded from: jar:file:/C:/Users/User/Documents/Curse/Minecraft/Instances/Mekanism/mods/Mekanism-1.10.2-9.2.0.292.jar!/cofh/api/energy/IEnergyStorage.class
                  * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/C:/Users/User/Documents/Curse/Minecraft/Instances/Mekanism/mods/Mekanism-1.10.2-9.2.0.292.jar!/cofh/api/energy/ItemEnergyContainer.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/C:/Users/User/Documents/Curse/Minecraft/Instances/Mekanism/mods/Mekanism-1.10.2-9.2.0.292.jar!/cofh/api/energy/TileEnergyHandler.class
	Detailed Tesla API diagnostics:
                  * Tesla API class 'Tesla' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.Tesla)
                  * Tesla API class 'TeslaCapabilities' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.capability.TeslaCapabilities)
                  * Tesla API class 'ITeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaConsumer)
                  * Tesla API class 'ITeslaHolder' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaHolder)
                  * Tesla API class 'ITeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaProducer)
                  * Tesla API class 'BaseTeslaContainer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainer)
                  * Tesla API class 'BaseTeslaContainerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainerProvider)
                  * Tesla API class 'InfiniteTeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumer)
                  * Tesla API class 'InfiniteTeslaConsumerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumerProvider)
                  * Tesla API class 'InfiniteTeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducer)
                  * Tesla API class 'InfiniteTeslaProducerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducerProvider)

	Launched Version: forge-12.18.2.2116
	LWJGL: 2.9.4
	OpenGL: AMD Radeon(TM) R5 Graphics GL version 4.5.13399 Compatibility Profile Context 15.201.1101.0, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x AMD A8-6410 APU with AMD Radeon R5 Graphics

**Comment by Alaberti** [comment]
I have this issue as well: http://pastebin.com/raw/3gtbRmKY. It happened directly after trying to break a Simple Covers hollow panel over an ultimate energy cable. Client crash only at least.

Mekanism 1.10.2-9.2.0.292
Multipart 1.3.0
Forge 2118
Simple Covers 0.4.1.14-mc1.10.2

**Comment by clmurphy74** [comment]
I don't know if it's related, but the Configurator is stuck on Items only mode.  The key bind to change it (changed from the default to another key that isn't taken by another mod) does not work.  Just fyi....

**Comment by RealGrep** [comment]
This seems to have appeared with the latest MCMultiPart update. Reverting to 1.2.1 and I can break them again without a crash. And I do notice you all have MCMP 1.3.0.

Perhaps @amadornes could pipe in here? Not sure if Mekanism merely needs something changed or fixed (in which case, it could be a while), or if maybe there's an issue in MCMP?

**Comment by ProsperCraft** [comment]
https://github.com/aidancbrady/Mekanism/issues/3887

**Comment by clmurphy74** [comment]
I've noticed a lot of other threads with the same issue and that it's being thought to be an issue with MCMP...  If so, is there a way, without reverting MCMP as other mods in this custom pack needs it, to fix this? I am still at .2118 and wondering if MCMP updated their code or not.  Should I try the latest MCMP version?

**Comment by amadornes** [comment]
Huh... I thought I said it here before, but I guess not...
Mekanism needs to update to support the new additions to blockstate support in MCMultiPart. I guess it was built on a relatively old version that didn't even support "actual states" (which are the ones it should be using), so that's a problem...

**Comment by RealGrep** [comment]
Thanks for the explanation, @amadornes . Yeah, that's indeed a huge problem. Darn. If I had the vaguest clue how to fix that, I would.
