### ISSUE TITLE
"java.lang.IllegalStateException: Not building!"

### ISSUE THREAD

**Issue by Polar891** [aidancbrady/Mekanism#3997]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  DepLoader (BrandonsCore-1.10.2-2.1.1.61-universal.jar)
  LoadingHook (Mekanism-1.10.2-9.2.0.294.jar)
  TransformerLoader (OpenComputers-MC1.10.2-1.6.0.4.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  llibrary (llibrary-1.7.1-1.10.2.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.4.3.124-universal.jar)
  DepLoader (CodeChickenCore-1.10.2-2.3.5.91-universal.jar)
Contact their authors BEFORE contacting forge

// I blame Dinnerbone.

Time: 11/22/16 12:00 AM
Description: Rendering item

java.lang.IllegalStateException: Not building!
	at net.minecraft.client.renderer.VertexBuffer.func_178977_d(VertexBuffer.java:720)
	at net.minecraft.client.renderer.Tessellator.func_78381_a(SourceFile:21)
	at net.minecraft.client.renderer.RenderItem.func_175045_a(RenderItem.java:164)
	at net.minecraft.client.renderer.RenderItem.func_175036_a(RenderItem.java:135)
	at net.minecraft.client.renderer.RenderItem.func_180454_a(RenderItem.java:198)
	at net.minecraft.client.renderer.RenderItem.func_184390_a(RenderItem.java:439)
	at net.minecraft.client.renderer.RenderItem.func_184391_a(RenderItem.java:478)
	at net.minecraft.client.gui.GuiIngame.func_184044_a(GuiIngame.java:1192)
	at net.minecraft.client.gui.GuiIngame.func_180479_a(GuiIngame.java:566)
	at net.minecraftforge.client.GuiIngameForge.func_180479_a(GuiIngameForge.java:329)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:140)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1370)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

I used a Tinkers Crafting station and inventory tweaks to put the required ingredients into the station which crashed my game.

**Comment by HyperBlueCore** [comment]
EVERYONE GETS THE SAME ERROR Come one Adian
my report
http://pastebin.com/YJJf6Z27

**Comment by ktole1999** [comment]
trying to understand the error. if it cant render is that the mods fault?

**Comment by aidancbrady** [comment]
This is a known interaction issue with the TC Crafting Station, I'm afraid there's not much I can do.
