### ISSUE TITLE
Game Crashes As soom as I load a world - plz help!

### ISSUE THREAD

**Issue by AryanVainala** [aidancbrady/Mekanism#4064]
Here's the Crash Report.

Time: 13/12/16 21:17
Description: Updating screen events

java.lang.NoSuchMethodError: net.minecraftforge.fluids.FluidStack.getFluidID()I
	at mekanism.common.item.ItemBlockMachine.setFluidStack(ItemBlockMachine.java:665)
	at mekanism.common.block.BlockMachine.func_149666_a(BlockMachine.java:473)
	at net.minecraft.item.ItemBlock.func_150895_a(ItemBlock.java:181)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147053_i(GuiContainerCreative.java:347)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147050_b(GuiContainerCreative.java:547)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146286_b(GuiContainerCreative.java:455)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:306)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146274_d(GuiContainerCreative.java:563)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1628)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at info.mineshafter.GameStarter.main(GameStarter.java:24)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at mekanism.common.item.ItemBlockMachine.setFluidStack(ItemBlockMachine.java:665)
	at mekanism.common.block.BlockMachine.func_149666_a(BlockMachine.java:473)
	at net.minecraft.item.ItemBlock.func_150895_a(ItemBlock.java:181)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147053_i(GuiContainerCreative.java:347)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147050_b(GuiContainerCreative.java:547)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146286_b(GuiContainerCreative.java:455)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:306)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146274_d(GuiContainerCreative.java:563)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiContainerCreative

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [GCEntityClientPlayerMP['monster66380'/114, l='MpServer', x=785.24, y=92.89, z=965.38]]
	Chunk stats: MultiplayerChunkCache: 733, 733
	Level seed: 0
	Level generator: ID 04 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (944,64,776), Chunk: (at 0,4,8 in 59,48; contains blocks 944,0,768 to 959,255,783), Region: (1,1; contains chunks 32,32 to 63,63, blocks 512,0,512 to 1023,255,1023)
	Level time: 95988 game time, 82960 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 1 total; [GCEntityClientPlayerMP['monster66380'/114, l='MpServer', x=785.24, y=92.89, z=965.38]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2432)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:909)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at info.mineshafter.GameStarter.main(GameStarter.java:24)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Mac OS X (x86_64) version 10.10.5
	Java Version: 1.7.0_80, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 151374312 bytes (144 MB) / 578813952 bytes (552 MB) up to 1029177344 bytes (981 MB)
	JVM Flags: 2 total; -Xmx1G -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 95
	FML: MCP v9.05 FML v7.10.18.1180 Minecraft Forge 10.13.0.1180 27 mods loaded, 27 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.18.1180} [Forge Mod Loader] (forge-1.7.10-10.13.0.1180.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.0.1180} [Minecraft Forge] (forge-1.7.10-10.13.0.1180.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	GalacticraftCore{3.0.12} [Galacticraft Core] (GalacticraftCore-1.7-3.0.12.375 (1).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	SpaceCore{4.1.9} [4Space Core] (4Space-4.1.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ExoCore{0.1.2} [4Space Exoplanets Core] (4Space-4.1.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ExoElipse{0.1.2} [4Space Exoplanets Elipse] (4Space-4.1.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	SpaceCallisto{4.1.9} [4Space Callisto] (4Space-4.1.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	SpaceEuropa{4.1.9} [4Space Europa] (4Space-4.1.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	SpaceVenus{4.1.9} [4Space Venus] (4Space-4.1.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	SpaceIo{4.1.9} [4Space Io] (4Space-4.1.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	SpaceMercury{4.1.9} [4Space Mercury] (4Space-4.1.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	SpacePluto{4.1.9} [4Space Pluto] (4Space-4.1.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BiomesOPlenty{2.0.2} [Biomes O' Plenty] (Biomes-O-Plenty-Mod-1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.12.375 (1).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	radixcore{1.3.0} [RadixCore] (RadixCore-1.3.0 MC-1.7.x.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	mca{4.1.1} [Minecraft Comes Alive] (MCA-4.1.1 MC-1.7.10 (1).zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ForgeMultipart{1.1.2.331} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Mekanism{8.1.9} [Mekanism] (Mekanism-1.7.10-8.1.9.265.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MekanismGenerators{8.1.9} [MekanismGenerators] (MekanismGenerators-1.7.10-8.1.9.265.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MekanismTools{8.1.9} [MekanismTools] (MekanismTools-1.7.10-8.1.9.265.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	cfm{3.4.7} [�9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.7(1.7.10).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	kitchen{1.3.22} [The Kitchen Mod] (TheKitchenMod-1.3.22-1.7.2-10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	TooMuchTNT{2.9} [TooMuchTNT] (Too-Much-TNT-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	McMultipart{1.1.2.331} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ForgeMicroblock{1.1.2.331} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.2.331-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Launched Version: 1.7.10-Forge10.13.0.1180
	LWJGL: 2.9.1
	OpenGL: Intel HD Graphics 4000 OpenGL Engine GL version 2.1 INTEL-10.6.33, Intel Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by bookerthegeek** [comment]
`9.1.0.281 for 1.7.10` is the latest version. You should update.

Also `Intel HD Graphics 4000 OpenGL Engine GL version` is an Issue, make sure to update video drivers.
