### ISSUE TITLE
Atomic Disassembler causing crash

### ISSUE THREAD

**Issue by Artemis-E** [aidancbrady/Mekanism#4075]
When attempting to break Advanced Universal Cable game immediately crashes.
Mekanism version 9.2.0.292
minecraft 1.10.2

Stacktrace:
	at mekanism.common.multipart.ConnectionProperty.valueToString(ConnectionProperty.java:48)
	at mekanism.client.render.obj.TransmitterModel.func_188616_a(TransmitterModel.java:135)
	at net.minecraft.client.renderer.block.model.SimpleBakedModel$Builder.func_188645_a(SourceFile:119)
	at net.minecraft.client.renderer.block.model.SimpleBakedModel$Builder.<init>(SourceFile:102)
	at mcmultipart.client.multipart.MultipartContainerSpecialRenderer.renderBreaking(MultipartContainerSpecialRenderer.java:159)
	at mcmultipart.client.multipart.MultipartContainerSpecialRenderer.renderMultipartContainerAt(MultipartContainerSpecialRenderer.java:53)
	at mcmultipart.client.multipart.MultipartContainerSpecialRenderer$TileMultipartSpecialRenderer.renderTileEntityAt(MultipartContainerSpecialRenderer.java:202)
	at mcmultipart.client.multipart.MultipartContainerSpecialRenderer$TileMultipartSpecialRenderer.func_180535_a(MultipartContainerSpecialRenderer.java:197)

**Comment by PJB3005** [comment]
Are you on the latest version of the mod?

**Comment by Artemis-E** [comment]
I realized after I posted I was not on the most current version. It's working now.
