### ISSUE TITLE
Dynamic Tank

### ISSUE THREAD

**Issue by sphynx1492** [aidancbrady/Mekanism#4112]
I am having some issues with the Dynamic Tank multiblock.  I can build a tank using Dynamic Tank blocks and Structural Glass blocks and the tank will form.  Once I try to add the Dynamic Tank Valve, however, the multiblock will not form.  Any suggestions would be great.

**Comment by ThatGamerBlue** [comment]
valves on the bottom and top only and not in corners

**Comment by sphynx1492** [comment]
Yup, tried that.

**Comment by ktole1999** [comment]
can you create tank in creative mode? what about if you use tank blocks instead of mixed. is there a requirement for where you can and cant place glass blocks?

**Comment by sphynx1492** [comment]
I tried an all tank block build in creative on my local computer, my friend tried on his, and we tried on our server.  No go on all, mixed or not mixed.

**Comment by ThatGamerBlue** [comment]
working fine for me - built latest from master http://i.imgur.com/0b9JHxC.png http://i.imgur.com/I9QxkZs.png

**Comment by sphynx1492** [comment]
Loaded up the latest update as of today, 9.2.1.298.  Still having issues, got this in a client log:

<details>
<summary>Click to expand log entry</summary>
[15:29:28] [Server thread/ERROR] [Mekanism/]: Unable to indirectly create tile entity.
[15:29:28] [Server thread/INFO] [STDERR/]: [mekanism.common.block.states.BlockStateBasic$BasicBlockType:create:190]: java.lang.NullPointerException
[15:29:28] [Server thread/INFO] [STDERR/]: [mekanism.common.block.states.BlockStateBasic$BasicBlockType:create:190]: 	at mekanism.common.tile.TileEntityDynamicValve.hasCapability(TileEntityDynamicValve.java:83)
[15:29:28] [Server thread/INFO] [STDERR/]: [mekanism.common.block.states.BlockStateBasic$BasicBlockType:create:190]: 	at net.drpmedieval.common.events.AttachCapabilityTileEntity.AttachCapability(AttachCapabilityTileEntity.java:16)
[15:29:28] [Server thread/INFO] [STDERR/]: [mekanism.common.block.states.BlockStateBasic$BasicBlockType:create:190]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_710_AttachCapabilityTileEntity_AttachCapability_TileEntity.invoke(.dynamic)
[15:29:28] [Server thread/INFO] [STDERR/]: [mekanism.common.block.states.BlockStateBasic$BasicBlockType:create:190]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[15:29:28] [Server thread/INFO] [STDERR/]: [mekanism.common.block.states.BlockStateBasic$BasicBlockType:create:190]: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
[15:29:28] [Server thread/INFO] [STDERR/]: [mekanism.common.block.states.BlockStateBasic$BasicBlockType:create:190]: 	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:565)
[15:29:28] [Server thread/INFO] [STDERR/]: [mekanism.common.block.states.BlockStateBasic$BasicBlockType:create:190]: 	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:545)
[15:29:28] [Server thread/INFO] [STDERR/]: [mekanism.common.block.states.BlockStateBasic$BasicBlockType:create:190]: 	at net.minecraft.tileentity.TileEntity.<init>(TileEntity.java:489)
[15:29:28] [Server thread/INFO] [STDERR/]: [mekanism.common.block.states.BlockStateBasic$BasicBlockType:create:190]: 	at mekanism.common.tile.TileEntityBasicBlock.<init>(TileEntityBasicBlock.java:38)
[15:29:28] [Server thread/INFO] [STDERR/]: [mekanism.common.block.states.BlockStateBasic$BasicBlockType:create:190]: 	at mekanism.common.tile.TileEntityContainerBlock.<init>(TileEntityContainerBlock.java:34)
[15:29:28] [Server thread/INFO] [STDERR/]: [mekanism.common.block.states.BlockStateBasic$BasicBlockType:create:190]: 	at mekanism.common.tile.TileEntityMultiblock.<init>(TileEntityMultiblock.java:56)
[15:29:28] [Server thread/INFO] [STDERR/]: [mekanism.common.block.states.BlockStateBasic$BasicBlockType:create:190]: 	at mekanism.common.tile.TileEntityDynamicTank.<init>(TileEntityDynamicTank.java:48)
[15:29:28] [Server thread/INFO] [STDERR/]: [mekanism.common.block.states.BlockStateBasic$BasicBlockType:create:190]: 	at mekanism.common.tile.TileEntityDynamicValve.<init>(TileEntityDynamicValve.java:21)
[15:29:28] [Server thread/INFO] [STDERR/]: [mekanism.common.block.states.BlockStateBasic$BasicBlockType:create:190]: 	at sun.reflect.GeneratedConstructorAccessor143.newInstance(Unknown Source)
[15:29:28] [Server thread/INFO] [STDERR/]: [mekanism.common.block.states.BlockStateBasic$BasicBlockType:create:190]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
</details>

**Comment by ThatGamerBlue** [comment]
Capability errors apparently. Will fix soon ^tm

**Comment by thiakil** [comment]
While there is a null pointer in Mek for worldObject, Dark-Roleplay-Medieval seems to be doing weird things, it adds an event handler to inject capabilities, and INSIDE that handler is runs hasCapability; BEFORE the TE is actually been initialised fully (it would seem).

It's also adding its own capability for its own TE, which is already does in the proper way in the TE class, confusingly enough.

**Comment by StimeyDman** [comment]
I have built and rebuilt this tank at least 20 times. Im pulling out hair now.
