### ISSUE TITLE
[Crash] Tesla support?

### ISSUE THREAD

**Issue by roboderpy** [aidancbrady/Mekanism#4123]
Server crashes when you try to connect EnderIO energy conduit to Mekanism machinery with Tesla installed.
```
Description: Exception in server tick loop

java.lang.ClassCastException: mekanism.common.multipart.PartUniversalCable cannot be cast to net.darkhax.tesla.api.ITeslaConsumer
	at crazypants.enderio.power.tesla.TeslaAdapter.getCapability(TeslaAdapter.java:59)
	at crazypants.enderio.power.tesla.TeslaAdapter.getPowerInterface(TeslaAdapter.java:41)
	at crazypants.enderio.power.PowerHandlerUtil.getPowerInterface(PowerHandlerUtil.java:42)
	at crazypants.enderio.conduit.power.PowerConduit.getExternalPowerReceptor(PowerConduit.java:460)
	at crazypants.enderio.conduit.power.PowerConduit.canConnectToExternal(PowerConduit.java:406)
	at crazypants.enderio.conduit.AbstractConduit.onNeighborBlockChange(AbstractConduit.java:522)
	at crazypants.enderio.conduit.power.PowerConduit.onNeighborBlockChange(PowerConduit.java:345)
	at crazypants.enderio.conduit.AbstractConduit.onNeighborChange(AbstractConduit.java:549)
	at crazypants.enderio.conduit.TileConduitBundle.onNeighborChange(TileConduitBundle.java:336)
	at crazypants.enderio.conduit.BlockConduitBundle.onNeighborChange(BlockConduitBundle.java:912)
	at net.minecraft.world.World.func_175666_e(World.java:3750)
	at net.minecraft.tileentity.TileEntity.func_70296_d(TileEntity.java:167)
	at mekanism.common.tile.TileEntityBasicBlock.onChunkLoad(TileEntityBasicBlock.java:106)
	at mekanism.common.Mekanism.onChunkLoad(Mekanism.java:1515)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_205_Mekanism_onChunkLoad_Load.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraft.world.chunk.Chunk.func_76631_c(Chunk.java:847)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:104)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:115)
	at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:86)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:132)
	at net.minecraft.world.World.func_72964_e(World.java:303)
	at net.minecraft.world.World.func_175726_f(World.java:298)
	at net.minecraft.world.World.func_175625_s(World.java:2402)
	at crazypants.enderio.conduit.power.PowerConduit.getExternalPowerReceptor(PowerConduit.java:453)
	at crazypants.enderio.conduit.power.PowerConduit.canConnectToExternal(PowerConduit.java:406)
	at crazypants.enderio.conduit.AbstractConduit.onNeighborBlockChange(AbstractConduit.java:522)
	at crazypants.enderio.conduit.power.PowerConduit.onNeighborBlockChange(PowerConduit.java:345)
	at crazypants.enderio.conduit.AbstractConduit.onNeighborChange(AbstractConduit.java:549)
	at crazypants.enderio.conduit.TileConduitBundle.onNeighborChange(TileConduitBundle.java:336)
	at crazypants.enderio.conduit.BlockConduitBundle.onNeighborChange(BlockConduitBundle.java:912)
	at net.minecraft.world.World.func_175666_e(World.java:3750)
	at net.minecraft.tileentity.TileEntity.func_70296_d(TileEntity.java:167)
	at mekanism.common.tile.TileEntityBasicBlock.onChunkLoad(TileEntityBasicBlock.java:106)
	at mekanism.common.Mekanism.onChunkLoad(Mekanism.java:1515)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_205_Mekanism_onChunkLoad_Load.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraft.world.chunk.Chunk.func_76631_c(Chunk.java:847)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:104)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:115)
	at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:86)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:132)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:298)
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:268)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:266)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by ThatGamerBlue** [comment]
Possibly a bug in ender io. Did you report it there?

**Comment by roboderpy** [comment]
Because `mekanism.common.multipart.PartUniversalCable cannot be cast to net.darkhax.tesla.api.ITeslaConsumer`. That means Mekanism Cable can't be used as Tesla energy consumer

**Comment by thommy101** [comment]
Do you have a whole crash report and a how to reproduce (preferably with an image)? I can't replicate it with the following setup: 
http://imgur.com/6uxflCz

Using:
Mekanism 1.10.2-9.2.1.295
EnderIO 1.10.2-3.1.156
EnderCore 1.10.2-0.4.1.62-beta
MCMultiPart 1.3.0
Tesla 1.10.2-1.2.1.49

**Comment by roboderpy** [comment]
[crash-2017-01-04_13.42.35-server.txt](https://github.com/aidancbrady/Mekanism/files/684675/crash-2017-01-04_13.42.35-server.txt)

**Comment by roboderpy** [comment]
god. Builds on GitHub TESLA API link is very old. Fixed with build 50.

**Comment by roboderpy** [comment]
@thommy101 But there is still another problem - #4116
