### ISSUE TITLE
mekanism crash

### ISSUE THREAD

**Issue by dritz56** [aidancbrady/Mekanism#4126]
all of a sudden mekanism has stopped working for me when i try to load a world. i dont get a normal crash report like other.

[18:25:50] [Client thread/INFO] [STDERR]: [mekanism.client.render.ctm.CTMModelFactory:func_188616_a:88]: 	at java.lang.reflect.Method.invoke(Method.java:483)
[18:25:50] [Client thread/INFO] [STDERR]: [mekanism.client.render.ctm.CTMModelFactory:func_188616_a:88]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[18:25:50] [Client thread/INFO] [STDERR]: [mekanism.client.render.ctm.CTMModelFactory:func_188616_a:88]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[18:25:50] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: Caused by: java.lang.NullPointerException
[18:25:50] [Client thread/INFO] [STDERR]: [mekanism.client.render.ctm.CTMModelFactory:func_188616_a:88]: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException
[18:25:50] [Client thread/INFO] [STDERR]: [mekanism.client.render.ctm.CTMModelFactory:func_188616_a:88]: 	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201)
[18:25:50] [Client thread/INFO] [STDERR]: [mekanism.client.render.ctm.CTMModelFactory:func_188616_a:88]: 	at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
[18:25:50] [Client thread/INFO] [STDERR]: [mekanism.client.render.ctm.CTMModelFactory:func_188616_a:88]: 	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4736)
[18:25:50] [Client thread/INFO] [STDERR]: [mekanism.client.render.ctm.CTMModelFactory:func_188616_a:88]: 	at mekanism.client.render.ctm.CTMModelFactory.func_188616_a(CTMModelFactory.java:81)
[18:25:50] [Client thread/INFO] [STDERR]: [mekanism.client.render.ctm.CTMModelFactory:func_188616_a:88]: 	at journeymap.client.forge.helper.ColorHelper.getFirstFoundSprite(ColorHelper.java:172)
[18:25:50] [Client thread/INFO] [STDERR]: [mekanism.client.render.ctm.CTMModelFactory:func_188616_a:88]: 	at journeymap.client.forge.helper.ColorHelper.getDirectIcon(ColorHelper.java:162)
[18:25:50] [Client thread/INFO] [STDERR]: [mekanism.client.render.ctm.CTMModelFactory:func_188616_a:88]: 	at journeymap.client.forge.helper.ColorHelper.getTextureColor(ColorHelper.java:110)
[18:25:50] [Client thread/INFO] [STDERR]: [mekanism.client.render.ctm.CTMModelFactory:func_188616_a:88]: 	at journeymap.client.model.mod.vanilla.VanillaColorHandler.getTextureColor(VanillaColorHandler.java:24)
[18:25:50] [Client thread/INFO] [STDERR]: [mekanism.client.render.ctm.CTMModelFactory:func_188616_a:88]: 	at journeymap.client.model.BlockMD.ensureColor(BlockMD.java:408)
[18:25:50] [Client thread/INFO] [STDERR]: [mekanism.client.render.ctm.CTMModelFactory:func_188616_a:88]: 	at journeymap.client.cartography.ColorManager.initBlockColors(ColorManager.java:193)
[18:25:50] [Client thread/INFO] [STDERR]: [mekanism.client.render.ctm.CTMModelFactory:func_188616_a:88]: 	at journeymap.client.cartography.ColorManager.ensureCurrent(ColorManager.java:130)
[18:25:50] [Client thread/INFO] [STDERR]: [mekanism.client.render.ctm.CTMModelFactory:func_188616_a:88]: 	at journeymap.client.task.main.EnsureCurrentColorsTask.perform(EnsureCurrentColorsTask.java:15)
[18:25:50] [Client thread/INFO] [STDERR]: [mekanism.client.render.ctm.CTMModelFactory:func_188616_a:88]: 	at journeymap.client.task.main.MainTaskController.performTasks(MainTaskController.java:64)
[18:25:50] [Client thread/INFO] [STDERR]: [mekanism.client.render.ctm.CTMModelFactory:func_188616_a:88]: 	at journeymap.client.JourneymapClient.performMainThreadTasks(JourneymapClient.java:568)
[18:25:50] [Client thread/INFO] [STDERR]: [mekanism.client.render.ctm.CTMModelFactory:func_188616_a:88]: 	at journeymap.client.forge.event.StateTickHandler.onClientTick(StateTickHandler.java:86)
[18:25:50] [Client thread/INFO] [STDERR]: [mekanism.client.render.ctm.CTMModelFactory:func_188616_a:88]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_99_StateTickHandler_onClientTick_ClientTickEvent.invoke(.dynamic)
[18:25:50] [Client thread/INFO] [STDERR]: [mekanism.client.render.ctm.CTMModelFactory:func_188616_a:88]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[18:25:50] [Client thread/INFO] [STDERR]: [mekanism.client.render.ctm.CTMModelFactory:func_188616_a:88]: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
[18:25:50] [Client thread/INFO] [STDERR]: [mekanism.client.render.ctm.CTMModelFactory:func_188616_a:88]: 	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:339)
[18:25:50] [Client thread/INFO] [STDERR]: [mekanism.client.render.ctm.CTMModelFactory:func_188616_a:88]: 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1650)
[18:25:50] [Client thread/INFO] [STDERR]: [mekanism.client.render.ctm.CTMModelFactory:func_188616_a:88]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
[18:25:50] [Client thread/INFO] [STDERR]: [mekanism.client.render.ctm.CTMModelFactory:func_188616_a:88]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
[18:25:50] [Client thread/INFO] [STDERR]: [mekanism.client.render.ctm.CTMModelFactory:func_188616_a:88]: 	at net.minecraft.client.main.Main.main(SourceFile:124)
[18:25:50] [Client thread/INFO] [STDERR]: [mekanism.client.render.ctm.CTMModelFactory:func_188616_a:88]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:25:50] [Client thread/INFO] [STDERR]: [mekanism.client.render.ctm.CTMModelFactory:func_188616_a:88]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[18:25:50] [Client thread/INFO] [STDERR]: [mekanism.client.render.ctm.CTMModelFactory:func_188616_a:88]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:25:50] [Client thread/INFO] [STDERR]: [mekanism.client.render.ctm.CTMModelFactory:func_188616_a:88]: 	at java.lang.reflect.Method.invoke(Method.java:483)
[18:25:50] [Client thread/INFO] [STDERR]: [mekanism.client.render.ctm.CTMModelFactory:func_188616_a:88]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[18:25:50] [Client thread/INFO] [STDERR]: [mekanism.client.render.ctm.CTMModelFactory:func_188616_a:88]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[18:25:50] [Client thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: Caused by: java.lang.NullPointerException
[18:25:50] [Client thread/INFO] [STDERR]: [mekanism.client.render.ctm.CTMModelFactory:func_188616_a:88]: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException
[18:25:50] [Client thread/INFO] [STDERR]: [mekanism.client.render.ctm.CTMModelFactory:func_188616_a:88]: 	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201)
[18:25:50] [Client thread/INFO] [STDERR]: [mekanism.client.render.ctm.CTMModelFactory:func_188616_a:88]: 	at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
[18:25:50] [Client thread/INFO] [STDERR]: [mekanism.client.render.ctm.CTMModelFactory:func_188616_a:88]: 	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4736)
[18:25:50] [Client thread/INFO] [STDERR]: [mekanism.client.render.ctm.CTMModelFactory:func_188616_a:88]: 	at mekanism.client.render.ctm.CTMModelFactory.func_188616_a(CTMModelFactory.java:81)
[18:25:50] [Client thread/INFO] [STDERR]: [mekanism.client.render.ctm.CTMModelFactory:func_188616_a:88]: 	at journeymap.client.forge.helper.ColorHelper.getFirstFoundSprite(ColorHelper.java:172)
[18:25:50] [Client thread/INFO] [STDERR]: [mekanism.client.render.ctm.CTMModelFactory:func_188616_a:88]: 	at journeymap.client.forge.helper.ColorHelper.getDirectIcon(ColorHelper.java:162)
[18:25:50] [Client thread/INFO] [STDERR]: [mekanism.client.render.ctm.CTMModelFactory:func_188616_a:88]: 	at journeymap.client.forge.helper.ColorHelper.getTextureColor(ColorHelper.java:110)
[18:25:50] [Client thread/INFO] [STDERR]: [mekanism.client.render.ctm.CTMModelFactory:func_188616_a:88]: 	at journeymap.client.model.mod.vanilla.VanillaColorHandler.getTextureColor(VanillaColorHandler.java:24)
[18:25:50] [Client thread/INFO] [STDERR]: [mekanism.client.render.ctm.CTMModelFactory:func_188616_a:88]: 	at journeymap.client.model.BlockMD.ensureColor(BlockMD.java:408)
[18:25:50] [Client thread/INFO] [STDERR]: [mekanism.client.render.ctm.CTMModelFactory:func_188616_a:88]: 	at journeymap.client.cartography.ColorManager.initBlockColors(ColorManager.java:193)
[18:25:50] [Client thread/INFO] [STDERR]: [mekanism.client.render.ctm.CTMModelFactory:func_188616_a:88]: 	at journeymap.client.cartography.ColorManager.ensureCurrent(ColorManager.java:130)
[18:25:50] [Client thread/INFO] [STDERR]: [mekanism.client.render.ctm.CTMModelFactory:func_188616_a:88]: 	at journeymap.client.task.main.EnsureCurrentColorsTask.perform(EnsureCurrentColorsTask.java:15)
[18:25:50] [Client thread/INFO] [STDERR]: [mekanism.client.render.ctm.CTMModelFactory:func_188616_a:88]: 	at journeymap.client.task.main.MainTaskController.performTasks(MainTaskController.java:64)
[18:25:50] [Client thread/INFO] [STDERR]: [mekanism.client.render.ctm.CTMModelFactory:func_188616_a:88]: 	at journeymap.client.JourneymapClient.performMainThreadTasks(JourneymapClient.java:568)
[18:25:50] [Client thread/INFO] [STDERR]: [mekanism.client.render.ctm.CTMModelFactory:func_188616_a:88]: 	at journeymap.client.forge.event.StateTickHandler.onClientTick(StateTickHandler.java:86)
[18:25:50] [Client thread/INFO] [STDERR]: [mekanism.client.render.ctm.CTMModelFactory:func_188616_a:88]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_99_StateTickHandler_onClientTick_ClientTickEvent.invoke(.dynamic)
[18:25:50] [Client thread/INFO] [STDERR]: [mekanism.client.render.ctm.CTMModelFactory:func_188616_a:88]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[18:25:50] [Client thread/INFO] [STDERR]: [mekanism.client.render.ctm.CTMModelFactory:func_188616_a:88]: 	at net.minecraftforge.fml.co

**Comment by dritz56** [comment]
nevermind i just needed to update java
