### ISSUE TITLE
[CRASH] Breaking Evap Tower Blocks

### ISSUE THREAD

**Issue by Utildayael** [aidancbrady/Mekanism#4132]
Taking apart a evap tower and boom.. crash to desktop. Was removing just a normal evap block. :(

http://pastebin.com/gZmu6Axg

`Description: Rendering Block Entity
 
java.lang.ArrayIndexOutOfBoundsException: 101646
    at mekanism.client.render.tileentity.RenderThermalEvaporationController.renderTileEntityAt(RenderThermalEvaporationController.java:49)
    at mekanism.client.render.tileentity.RenderThermalEvaporationController.func_180535_a(RenderThermalEvaporationController.java:23)
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_178469_a(TileEntityRendererDispatcher.java:168)
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:141)
    at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:997)
    at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1730)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1557)
    at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1336)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)`

Mekanism-1.10.2-9.2.1.295
MC 1.10.2

Cheers

**Comment by VT-14** [comment]
Does it crash without Optifine installed/enabled?

**Comment by VT-14** [comment]
@ThatGamerBlue That's an Ender IO message...

...But it does apply for 95%+ of mods out there (including Mekanism).  Optifine majorly f***s with rendering, which causes these kinds of rendering crashes all the time.  Frankly I think that Forge itself needs to start putting an "Optifine not supported (by most mods)" error messages at the top of crash logs.

Unfortunately the majority of people who use Optifine seem rather fanatical and will often remove some really great mods rather than dare play without a few graphics tweaks and 'optimizations.'  

In this case, he can at least remove Optifine, tear down the structure (probably only needs to break the first block to remove the multiblock), and reapply Optifine.

**Comment by ThatGamerBlue** [comment]
@VT-14 I know that message is from ender io, but it still applies.

**Comment by Utildayael** [comment]
I wont say fanatical but it does seem to make the game run quite a bit better. It literally doubles my framerate and gives more options to tweak the graphics stuff. That said, more than open to any suggestions for anything else as ya, I've read Opti can/does cause issues with some mods. 

I spaced off I was using it again when I posted by bug report. While @aidancbrady isn't one of the devs who goes ballistic about people using it, I know it could cause issues. I can't repro it either but I've had issues with his pipes in the past [not using Opti] that I had trouble repro and he still found a bug in the code where something wasn't caught or whatnot and fixed it so figured I'd toss the report up. Upon relaunching I was able to break rest of structure but I went and broke the controller first. I think the issue was I started at the top and the multi kept reforming now that the solars aren't required so it would form, break, form, break a few times. Once controller was gone, whole thing came down without a hitch.

**Comment by roboderpy** [comment]
@VT-14 For some reason, OptiFine without any tweaking (out of box) increases FPS. it is impossible to play without OptiFine with Mekanism installed, sadly. For some reason Mekanism causes **big** tick lag on **clientside** when server runs smoothly. OptiFine smoothes that lags, so this is possible to play with 20 FPS :c

**Comment by aidancbrady** [comment]
Fixed in development.

**Comment by Utildayael** [comment]
Thank you sir!
