### ISSUE TITLE
Ic2 crash

### ISSUE THREAD

**Issue by clienthax** [aidancbrady/Mekanism#4149]
1.7.10

seems related to this (last few comments) https://github.com/LemADEC/WarpDrive/issues/206

```
---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 18/01/17 05:36
Description: Exception getting block type in world

java.lang.NullPointerException: Exception getting block type in world
	at ic2.core.energy.EnergyNetLocal.addTileToGrids(EnergyNetLocal.java:627)
	at ic2.core.energy.EnergyNetLocal.addTileEntity(EnergyNetLocal.java:185)
	at ic2.core.energy.EnergyNetLocal.addTileEntity(EnergyNetLocal.java:66)
	at ic2.core.energy.EventHandler.onEnergyTileLoad(EventHandler.java:28)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_52_EventHandler_onEnergyTileLoad_EnergyTileLoadEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at mekanism.common.tile.TileEntityElectricBlock.register(TileEntityElectricBlock.java:66)
	at mekanism.common.Mekanism.onChunkLoad(Mekanism.java:1473)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_889_Mekanism_onChunkLoad_Load.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.world.chunk.Chunk.func_76631_c(Chunk.java:1054)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:49)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:15)
	at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344)
	at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:212)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:185)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:323)
	at net.minecraft.world.World.func_72964_e(World.java:799)
	at net.minecraft.world.World.func_147439_a(World.java:702)
	at net.minecraft.world.World.func_72879_k(World.java:4156)
	at net.minecraft.world.World.func_94577_B(World.java:4202)
	at net.minecraft.world.World.func_72878_l(World.java:4219)
	at net.minecraft.world.World.func_72864_z(World.java:4224)
	at mekanism.common.tile.TileEntityBasicBlock.updatePower(TileEntityBasicBlock.java:282)
	at mekanism.common.tile.TileEntityBasicBlock.onNeighborChange(TileEntityBasicBlock.java:276)
	at mekanism.common.block.BlockMachine.func_149695_a(BlockMachine.java:956)
	at net.minecraft.world.World.func_147460_e(World.java:1147)
	at ic2.core.energy.EnergyNetLocal.addTileEntity(EnergyNetLocal.java:181)
	at ic2.core.energy.EnergyNetLocal.addTileEntity(EnergyNetLocal.java:66)
	at ic2.core.energy.EventHandler.onEnergyTileLoad(EventHandler.java:28)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_52_EventHandler_onEnergyTileLoad_EnergyTileLoadEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at ic2.core.block.wiring.TileEntityCable.onLoaded(TileEntityCable.java:159)
	at ic2.core.block.TileEntityBlock$1.tickCallback(TileEntityBlock.java:60)
	at ic2.core.TickHandler.processTickCallbacks(TickHandler.java:175)
	at ic2.core.TickHandler.onWorldTick(TickHandler.java:60)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_34_TickHandler_onWorldTick_WorldTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:273)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:957)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at ic2.core.energy.EnergyNetLocal.addTileToGrids(EnergyNetLocal.java:627)
	at ic2.core.energy.EnergyNetLocal.addTileEntity(EnergyNetLocal.java:185)
	at ic2.core.energy.EnergyNetLocal.addTileEntity(EnergyNetLocal.java:66)
	at ic2.core.energy.EventHandler.onEnergyTileLoad(EventHandler.java:28)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_52_EventHandler_onEnergyTileLoad_EnergyTileLoadEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at mekanism.common.tile.TileEntityElectricBlock.register(TileEntityElectricBlock.java:66)
	at mekanism.common.Mekanism.onChunkLoad(Mekanism.java:1473)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_889_Mekanism_onChunkLoad_Load.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.world.chunk.Chunk.func_76631_c(Chunk.java:1054)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:49)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:15)
	at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344)
	at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:212)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:185)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:323)
	at net.minecraft.world.World.func_72964_e(World.java:799)

-- Requested block coordinates --
Details:
	Found chunk: true
	Location: 
Stacktrace:
	at net.minecraft.world.World.func_147439_a(World.java:702)
	at net.minecraft.world.World.func_72879_k(World.java:4156)
	at net.minecraft.world.World.func_94577_B(World.java:4202)
	at net.minecraft.world.World.func_72878_l(World.java:4219)
	at net.minecraft.world.World.func_72864_z(World.java:4224)
	at mekanism.common.tile.TileEntityBasicBlock.updatePower(TileEntityBasicBlock.java:282)
	at mekanism.common.tile.TileEntityBasicBlock.onNeighborChange(TileEntityBasicBlock.java:276)
	at mekanism.common.block.BlockMachine.func_149695_a(BlockMachine.java:956)

-- Block being updated --
Details:
	Source block type: ID #0 (tile.air // net.minecraft.block.BlockAir)
	Block type: ID #1800 (tile.MachineBlock2 // mekanism.common.block.BlockMachine)
	Block data value: 0 / 0x0 / 0b0000

	at net.minecraft.world.World.func_147460_e(World.java:1147)
	at ic2.core.energy.EnergyNetLocal.addTileEntity(EnergyNetLocal.java:181)
	at ic2.core.energy.EnergyNetLocal.addTileEntity(EnergyNetLocal.java:66)
	at ic2.core.energy.EventHandler.onEnergyTileLoad(EventHandler.java:28)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_52_EventHandler_onEnergyTileLoad_EnergyTileLoadEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at ic2.core.block.wiring.TileEntityCable.onLoaded(TileEntityCable.java:159)
	at ic2.core.block.TileEntityBlock$1.tickCallback(TileEntityBlock.java:60)
	at ic2.core.TickHandler.processTickCallbacks(TickHandler.java:175)
	at ic2.core.TickHandler.onWorldTick(TickHandler.java:60)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_34_TickHandler_onWorldTick_WorldTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:273)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:957)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by ThatGamerBlue** [comment]
1) 1.7.10 isn't supported
2) This is IC2
3) Versions?
