### ISSUE TITLE
RPC to Enrichment Chamber and Chest

### ISSUE THREAD

**Issue by duncanwebb** [aidancbrady/Mekanism#4171]
I have a PRC connected to an Enrichment Chamber and a Restrictive Transporter connected to a chest as shown below.

![prc-enrichment](https://cloud.githubusercontent.com/assets/4198031/22463481/06700872-e7b2-11e6-83e3-6d9f12289fa6.png)

All the HDPE Pellets are going to the chest and causing this error message.

`[12:30:05] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240) [bzl.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.NullPointerException
[12:30:06] [Server thread/FATAL]: Error executing task`

If I remove the Restrictive Transporter then it works correctly. The difference seems to be that the HDPE Pellets are going is sets instead of one at a time.

Thanks,

**Comment by thommy101** [comment]
Do you have a full log? Because this log doesn't tell anything about where in Mekanism it could go wrong.

**Comment by duncanwebb** [comment]
No sorry, this above extract was being generated every second, once for each pellet. The game wasn't crashing just that all the pellets were going down the restrictive pipe. Looks like a call back message. I can run the game again and give you the full log if it helps.

Cheers,

**Comment by aidancbrady** [comment]
I'm afraid that log gives no detail of a bad Mekanism interaction.  Let me know if you can isolate Mekanism in a crash log.

**Comment by duncanwebb** [comment]
Would a 20 second video help to show what is happening? https://youtu.be/DSIj9FX7P6U
