### ISSUE TITLE
[1.10.2] Game crashes when ever cables are connected to existing machines

### ISSUE THREAD

**Issue by ObsidianChief** [aidancbrady/Mekanism#4175]
I first saw this when I attempted to use an electric pump, and thought not much of it, I have other pumps from other mods. However, it is now affecting my generators, my power source making this relatively unplayable. It only occurs when I break a machine, and replace it in the same spot/cable or when I place a new cable to it... I can also provide sys specs if needed...

COMMENCE CRASH REPORT: 

WARNING: coremods are present:
  ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.1.jar)
  MovingWorldCoreMod (movingworld-1.10.2-0006-full.jar)
  TANLoadingPlugin (ToughAsNails-1.9.4-1.0.11.jar)
  IC2core (industrialcraft-2-2.6.129-ex110.jar)
  MalisisCorePlugin (malisiscore-1.10.2-4.2.3.jar)
  AdvancedRocketryPlugin (AdvancedRocketry-1.10.2-1.0.8.jar)
  TransformerLoader (OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar)
  LoadingHook (Mekanism-1.10.2-9.2.1.295.jar)
Contact their authors BEFORE contacting forge

// Ooh. Shiny.

Time: 2/1/17 9:40 AM
Description: Exception while updating neighbours

java.lang.NoSuchMethodError: cofh.api.energy.IEnergyConnection.canConnectEnergy(Lnet/minecraft/util/EnumFacing;)Z
	at mekanism.common.util.CableUtils.isOutputter(CableUtils.java:125)
	at mekanism.common.util.CableUtils.isValidAcceptorOnSide(CableUtils.java:72)
	at mekanism.common.multipart.PartUniversalCable.isValidAcceptor(PartUniversalCable.java:222)
	at mekanism.common.multipart.PartSidedPipe.getPossibleAcceptorConnections(PartSidedPipe.java:318)
	at mekanism.common.multipart.PartSidedPipe.refreshConnections(PartSidedPipe.java:611)
	at mekanism.common.multipart.PartSidedPipe.onNeighborBlockChange(PartSidedPipe.java:698)
	at mcmultipart.multipart.MultipartContainer.onNeighborBlockChange(MultipartContainer.java:362)
	at mcmultipart.block.BlockMultipartContainer.func_189540_a(BlockMultipartContainer.java:237)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:474)
	at net.minecraft.world.World.func_180496_d(World.java:519)
	at ic2.core.energy.leg.EnergyNetLocalLeg.tickStart(EnergyNetLocalLeg.java:192)
	at ic2.core.energy.leg.EventHandler.preTick(EventHandler.java:44)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_78_EventHandler_preTick_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:282)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:694)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)

**Comment by ObsidianChief** [comment]
For the record, this occurred on the 1.10.2 9.2.1.925 build (stable given the green background on it)

**Comment by ThatGamerBlue** [comment]
Can I get world download to test this on?

**Comment by ObsidianChief** [comment]
For the record, this map uses many other mods.
http://www.mediafire.com/file/qmot193s2r179sg/Le_Map.7z
It's also rather large
