### ISSUE TITLE
1.7.10 - Mekanism V9 - Thermoelectric Boiler & Turbine Render Issue

### ISSUE THREAD

**Issue by msgtfox** [aidancbrady/Mekanism#4208]
I've been getting this issue when I log into a server: 
Now this only started happening AS I placed a conductive pipe to attach to the thermoelectric boiler, and as soon as I did that I got a render crash, and nothing has seemed to fix it.
And I don't wanna remove Mekanism. D:
This is also only client-side, it doesn't cause a crash on the server side.

Edit: Seem to be getting a render crash when attempting to access the Steam Turbine with a right click while it's spinning, I had to use MER Steam productions tools.
Maybe this is a Java related issue?

Turbine Crash: 
[crash-2017-02-17_11.09.30-client.txt](https://github.com/aidancbrady/Mekanism/files/784108/crash-2017-02-17_11.09.30-client.txt)
Boiler Crash:
[crash-2017-02-16_16.01.53-client.txt](https://github.com/aidancbrady/Mekanism/files/781909/crash-2017-02-16_16.01.53-client.txt)

---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 2/16/17 3:36 PM
Description: Rendering Block Entity

java.lang.NullPointerException: Rendering Block Entity
	at net.minecraft.client.renderer.RenderBlocks.func_147768_a(RenderBlocks.java:7807)
	at mekanism.client.render.MekanismRenderer.renderObject(MekanismRenderer.java:337)
	at mekanism.client.render.tileentity.RenderThermoelectricBoiler.getUpperDisplay(RenderThermoelectricBoiler.java:216)
	at mekanism.client.render.tileentity.RenderThermoelectricBoiler.renderAModelAt(RenderThermoelectricBoiler.java:121)
	at mekanism.client.render.tileentity.RenderThermoelectricBoiler.func_147500_a(RenderThermoelectricBoiler.java:40)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147549_a(SourceFile:100)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147544_a(SourceFile:92)
	at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:781)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1599)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1337)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)

**Comment by ThatGamerBlue** [comment]
does it happen without fastcraft enabled?

**Comment by msgtfox** [comment]
I'm not sure, I'll be sure to check, give me a bit and I'll report back.

**Comment by msgtfox** [comment]
Yeah, I'm still getting the same crashes regardless of Fast Craft, I've also taken out optifine and tried that too.
I'm still running into the issues, like with the Boiler, I can fully build it, load it with water, but ONCE I connect a thermal pipe to heat it up, and set it to 100,000, the Boiler begins producing, but then I get the render crash.
For the Turbine, I'm fine right clicking it when it's not spinning, but once it hits a certain speed, then I can't right click as it'll make me crash.

**Comment by aidancbrady** [comment]
Can't reproduce this in 1.11. Calling this fixed until further notice
