### ISSUE TITLE
[1.7.10-latest] Crash, but no report.

### ISSUE THREAD

**Issue by AugiteSoul** [aidancbrady/Mekanism#4234]
Had to look in the logs for this one.
 An error occurred trying to configure the minecraft home at C:\Users\augitesoul\Desktop\Apocalypse for Forge Mod Loader
java.lang.NoClassDefFoundError: net/minecraftforge/fml/relauncher/IFMLLoadingPlugin
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_25]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760) ~[?:1.8.0_25]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_25]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:455) ~[?:1.8.0_25]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[?:1.8.0_25]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:367) ~[?:1.8.0_25]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.8.0_25]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_25]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_25]
	at java.lang.Class.forName(Class.java:344) ~[?:1.8.0_25]
	at cpw.mods.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:460) ~[forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:389) ~[forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:221) ~[forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126) [forge-1.7.10-10.13.4.1614-1.7.10.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.fml.relauncher.IFMLLoadingPlugin
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
	... 23 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
	... 23 more

**Comment by ThatGamerBlue** [comment]
reinstall forge

**Comment by AugiteSoul** [comment]
still not working

**Comment by thommy101** [comment]
First of all, I see nothing related to Mekanism in your logs. But my guess is, outdated Forge. Can't help much more without some specific version numbers, a whole log, a modlist.

**Comment by tttogo** [comment]
I have the latest Forge reinstalled, with removal of all config files, and I'm also getting a crash

**Comment by AugiteSoul** [comment]
What version of Forge I need? It's doing that with 1614 too.
Log:http://pastebin.com/dxxRiA8F
Modlist is linked.
[modlist.txt](https://github.com/aidancbrady/Mekanism/files/797472/modlist.txt)

**Comment by tttogo** [comment]
A completely fresh install of Minecraft - to remove all possible files - and as soon as I add Mekanism Core it crashes.

**Comment by tttogo** [comment]
[19:29:54] [main/WARN]: The coremod mekanism.common.launch.LoadingHook does not have a MCVersion annotation, it may cause issues with this version of Minecraft

Only thing I can see in the log

**Comment by tttogo** [comment]
Using an nVidia Card? [https://github.com/aidancbrady/Mekanism/issues/4205]

**Comment by thommy101** [comment]
@AugiteSoul You have a double mekanism in your mod folder. Mekanism 1.7.10 and Mekanism 1.10.2. Please remove the 1.10.2 version

**Comment by AugiteSoul** [comment]
Nice, you seen something that I didn't see. Thanks!
