### ISSUE TITLE
Null-side fluid capability on the Pressurized Reaction Chamber throws an NPE

### ISSUE THREAD

**Issue by unascribed** [aidancbrady/Mekanism#4250]
See: elytra/FruitPhone#2

```
[08:01:26] [Server thread/ERROR] [FML/]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.TickEvent$PlayerTickEvent@3b30e68a:
java.lang.NullPointerException
	at mekanism.common.util.MekanismUtils.getBaseOrientation(MekanismUtils.java:490) ~[MekanismUtils.class:?]
	at mekanism.common.tile.component.TileComponentConfig.getOutput(TileComponentConfig.java:141) ~[TileComponentConfig.class:?]
	at mekanism.common.tile.TileEntityPRC.getTankInfo(TileEntityPRC.java:402) ~[TileEntityPRC.class:?]
	at mekanism.common.base.FluidHandlerWrapper.getTankProperties(FluidHandlerWrapper.java:24) ~[FluidHandlerWrapper.class:?]
	at com.elytradev.fruitphone.FruitPhone.generateProbeData(FruitPhone.java:412) ~[FruitPhone.class:?]
	at com.elytradev.fruitphone.FruitPhone.onPlayerTick(FruitPhone.java:326) ~[FruitPhone.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_486_FruitPhone_onPlayerTick_PlayerTickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) [EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPreTick(FMLCommonHandler.java:360) [FMLCommonHandler.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:189) [zs.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:303) [lu.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:162) [me.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:213) [NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287) [eo.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [md.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_77]
```

Happens after I retrieve a capability with a null facing (which is completely valid, I may add)

Mekanism 1.10.2-9.2.1.298

**Comment by ThatGamerBlue** [comment]
duplicate of #4185

**Comment by unascribed** [comment]
Ah, sorry. I didn't have time to check.
