### ISSUE TITLE
Support in NetherTweaksMod

### ISSUE THREAD

**Issue by Gaprosys** [aidancbrady/Mekanism#4293]
Hello,

I am a co-programmer of the NetherTweaks Mod and we have a little problem with the compatibility to your mod. NTM has a sieve, to sieve the ores, but if we add your mod to our modpack, with a bunch of other mods, we getting an error, which has something to do with a wildcard or something similar by your mod. 

Were trying to get the Osmium Ore about the Ore Directory.

At the evening I can send you a report.

Hope someone could help.

 - Gaprosys

**Comment by aidancbrady** [comment]
I'll need a report to do anything

**Comment by Gaprosys** [comment]
Sorry, my false.

Here is the false place to do anything in this direction.

But here is the Error code which we get in 1.7.10 only on Servers(by singleplayer they don't load the world):
`java.lang.NullPointerException
        at net.minecraft.item.ItemStack.func_77960_j(ItemStack.java:217) ~[add.class:?]
        at mekanism.api.util.StackUtils.equalsWildcard(StackUtils.java:63) ~[StackUtils.class:?]
        at mekanism.api.util.StackUtils.equalsWildcardWithNBT(StackUtils.java:68) ~[StackUtils.class:?]
        at mekanism.common.recipe.inputs.ItemStackInput.testEquality(ItemStackInput.java:66) ~[ItemStackInput.class:?]
        at mekanism.common.recipe.inputs.ItemStackInput.testEquality(ItemStackInput.java:8) ~[ItemStackInput.class:?]
        at mekanism.common.recipe.inputs.MachineInput.equals(MachineInput.java:36) ~[MachineInput.class:?]
        at java.util.HashMap.putVal(HashMap.java:634) ~[?:1.8.0_111]
        at java.util.HashMap.put(HashMap.java:611) ~[?:1.8.0_111]
        at mekanism.common.recipe.RecipeHandler$Recipe.put(RecipeHandler.java:546) ~[RecipeHandler$Recipe.class:?]
        at mekanism.common.Mekanism.serverStarting(Mekanism.java:1086) ~[Mekanism.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
        at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) ~[FMLModContainer.class:?]
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
        at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[LoadController.class:?]
        at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[LoadController.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
        at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) [LoadController.class:?]
        at cpw.mods.fml.common.Loader.serverStarting(Loader.java:789) [Loader.class:?]
        at cpw.mods.fml.common.FMLCommonHandler.handleServerStarting(FMLCommonHandler.java:278) [FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:277) [lt.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[15:54:25] [Server thread/ERROR] [FML]: A fatal exception occurred during the server starting event
java.lang.NullPointerException
        at net.minecraft.item.ItemStack.func_77960_j(ItemStack.java:217) ~[add.class:?]
        at mekanism.api.util.StackUtils.equalsWildcard(StackUtils.java:63) ~[StackUtils.class:?]
        at mekanism.api.util.StackUtils.equalsWildcardWithNBT(StackUtils.java:68) ~[StackUtils.class:?]
        at mekanism.common.recipe.inputs.ItemStackInput.testEquality(ItemStackInput.java:66) ~[ItemStackInput.class:?]
        at mekanism.common.recipe.inputs.ItemStackInput.testEquality(ItemStackInput.java:8) ~[ItemStackInput.class:?]
        at mekanism.common.recipe.inputs.MachineInput.equals(MachineInput.java:36) ~[MachineInput.class:?]
        at java.util.HashMap.putVal(HashMap.java:634) ~[?:1.8.0_111]
        at java.util.HashMap.put(HashMap.java:611) ~[?:1.8.0_111]
        at mekanism.common.recipe.RecipeHandler$Recipe.put(RecipeHandler.java:546) ~[RecipeHandler$Recipe.class:?]
        at mekanism.common.Mekanism.serverStarting(Mekanism.java:1086) ~[Mekanism.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
        at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) ~[FMLModContainer.class:?]
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
        at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[LoadController.class:?]
        at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[LoadController.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
        at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) ~[LoadController.class:?]
        at cpw.mods.fml.common.Loader.serverStarting(Loader.java:789) [Loader.class:?]
        at cpw.mods.fml.common.FMLCommonHandler.handleServerStarting(FMLCommonHandler.java:278) [FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:277) [lt.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]`

The Code in which we suspect the Error:
`//if(Loader.isModLoaded("Mekanism")){
    	if(OreDictionary.doesOreNameExist("oreOsmium")){
			OreDictionary.registerOre("oreOsmium", new ItemStack(oreGravel, 1, 7));
			OreDictionary.registerOre("oreOsmium", new ItemStack(oreSand, 1, 7));
			OreDictionary.registerOre("oreOsmium", new ItemStack(oreDust, 1, 7));
    	}`

And the mods, we've installed:
`AgriCraft-1.7.10-1.5.0.jar
ArcaneArteries0.8.2.jar
Automagy-1.7.10-0.27.1.jar
Bagginses-2.1.1.jar
BigReactors-0.4.3A.jar
BloodArsenal-1.7.10-1.2-3.jar
BloodMagic-1.7.10-1.3.3-13.jar
Botania r1.8-249.jar
buildcraft-7.1.14.jar
buildcraft-compat-7.1.3.jar
BuildcraftAdditions-1.7.10-2.2.5.jar
Chisel2-2.5.1.44.jar
CodeChickenCore-1.7.10-1.0.7.46-universal.jar
CoFHCore-[1.7.10]3.1.3-327.jar
CoFHTweaks-[1.7.10]1.1.2-89.jar
EnchantingPlus-1.7.10-3.0.2-d.jar
Eureka-1.7.10-3.0.2.jar
Ex-Nihilo-1.38-53.jar
ExtraTiC-1.7.10-1.4.5.jar
extrautilities-1.2.12.jar
Forbidden Magic-1.7.10-0.573.jar
gadomancy-1.7.10-1.0.5.jar
Galacticraft-Planets-1.7-3.0.12.375.jar
GalacticraftCore-1.7-3.0.12.375.jar
GardenStuff-1.7.10-1.7.0.jar
Guide-API-1.7.10-1.0.1-20.jar
IndustriousMage-0.0.5.jar
InventoryTweaks-1.58-147.jar
ironchest-1.7.10-6.0.62.742-universal.jar
Jabba-1.2.2_1.7.10.jar
journeymap-1.7.10-5.1.4-unlimited.jar
magicalcrops-1.7.10_0.1.jar
Mantle-1.7.10-0.3.2b.jar
Mekanism-1.7.10-8.1.9.265.jar
MekanismGenerators-1.7.10-8.1.9.265.jar
MekanismTools-1.7.10-8.1.9.265.jar
MicdoodleCore-1.7-3.0.12.375.jar
MineFactoryReloaded-[1.7.10]2.8.1-174.jar
neiaddons-1.12.11.36-mc1.7.10.jar
NethertweaksMod-1.4.6.jar
NotEnoughItems-1.7.10-1.0.5.118-universal.jar
OpenBlocks-1.7.10-1.5.jar
OpenModsLib-1.7.10-0.9.jar
Pam's HarvestCraft 1.7.10j.jar
Railcraft_1.7.10-9.12.2.0.jar
Sanguimancy-1.7.10-1.1.9-32.jar
StorageDrawers-1.7.10-1.10.5.jar
supercraftingframe-1.7.10.3.jar
TConstruct-1.7.10-1.8.8.jar
Thaumcraft-1.7.10-4.2.3.5.jar
thaumcraftneiplugin-1.7.10-1.7a.jar
ThaumicExploration-1.7.10-1.1-53.jar
ThermalDynamics-[1.7.10]1.2.0-171.jar
ThermalExpansion-[1.7.10]4.1.3-246.jar
ThermalFoundation-[1.7.10]1.2.5-115.jar
Traincraft-4.3.0_003.jar
TravellersGear-1.7.10-1.16.6.jar
Waila-1.5.10_1.7.10.jar
WailaHarvestability-mc1.7.10-1.1.6.jar
witchery-1.7.10-0.24.1.jar
WitchingGadgets-1.7.10-1.1.10.jar
[1.7.10]Treecapitator-universal-2.0.4.jar
1.7.10\Baubles-1.7.10-1.0.1.10.jar
1.7.10\CodeChickenLib-1.7.10-1.1.3.138-universal.jar
1.7.10\ForgeMultipart-1.7.10-1.2.0.345-universal.jar
1.7.10\[1.7.10]bspkrsCore-universal-6.15.jar
railcraft\emblems`

To be sure, we're playing on 1.7.10.

I hope, you can tell me a forum, which I can ask this think.

Sorry, that I was so stupid to take a issues tracker as a forum.
