### ISSUE TITLE
[1.11.2] Mechanical pipe visually corrupting chunks

### ISSUE THREAD

**Issue by allanf181** [aidancbrady/Mekanism#4323]
```java
[01:51:53] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
    at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_92]
    at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_92]
    at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1046) [bes.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372) [bes.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_92]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_92]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_92]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_92]
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236) [NewLaunch.jar:?]
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.listen(EntryPoint.java:162) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.main(EntryPoint.java:53) [NewLaunch.jar:?]
Caused by: java.lang.NullPointerException
    at mekanism.common.tile.transmitter.TileEntityMechanicalPipe.getCapacity(TileEntityMechanicalPipe.java:205) ~[TileEntityMechanicalPipe.class:?]
    at mekanism.common.transmitters.TransmitterImpl.getCapacity(TransmitterImpl.java:28) ~[TransmitterImpl.class:?]
    at mekanism.common.transmitters.grid.FluidNetwork.updateMeanCapacity(FluidNetwork.java:129) ~[FluidNetwork.class:?]
    at mekanism.api.transmitters.DynamicNetwork.updateCapacity(DynamicNetwork.java:311) ~[DynamicNetwork.class:?]
    at mekanism.common.network.PacketTransmitterUpdate$1.run(PacketTransmitterUpdate.java:67) ~[PacketTransmitterUpdate$1.class:?]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_92]
    at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_92]
    at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
```

**Comment by aidancbrady** [comment]
Fixed
