### ISSUE TITLE
Mekanism with MCMultipart doesn't work

### ISSUE THREAD

**Issue by rajdik** [aidancbrady/Mekanism#4546]
I installed Mekanism to my modpack ... and it crashes :/ But i already have MCMultiPart i tried all.

**Forge: 12.17.0.1987/12.17.0.1976** 
**Mekanism: 9.1.0.282** 
**Other relevant version:** 

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CXLibraryCore (CXLibrary-1.9.4.jar)
  CoreXU2 (Extra-Utilities-Mod-1.9.4.jar)
  LoadingPlugin (Blood-Moon-Mod-1.9.4.jar)
  FarseekCoreMod (Farseek-Mod-1.10.2.jar)
  CCCDeobfPlugin (unknown)
  MalisisCorePlugin (MalisisCore-1.10.2.jar)
  CodeChickenCorePlugin (CodeChickenCore-1.9.4-Recommended.jar)
  CCLCorePlugin (CodeChickenLib-1.9.4-Recommended.jar)
  Reborn Core ASM (RebornCore-1.9.4.jar)
  BetterSleeping Core (BetterSleeping-1.9.4-2.0-gamma-7.jar)
  CCLCorePlugin (CodeChickenLib-1.9.4-2.1.2.42-universal.jar)
  NEICorePlugin (Not-Enough-Items-1.9.4-Recommended.jar)
Contact their authors BEFORE contacting forge

// I feel sad now :(

Time: 19.7.17 19:07
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: ic2/core/item/type/CraftingItemType
	at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:179)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:769)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:316)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:518)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: ic2/core/item/type/CraftingItemType
	at techreborn.Core.init(Core.java:128)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:566)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:228)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:206)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:767)
	... 10 more
Caused by: java.lang.ClassNotFoundException: ic2.core.item.type.CraftingItemType
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 37 more
[gist/pastebin/etc link here]

**Comment by thommy101** [comment]
That's not a lot of provided information...

Please fill in the provided format :)

**Comment by ANTdentarg** [comment]
I was actually looking for this. I just had an interaction between these two. 
Singleplayer modded foolcraft modpack 1.4.7.
Visited the nether, 2 chests connected with transporter. one end set to push had a chisel and bits around it. That's the only transporter I have in my save.

Forge: 12.18.3.2281
Mekanism: 1.10.2-9.2.2.301
MCmultipart: 1.4.0-universal
Chisel&bits: 12.14

The small part -
java.lang.NullPointerException: Ticking block entity
	at mcmultipart.network.MessageMultipartChange.toBytes(MessageMultipartChange.java:51)
	at mcmultipart.network.MessageSplit.split(MessageSplit.java:94)
	at mcmultipart.network.MessageMultipartChange.send(MessageMultipartChange.java:142)
	at mcmultipart.multipart.Multipart.sendUpdatePacket(Multipart.java:340)
	at mcmultipart.multipart.Multipart.sendUpdatePacket(Multipart.java:330)
	at mekanism.common.multipart.PartSidedPipe.func_73660_a(PartSidedPipe.java:193)
	at mekanism.common.multipart.PartTransmitter.func_73660_a(PartTransmitter.java:59)
	at mekanism.common.multipart.PartLogisticalTransporter.func_73660_a(PartLogisticalTransporter.java:125)
	at mcmultipart.block.TileMultipartContainer$Ticking.func_73660_a(TileMultipartContainer.java:328)
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

The whole thing - https://pastebin.com/sDCD5sRz

**Comment by thommy101** [comment]
@rajdik Sorry, but 1.9.4 isn't supported any more, it also looks like a crash from IC2, not Mekanism.

@ANTdentarg That looks like a MCMultiPart crash which has been reported before in #4374
