### ISSUE TITLE
Clientside crash when placing down Quantum Entangloporter

### ISSUE THREAD

**Issue by roboderpy** [aidancbrady/Mekanism#4630]
```
java.lang.NullPointerException: Unexpected error
	at mekanism.common.frequency.FrequencyManager.addFrequency(FrequencyManager.java:196)
	at mekanism.common.tile.TileEntityQuantumEntangloporter.setFrequency(TileEntityQuantumEntangloporter.java:246)
	at mekanism.common.item.ItemBlockMachine.placeBlockAt(ItemBlockMachine.java:436)
	at net.minecraft.item.ItemBlock.func_180614_a(ItemBlock.java:54)
	at mekanism.common.item.ItemBlockMachine.func_180614_a(ItemBlockMachine.java:304)
	at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:187)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:476)
	at PlayerControllerOF.func_187099_a(PlayerControllerOF.java:87)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1577)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2253)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2019)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1806)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

*Quantum Entangloporter is not being placed in Overworld*

#### Version
**Forge:** Build 2428
**Mekanism:** Build 318

This is pure clientside crash, and after server rejoin, Quantum Entangloporter is placed down

**Comment by thiakil** [comment]
Whoops, I guess `setFrequency` should only run serverside.

Also not sure why you linked that particular line, it's not even the line mentioned from that class...

**Comment by roboderpy** [comment]
```java
private FrequencyDataHandler dataHandler;
<...>
dataHandler.markDirty();
```

**Comment by aidancbrady** [comment]
Fixed
