### ISSUE TITLE
Crash when building turbine next to reactor

### ISSUE THREAD

**Issue by josephcsible** [aidancbrady/Mekanism#4645]
#### Issue description:
The game crashes if you build a turbine next to a reactor, with ports touching. Once it happens, you can't open the world anymore, since it crashes as soon as it loads.

#### Steps to reproduce:
1. Build and activate a fusion reactor.
2. Build a turbine with ports that are directly adjacent to the fusion reactor's ports.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.22.0.2459
**Mekanism:** 9.4.0.318

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

https://gist.github.com/josephcsible/c73df1a7816b4e0252ed738e92f15df8

Here's the important part for convenience:
```
java.lang.NoSuchMethodError: mekanism.common.base.IEnergyWrapper.receiveEnergy(Lnet/minecraft/util/EnumFacing;IZ)I
	at mekanism.common.integration.forgeenergy.ForgeEnergyIntegration.receiveEnergy(ForgeEnergyIntegration.java:23)
	at mekanism.common.util.CableUtils.emit_do_do(CableUtils.java:272)
	at mekanism.common.util.CableUtils.emit_do(CableUtils.java:240)
	at mekanism.common.util.CableUtils.emit(CableUtils.java:212)
	at mekanism.generators.common.tile.reactor.TileEntityReactorPort.onUpdate(TileEntityReactorPort.java:95)
	at mekanism.common.tile.prefab.TileEntityBasicBlock.func_73660_a(TileEntityBasicBlock.java:79)
	at net.minecraft.world.World.func_72939_s(World.java:1812)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:614)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by thiakil** [comment]
It looks like some RF methods are getting stripped when they have no need to, and this particular one is shared between RF and FE.

In the meantime, you should be able to load if you add the RedstoneFlux mod
