### ISSUE TITLE
Crash mekanism on 1.12.1

### ISSUE THREAD

**Issue by FernandoVpro** [aidancbrady/Mekanism#4656]
Crash Log

Short Error:

Description: Initializing game

java.lang.ArrayIndexOutOfBoundsException: 0
	at xreliquary.crafting.factories.AlkahestryCraftingRecipeFactory.parse(AlkahestryCraftingRecipeFactory.java:48)
	at net.minecraftforge.common.crafting.CraftingHelper.getRecipe(CraftingHelper.java:408)
	at net.minecraftforge.common.crafting.CraftingHelper.lambda$loadRecipes$22(CraftingHelper.java:711)
	at net.minecraftforge.common.crafting.CraftingHelper.findFiles(CraftingHelper.java:822)
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:668)
	at java.util.ArrayList.forEach(Unknown Source)
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:620)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:779)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:343)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

Full log on pastebin:

https://pastebin.com/nWa7iZUd

Mekanism 9.4.0.318
MC 1.12.1
Forge 2462

**Comment by thiakil** [comment]
`at xreliquary.crafting.factories.AlkahestryCraftingRecipeFactory.parse(AlkahestryCraftingRecipeFactory.java:48)`

That's not Mekanism. Report to Reliquary.

**Comment by FernandoVpro** [comment]
Thanks
