### ISSUE TITLE
[1.12.1] Crash on launch, not the same as previous topic on here

### ISSUE THREAD

**Issue by coraxel** [aidancbrady/Mekanism#4678]
The game crashed whilst initializing game
Error: java.lang.NullPointerException: Can't use a null-name for the registry, object null.

Here's the full crash report. Not sure how to use spoiler on here, if there is one

---- Minecraft Crash Report ----
// I feel sad now :(

Time: 9/6/17 8:47 PM
Description: Initializing game

java.lang.NullPointerException: Can't use a null-name for the registry, object null.
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:864)
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:269)
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:263)
	at net.minecraftforge.registries.ForgeRegistry.register(ForgeRegistry.java:107)
	at mekanism.tools.common.ToolsItems.registerItems(ToolsItems.java:216)
	at mekanism.tools.common.MekanismTools.registerItems(MekanismTools.java:76)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_12_MekanismTools_registerItems_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:734)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:605)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:266)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:864)
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:269)
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:263)
	at net.minecraftforge.registries.ForgeRegistry.register(ForgeRegistry.java:107)
	at mekanism.tools.common.ToolsItems.registerItems(ToolsItems.java:216)
	at mekanism.tools.common.MekanismTools.registerItems(MekanismTools.java:76)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_12_MekanismTools_registerItems_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:734)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:605)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:266)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 182275984 bytes (173 MB) / 436191232 bytes (415 MB) up to 12871532544 bytes (12275 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx12G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.41 Powered by Forge 14.22.0.2469 9 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                 | Version       | Source                                  | Signature                                |
	|:----- |:------------------ |:------------- |:--------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft          | 1.12.1        | minecraft.jar                           | None                                     |
	| UCH   | mcp                | 9.19          | minecraft.jar                           | None                                     |
	| UCH   | FML                | 8.0.99.99     | forge-1.12.1-14.22.0.2469.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge              | 14.22.0.2469  | forge-1.12.1-14.22.0.2469.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | mercurius_updater  | 1.0           | MercuriusUpdater-1.12.1.jar             | None                                     |
	| UCH   | mantle             | 1.12-1.3.1.21 | Mantle-1.12-1.3.1.21.jar                | None                                     |
	| UCE   | mekanism           | 9.4.1         | Mekanism-1.12.1-9.4.1.326.jar           | None                                     |
	| UCE   | mekanismgenerators | 9.4.1         | MekanismGenerators-1.12.1-9.4.1.326.jar | None                                     |
	| UCE   | mekanismtools      | 9.4.1         | MekanismTools-1.12.1-9.4.1.326.jar      | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 385.41' Renderer: 'GeForce GTX 970/PCIe/SSE2'
	Launched Version: 1.12.1-forge1.12.1-14.22.0.2469
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 970/PCIe/SSE2 GL version 4.5.0 NVIDIA 385.41, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-4771 CPU @ 3.50GHz

**Comment by thommy101** [comment]
It looks a lot like #4610.

Could you check if you have a Mekanism API jar in your mod folder? If so, delete it and try again.
If not, please provide the client startup log (fml-client-latest)

**Comment by coraxel** [comment]
Oh, well that worked overly well. Now to figure out what other mods I'm placing in my game...

**Comment by thommy101** [comment]
Just confirming, your issue is fixed (so we/you can close the issue)?

**Comment by coraxel** [comment]
Ah, yes.
