### ISSUE TITLE
Mekanism crashing when I add extracells 2

### ISSUE THREAD

**Issue by Zdyzeus** [aidancbrady/Mekanism#4854]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Mekanism crashes when I add extracells 2.

#### Steps to reproduce:
1. Get the mods I have in my game (except extracells 2)
2. Add extracells 2
3. Crash???

#### Version (make sure you are on the latest version before reporting):
**Forge:1.10.2-12.18.3.2511** 
**Mekanism: 1.10.2-9.2.3.97** 
**Other relevant version: Extracells 2 version 1.10.2-2.4.4a15** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
[latest.log](https://github.com/aidancbrady/Mekanism/files/1540569/latest.log)
It exceeded pastekinds 512 kilobyte limit, there's the straight crash log
[gist/pastebin/etc link here]

**Comment by thiakil** [comment]
That looks like an incompatibility between EC & Wireless Crafting Terminal.

```
Caused by: java.lang.NoSuchMethodError: p455w0rd.wct.api.WCTApi.items()Lp455w0rd/wct/api/IWCTItems;
	at extracells.integration.WirelessCrafting.WirelessCrafting$.getCraftingTerminal(WirelessCrafting.scala:25)
	at extracells.util.UniversalTerminal$.<init>(UniversalTErminal.scala:41)
	at extracells.util.UniversalTerminal$.<clinit>(UniversalTErminal.scala)
	at extracells.util.recipe.RecipeUniversalTerminal$$anonfun$matches$1.apply$mcVI$sp(RecipeUniversalTerminal.scala:42)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
	at extracells.util.recipe.RecipeUniversalTerminal$.func_77569_a(RecipeUniversalTerminal.scala:30)
	at mekanism.common.util.MekanismUtils.findMatchingRecipe(MekanismUtils.java:1366)
```

**Comment by Sandriell** [comment]
Wireless Crafting Terminal already updated to fix this.

**Comment by Zdyzeus** [comment]
Thanks so much! I didn't realize I had an old version!

**Comment by zeldamon** [comment]
I've had the same issue, but I knew my WCT was updated because I made my pack just a few days ago. Downgrading my version solved the problem.
