### ISSUE TITLE
Mekanism Generators crashes my game 1.12.2

### ISSUE THREAD

**Issue by rnfudge** [aidancbrady/Mekanism#4859]
Mekanism generators crashes the game whenever i try to use it.  It wont work for me no matter which mods I use with it.

Forge 1.12.2-14.23.1.2555
Mekanism  1.12.2-9.4.327

This is the crash log:
---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Quite honestly, I wouldn't worry myself about that.

Time: 12/9/17 11:01 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from MekanismGenerators (mekanismgenerators)
Caused by: java.lang.IllegalStateException: Gasses must be registered before postInit.
	at com.google.common.base.Preconditions.checkState(Preconditions.java:444)
	at mekanism.api.gas.GasRegistry.checkPhase(GasRegistry.java:120)
	at mekanism.api.gas.GasRegistry.register(GasRegistry.java:22)
	at mekanism.generators.common.MekanismGenerators.postInit(MekanismGenerators.java:121)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:606)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:724)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:352)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1407317520 bytes (1342 MB) / 2651324416 bytes (2528 MB) up to 11453595648 bytes (10923 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx12G
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.1.2555 32 mods loaded, 32 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                  | Version         | Source                                          | Signature                                |
	|:----- |:------------------- |:--------------- |:----------------------------------------------- |:---------------------------------------- |
	| UCHIJ | minecraft           | 1.12.2          | minecraft.jar                                   | None                                     |
	| UCHIJ | mcp                 | 9.42            | minecraft.jar                                   | None                                     |
	| UCHIJ | FML                 | 8.0.99.99       | forge-1.12.2-14.23.1.2555.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJ | forge               | 14.23.1.2555    | forge-1.12.2-14.23.1.2555.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJ | mercurius_updater   | 1.0             | MercuriusUpdater-1.12.2.jar                     | None                                     |
	| UCHIJ | jei                 | 4.8.0.114       | jei_1.12.2-4.8.0.114.jar                        | None                                     |
	| UCHIJ | abyssalcraft        | 1.9.4.2         | AbyssalCraft-1.12.2-1.9.4.2.jar                 | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| UCHIJ | appliedenergistics2 | rv5-stable-3    | appliedenergistics2-rv5-stable-3.jar            | None                                     |
	| UCHIJ | buildcraftlib       | 7.99.12         | buildcraft-7.99.12.jar                          | None                                     |
	| UCHIJ | buildcraftcore      | 7.99.12         | buildcraft-7.99.12.jar                          | None                                     |
	| UCHIJ | buildcraftbuilders  | 7.99.12         | buildcraft-7.99.12.jar                          | None                                     |
	| UCHIJ | buildcraftenergy    | 7.99.12         | buildcraft-7.99.12.jar                          | None                                     |
	| UCHIJ | buildcraftfactory   | 7.99.12         | buildcraft-7.99.12.jar                          | None                                     |
	| UCHIJ | buildcraftrobotics  | 7.99.12         | buildcraft-7.99.12.jar                          | None                                     |
	| UCHIJ | buildcraftsilicon   | 7.99.12         | buildcraft-7.99.12.jar                          | None                                     |
	| UCHIJ | buildcrafttransport | 7.99.12         | buildcraft-7.99.12.jar                          | None                                     |
	| UCHIJ | codechickenlib      | 3.1.3.313       | CodeChickenLib-1.12-3.1.3.313-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJ | redstoneflux        | 2.0.1           | RedstoneFlux-1.12-2.0.1.2-universal.jar         | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCHIJ | cofhcore            | 4.3.7           | CoFHCore-1.12.2-4.3.7.25-universal.jar          | None                                     |
	| UCHIJ | cofhworld           | 1.0.2           | CoFHWorld-1.12.2-1.0.2.10-universal.jar         | None                                     |
	| UCHIJ | zerocore            | 1.12-0.1.1.0    | zerocore-1.12-0.1.1.0.jar                       | None                                     |
	| UCHIJ | bigreactors         | 1.12-0.4.5.44   | ExtremeReactors-1.12-0.4.5.44.jar               | None                                     |
	| UCHIJ | journeymap          | 1.12.2-5.5.2    | journeymap-1.12.2-5.5.2.jar                     | None                                     |
	| UCHIJ | mekanism            | 9.4.2           | Mekanism-1.12.2-9.4.2.327.jar                   | None                                     |
	| UCHIE | mekanismgenerators  | 9.4.2           | MekanismGenerators-1.12.2-9.4.2.327.jar         | None                                     |
	| UCHIJ | mekanismtools       | 9.4.2           | MekanismTools-1.12.2-9.4.2.327.jar              | None                                     |
	| UCHIJ | minecolonies        | 1.12.2-0.8.4932 | minecolonies-universal-1.12.2-0.8.4932.jar      | None                                     |
	| UCHIJ | roguelike           | 1.8.0           | RoguelikeDungeons-1.12.2-1.8.0.jar              | None                                     |
	| UCHIJ | thermalfoundation   | 2.3.7           | ThermalFoundation-1.12.2-2.3.7.18-universal.jar | None                                     |
	| UCHIJ | thermaldynamics     | 2.3.7           | ThermalDynamics-1.12.2-2.3.7.14-universal.jar   | None                                     |
	| UCHIJ | thermalexpansion    | 5.3.7           | ThermalExpansion-1.12.2-5.3.7.31-universal.jar  | None                                     |
	| UCHIJ | twilightforest      | 3.5.263         | twilightforest-1.12.2-3.5.263-universal.jar     | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 375.63' Renderer: 'GeForce GTX 960/PCIe/SSE2'
	AE2 Version: stable rv5-stable-3 for Forge 14.23.1.2554
	AE2 Integration: IC2:OFF, RC:OFF, MFR:OFF, Waila:OFF, InvTweaks:OFF, JEI:ON, Mekanism:ON, OpenComputers:OFF, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:OFF

**Comment by deanmsands3** [comment]
Can confirm same issue. Disabled BuildCraft. Game loads fine.

**Comment by rnfudge** [comment]
Okay Thanks, ill try that later

**Comment by rnfudge** [comment]
Yeah, that worked after

**Comment by thiakil** [comment]
_**SEARCH BEFORE YOU POST**_

_**SEARCH BEFORE YOU POST**_
