### ISSUE TITLE
Lots of "crash" mssages in the log caused by the induction matrix

### ISSUE THREAD

**Issue by MatthiasMann** [aidancbrady/Mekanism#5015]
(except from the log file - it's >600MB - the same stack trace repeats a lot - directly after loading the world)
[07:47:26] [Server thread/FATAL] [FML]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.20.jar)
  BedPatch (bedpatch-2.2-1.12.2.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.170.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.5.jar)
  AstralCore (astralsorcery-1.12.2-1.8.5.jar)
  LoadingPlugin (Quark-r1.4-123.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.7-1.12.2-anarchy.jar)
  Plugin (NotEnoughIDs-1.5.4.2.jar)
  ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.6.jar)
  FMLPlugin (elulib-0.1.12.jar)
  ModFixLC (ModFix-1.12.2-1.0.0.1.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64-dev.jar)
  ForgelinPlugin (Forgelin-1.6.0.jar)
  LoadingPlugin (RandomThings-MC1.12.2-4.1.5.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.2.67.jar)
  AppleCore (AppleCore-mc1.12.2-3.1.1.jar)
  IELoadingPlugin (ImmersiveEngineering-0.12-80-core.jar)
Contact their authors BEFORE contacting forge

// Quite honestly, I wouldn't worry myself about that.

Description: Ticking block entity

java.lang.NullPointerException: The validated object is null
        at org.apache.commons.lang3.Validate.notNull(Validate.java:225)
        at org.apache.commons.lang3.Validate.notNull(Validate.java:206)
        at net.minecraft.util.NonNullList.add(SourceFile:56)
        at java.util.AbstractList.add(AbstractList.java:108)
        at mekanism.common.tile.TileEntityMultiblock.getNetworkedData(TileEntityMultiblock.java:208)
        at mekanism.common.tile.TileEntityInductionCasing.getNetworkedData(TileEntityInductionCasing.java:83)
        at mekanism.common.tile.TileEntityMultiblock.onUpdate(TileEntityMultiblock.java:130)
        at mekanism.common.tile.TileEntityInductionCasing.onUpdate(TileEntityInductionCasing.java:48)
        at mekanism.common.tile.prefab.TileEntityBasicBlock.func_73660_a(TileEntityBasicBlock.java:80)
        at net.minecraft.world.World.func_72939_s(World.java:1832)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
        at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
        at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
        at org.apache.commons.lang3.Validate.notNull(Validate.java:225)
        at org.apache.commons.lang3.Validate.notNull(Validate.java:206)
        at net.minecraft.util.NonNullList.add(SourceFile:56)
        at java.util.AbstractList.add(AbstractList.java:108)
        at mekanism.common.tile.TileEntityMultiblock.getNetworkedData(TileEntityMultiblock.java:208)
        at mekanism.common.tile.TileEntityInductionCasing.getNetworkedData(TileEntityInductionCasing.java:83)
        at mekanism.common.tile.TileEntityMultiblock.onUpdate(TileEntityMultiblock.java:130)
        at mekanism.common.tile.TileEntityInductionCasing.onUpdate(TileEntityInductionCasing.java:48)
        at mekanism.common.tile.prefab.TileEntityBasicBlock.func_73660_a(TileEntityBasicBlock.java:80)

-- Block entity being ticked --
Details:
        Name: minecraft:inductioncasing // mekanism.common.tile.TileEntityInductionCasing
        Block type: ID #2969 (tile.BasicBlock2 // null)
        Block data value: 1 / 0x1 / 0b0001
        Block location: World: (-1062,86,-1029), Chunk: (at 10,5,11 in -67,-65; contains blocks -1072,0,-1040 to -1057,255,-1025), Region: (-3,-3; contains chunks -96,-96 to -65,-65, blocks -1536,0,-1536 to -1025,255,-1025)
        Actual block type: ID #2969 (tile.BasicBlock2 // null)
        Actual block data value: 1 / 0x1 / 0b0001
Stacktrace:
        at net.minecraft.world.World.func_72939_s(World.java:1832)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
        at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
        at java.lang.Thread.run(Thread.java:748)
-- System Details --
Details:
        Minecraft Version: 1.12.2
        Operating System: Linux (amd64) version 4.13.0-38-generic
        Java Version: 1.8.0_162, Oracle Corporation
        Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
        Memory: 3658156384 bytes (3488 MB) / 7916421120 bytes (7549 MB) up to 12871532544 bytes (12275 MB)
        JVM Flags: 6 total; -Xmx12G -Xms4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
        IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
        FML: MCP 9.42 Powered by Forge 14.23.3.2668 280 mods loaded, 280 mods active

(the game did NOT crash - it kept running and generating these messages over and over)

#### Steps to reproduce:
I have a 5x5x3 induction matrix with 1 basic provider (25KRF/t) and 4 advanced cells in it. The matrix has 8 ports on the top, 4 as input, 4 as output all wired up using Immersive Engineering HV connectors.

I noticed after some time in the world (single player) that everything was out of power and no input/output was happening (statistics in the matrix was 0/0 powered stored was what I expected).

Then I broke one casing block and placed it back (not one of the ports) - at that point everything worked again (except the input/output statistic which randomly was showing 25KRF I/O - even so with 4x HV connector that shouldn't be possible - and the energy stored was increasing correctly - so I think there might be an issue with the statistic).

From the time stamps in the log the messages seem to have stopped after breaking and replacing the casing.

#### Version (make sure you are on the latest version before reporting):
forge-1.12.2-14.23.3.2668
Mekanism-1.12.2-9.4.3.330
MekanismGenerators-1.12.2-9.4.3.330
MekanismTools-1.12.2-9.4.3.330
ImmersiveEngineering-0.12-80

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
Sadly the log is too big up upload - but I'll keep it around and can try to extract further parts if needed/possible.

**Comment by MatthiasMann** [comment]
PS: The induction matrix has at least 3 blocks on each side to a chunk boundary - and no chunk loader is active.

**Comment by MatthiasMann** [comment]
I haven't found any other report - can you link the issue here?

**Comment by thiakil** [comment]
#4972

(it was closed automatically by github when a merge to master was done but the server's commit hook is broken so no release was made)
