### ISSUE TITLE
Atomic disassembler has error breaking pipes from thermal expansion

### ISSUE THREAD

**Issue by ss1h2a3tw** [aidancbrady/Mekanism#5034]
#### Issue description:
When breaking pipes like itemduct or fluxduct from thermal expansion with atomic disassembler,
the pipe block will disappear, but can't pick it up. Placing a block beside it will make the pipe appear again. Looks like the breaking block didn't work.

#### Steps to reproduce:
1. Place itemduct
2. Try to break it by atomic disassembler

#### Version (make sure you are on the latest version before reporting):
**Forge:14.23.3.2676** 
**Mekanism: from 1.12.2-9.4.4.337 to 1.12.2-9.4.7.342** 
**Thermal Expansion: 1.12.2-5.4.2.27**
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
```
[03:00:34] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.NullPointerException
	at cofh.thermaldynamics.block.BlockDuct.getPickBlock(BlockDuct.java:288) ~[BlockDuct.class:?]
	at mekanism.common.item.ItemAtomicDisassembler.onBlockStartBreak(ItemAtomicDisassembler.java:132) ~[ItemAtomicDisassembler.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:302) ~[or.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_180785_a(PlayerInteractionManager.java:244) ~[or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:702) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:40) ~[lp.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:10) ~[lp.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more
```

**Comment by ss1h2a3tw** [comment]
Thanks!

**Comment by ss1h2a3tw** [comment]
Any plans for a new release including this patch?

**Comment by thiakil** [comment]
Soon. We don't currently push out updates for every single fix

**Comment by ss1h2a3tw** [comment]
Ok, thanks!
