### ISSUE TITLE
Heat Generator Crash

### ISSUE THREAD

**Issue by Adam022695** [aidancbrady/Mekanism#5220]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Steps to reproduce:
1.Place Heat generator in the world, Mine it up to try and move it
2.Place heat generator in world and connect or disconnect cables. Doesn't matter if its from mekanism or not it crashes anyways
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:*14.23.5.2796* 
**Mekanism:*Current release version* 
**Other relevant version:*Also have the mekanism generator mod installed* 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
[2018-12-13-7.log.gz](https://github.com/aidancbrady/Mekanism/files/2678027/2018-12-13-7.log.gz)

**Comment by Adam022695** [comment]
[crash-2018-12-13_18.07.38-server.txt](https://github.com/aidancbrady/Mekanism/files/2678040/crash-2018-12-13_18.07.38-server.txt)
This is my first time reporting so i'm not sure if its the file with the report or this one you need

**Comment by thiakil** [comment]
```
java.util.ConcurrentModificationException
	at java.util.IdentityHashMap$IdentityHashMapIterator.nextIndex(IdentityHashMap.java:734)
	at java.util.IdentityHashMap$KeyIterator.next(IdentityHashMap.java:825)
	at aroma1997.tatw.ic2usesfe.block.ICSourceEventListener.tick(ICSourceEventListener.java:76)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2418_ICSourceEventListener_tick_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
```

Not us, report to `ic2usesfe`
